Repository chatwoot/chatwoot, pull requests merged in 2020-09, with the labels that each got.

#1182 Fix: fonts cors issue with cdn
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/test.rb
  config/initializers/assets.rb
Labels: PR: reviewed-approved

#1187 bug fix: validate_queue method - map then sort, instead of sort then map
  app/services/round_robin/manage_service.rb
Labels: PR: reviewed-approved

#1191 chore: Improve widget loading performance
  .env.example
  app/javascript/shared/assets/fonts/widget_fonts.scss
  app/javascript/widget/assets/scss/woot.scss
  config/environments/production.rb
Labels: PR: partially-approved

#1167 #1165 - Improves styling for conversation header
  app/javascript/dashboard/assets/scss/_helper-classes.scss
  app/javascript/dashboard/assets/scss/_mixins.scss
  app/javascript/dashboard/assets/scss/widgets/_conv-header.scss
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/components/widgets/conversation/MoreActions.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
  app/javascript/shared/assets/stylesheets/colors.scss
Labels: PR: partially-approved

#1193 chore: Add document to setup Cloudfront as the CDN
  docs/deployment/frontend/cloudfront-cdn.md
  docs/deployment/frontend/images/cloudfront/cache-behaviour.png
  docs/deployment/frontend/images/cloudfront/cdn-distribution-settings.png
  docs/deployment/frontend/images/cloudfront/create-distribution.png
  docs/deployment/frontend/images/cloudfront/extra-headers.png
  docs/deployment/frontend/images/cloudfront/origin-settings.png
  docs/deployment/frontend/images/cloudfront/web-delivery-method.png
  docs/development/project-setup/environment-variables.md
Labels: PR: reviewed-approved

#1190 chore: Remove unused packages from package.json
  package.json
  yarn.lock
Labels: PR: partially-approved

#1178 chore: Enable runtime metrics on Heroku
  Gemfile
  Gemfile.lock
  app/builders/messages/facebook/message_builder.rb
  app/controllers/api/v1/accounts/callbacks_controller.rb
  app/jobs/contact_avatar_job.rb
  app/services/twilio/incoming_message_service.rb
Labels: PR: unreviewed

#1200 chore: Add alt text for bubble icon
  app/javascript/sdk/bubbleHelpers.js
Labels: PR: unreviewed

#1192 chore: Add message_echo listener for Facebook
  app/bot/facebook_bot.rb
  app/builders/messages/facebook/message_builder.rb
  app/models/channel/api.rb
  app/models/channel/email.rb
  app/models/channel/facebook_page.rb
  app/models/channel/twilio_sms.rb
  app/models/channel/twitter_profile.rb
  app/models/channel/web_widget.rb
  app/models/inbox.rb
  lib/integrations/slack/send_on_slack_service.rb
  spec/models/channel/facebook_page_spec.rb
  spec/models/inbox_spec.rb
Labels: PR: unreviewed

#1202 chore: Upgrade yargs-parser to fix GHSA-p9pc-299p-vxgp
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#1173 chore: update gem files
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/builders/messages/facebook/message_builder.rb
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/controllers/api/v1/accounts/inbox_members_controller.rb
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/controllers/api/v1/widget/conversations_controller.rb
  app/controllers/api/v1/widget/messages_controller.rb
  app/controllers/devise_overrides/confirmations_controller.rb
  app/controllers/twitter/callbacks_controller.rb
  app/dispatchers/async_dispatcher.rb
  app/finders/conversation_finder.rb
  app/jobs/send_reply_job.rb
  app/listeners/action_cable_listener.rb
  app/models/channel/twitter_profile.rb
  app/models/concerns/featurable.rb
  app/models/conversation.rb
  app/models/integrations/app.rb
  app/models/notification.rb
  app/models/user.rb
  app/policies/application_policy.rb
  app/presenters/mail_presenter.rb
  app/services/twitter/send_on_twitter_service.rb
  app/services/twitter/webhook_subscribe_service.rb
  app/views/super_admin/application/_navigation.html.erb
  config/environments/production.rb
  config/environments/staging.rb
  config/initializers/sentry.rb
  lib/custom_exceptions/base.rb
  lib/integrations/facebook/message_creator.rb
  spec/mailboxes/default_mailbox_spec.rb
  spec/models/super_admin_spec.rb
Labels: PR: reviewed-approved

#1212 fix: Update documentation to use `launcherTitle`
  docs/channels/website-sdk.md
Labels: PR: reviewed-approved

#1204 feat: Notification on new messages in conversation
  .rubocop.yml
  Gemfile.lock
  app/controllers/api/v1/widget/conversations_controller.rb
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/profile/NotificationSettings.vue
  app/javascript/dashboard/store/modules/specs/contactConversations/fixtures.js
  app/javascript/widget/api/conversation.js
  app/javascript/widget/store/modules/conversationAttributes.js
  app/jobs/contact_avatar_job.rb
  app/jobs/notification/email_notification_job.rb
  app/listeners/notification_listener.rb
  app/mailers/agent_notifications/conversation_notifications_mailer.rb
  app/mailers/application_mailer.rb
  app/mailers/conversation_reply_mailer.rb
  app/models/conversation.rb
  app/models/message.rb
  app/models/notification.rb
  app/presenters/conversations/event_data_presenter.rb
  app/services/notification/push_notification_service.rb
  app/views/api/v1/conversations/partials/_conversation.json.jbuilder
  app/views/api/v1/widget/conversations/index.json.jbuilder
  app/views/mailers/agent_notifications/conversation_notifications_mailer/assigned_conversation_new_message.liquid
  db/migrate/20200907094912_rename_user_last_seen.rb
  db/schema.rb
  docs/channels/api-channel/callback-url.md
  lib/integrations/facebook/delivery_status.rb
  package.json
  spec/controllers/api/v1/widget/conversations_controller_spec.rb
  spec/mailboxes/conversation_mailbox_spec.rb
  spec/mailers/agent_notifications/conversation_notifications_mailer_spec.rb
  spec/mailers/conversation_reply_mailer_spec.rb
  spec/models/conversation_spec.rb
  spec/models/message_spec.rb
  spec/presenters/conversations/event_data_presenter_spec.rb
  swagger/definitions/resource/conversation.yml
  swagger/swagger.json
Labels: PR: reviewed-approved

#1147 Fix 1145 by allowing DATABASE_URL env to take presedence over individ…
  docker/entrypoints/rails.sh
Labels: PR: reviewed-approved

#1224 chore: Fix integration hooks destroy
  app/controllers/api/v1/accounts/integrations/slack_controller.rb
  lib/integrations/slack/send_on_slack_service.rb
Labels: PR: reviewed-approved

#1232 chore: Remove `emojione`, cleanup styles
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/assets/scss/widgets/_emojiinput.scss
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/emoji/EmojiInput.vue
  app/javascript/dashboard/components/widgets/emoji/categories.js
  app/javascript/dashboard/components/widgets/emoji/utils.js
  app/javascript/shared/components/emoji/EmojiInput.vue
  app/javascript/shared/components/emoji/emojis.json
  app/javascript/widget/components/ChatInputWrap.vue
  package.json
  yarn.lock
Labels: PR: partially-approved

#1233 chore: Remove `momentjs`, use `date-fns`
  app/javascript/dashboard/mixins/time.js
  app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
  app/javascript/dashboard/store/modules/reports.js
  app/javascript/dashboard/store/utils/api.js
  app/javascript/shared/helpers/DateHelper.js
  app/javascript/widget/store/modules/conversation.js
  package.json
  yarn.lock
Labels: PR: partially-approved

#1238 fix: Add available_name method to agent_bot
  app/models/agent_bot.rb
Labels: PR: reviewed-approved

#1242 chore: Upgrade selfsigned to fix CVE-2020-7720
  yarn.lock
Labels: PR: reviewed-approved

#1245 fix: Check medium to decide 24 hour window
  app/models/channel/twilio_sms.rb
  spec/models/channel/twilio_sms_spec.rb
Labels: PR: reviewed-approved

#1243 chore: sentry error fixes
  app/controllers/api/v1/widget/labels_controller.rb
  app/jobs/contact_avatar_job.rb
  lib/webhooks/trigger.rb
Labels: PR: reviewed-approved

#1254 Chore: Fix N+1 queries in dashboard side
  app/controllers/api/v1/accounts/contacts/conversations_controller.rb
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/finders/conversation_finder.rb
  app/finders/message_finder.rb
  app/views/api/v1/conversations/partials/_conversation.json.jbuilder
Labels: PR: partially-approved

#1260 chore: Add browser logs and server logs to the template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: PR: reviewed-approved

#1259 chore: Add a check for defined labels in SDK API
  app/controllers/api/v1/widget/labels_controller.rb
  spec/controllers/api/v1/widget/labels_controller_spec.rb
Labels: PR: reviewed-approved

#1261 fix: Remove agent keys from translation file
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/i18n/locale/ar/agentMgmt.json
  app/javascript/dashboard/i18n/locale/ca/agentMgmt.json
  app/javascript/dashboard/i18n/locale/cs/agentMgmt.json
  app/javascript/dashboard/i18n/locale/da/agentMgmt.json
  app/javascript/dashboard/i18n/locale/de/agentMgmt.json
  app/javascript/dashboard/i18n/locale/el/agentMgmt.json
  app/javascript/dashboard/i18n/locale/en/agentMgmt.json
  app/javascript/dashboard/i18n/locale/es/agentMgmt.json
  app/javascript/dashboard/i18n/locale/fa/agentMgmt.json
  app/javascript/dashboard/i18n/locale/fi/agentMgmt.json
  app/javascript/dashboard/i18n/locale/fr/agentMgmt.json
  app/javascript/dashboard/i18n/locale/hi/agentMgmt.json
  app/javascript/dashboard/i18n/locale/hu/agentMgmt.json
  app/javascript/dashboard/i18n/locale/it/agentMgmt.json
  app/javascript/dashboard/i18n/locale/ja/agentMgmt.json
  app/javascript/dashboard/i18n/locale/ko/agentMgmt.json
  app/javascript/dashboard/i18n/locale/ml/agentMgmt.json
  app/javascript/dashboard/i18n/locale/nl/agentMgmt.json
  app/javascript/dashboard/i18n/locale/pl/agentMgmt.json
  app/javascript/dashboard/i18n/locale/pt/agentMgmt.json
  app/javascript/dashboard/i18n/locale/pt_BR/agentMgmt.json
  app/javascript/dashboard/i18n/locale/ro/agentMgmt.json
  app/javascript/dashboard/i18n/locale/ru/agentMgmt.json
  app/javascript/dashboard/i18n/locale/sk/agentMgmt.json
  app/javascript/dashboard/i18n/locale/sv/agentMgmt.json
  app/javascript/dashboard/i18n/locale/ta/agentMgmt.json
  app/javascript/dashboard/i18n/locale/th/agentMgmt.json
  app/javascript/dashboard/i18n/locale/tr/agentMgmt.json
  app/javascript/dashboard/i18n/locale/uk/agentMgmt.json
  app/javascript/dashboard/i18n/locale/vi/agentMgmt.json
  app/javascript/dashboard/i18n/locale/zh/agentMgmt.json
  app/javascript/dashboard/i18n/locale/zh_CN/agentMgmt.json
  app/javascript/dashboard/i18n/locale/zh_TW/agentMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/agents/AddAgent.vue
  app/javascript/dashboard/routes/dashboard/settings/agents/EditAgent.vue
  app/javascript/dashboard/routes/dashboard/settings/agents/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/canned/AddCanned.vue
Labels: PR: reviewed-approved

#1256 Bug: Fix 1246 (Facebook inbox filename bug)
  app/builders/messages/facebook/message_builder.rb
  lib/local_resource.rb
Labels: PR: reviewed-approved

#1255 feat: email channel backend (#140)
  .gitignore
  app/mailboxes/application_mailbox.rb
  app/mailboxes/mailbox_helper.rb
  app/mailboxes/reply_mailbox.rb
  app/mailboxes/support_mailbox.rb
  app/models/concerns/featurable.rb
  app/presenters/mail_presenter.rb
  spec/factories/channel/channel_email.rb
  spec/fixtures/files/support.eml
  spec/mailboxes/application_mailbox_spec.rb
  spec/mailboxes/reply_mailbox_spec.rb
  spec/mailboxes/support_mailbox_spec.rb
Labels: PR: partially-approved

#1264 Bugfix: Email encoding issue for utf8 characters (#1081)
  app/presenters/mail_presenter.rb
Labels: PR: unreviewed

#1267 chore: Update website-sdk documentation
  docs/channels/website-sdk.md
Labels: PR: reviewed-approved

#1265 feat: Ability to search conversation with message content
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/finders/conversation_finder.rb
  app/views/api/v1/accounts/conversations/search.json.jbuilder
  config/routes.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
  swagger/paths/conversation/index_or_create.yml
  swagger/swagger.json
Labels: PR: unreviewed

#1269 chore: Fix wrong documentation to set a label
  docs/channels/website-sdk.md
Labels: PR: unreviewed

#1276 DE Widget - 100% Translation
  app/javascript/widget/i18n/locale/de.json
Labels: PR: reviewed-approved

#1002 Feature: Knowledge Base APIs
  app/controllers/api/v1/accounts/kbase/base_controller.rb
  app/controllers/api/v1/accounts/kbase/categories_controller.rb
  app/controllers/api/v1/accounts/kbase/portals_controller.rb
  app/models/account.rb
  app/models/kbase.rb
  app/models/kbase/article.rb
  app/models/kbase/category.rb
  app/models/kbase/folder.rb
  app/models/kbase/portal.rb
  app/views/api/v1/accounts/kbase/categories/_category.json.jbuilder
  app/views/api/v1/accounts/kbase/categories/create.json.jbuilder
  app/views/api/v1/accounts/kbase/categories/index.json.jbuilder
  app/views/api/v1/accounts/kbase/categories/update.json.jbuilder
  app/views/api/v1/accounts/kbase/portals/_portal.json.jbuilder
  app/views/api/v1/accounts/kbase/portals/create.json.jbuilder
  app/views/api/v1/accounts/kbase/portals/index.json.jbuilder
  app/views/api/v1/accounts/kbase/portals/update.json.jbuilder
  config/routes.rb
  db/migrate/20200704135408_create_kbase_portals.rb
  db/migrate/20200704135810_create_kbase_categories.rb
  db/migrate/20200704140029_create_kbase_folders.rb
  db/migrate/20200704140509_create_kbase_articles.rb
  db/schema.rb
  spec/factories/kbase/articles.rb
  spec/factories/kbase/categories.rb
  spec/factories/kbase/folders.rb
  spec/factories/kbase/portals.rb
  spec/models/account_spec.rb
  spec/models/kbase/article_spec.rb
  spec/models/kbase/category_spec.rb
  spec/models/kbase/folder_spec.rb
  spec/models/kbase/portal_spec.rb
  spec/requests/api/v1/accounts/kbase/categories_request_spec.rb
  spec/requests/api/v1/accounts/kbase/portals_request_spec.rb
Labels: PR: unreviewed

#1272 chore: Add a check for data diff in setUser call
  app/javascript/packs/sdk.js
  app/javascript/specs/packs/sdk.spec.js
  package.json
  yarn.lock
Labels: PR: unreviewed

#1279 fix: Remove keys for reports from translation file
  app/javascript/dashboard/i18n/locale/ar/report.json
  app/javascript/dashboard/i18n/locale/ca/report.json
  app/javascript/dashboard/i18n/locale/cs/report.json
  app/javascript/dashboard/i18n/locale/da/report.json
  app/javascript/dashboard/i18n/locale/de/report.json
  app/javascript/dashboard/i18n/locale/el/report.json
  app/javascript/dashboard/i18n/locale/en/report.json
  app/javascript/dashboard/i18n/locale/es/report.json
  app/javascript/dashboard/i18n/locale/fa/report.json
  app/javascript/dashboard/i18n/locale/fi/report.json
  app/javascript/dashboard/i18n/locale/fr/report.json
  app/javascript/dashboard/i18n/locale/hi/report.json
  app/javascript/dashboard/i18n/locale/hu/report.json
  app/javascript/dashboard/i18n/locale/it/report.json
  app/javascript/dashboard/i18n/locale/ja/report.json
  app/javascript/dashboard/i18n/locale/ko/report.json
  app/javascript/dashboard/i18n/locale/ml/report.json
  app/javascript/dashboard/i18n/locale/nl/report.json
  app/javascript/dashboard/i18n/locale/pl/report.json
  app/javascript/dashboard/i18n/locale/pt/report.json
  app/javascript/dashboard/i18n/locale/pt_BR/report.json
  app/javascript/dashboard/i18n/locale/ro/report.json
  app/javascript/dashboard/i18n/locale/ru/report.json
  app/javascript/dashboard/i18n/locale/sk/report.json
  app/javascript/dashboard/i18n/locale/sv/report.json
  app/javascript/dashboard/i18n/locale/ta/report.json
  app/javascript/dashboard/i18n/locale/th/report.json
  app/javascript/dashboard/i18n/locale/tr/report.json
  app/javascript/dashboard/i18n/locale/uk/report.json
  app/javascript/dashboard/i18n/locale/vi/report.json
  app/javascript/dashboard/i18n/locale/zh/report.json
  app/javascript/dashboard/i18n/locale/zh_CN/report.json
  app/javascript/dashboard/i18n/locale/zh_TW/report.json
  app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
Labels: PR: reviewed-approved

#1286 feat: Enables reauthorization of Third Party tokens
  app/controllers/api/v1/accounts/callbacks_controller.rb
  app/javascript/dashboard/api/channel/fbChannel.js
  app/javascript/dashboard/assets/scss/widgets/_forms.scss
  app/javascript/dashboard/components/SettingsSection.vue
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/facebook/Reauthorize.vue
  app/javascript/dashboard/store/modules/inboxes.js
  app/models/channel/facebook_page.rb
  app/models/concerns/reauthorizable.rb
  app/services/facebook/send_on_facebook_service.rb
  app/views/api/v1/accounts/callbacks/reauthorize_page.json.jbuilder
  app/views/api/v1/models/_inbox.json.jbuilder
  lib/redis/alfred.rb
  lib/redis/redis_keys.rb
  spec/controllers/api/v1/accounts/callbacks_controller_spec.rb
  spec/models/channel/facebook_page_spec.rb
  spec/models/concerns/reauthorizable_spec.rb
  spec/services/facebook/send_on_facebook_service_spec.rb
Labels: PR: reviewed-approved
