Repository chatwoot/chatwoot, pull requests merged in 2020-07, with the labels that each got.

#991 Font proposals
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/widget/assets/scss/_variables.scss
Labels: PR: partially-approved

#986 Update .conversation--message text color
  app/javascript/dashboard/assets/scss/widgets/_conversation-card.scss
Labels: PR: unreviewed

#994 Update documentation with Sendgrid instructions
  docs/development/project-setup/environment-variables.md
Labels: PR: reviewed-approved

#987 fix duplicate messages on repeating enter button press on slow network
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  db/seeds.rb
Labels: PR: reviewed-approved

#992 Proposed Enhancements for Chat Bubble Looks in the Dashboard
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
Labels: PR: reviewed-approved

#997 Add icon show last reply is from agent on conversation list
  app/javascript/dashboard/assets/scss/widgets/_conversation-card.scss
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
Labels: PR: unreviewed

#874 Feature: Availability Statuses
  app/channels/room_channel.rb
  app/controllers/api/v1/profiles_controller.rb
  app/javascript/dashboard/api/auth.js
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/widgets/Thumbnail.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/helper/actionCable.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
  app/javascript/dashboard/store/modules/agents.js
  app/javascript/dashboard/store/modules/contacts.js
  app/javascript/dashboard/store/modules/specs/agents/actions.spec.js
  app/javascript/dashboard/store/modules/specs/agents/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/shared/helpers/BaseActionCableConnector.js
  app/javascript/shared/helpers/vuex/mutationHelpers.js
  app/javascript/widget/helpers/actionCable.js
  app/javascript/widget/store/modules/agent.js
  app/javascript/widget/store/modules/specs/agent/actions.spec.js
  app/javascript/widget/store/modules/specs/agent/mutations.spec.js
  app/models/concerns/availability_statusable.rb
  app/models/user.rb
  app/views/api/v1/accounts/contacts/index.json.jbuilder
  app/views/api/v1/accounts/contacts/show.json.jbuilder
  app/views/api/v1/accounts/contacts/update.json.jbuilder
  app/views/api/v1/models/_contact.json.jbuilder
  app/views/api/v1/models/_user.json.jbuilder
  config/cable.yml
  db/migrate/20200629122646_add_availability_to_user.rb
  db/schema.rb
  lib/online_status_tracker.rb
  lib/redis/alfred.rb
  spec/channels/room_channel_spec.rb
  spec/controllers/api/v1/profiles_controller_spec.rb
Labels: PR: unreviewed

#999 Enhancement - Add a visual feedback to show reply box is focused on dashboard #998
  .scss-lint.yml
  app/javascript/dashboard/assets/scss/_helper-classes.scss
  app/javascript/dashboard/assets/scss/_mixins.scss
  app/javascript/dashboard/assets/scss/widgets/_reply-box.scss
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: reviewed-approved

#1000 Chore: Fix issues with conversation data models
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/store/modules/contacts.js
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/modules/specs/contacts/actions.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
  app/models/notification.rb
  app/presenters/conversations/event_data_presenter.rb
  app/views/api/v1/conversations/partials/_conversation.json.jbuilder
  spec/models/conversation_spec.rb
  spec/presenters/conversations/event_data_presenter_spec.rb
Labels: PR: unreviewed

#1001 Chore: Fix presence for current user
  app/channels/room_channel.rb
  app/javascript/dashboard/helper/actionCable.js
  app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/auth.js
  app/javascript/dashboard/store/modules/channels.js
  app/javascript/dashboard/store/modules/specs/auth/actions.spec.js
  app/javascript/dashboard/store/modules/specs/auth/getters.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/models/concerns/availability_statusable.rb
  lib/online_status_tracker.rb
Labels: PR: unreviewed

#1012 Chore: Fix spelling mistakes in docs
  docs/channels/facebook-channel.md
  docs/channels/twitter-channel.md
  docs/channels/website-channel.md
  docs/channels/whatsapp-sms-twilio.md
  docs/deployment/production/architecture.md
  docs/deployment/production/caprover.md
  docs/deployment/production/docker.md
  docs/deployment/production/heroku.md
  docs/deployment/production/linux-vm.md
  docs/development/environment-setup/windows.md
  docs/development/project-setup/slack-integration-setup.md
Labels: PR: unreviewed

#1010 Chore: Feature Flags for Channels
  app/javascript/dashboard/components/widgets/ChannelItem.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue
  app/models/user.rb
  app/views/api/v1/accounts/show.json.jbuilder
  config/features.yml
  db/migrate/20200704173104_add_twitter_feature_flag.rb
  db/schema.rb
Labels: PR: reviewed-approved

#1014 Add documentation for Mailgun & Mailchimp
  docs/development/project-setup/environment-variables.md
Labels: PR: unreviewed

#1013 Bug: Set auto width to email input
  app/javascript/widget/components/template/EmailInput.vue
Labels: PR: unreviewed

#943 Adds unread message bubbles for widget
  app/controllers/api/v1/widget/conversations_controller.rb
  app/javascript/packs/widget.js
  app/javascript/sdk/DOMHelpers.js
  app/javascript/sdk/IFrameHelper.js
  app/javascript/sdk/bubbleHelpers.js
  app/javascript/widget/App.vue
  app/javascript/widget/api/conversation.js
  app/javascript/widget/assets/scss/_variables.scss
  app/javascript/widget/assets/scss/sdk.js
  app/javascript/widget/components/AgentMessageBubble.vue
  app/javascript/widget/helpers/actionCable.js
  app/javascript/widget/i18n/locale/en.json
  app/javascript/widget/store/modules/agent.js
  app/javascript/widget/store/modules/conversation.js
  app/javascript/widget/store/modules/conversationAttributes.js
  app/javascript/widget/store/modules/specs/conversation/actions.spec.js
  app/javascript/widget/store/modules/specs/conversation/getters.spec.js
  app/javascript/widget/store/modules/specs/conversationAttributes/actions.spec.js
  app/javascript/widget/views/Home.vue
  app/javascript/widget/views/Router.vue
  app/javascript/widget/views/Unread.vue
  app/views/api/v1/widget/conversations/index.json.jbuilder
  config/routes.rb
  spec/controllers/api/v1/widget/conversations_controller_spec.rb
  spec/factories/conversations.rb
Labels: PR: unreviewed

#1015 Chore: Refactor round robin logic
  .rubocop.yml
  .rubocop_todo.yml
  app/models/conversation.rb
  app/models/inbox.rb
  app/models/inbox_member.rb
  app/models/message.rb
  app/services/round_robin/assignment_service.rb
  app/services/round_robin/manage_service.rb
  app/workers/conversation_reply_email_worker.rb
  config/initializers/redis.rb
  config/puma.rb
  db/migrate/20170525104650_round_robin.rb
  lib/constants/redis_keys.rb
  lib/online_status_tracker.rb
  lib/redis/alfred.rb
  lib/redis/redis_keys.rb
  spec/models/conversation_spec.rb
  spec/services/round_robin/manage_service_spec.rb
Labels: PR: unreviewed

#1019 Feature: Add support for options in form
  app/javascript/shared/components/ChatForm.vue
  app/javascript/widget/assets/scss/_forms.scss
  app/javascript/widget/components/AgentMessageBubble.vue
Labels: PR: reviewed-approved

#1023 Chore: Update copy on Signup page
  app/javascript/dashboard/components/widgets/ChannelItem.vue
  app/javascript/dashboard/routes/auth/Signup.vue
  semantic.yml
Labels: PR: reviewed-approved

#1024 Chore: Migration fix for feature flags
  config/app.yml
  db/migrate/20200709145000_remove_multiple_feature_flags.rb
  db/schema.rb
  lib/config_loader.rb
Labels: PR: reviewed-approved

#1017 Feature: Add persian translation
  app/javascript/dashboard/i18n/index.js
  app/javascript/dashboard/i18n/locale/fa/agentMgmt.json
  app/javascript/dashboard/i18n/locale/fa/cannedMgmt.json
  app/javascript/dashboard/i18n/locale/fa/chatlist.json
  app/javascript/dashboard/i18n/locale/fa/contact.json
  app/javascript/dashboard/i18n/locale/fa/conversation.json
  app/javascript/dashboard/i18n/locale/fa/generalSettings.json
  app/javascript/dashboard/i18n/locale/fa/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/fa/index.js
  app/javascript/dashboard/i18n/locale/fa/integrations.json
  app/javascript/dashboard/i18n/locale/fa/login.json
  app/javascript/dashboard/i18n/locale/fa/report.json
  app/javascript/dashboard/i18n/locale/fa/resetPassword.json
  app/javascript/dashboard/i18n/locale/fa/setNewPassword.json
  app/javascript/dashboard/i18n/locale/fa/settings.json
  app/javascript/dashboard/i18n/locale/fa/signup.json
  app/javascript/dashboard/i18n/locale/fa/webhooks.json
  app/javascript/widget/i18n/index.js
  app/javascript/widget/i18n/locale/fa.json
  config/initializers/languages.rb
  config/locales/devise.fa.yml
  config/locales/fa.yml
Labels: PR: reviewed-approved

#1030 Update Heroku deploy
  app.json
Labels: PR: partially-approved

#1032 Chore: Add docs on supported features per channel
  docs/channels/supported-features.md
Labels: PR: reviewed-approved

#1034 Chore: Update PostgreSQL version to 12
  app.json
  docker-compose.production.yaml
  docker-compose.yaml
Labels: PR: unreviewed

#1036 fixed db:migrate RoundRobin dup
  db/migrate/20170525104650_create_round_robin.rb
Labels: PR: unreviewed

#1035 Made some grammatical changes
  README.md
Labels: PR: unreviewed

#1049 Enhancement: Ability to send out an email without summary (#1048)
  app/mailers/conversation_reply_mailer.rb
  app/views/mailers/conversation_reply_mailer/reply_without_summary.html.erb
  app/workers/conversation_reply_email_worker.rb
  spec/factories/messages.rb
  spec/mailers/conversation_reply_mailer_spec.rb
  spec/workers/conversation_reply_email_worker_spec.rb
Labels: PR: unreviewed

#1050 Bug: Fix translated keys for availability statuses in Greek
  app/javascript/dashboard/i18n/locale/el/settings.json
  app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
Labels: PR: reviewed-approved

#1051 Chore: Cleanup attachment handling for Facebook & Whatsapp
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/shared/helpers/KeyboardHelpers.js
  app/javascript/shared/helpers/MessageFormatter.js
  app/javascript/shared/helpers/MessageTypeHelper.js
  app/javascript/shared/helpers/specs/KeyboardHelpers.spec.js
  app/jobs/send_reply_job.rb
  app/models/message.rb
  app/services/facebook/send_on_facebook_service.rb
  docs/channels/supported-features.md
  spec/factories/messages.rb
  spec/services/facebook/send_on_facebook_service_spec.rb
  spec/services/twilio/send_on_twilio_service_spec.rb
  spec/services/twitter/send_on_twitter_service_spec.rb
Labels: PR: unreviewed

#1054 Make minor grammatical changes
  docs/development/environment-setup/windows.md
Labels: PR: reviewed-approved

#1060 Chore: Change the prefix in reply emails
  app/mailboxes/application_mailbox.rb
  app/mailboxes/conversation_mailbox.rb
  app/mailers/conversation_reply_mailer.rb
  spec/fixtures/files/reply.eml
  spec/mailers/conversation_reply_mailer_spec.rb
Labels: PR: partially-approved

#1064 Chore: Move email configs to ENV variables
  .env.example
  app/mailers/conversation_reply_mailer.rb
  config/installation_config.yml
  spec/mailers/conversation_reply_mailer_spec.rb
Labels: PR: reviewed-approved

#1041 Chore: Enable bot conversations in status dropdown
  app/javascript/dashboard/constants.js
  app/javascript/dashboard/i18n/locale/en/chatlist.json
Labels: PR: reviewed-approved

#1065 Chore: Feature lock email settings in UI
  app/controllers/api/v1/accounts_controller.rb
  app/javascript/dashboard/i18n/locale/en/generalSettings.json
  app/javascript/dashboard/routes/dashboard/settings/account/Index.vue
  app/mailers/conversation_reply_mailer.rb
  app/models/account.rb
  app/models/concerns/featurable.rb
  app/views/api/v1/accounts/show.json.jbuilder
  app/views/api/v1/accounts/update.json.jbuilder
  app/views/mailers/conversation_reply_mailer/reply_without_summary.html.erb
  db/migrate/20200709145000_remove_multiple_feature_flags.rb
  spec/controllers/api/v1/accounts_controller_spec.rb
  spec/factories/accounts.rb
  spec/mailers/conversation_reply_mailer_spec.rb
Labels: PR: partially-approved

#1068 Bugfix: Private notes in emails & broken Signup
  app/mailers/conversation_reply_mailer.rb
  app/models/concerns/featurable.rb
  app/models/message.rb
  spec/mailers/conversation_reply_mailer_spec.rb
Labels: PR: reviewed-approved

#1071 Enhancement: Remove v-model.trim from reply box
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: partially-approved

#1070 Fix grammatical issues in Ubuntu Environment Setup
  docs/development/environment-setup/ubuntu.md
Labels: PR: unreviewed

#1067 Chore: Minor Fixes and Improvements
  app/controllers/api/v1/widget/base_controller.rb
  app/controllers/api/v1/widget/events_controller.rb
  app/controllers/api/v1/widget/messages_controller.rb
  app/dashboards/user_dashboard.rb
  app/models/user.rb
  app/views/api/v1/models/_user.json.jbuilder
  db/migrate/20200719171437_rename_nick_name_to_display_name.rb
  db/schema.rb
  docs/deployment/production/linux-vm.md
  spec/controllers/api/v1/widget/events_controller_spec.rb
  spec/factories/users.rb
  swagger/definitions/resource/user.yml
  swagger/swagger.json
Labels: PR: reviewed-approved

#1072 Chore: Run ConfigLoader on migrate
  config/installation_config.yml
  lib/tasks/db_enhancements.rake
Labels: PR: reviewed-approved

#1052 Feature: Additional Channel Types
  app/builders/messages/facebook/message_builder.rb
  app/builders/messages/incoming_message_builder.rb
  app/builders/messages/message_builder.rb
  app/builders/messages/outgoing/echo_builder.rb
  app/builders/messages/outgoing/normal_builder.rb
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/controllers/api/v1/accounts/conversations/messages_controller.rb
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/javascript/dashboard/assets/images/channels/api.png
  app/javascript/dashboard/assets/images/channels/email.png
  app/javascript/dashboard/components/layout/SidebarItem.vue
  app/javascript/dashboard/components/widgets/ChannelItem.vue
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channel-factory.js
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Api.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Email.vue
  app/javascript/dashboard/store/modules/inboxes.js
  app/listeners/webhook_listener.rb
  app/models/account.rb
  app/models/channel/api.rb
  app/models/channel/email.rb
  app/models/channel/facebook_page.rb
  app/views/api/v1/accounts/contacts/create.json.jbuilder
  app/views/api/v1/accounts/inboxes/create.json.jbuilder
  app/views/api/v1/accounts/inboxes/index.json.jbuilder
  app/views/api/v1/accounts/inboxes/update.json.jbuilder
  app/views/api/v1/models/_inbox.json.jbuilder
  db/migrate/20200627115105_create_api_channel.rb
  db/migrate/20200715124113_create_email_channel.rb
  db/schema.rb
  lib/integrations/facebook/message_creator.rb
  lib/webhooks/trigger.rb
  spec/builders/messages/facebook/message_builder_spec.rb
  spec/builders/messages/message_builder_spec.rb
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
  spec/factories/channel/channel_api.rb
  spec/lib/webhooks/trigger_spec.rb
Labels: PR: reviewed-approved

#1076 Bug: Fixed quoted text parsing in incoming email
  app/presenters/mail_presenter.rb
Labels: PR: reviewed-approved

#1078 Chore: Cypress Tests
  .gitignore
  Gemfile
  Gemfile.lock
  Procfile.test
  app/javascript/dashboard/components/buttons/FormSubmitButton.vue
  app/javascript/dashboard/routes/login/Login.vue
  config/initializers/cypress_on_rails.rb
  docs/README.md
  docs/development/project-setup/quick-setup.md
  package.json
  spec/cypress.json
  spec/cypress/app_commands/activerecord_fixtures.rb
  spec/cypress/app_commands/clean.rb
  spec/cypress/app_commands/eval.rb
  spec/cypress/app_commands/factory_bot.rb
  spec/cypress/app_commands/load_seed.rb
  spec/cypress/app_commands/log_fail.rb
  spec/cypress/app_commands/scenarios/default.rb
  spec/cypress/cypress_helper.rb
  spec/cypress/integration/happy_paths/admin_dashboard_authentication.js
  spec/cypress/plugins/index.js
  spec/cypress/support/commands.js
  spec/cypress/support/index.js
  spec/cypress/support/on-rails.js
  yarn.lock
Labels: PR: reviewed-approved

#1082 Chore: Update storage to support s3 compatible services
  config/environments/development.rb
  config/storage.yml
  docs/development/project-setup/configuring-cloud-storage.md
Labels: PR: unreviewed

#1087 Chore: Remove selectedChat from store
  app/javascript/dashboard/components/widgets/conversation/EmptyState.vue
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/getters.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/modules/specs/conversations/getters.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
Labels: PR: unreviewed

#1091 feat: Add `chatwoot:ready` event listener on window
  app/javascript/sdk/IFrameHelper.js
  app/javascript/shared/helpers/CustomEventHelper.js
  app/javascript/shared/helpers/specs/CustomEventHelper.spec.js
  app/views/widget_tests/index.html.erb
  docs/channels/website-sdk.md
Labels: PR: partially-approved

#1084 fix: Add a check for 24 hour window before sending a message
  .scss-lint.yml
  app/javascript/dashboard/api/inbox/message.js
  app/javascript/dashboard/assets/scss/_variables.scss
  app/javascript/dashboard/assets/scss/app.scss
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/shared/assets/stylesheets/colors.scss
  app/javascript/shared/assets/stylesheets/font-size.scss
  app/javascript/shared/assets/stylesheets/spacing.scss
  app/models/channel/api.rb
  app/models/channel/email.rb
  app/models/channel/facebook_page.rb
  app/models/channel/twilio_sms.rb
  app/models/channel/twitter_profile.rb
  app/models/channel/web_widget.rb
  app/models/conversation.rb
  app/presenters/conversations/event_data_presenter.rb
  app/views/api/v1/conversations/partials/_conversation.json.jbuilder
  spec/models/conversation_spec.rb
  spec/presenters/conversations/event_data_presenter_spec.rb
Labels: PR: unreviewed

#1094 Fix files in Channels: /website-sdk.md + /whatsapp-sms-twilio.md
  docs/channels/website-sdk.md
  docs/channels/whatsapp-sms-twilio.md
Labels: PR: reviewed-approved

#985 feat: Ability for the logged in user to create a new account
  app/builders/account_builder.rb
  app/controllers/api/v1/accounts_controller.rb
  app/controllers/dashboard_controller.rb
  app/javascript/dashboard/api/account.js
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/store/modules/accounts.js
  app/javascript/dashboard/store/modules/specs/account/actions.spec.js
  app/javascript/shared/store/globalConfig.js
  app/models/user.rb
  app/views/api/v1/accounts/create.json.jbuilder
  config/installation_config.yml
  spec/controllers/api/v1/accounts_controller_spec.rb
Labels: PR: unreviewed

#1096 chore: Add showBadge prop to tabs-item component
  app/javascript/dashboard/components/ui/Tabs/Tabs.js
  app/javascript/dashboard/components/ui/Tabs/TabsItem.vue
Labels: PR: reviewed-approved

#1097 feat: Use display_name instead of name of the agent
  app/controllers/api/v1/profiles_controller.rb
  app/javascript/dashboard/api/auth.js
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
  app/javascript/dashboard/store/modules/conversations/getters.js
  app/mailers/conversation_reply_mailer.rb
  app/models/conversation.rb
  app/models/user.rb
  app/presenters/conversations/event_data_presenter.rb
  app/views/api/v1/accounts/inbox_members/show.json.jbuilder
  app/views/api/v1/conversations/partials/_conversation.json.jbuilder
  app/views/api/v1/models/_agent.json.jbuilder
  app/views/api/v1/models/_user.json.jbuilder
  app/views/api/v1/widget/inbox_members/index.json.jbuilder
  app/views/mailers/conversation_reply_mailer/reply_with_summary.html.erb
  spec/mailers/conversation_reply_mailer_spec.rb
  spec/models/conversation_spec.rb
Labels: PR: partially-approved

#1103 chore: Update mailer to remove hardcoded Twitter links
  app/controllers/widgets_controller.rb
  app/javascript/shared/store/globalConfig.js
  app/javascript/widget/components/Branding.vue
  app/mailers/application_mailer.rb
  app/views/layouts/mailer.html.erb
  config/installation_config.yml
Labels: PR: reviewed-approved

#1106 bug: Fix emails if assignee is nil
  app/mailers/conversation_reply_mailer.rb
  spec/mailers/conversation_reply_mailer_spec.rb
Labels: PR: partially-approved
