Repository chatwoot/chatwoot, pull requests merged in 2020-08, with the labels that each got.

#1110 chore: Update the usage of available_name instead of name
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/widget/components/AgentMessage.vue
  app/mailers/agent_notifications/conversation_notifications_mailer.rb
  app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_assignment.html.erb
  app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_creation.html.erb
  app/views/mailers/conversation_reply_mailer/reply_with_summary.html.erb
  spec/mailers/agent_notifications/conversation_notifications_mailer_spec.rb
Labels: PR: partially-approved

#1112 chore: Add an indicator for incoming emails
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Audio.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/File.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Image.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Map.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Text.vue
  app/javascript/dashboard/i18n/locale/en/chatlist.json
  app/javascript/shared/constants/contentType.js
  app/javascript/shared/mixins/contentTypeMixin.js
  app/javascript/shared/mixins/specs/contentTypeMixin.spec.js
  app/views/api/v1/accounts/conversations/messages/index.json.jbuilder
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#1113 chore: Fix scroll in message view
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
Labels: PR: reviewed-approved

#1115 fix: Move integration logos out of public/assets
  app/javascript/dashboard/routes/dashboard/settings/integrations/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/Integration.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/ShowIntegration.vue
  config/integration/apps.yml
  public/dashboard/images/integrations/cable.svg
  public/dashboard/images/integrations/slack.png
Labels: PR: reviewed-approved

#1114 fix: Use server timestamp to set agent_last_seen_at
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/javascript/dashboard/api/inbox/conversation.js
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/routes/dashboard/conversation/labels/LabelBox.vue
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js
  app/views/api/v1/accounts/conversations/update_last_seen.json.jbuilder
  db/migrate/20200802170002_reset_agent_last_seen_at.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
Labels: PR: unreviewed

#1102 feat: Disable attachments and emoji picker in the web widget
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/javascript/dashboard/assets/scss/_layout.scss
  app/javascript/dashboard/assets/scss/views/settings/inbox.scss
  app/javascript/dashboard/components/ModalHeader.vue
  app/javascript/dashboard/components/layout/SidebarItem.vue
  app/javascript/dashboard/components/widgets/ChannelItem.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/AddAgents.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/store/modules/inboxes.js
  app/javascript/shared/mixins/inboxMixin.js
  app/javascript/shared/mixins/specs/inboxMixin.spec.js
  app/javascript/widget/components/ChatInputWrap.vue
  app/javascript/widget/mixins/configMixin.js
  app/javascript/widget/mixins/specs/configMixin.spec.js
  app/models/channel/web_widget.rb
  app/models/inbox.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  app/views/widgets/show.html.erb
  db/migrate/20200730080242_add_feature_setting_to_website_inbox.rb
  db/schema.rb
Labels: PR: reviewed-approved

#1095 feat: Customisable Email Templates
  Gemfile
  Gemfile.lock
  app/drops/account_drop.rb
  app/drops/base_drop.rb
  app/drops/conversation_drop.rb
  app/drops/inbox_drop.rb
  app/drops/user_drop.rb
  app/mailers/agent_notifications/conversation_notifications_mailer.rb
  app/mailers/application_mailer.rb
  app/mailers/conversation_reply_mailer.rb
  app/models/application_record.rb
  app/models/conversation.rb
  app/models/email_template.rb
  app/services/email_templates/db_resolver_service.rb
  app/services/notification/email_notification_service.rb
  app/views/layouts/mailer/base.liquid
  app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_assignment.html.erb
  app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_assignment.liquid
  app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_creation.html.erb
  app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_creation.liquid
  config/initializers/liquid_handler.rb
  db/migrate/20200725131651_create_email_templates.rb
  db/schema.rb
  lib/action_view/template/handlers/liquid.rb
  spec/factories/email_template.rb
  spec/lib/email_templates/db_resolver_service_spec.rb
  spec/mailers/confirmation_instructions_spec.rb
Labels: PR: reviewed-approved

#1129 chore: Use 'Lax' instead of 'None'
  app/javascript/dashboard/store/utils/api.js
  config/initializers/session_store.rb
Labels: PR: reviewed-approved

#1130 chore: Additional Contact APIs
  app/builders/messages/message_builder.rb
  app/controllers/api/v1/accounts/contacts/contact_inboxes_controller.rb
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/policies/contact_policy.rb
  app/views/api/v1/accounts/contacts/contact_inboxes/create.json.jbuilder
  app/views/api/v1/accounts/contacts/search.json.jbuilder
  app/views/api/v1/models/_contact.json.jbuilder
  app/views/api/v1/models/_contact_inbox.json.jbuilder
  config/routes.rb
  spec/controllers/api/v1/accounts/contacts/contact_inboxes_controller_spec.rb
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
Labels: PR: reviewed-approved

#1117 Chore: Add in reply to option for twitter
  .eslintrc.js
  app/builders/messages/message_builder.rb
  app/javascript/dashboard/api/inbox/message.js
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
  app/javascript/dashboard/helper/actionCable.js
  app/javascript/dashboard/i18n/locale/en/chatlist.json
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/shared/constants/busEvents.js
  app/javascript/shared/constants/messageTypes.js
  app/javascript/shared/helpers/MessageFormatter.js
  app/javascript/shared/helpers/specs/MessageFormatter.spec.js
  app/javascript/shared/mixins/alertMixin.js
  app/javascript/shared/mixins/messageFormatterMixin.js
  app/javascript/widget/assets/scss/woot.scss
  app/javascript/widget/components/AgentMessageBubble.vue
  app/javascript/widget/components/UserMessageBubble.vue
  app/models/message.rb
  app/services/twitter/send_on_twitter_service.rb
  spec/factories/messages.rb
  spec/lib/integrations/slack/send_on_slack_service_spec.rb
Labels: PR: reviewed-approved

#1134 Bugfix: add missing option to s3_compatible to support minio
  config/storage.yml
Labels: PR: reviewed-approved

#1141 chore: Add docs on customizing email template content
  docs/customizations/email-notifications.md
Labels: PR: reviewed-approved

#1144 Chore: Enable additional attributes in liquid
  app/drops/user_drop.rb
  app/mailers/application_mailer.rb
  app/mailers/conversation_reply_mailer.rb
  app/views/layouts/mailer/base.liquid
Labels: PR: reviewed-approved

#1146 chore: Add documentation for DATABASE_URL environment variable
  docs/development/project-setup/environment-variables.md
Labels: PR: reviewed-approved

#1149 chore: Update Readme with feature details
  README.md
Labels: PR: reviewed-approved

#1151 chore: update swagger definitions
  swagger/definitions/request/contact/create.yml
  swagger/definitions/request/conversation/create_message.yml
  swagger/paths/contact/list_create.yml
  swagger/swagger.json
Labels: PR: reviewed-approved

#1153 chore: Update API docs
  swagger/definitions/index.yml
  swagger/definitions/resource/account.yml
  swagger/definitions/resource/contact.yml
  swagger/definitions/resource/contact_inboxes.yml
  swagger/definitions/resource/inbox.yml
  swagger/definitions/resource/user.yml
  swagger/paths/contact/search.yml
  swagger/paths/contact_inboxes/create.yml
  swagger/paths/index.yml
  swagger/paths/profile/index.yml
  swagger/swagger.json
Labels: PR: reviewed-approved

#1155 feat: Allow user to change the bubble title using SDK
  app/javascript/packs/sdk.js
  app/javascript/sdk/IFrameHelper.js
  docs/channels/website-sdk.md
Labels: PR: reviewed-approved

#1157 chore: Control rendering contact inbox
  app/views/api/v1/accounts/contacts/create.json.jbuilder
  app/views/api/v1/accounts/contacts/index.json.jbuilder
  app/views/api/v1/accounts/contacts/search.json.jbuilder
  app/views/api/v1/accounts/contacts/show.json.jbuilder
  app/views/api/v1/accounts/contacts/update.json.jbuilder
  app/views/api/v1/models/_contact.json.jbuilder
Labels: PR: reviewed-approved

#1169 chore: General fixes and clean up
  app/builders/messages/facebook/message_builder.rb
  app/controllers/api/v1/accounts/callbacks_controller.rb
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/dispatchers/async_dispatcher.rb
  app/jobs/contact_avatar_job.rb
  app/listeners/installation_webhook_listener.rb
  app/models/account.rb
  app/models/account_user.rb
  app/models/application_record.rb
  app/models/contact.rb
  app/models/conversation.rb
  app/models/message.rb
  app/models/plan.rb
  app/models/user.rb
  app/services/twilio/incoming_message_service.rb
  config/installation_config.yml
  lib/events/types.rb
  lib/webhooks/trigger.rb
  spec/factories/installation_config.rb
  spec/listeners/installation_webhook_listener_spec.rb
  spec/listeners/webhook_listener_spec.rb
  swagger/definitions/request/conversation/create_message.yml
  swagger/swagger.json
Labels: PR: reviewed-approved

#1174 feat: Add a popout option on webwidget
  app/javascript/packs/sdk.js
  app/javascript/sdk/IFrameHelper.js
  app/javascript/widget/App.vue
  app/javascript/widget/assets/scss/_buttons.scss
  app/javascript/widget/assets/scss/woot.scss
  app/javascript/widget/components/ChatHeader.vue
  app/javascript/widget/components/ChatHeaderExpanded.vue
  app/javascript/widget/components/HeaderActions.vue
  app/javascript/widget/helpers/constants.js
  app/javascript/widget/helpers/specs/urlParamsHelper.spec.js
  app/javascript/widget/helpers/specs/utils.spec.js
  app/javascript/widget/helpers/urlParamsHelper.js
  app/javascript/widget/helpers/utils.js
  app/javascript/widget/views/Home.vue
  app/javascript/widget/views/Router.vue
  app/views/widget_tests/index.html.erb
  docs/channels/website-sdk.md
Labels: PR: reviewed-approved

#1175 feat: Enable Slack Integration in all channels
  app/models/message.rb
  app/services/base/send_on_channel_service.rb
  db/migrate/20200828175931_add_external_source_ids_to_messages.rb
  db/schema.rb
  lib/integrations/slack/incoming_message_builder.rb
  lib/integrations/slack/send_on_slack_service.rb
Labels: PR: reviewed-approved

#1177 chore: Fix nil class error at bot endpoint
  lib/integrations/facebook/delivery_status.rb
Labels: PR: reviewed-approved

#1179 chore: Add documentation for API channel
  docs/channels/api-channel/callback-url.md
  docs/channels/api-channel/create-channel.md
  docs/channels/api-channel/images/add-agents.png
  docs/channels/api-channel/images/configure-screen.png
  docs/channels/api-channel/images/conversation.png
  docs/channels/api-channel/images/inbox-welcome-screen.png
  docs/channels/api-channel/images/select-api-inbox.png
  docs/channels/api-channel/images/take-me-there.png
  docs/channels/api-channel/send-message-api-channel.md
Labels: PR: reviewed-approved
