Repository chatwoot/chatwoot, pull requests merged in 2020-05, with the labels that each got.

#803 Bug: Use beginAtZero option for reports
  app/javascript/dashboard/components/widgets/chart/BarChart.js
Labels: Bug

#669 Chore: Remove redis backed reporting
  Gemfile
  Gemfile.lock
  app/builders/report_builder.rb
  app/controllers/api/v1/accounts/reports_controller.rb
  app/dispatchers/async_dispatcher.rb
  app/identities/account_identity.rb
  app/identities/agent_identity.rb
  config/initializers/redis.rb
  config/reports_redis.yml
  config/routes.rb
  lib/constants/report.rb
  lib/custom_exceptions/report.rb
  spec/listeners/reporting_listener_spec.rb
Labels: Backend, Chore

#806 Chore: Moved the email ingress method to an env variable (#777)
  .env.example
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  docs/development/project-setup/conversation-continuity.md
Labels: Chore

#815 Feature: Feature flags on account (#814)
  .codeclimate.yml
  app/javascript/dashboard/routes/dashboard/settings/account/Index.vue
  app/models/account.rb
  app/models/concerns/features.rb
  app/views/api/v1/accounts/show.json.jbuilder
  app/views/api/v1/accounts/update.json.jbuilder
  config/features.yml
  db/migrate/20200503151130_add_account_feature_flag.rb
  db/schema.rb
Labels: Feature

#888 Fixed rspec due to unescaped html check for user name (#887)
  spec/controllers/super_admin/users_controller_spec.rb
Labels: Backend, Bug

#884 Chore: Parse quoted text in incoming emails (#883)
  app/mailboxes/conversation_mailbox.rb
  app/presenters/mail_presenter.rb
  spec/mailboxes/conversation_mailbox_spec.rb
  spec/presenters/mail_presenter_spec.rb
Labels: Enhancement

#886 Chore: Threaded email replies for a conversation (#885)
  app/mailers/conversation_reply_mailer.rb
  config/installation_config.yml
  config/locales/en.yml
  db/migrate/20200522115645_reload_config.rb
  db/schema.rb
  spec/mailers/conversation_reply_mailer_spec.rb
Labels: Chore
