Repository chatwoot/chatwoot, pull requests merged in 2020-12, with the labels that each got.

#1470 fix: Add worker to the formation to avoid default turned off state
  app.json
Labels: PR: partially-approved

#1478 Add translation strings to locale NL for widget
  app/javascript/widget/i18n/locale/nl.json
Labels: PR: unreviewed

#1474 fix: Check if the branch argument is an empty string
  deployment/setup_18.04.sh
  deployment/setup_20.04.sh
Labels: PR: unreviewed

#1483 chore: Upgrade highlight.js to 10.4.1
  app/javascript/dashboard/components/Code.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue
  app/javascript/packs/application.js
  app/models/channel/web_widget.rb
  package.json
  yarn.lock
Labels: PR: unreviewed

#1492 feat: Allow only image, pdf, audio, video,csv on file uploader
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/widget/components/ChatAttachment.vue
Labels: PR: reviewed-approved

#1494 chore: Fix translation issues
  app/javascript/dashboard/i18n/locale/de/conversation.json
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/i18n/locale/en/integrations.json
  app/javascript/dashboard/i18n/locale/fa/conversation.json
  app/javascript/dashboard/i18n/locale/fi/conversation.json
  app/javascript/dashboard/i18n/locale/hi/conversation.json
  app/javascript/dashboard/i18n/locale/hu/conversation.json
  app/javascript/dashboard/i18n/locale/it/conversation.json
  app/javascript/dashboard/i18n/locale/ko/conversation.json
  app/javascript/dashboard/i18n/locale/nl/conversation.json
  app/javascript/dashboard/i18n/locale/pl/conversation.json
  app/javascript/dashboard/i18n/locale/pt/conversation.json
  app/javascript/dashboard/i18n/locale/ro/conversation.json
  app/javascript/dashboard/i18n/locale/sk/conversation.json
  app/javascript/dashboard/i18n/locale/sv/conversation.json
  app/javascript/dashboard/i18n/locale/ta/conversation.json
  app/javascript/dashboard/i18n/locale/uk/conversation.json
  app/javascript/dashboard/i18n/locale/zh/conversation.json
  app/javascript/dashboard/i18n/locale/zh_CN/conversation.json
  app/javascript/dashboard/i18n/locale/zh_TW/conversation.json
Labels: PR: unreviewed

#1500 fix: Display assignee only if the assignee has access to the account
  app/views/api/v1/conversations/partials/_conversation.json.jbuilder
Labels: PR: reviewed-approved

#1501 fix: Move untranslated text to translation files
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/i18n/locale/en/generalSettings.json
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/en/signup.json
  app/javascript/dashboard/routes/auth/Signup.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/AddAgents.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Facebook.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
Labels: PR: unreviewed

#1282 chore: Development Environment with Github Codespaces [alpha]
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .env.example
Labels: PR: unreviewed

#1505 chore: Ignore case while searching contact name, email
  app/controllers/api/v1/accounts/contacts_controller.rb
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
  spec/factories/contacts.rb
Labels: PR: reviewed-approved

#1383 Chore: upgrade vue i18n
  app/controllers/api/v1/widget/base_controller.rb
  app/javascript/dashboard/App.vue
  app/javascript/dashboard/components/layout/specs/AvailabilityStatus.spec.js
  app/javascript/dashboard/components/widgets/conversation/specs/MoreActions.spec.js
  app/javascript/dashboard/routes/dashboard/settings/account/Index.vue
  app/javascript/packs/application.js
  app/javascript/packs/widget.js
  app/javascript/widget/App.vue
  app/javascript/widget/api/specs/endPoints.spec.js
  app/javascript/widget/components/HeaderActions.vue
  app/javascript/widget/helpers/specs/urlParamsHelper.spec.js
  app/javascript/widget/helpers/urlParamsHelper.js
  app/javascript/widget/store/modules/specs/conversation/actions.spec.js
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#1508 chore: Add steps for copying targets in linux VM
  docs/deployment/production/linux-vm.md
Labels: PR: reviewed-approved

#1509 chore: Improve location display in sidebar
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/controllers/widgets_controller.rb
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/EditContact.vue
  app/jobs/contact_ip_lookup_job.rb
  app/models/channel/web_widget.rb
  app/models/contact.rb
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#1512 chore: Update Mac OS setup guide
  docs/development/environment-setup/mac-os.md
  docs/development/project-setup/errors.md
  docs/development/project-setup/quick-setup.md
Labels: PR: reviewed-approved

#1513 chore: Add missing label to locale file
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
Labels: PR: reviewed-approved

#1516 chore: Fix i18n_key for webhooks
  config/integration/apps.yml
Labels: PR: reviewed-approved

#1517 feat: Download Agent wise report
  app/javascript/dashboard/api/reports.js
  app/javascript/dashboard/api/specs/reports.spec.js
  app/javascript/dashboard/i18n/locale/en/report.json
  app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
  app/javascript/dashboard/store/modules/reports.js
  app/javascript/dashboard/store/modules/specs/reports/actions.spec.js
  app/views/api/v2/accounts/reports/agents.csv.erb
  config/locales/en.yml
Labels: PR: partially-approved

#1518 chore: Add documentation for Maxmind geocoder setup
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  docs/self-hosted/enable-ip-logging.md
Labels: PR: reviewed-approved

#1520 fix: Use empty object if additional_attribute is null
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
Labels: PR: reviewed-approved

#1523 Add href to "initiated from" url #1522
  app/javascript/dashboard/routes/dashboard/conversation/ContactDetailsItem.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
Labels: PR: reviewed-approved

#1525 Chore: Fix translation link in docs
  README.md
Labels: PR: reviewed-approved

#1530 chore: Remove account.destroy listener
  app/builders/account_builder.rb
  app/listeners/installation_webhook_listener.rb
  app/models/account.rb
  lib/events/types.rb
  spec/listeners/installation_webhook_listener_spec.rb
Labels: PR: reviewed-approved

#1533 chore: fix add agent select placeholder translation
  app/javascript/dashboard/routes/dashboard/settings/inbox/AddAgents.vue
Labels: PR: reviewed-approved

#1531 feature: smart app banner in website(iOS)
  .env.example
  app/views/layouts/vueapp.html.erb
Labels: PR: reviewed-approved, mobile-app

#1534 feat: Add full name to the user signup form
  app/builders/account_builder.rb
  app/controllers/api/v1/accounts_controller.rb
  app/javascript/dashboard/api/auth.js
  app/javascript/dashboard/assets/scss/_woot.scss
  app/javascript/dashboard/assets/scss/views/_signup.scss
  app/javascript/dashboard/assets/scss/widgets/_forms.scss
  app/javascript/dashboard/components/widgets/forms/Input.vue
  app/javascript/dashboard/i18n/locale/en/signup.json
  app/javascript/dashboard/routes/auth/Signup.vue
  spec/controllers/api/v1/accounts_controller_spec.rb
Labels: PR: partially-approved

#1528 enhancement: change the date format in widget
  app/javascript/shared/components/DateSeparator.vue
  app/javascript/shared/components/specs/DateSeparator.spec.js
  app/javascript/shared/components/specs/__snapshots__/DateSeparator.spec.js.snap
  app/javascript/shared/helpers/DateHelper.js
  app/javascript/shared/helpers/specs/DateHelper.sepc.js
  app/javascript/shared/helpers/specs/DateHelper.spec.js
  app/javascript/widget/i18n/locale/en.json
Labels: PR: unreviewed

#1547 Enhancement 731- Add pending message view for text messages
  app/javascript/dashboard/api/inbox/message.js
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
  app/javascript/dashboard/helper/commons.js
  app/javascript/dashboard/helper/specs/commons.spec.js
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/helpers.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/modules/specs/conversations/helpers.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/shared/assets/stylesheets/colors.scss
  app/javascript/shared/constants/messageTypes.js
  app/javascript/shared/constants/messages.js
  app/views/api/v1/accounts/conversations/messages/create.json.jbuilder
  app/views/api/v1/accounts/conversations/messages/index.json.jbuilder
  app/views/api/v1/models/_message.json.jbuilder
Labels: PR: reviewed-approved

#1552 Fix:1540 Contacts: Remove beta, update the styles
  app/javascript/dashboard/i18n/default-sidebar.js
  app/javascript/dashboard/i18n/locale/ar/settings.json
  app/javascript/dashboard/i18n/locale/ca/settings.json
  app/javascript/dashboard/i18n/locale/cs/settings.json
  app/javascript/dashboard/i18n/locale/da/settings.json
  app/javascript/dashboard/i18n/locale/de/settings.json
  app/javascript/dashboard/i18n/locale/el/settings.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/i18n/locale/es/settings.json
  app/javascript/dashboard/i18n/locale/fa/settings.json
  app/javascript/dashboard/i18n/locale/fi/settings.json
  app/javascript/dashboard/i18n/locale/fr/settings.json
  app/javascript/dashboard/i18n/locale/hi/settings.json
  app/javascript/dashboard/i18n/locale/hu/settings.json
  app/javascript/dashboard/i18n/locale/id/settings.json
  app/javascript/dashboard/i18n/locale/it/settings.json
  app/javascript/dashboard/i18n/locale/ja/settings.json
  app/javascript/dashboard/i18n/locale/ko/settings.json
  app/javascript/dashboard/i18n/locale/ml/settings.json
  app/javascript/dashboard/i18n/locale/nl/settings.json
  app/javascript/dashboard/i18n/locale/pl/settings.json
  app/javascript/dashboard/i18n/locale/pt/settings.json
  app/javascript/dashboard/i18n/locale/pt_BR/settings.json
  app/javascript/dashboard/i18n/locale/ro/settings.json
  app/javascript/dashboard/i18n/locale/ru/settings.json
  app/javascript/dashboard/i18n/locale/sk/settings.json
  app/javascript/dashboard/i18n/locale/sv/settings.json
  app/javascript/dashboard/i18n/locale/ta/settings.json
  app/javascript/dashboard/i18n/locale/th/settings.json
  app/javascript/dashboard/i18n/locale/tr/settings.json
  app/javascript/dashboard/i18n/locale/uk/settings.json
  app/javascript/dashboard/i18n/locale/vi/settings.json
  app/javascript/dashboard/i18n/locale/zh_CN/settings.json
  app/javascript/dashboard/i18n/locale/zh_TW/settings.json
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
Labels: PR: partially-approved

#1554 chore: Remove Ionicons TTF references
  app/javascript/dashboard/assets/scss/app.scss
  app/javascript/dashboard/assets/scss/super_admin/pages.scss
  app/javascript/shared/assets/stylesheets/ionicons.scss
  app/javascript/widget/assets/scss/woot.scss
Labels: PR: partially-approved

#1553 chore: Use font subsetting for Inter
  app/javascript/shared/assets/fonts/Inter-Bold.woff
  app/javascript/shared/assets/fonts/Inter-Bold.woff2
  app/javascript/shared/assets/fonts/Inter-Italic.woff
  app/javascript/shared/assets/fonts/Inter-Italic.woff2
  app/javascript/shared/assets/fonts/Inter-Light-BETA.woff
  app/javascript/shared/assets/fonts/Inter-Light-BETA.woff2
  app/javascript/shared/assets/fonts/Inter-Light.woff
  app/javascript/shared/assets/fonts/Inter-Light.woff2
  app/javascript/shared/assets/fonts/Inter-Medium.woff
  app/javascript/shared/assets/fonts/Inter-Medium.woff2
  app/javascript/shared/assets/fonts/Inter-Regular.woff
  app/javascript/shared/assets/fonts/Inter-Regular.woff2
  app/javascript/shared/assets/fonts/Inter-SemiBold.woff
  app/javascript/shared/assets/fonts/Inter-SemiBold.woff2
  app/javascript/shared/assets/fonts/Inter-Thin-BETA.woff
  app/javascript/shared/assets/fonts/Inter-Thin-BETA.woff2
  app/javascript/shared/assets/fonts/Inter-Thin.woff
  app/javascript/shared/assets/fonts/Inter-Thin.woff2
  app/javascript/shared/assets/fonts/inter.scss
  app/javascript/shared/assets/fonts/widget_fonts.scss
Labels: PR: partially-approved

#1559 chore: Add limitations section to Heroku
  docs/deployment/production/heroku.md
Labels: PR: reviewed-approved

#1560 chore: Add docs about GCS Storage
  docs/development/project-setup/storage/s3-bucket.md
  docs/self-hosted/enable-ip-logging.md
  docs/self-hosted/storage/configuring-gcs.md
  docs/self-hosted/storage/images/create-a-bucket.png
  docs/self-hosted/storage/images/get-your-project-id.png
  docs/self-hosted/storage/images/json.png
  docs/self-hosted/storage/images/permissions.png
  docs/self-hosted/storage/images/storage-admin.png
Labels: PR: reviewed-approved

#1353 feat: API to allow agents to delete a message
  app/controllers/api/v1/accounts/conversations/messages_controller.rb
  app/models/message.rb
  app/views/api/v1/accounts/conversations/messages/destroy.json.jbuilder
  config/locales/en.yml
  config/routes.rb
  spec/controllers/api/v1/accounts/conversations/messages_controller_spec.rb
Labels: PR: reviewed-approved

#1569 fix: Update `listen` gem
  Gemfile.lock
Labels: PR: unreviewed

#1570 fix: Remove Twitter links rendered in messages
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
Labels: PR: unreviewed
