Repository chatwoot/chatwoot, pull requests merged in 2020-10, with the labels that each got.

#1293 add: self-assign conversation activity message
  app/models/conversation.rb
  config/locales/en.yml
  spec/models/conversation_spec.rb
Labels: PR: partially-approved

#1295 fix(1296): Call hasUserKeys() with user argument
  app/javascript/packs/sdk.js
Labels: PR: reviewed-approved

#1288 Feature/1234 change availability status from sidebar
  app/javascript/dashboard/api/auth.js
  app/javascript/dashboard/components/layout/AvailabilityStatus.vue
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/specs/AvailabilityStatus.spec.js
  app/javascript/dashboard/i18n/locale/ar/settings.json
  app/javascript/dashboard/i18n/locale/ca/settings.json
  app/javascript/dashboard/i18n/locale/cs/settings.json
  app/javascript/dashboard/i18n/locale/da/settings.json
  app/javascript/dashboard/i18n/locale/de/settings.json
  app/javascript/dashboard/i18n/locale/el/settings.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/i18n/locale/es/settings.json
  app/javascript/dashboard/i18n/locale/fa/settings.json
  app/javascript/dashboard/i18n/locale/fi/settings.json
  app/javascript/dashboard/i18n/locale/fr/settings.json
  app/javascript/dashboard/i18n/locale/hi/settings.json
  app/javascript/dashboard/i18n/locale/hu/settings.json
  app/javascript/dashboard/i18n/locale/it/settings.json
  app/javascript/dashboard/i18n/locale/ja/settings.json
  app/javascript/dashboard/i18n/locale/ko/settings.json
  app/javascript/dashboard/i18n/locale/ml/settings.json
  app/javascript/dashboard/i18n/locale/nl/settings.json
  app/javascript/dashboard/i18n/locale/pl/settings.json
  app/javascript/dashboard/i18n/locale/pt/settings.json
  app/javascript/dashboard/i18n/locale/pt_BR/settings.json
  app/javascript/dashboard/i18n/locale/ro/settings.json
  app/javascript/dashboard/i18n/locale/ru/settings.json
  app/javascript/dashboard/i18n/locale/sk/settings.json
  app/javascript/dashboard/i18n/locale/sv/settings.json
  app/javascript/dashboard/i18n/locale/ta/settings.json
  app/javascript/dashboard/i18n/locale/th/settings.json
  app/javascript/dashboard/i18n/locale/tr/settings.json
  app/javascript/dashboard/i18n/locale/uk/settings.json
  app/javascript/dashboard/i18n/locale/vi/settings.json
  app/javascript/dashboard/i18n/locale/zh/settings.json
  app/javascript/dashboard/i18n/locale/zh_CN/settings.json
  app/javascript/dashboard/i18n/locale/zh_TW/settings.json
  app/javascript/dashboard/store/modules/auth.js
Labels: PR: reviewed-approved

#1292 Update vi locales with translation for Vietnamese
  config/locales/devise.vi.yml
  config/locales/vi.yml
Labels: PR: reviewed-approved

#1297 Refactor `DeviseOverrides::ConfirmationsController#create`
  app/controllers/devise_overrides/confirmations_controller.rb
  spec/controllers/devise/confirmations_controller_spec.rb
Labels: PR: unreviewed

#1291 feat: Activity message for label addition/deletion
  app/models/conversation.rb
  config/locales/en.yml
  spec/models/conversation_spec.rb
Labels: PR: reviewed-approved

#1302 fix: Fixing failing tests post introduction of last_activity_at in conversations
  spec/models/conversation_spec.rb
  spec/presenters/conversations/event_data_presenter_spec.rb
Labels: PR: unreviewed

#1300 fix: array length check
  app/javascript/dashboard/components/widgets/ChannelItem.vue
Labels: PR: reviewed-approved

#1301 add: support for redis sentinel
  .env.example
  config/initializers/redis.rb
Labels: PR: partially-approved

#1307 feat: use gravatar if no avatar image
  app/models/user.rb
Labels: PR: reviewed-approved

#1311 resolve #1303 Replace Whatsapp inbox icon
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/SidebarItem.vue
Labels: PR: partially-approved

#1306 Fixed word break in file with long name in agent conversation view.
  app/javascript/dashboard/components/widgets/conversation/bubble/File.vue
Labels: PR: reviewed-approved

#1310 refactor: redis config
  config/initializers/redis.rb
  config/initializers/sidekiq.rb
  lib/redis/config.rb
  spec/lib/redis/config_spec.rb
Labels: PR: unreviewed

#1214 chore: Prevent I18n config bleeding across requests
  app/controllers/api/v1/accounts/base_controller.rb
  app/controllers/api/v1/widget/base_controller.rb
  app/controllers/api/v1/widget/labels_controller.rb
  app/controllers/api/v1/widget/messages_controller.rb
  app/controllers/application_controller.rb
  app/mailers/application_mailer.rb
Labels: PR: unreviewed

#1312 Translation for vietnamese
  app/javascript/dashboard/i18n/locale/vi/agentMgmt.json
  app/javascript/dashboard/i18n/locale/vi/cannedMgmt.json
  app/javascript/dashboard/i18n/locale/vi/chatlist.json
  app/javascript/dashboard/i18n/locale/vi/contact.json
  app/javascript/dashboard/i18n/locale/vi/conversation.json
  app/javascript/dashboard/i18n/locale/vi/generalSettings.json
  app/javascript/dashboard/i18n/locale/vi/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/vi/integrations.json
  app/javascript/dashboard/i18n/locale/vi/labelsMgmt.json
  app/javascript/dashboard/i18n/locale/vi/login.json
  app/javascript/dashboard/i18n/locale/vi/report.json
  app/javascript/dashboard/i18n/locale/vi/resetPassword.json
  app/javascript/dashboard/i18n/locale/vi/setNewPassword.json
  app/javascript/dashboard/i18n/locale/vi/settings.json
  app/javascript/dashboard/i18n/locale/vi/signup.json
  app/javascript/dashboard/i18n/locale/vi/webhooks.json
Labels: PR: reviewed-approved

#1281 fix: Use last_activity_at instead of updated_at for sorting
  app/javascript/dashboard/store/modules/conversations/index.js
  app/models/conversation.rb
  app/models/message.rb
  app/presenters/conversations/event_data_presenter.rb
  app/views/api/v1/accounts/conversations/search.json.jbuilder
  app/views/api/v1/conversations/partials/_conversation.json.jbuilder
  db/migrate/20200927135222_add_last_activity_at_to_conversation.rb
  db/schema.rb
  spec/models/conversation_spec.rb
  spec/models/message_spec.rb
  spec/presenters/conversations/event_data_presenter_spec.rb
Labels: PR: unreviewed

#1314 chore: Enable Vietnamese in languages
  config/initializers/languages.rb
Labels: PR: unreviewed

#1313 feat: API to get the active contacts
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/policies/contact_policy.rb
  app/views/api/v1/accounts/contacts/active.json.jbuilder
  config/routes.rb
  lib/online_status_tracker.rb
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
Labels: PR: reviewed-approved

#1316 fix: Add default 404 param on gravatar
  app/models/user.rb
Labels: PR: reviewed-approved

#1320 Bug: Fix 1196 Integrations page is broken on safari
  app/javascript/dashboard/assets/scss/views/settings/integrations.scss
Labels: PR: reviewed-approved

#1319 Feature/937 unmute muted contacts
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/javascript/dashboard/api/inbox/conversation.js
  app/javascript/dashboard/api/specs/inbox/conversation.spec.js
  app/javascript/dashboard/components/widgets/conversation/MoreActions.vue
  app/javascript/dashboard/components/widgets/conversation/specs/MoreActions.spec.js
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/mutation-types.js
  app/models/conversation.rb
  config/routes.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
  spec/models/conversation_spec.rb
Labels: PR: reviewed-approved

#1329 fix: Security: CVE-2020-8264 (#1328)
  Gemfile.lock
  config/environments/development.rb
Labels: PR: reviewed-approved

#1327 chore: refactored redis config (sentinel related)
  lib/redis/config.rb
  spec/lib/redis/config_spec.rb
Labels: PR: reviewed-approved

#1326 chore: update contribution guidelines
  docs/contributing.md
Labels: PR: reviewed-approved

#1331 chore: Block Search bots from rendering widget
  public/robots.txt
Labels: PR: unreviewed

#1333 chore: Use agent partial instead of user in conversation API
  app/views/api/v1/conversations/partials/_conversation.json.jbuilder
Labels: PR: partially-approved

#1309 Fixed long label names getting broken in the sidebar
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/SidebarItem.vue
Labels: PR: unreviewed

#1334 chore: Handle exceptions on external URL calls
  app/builders/messages/facebook/message_builder.rb
  app/controllers/api/v1/accounts/callbacks_controller.rb
  app/jobs/contact_avatar_job.rb
  app/services/twilio/incoming_message_service.rb
  lib/exception_list.rb
  lib/webhooks/trigger.rb
Labels: PR: unreviewed

#1332 fix: Remove duplicate message in slow networks
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
Labels: PR: unreviewed

#1336 feat: Allow custom email address for inbox
  app/mailers/conversation_reply_mailer.rb
  app/models/inbox.rb
  db/migrate/20201011152227_add_email_address_to_inbox.rb
  db/schema.rb
  spec/mailers/conversation_reply_mailer_spec.rb
Labels: PR: reviewed-approved

#1339 Use full name in activity messages, fix specs
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/models/conversation.rb
  spec/models/conversation_spec.rb
Labels: PR: reviewed-approved

#1340 chore: Reduce the click area on Branding
  app/javascript/sdk/IFrameHelper.js
  app/javascript/shared/constants/busEvents.js
  app/javascript/widget/App.vue
  app/javascript/widget/api/endPoints.js
  app/javascript/widget/components/Branding.vue
Labels: PR: unreviewed

#1344 Improve mobile styling of registration view a bit
  app/javascript/dashboard/routes/auth/Signup.vue
Labels: PR: reviewed-approved

#1342 Update Spanish translation
  app/javascript/dashboard/i18n/locale/es/agentMgmt.json
  app/javascript/dashboard/i18n/locale/es/cannedMgmt.json
  app/javascript/dashboard/i18n/locale/es/chatlist.json
  app/javascript/dashboard/i18n/locale/es/contact.json
  app/javascript/dashboard/i18n/locale/es/conversation.json
  app/javascript/dashboard/i18n/locale/es/generalSettings.json
  app/javascript/dashboard/i18n/locale/es/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/es/integrations.json
  app/javascript/dashboard/i18n/locale/es/labelsMgmt.json
  app/javascript/dashboard/i18n/locale/es/login.json
  app/javascript/dashboard/i18n/locale/es/report.json
  app/javascript/dashboard/i18n/locale/es/resetPassword.json
  app/javascript/dashboard/i18n/locale/es/setNewPassword.json
  app/javascript/dashboard/i18n/locale/es/settings.json
  app/javascript/dashboard/i18n/locale/es/signup.json
Labels: PR: unreviewed

#1349 feat: Display reply time in widget
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/controllers/api/v1/widget/base_controller.rb
  app/javascript/dashboard/assets/scss/_foundation-custom.scss
  app/javascript/dashboard/assets/scss/app.scss
  app/javascript/dashboard/components/widgets/Label.vue
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/auth/Signup.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/shared/assets/fonts/widget_fonts.scss
  app/javascript/shared/components/Button.vue
  app/javascript/shared/components/ResizableTextArea.vue
  app/javascript/shared/helpers/ColorHelper.js
  app/javascript/widget/assets/scss/_variables.scss
  app/javascript/widget/assets/scss/woot.scss
  app/javascript/widget/components/AgentTypingBubble.vue
  app/javascript/widget/components/AvailableAgents.vue
  app/javascript/widget/components/ChatHeader.vue
  app/javascript/widget/components/ChatHeaderExpanded.vue
  app/javascript/widget/components/ChatSendButton.vue
  app/javascript/widget/components/GroupedAvatars.vue
  app/javascript/widget/components/HeaderActions.vue
  app/javascript/widget/components/TeamAvailability.vue
  app/javascript/widget/i18n/locale/en.json
  app/javascript/widget/mixins/agentMixin.js
  app/javascript/widget/mixins/configMixin.js
  app/javascript/widget/mixins/specs/agentMixin.spec.js
  app/javascript/widget/mixins/teamAvailabilityMixin.js
  app/javascript/widget/views/Home.vue
  app/javascript/widget/views/Unread.vue
  app/models/channel/web_widget.rb
  app/services/message_templates/hook_execution_service.rb
  app/services/message_templates/template/greeting.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  app/views/widget_tests/index.html.erb
  app/views/widgets/show.html.erb
  db/migrate/20200907171106_add_reply_time_to_web_widget.rb
  db/schema.rb
  package.json
  postcss.config.js
  spec/services/message_templates/hook_execution_service_spec.rb
  tailwind.config.js
  yarn.lock
Labels: PR: unreviewed

#1354 chore: Update documentation for inbound email service
  .env.example
Labels: PR: reviewed-approved

#1351 DRY up check_authorization method
  app/controllers/api/base_controller.rb
  app/controllers/api/v1/accounts/agents_controller.rb
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/controllers/api/v1/accounts/labels_controller.rb
  app/controllers/api/v1/accounts/webhooks_controller.rb
  app/controllers/api/v1/accounts_controller.rb
Labels: PR: reviewed-approved

#1356 feat: Enable File Upload for API Inbox in the UI
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: reviewed-approved

#1352 fix: Add compact type, fix spacing in contact panel
  app/javascript/dashboard/assets/scss/widgets/_buttons.scss
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfoRow.vue
Labels: PR: reviewed-approved

#1360 PL Widget - 100% Translation
  app/javascript/widget/i18n/locale/pl.json
Labels: PR: reviewed-approved

#1364 fix: Update production installation setup script for Ubuntu 20.04
  deployment/setup_18.04.sh
  deployment/setup_20.04.sh
  docs/README.md
  docs/deployment/production/linux-vm.md
Labels: PR: unreviewed

#1363 fix: Add a full width image view to fix resolution issues
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/components/Modal.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Image.vue
Labels: PR: partially-approved

#1366 chore: Monkey patch Azure storage service
  .rubocop.yml
  config/initializers/azure_storage_service_patch.rb
  lib/azure/storage.rb
  lib/azure/storage/core/auth/shared_access_signature.rb
Labels: PR: unreviewed

#1368 fix: Add lib/azure to autoload ignore list
  config/application.rb
Labels: PR: unreviewed

#1369 Fixed typo with misspell
  lib/integrations/facebook/message_parser.rb
  lib/tasks/swagger.rake
Labels: PR: reviewed-approved

#1323 feat: notify on slack disconnect
  app/mailers/administrator_notifications/channel_notifications_mailer.rb
  app/models/concerns/reauthorizable.rb
  app/models/integrations/hook.rb
  app/views/mailers/administrator_notifications/channel_notifications_mailer/slack_disconnect.liquid
  lib/integrations/slack/send_on_slack_service.rb
  spec/lib/integrations/slack/send_on_slack_service_spec.rb
Labels: PR: reviewed-approved

#1315 feature: IP lookup
  .env.example
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/jobs/contact_ip_lookup_job.rb
  app/models/contact.rb
  bin/validate_push
  config/features.yml
  config/initializers/geocoder.rb
  db/migrate/20201019173944_add_default_value_to_jsonb_colums.rb
  db/schema.rb
  package.json
  spec/models/conversation_spec.rb
  spec/presenters/conversations/event_data_presenter_spec.rb
  vendor/db/.keep
Labels: PR: unreviewed

#1365 Added missing keywords to Spanish translation
  app/javascript/dashboard/i18n/locale/es/contact.json
  app/javascript/dashboard/i18n/locale/es/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/es/settings.json
Labels: PR: unreviewed

#1294 fix(1285): make the field not selectable
  app/javascript/sdk/sdk.js
Labels: PR: reviewed-approved

#1373 Add messages on mute / unmute actions
  app/models/conversation.rb
  config/locales/en.yml
  spec/models/conversation_spec.rb
Labels: PR: unreviewed

#1376 chore: Upgrade tailwindcss to 1.9.x
  package.json
  yarn.lock
Labels: PR: partially-approved

#1370 Working hours: Backend and tests ready
  .gitignore
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/controllers/api/v1/accounts/working_hours_controller.rb
  app/models/account.rb
  app/models/channel/web_widget.rb
  app/models/concerns/out_of_offisable.rb
  app/models/inbox.rb
  app/models/message.rb
  app/models/working_hour.rb
  app/services/message_templates/hook_execution_service.rb
  app/services/message_templates/template/out_of_office.rb
  config/routes.rb
  db/migrate/20201027135006_create_working_hours.rb
  db/schema.rb
  lib/current.rb
  spec/factories/messages.rb
  spec/factories/working_hours.rb
  spec/models/concerns/out_of_offisable_spec.rb
  spec/models/inbox_spec.rb
  spec/models/working_hour_spec.rb
  spec/rails_helper.rb
  spec/services/message_templates/hook_execution_service_spec.rb
  spec/services/message_templates/template/out_of_office_spec.rb
Labels: PR: partially-approved
