Repository chatwoot/chatwoot, pull requests merged in 2020-11, with the labels that each got.

#1380 Enhancement: Add status color for items in availability status menu
  app/javascript/dashboard/components/layout/AvailabilityStatus.vue
Labels: PR: reviewed-approved

#1382 fix: pg pass printed by docker container (#1371)
  docker-compose.yaml
  docker/entrypoints/helpers/pg_database_url.sh
  docker/entrypoints/rails.sh
  yarn.lock
Labels: PR: partially-approved

#1387 Fix: Sort label links on sidebar for homepage #1386
  app/javascript/dashboard/store/modules/labels.js
Labels: PR: reviewed-approved

#1385 feat: Add global message search
  app/finders/conversation_finder.rb
  app/javascript/dashboard/api/inbox/conversation.js
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
  app/javascript/dashboard/routes/dashboard/conversation/search/Search.vue
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/conversationSearch.js
  app/javascript/dashboard/store/modules/specs/conversationSearch/actions.spec.js
  app/javascript/dashboard/store/modules/specs/conversationSearch/getters.spec.js
  app/javascript/dashboard/store/modules/specs/conversationSearch/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/views/api/v1/accounts/conversations/search.json.jbuilder
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
Labels: PR: reviewed-approved

#1389 fix: Add a check for thread_ts
  lib/integrations/slack/incoming_message_builder.rb
  spec/lib/integrations/slack/incoming_message_builder_spec.rb
  spec/support/slack_stubs.rb
Labels: PR: reviewed-approved

#1335 feat: Add Contacts page
  app/controllers/api/v1/accounts/agents_controller.rb
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/finders/conversation_finder.rb
  app/finders/message_finder.rb
  app/javascript/dashboard/api/contacts.js
  app/javascript/dashboard/assets/scss/_woot.scss
  app/javascript/dashboard/assets/scss/app.scss
  app/javascript/dashboard/assets/scss/plugins/_dropdown.scss
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/widgets/EmptyState.vue
  app/javascript/dashboard/i18n/default-sidebar.js
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/i18n/locale/en/contactsPage.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/Dashboard.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/Footer.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue
  app/javascript/dashboard/routes/dashboard/contacts/routes.js
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/routes/dashboard/dashboard.routes.js
  app/javascript/dashboard/store/modules/contacts.js
  app/javascript/dashboard/store/modules/contacts/actions.js
  app/javascript/dashboard/store/modules/contacts/getters.js
  app/javascript/dashboard/store/modules/contacts/index.js
  app/javascript/dashboard/store/modules/contacts/mutations.js
  app/javascript/dashboard/store/modules/specs/contacts/actions.spec.js
  app/javascript/dashboard/store/modules/specs/contacts/getters.spec.js
  app/javascript/dashboard/store/modules/specs/contacts/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/shared/assets/stylesheets/font-weights.scss
  app/javascript/shared/assets/stylesheets/spacing.scss
  app/javascript/widget/components/ConversationWrap.vue
  app/views/api/v1/accounts/contacts/active.json.jbuilder
  app/views/api/v1/accounts/contacts/index.json.jbuilder
  app/views/api/v1/accounts/contacts/search.json.jbuilder
  app/views/api/v1/models/_contact.json.jbuilder
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
Labels: PR: unreviewed

#1393 DE Widget - 100% Translation
  app/javascript/widget/i18n/locale/de.json
Labels: PR: reviewed-approved

#1397 fix: Enhance CRM UI
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/i18n/locale/en/contactsPage.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/Footer.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/EditContact.vue
  app/views/api/v1/models/_contact.json.jbuilder
Labels: PR: unreviewed

#1404 Fix-1403 Ui Chore fix
  app/javascript/widget/components/FileBubble.vue
Labels: PR: unreviewed

#1407 feat: Gravatar urls for contacts
  app/models/concerns/avatarable.rb
  app/models/user.rb
Labels: PR: reviewed-approved

#1408 feat: Ignore tweets from blocked users
  app/services/twitter/tweet_parser_service.rb
  spec/factories/twitter/tweet_create_event.rb
  spec/lib/webhooks/twitter_spec.rb
Labels: PR: reviewed-approved

#1413 fix: Fire query only if search term is available
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
Labels: PR: reviewed-approved

#1391 feat: Agent & Inbox Report APIs
  app/controllers/api/v2/accounts/reports_controller.rb
  app/javascript/dashboard/api/reports.js
  app/javascript/dashboard/store/modules/reports.js
  app/models/account.rb
  app/models/user.rb
  app/views/api/v2/accounts/reports/agents.csv.erb
  app/views/api/v2/accounts/reports/inboxes.csv.erb
  config/routes.rb
  db/schema.rb
  lib/integrations/slack/send_on_slack_service.rb
  spec/controllers/api/v2/accounts/report_controller_spec.rb
Labels: PR: reviewed-approved

#1410 Update inboxMgmt.json
  .github/PULL_REQUEST_TEMPLATE.md
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
Labels: PR: unreviewed

#1377 Added translations in the language menu
  config/initializers/languages.rb
Labels: PR: unreviewed

#1419 fix: Remove duplicate API calls for conversation
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
Labels: PR: reviewed-approved

#1418 fix: Avoid keys getting translated in availability
  app/javascript/dashboard/components/layout/AvailabilityStatus.vue
  app/javascript/dashboard/components/layout/specs/AvailabilityStatus.spec.js
  app/javascript/dashboard/i18n/locale/ar/settings.json
  app/javascript/dashboard/i18n/locale/ca/settings.json
  app/javascript/dashboard/i18n/locale/cs/settings.json
  app/javascript/dashboard/i18n/locale/da/settings.json
  app/javascript/dashboard/i18n/locale/el/settings.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/i18n/locale/es/settings.json
  app/javascript/dashboard/i18n/locale/fa/settings.json
  app/javascript/dashboard/i18n/locale/fi/settings.json
  app/javascript/dashboard/i18n/locale/fr/settings.json
  app/javascript/dashboard/i18n/locale/hi/settings.json
  app/javascript/dashboard/i18n/locale/hu/settings.json
  app/javascript/dashboard/i18n/locale/it/settings.json
  app/javascript/dashboard/i18n/locale/ja/settings.json
  app/javascript/dashboard/i18n/locale/ko/settings.json
  app/javascript/dashboard/i18n/locale/ml/settings.json
  app/javascript/dashboard/i18n/locale/nl/settings.json
  app/javascript/dashboard/i18n/locale/pt/settings.json
  app/javascript/dashboard/i18n/locale/pt_BR/settings.json
  app/javascript/dashboard/i18n/locale/ro/settings.json
  app/javascript/dashboard/i18n/locale/ru/settings.json
  app/javascript/dashboard/i18n/locale/sk/settings.json
  app/javascript/dashboard/i18n/locale/sv/settings.json
  app/javascript/dashboard/i18n/locale/ta/settings.json
  app/javascript/dashboard/i18n/locale/th/settings.json
  app/javascript/dashboard/i18n/locale/tr/settings.json
  app/javascript/dashboard/i18n/locale/uk/settings.json
  app/javascript/dashboard/i18n/locale/vi/settings.json
  app/javascript/dashboard/i18n/locale/zh/settings.json
  app/javascript/dashboard/i18n/locale/zh_CN/settings.json
  app/javascript/dashboard/i18n/locale/zh_TW/settings.json
  app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
Labels: PR: reviewed-approved

#1424 [skip ci] chore: Add documentation on translation process
  README.md
  docs/contributing.md
  docs/contributing/translating-chatwoot-to-your-language.md
Labels: PR: reviewed-approved

#1426 chore: Bump ruby from 2.7.1 to 2.7.2
  .circleci/config.yml
  .env.example
  .ruby-version
  Gemfile
  Gemfile.lock
  deployment/chatwoot-web.1.service
  deployment/chatwoot-worker.1.service
  deployment/setup_18.04.sh
  deployment/setup_20.04.sh
  docker/Dockerfile
  docs/development/environment-setup/mac-os.md
  docs/development/environment-setup/ubuntu.md
  docs/development/environment-setup/windows.md
Labels: PR: reviewed-approved

#1436 fix: Update agent list when the user changes their presence
  app/javascript/dashboard/store/modules/auth.js
  app/javascript/dashboard/store/modules/specs/auth/actions.spec.js
Labels: PR: partially-approved

#1431 remove invalid quotes in Dockerfile instructions
  docs/deployment/production/docker.md
Labels: PR: unreviewed

#1435 fix: Add missing close button if bubble is hidden
  Gemfile.lock
  app/javascript/sdk/IFrameHelper.js
  app/javascript/sdk/sdk.js
  app/javascript/widget/assets/scss/woot.scss
  app/javascript/widget/views/Router.vue
Labels: PR: partially-approved

#1440 feat: Search contacts using phone number
  app/controllers/api/v1/accounts/contacts_controller.rb
Labels: PR: reviewed-approved

#1442 enh: Create superadmin in seeds
  db/seeds.rb
Labels: PR: merged

#1433 feat: Default locale
  .env.example
  app/builders/account_builder.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/switch_locale.rb
  app/controllers/dashboard_controller.rb
  app/javascript/dashboard/App.vue
  app/views/layouts/vueapp.html.erb
  docs/development/project-setup/environment-variables.md
Labels: PR: reviewed-approved

#1443 chore: Enable Danish language
  app/javascript/dashboard/i18n/locale/da/agentMgmt.json
  app/javascript/dashboard/i18n/locale/da/cannedMgmt.json
  app/javascript/dashboard/i18n/locale/da/chatlist.json
  app/javascript/dashboard/i18n/locale/da/contact.json
  app/javascript/dashboard/i18n/locale/da/conversation.json
  app/javascript/dashboard/i18n/locale/da/generalSettings.json
  app/javascript/dashboard/i18n/locale/da/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/da/integrations.json
  app/javascript/dashboard/i18n/locale/da/labelsMgmt.json
  app/javascript/dashboard/i18n/locale/da/login.json
  app/javascript/dashboard/i18n/locale/da/report.json
  app/javascript/dashboard/i18n/locale/da/resetPassword.json
  app/javascript/dashboard/i18n/locale/da/setNewPassword.json
  app/javascript/dashboard/i18n/locale/da/settings.json
  app/javascript/dashboard/i18n/locale/da/signup.json
  app/javascript/dashboard/i18n/locale/da/webhooks.json
  app/javascript/dashboard/i18n/locale/de/settings.json
  app/javascript/dashboard/i18n/locale/el/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/fa/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/fi/settings.json
  app/javascript/dashboard/i18n/locale/nl/settings.json
  app/javascript/dashboard/i18n/locale/pl/settings.json
  app/javascript/dashboard/i18n/locale/zh_CN/agentMgmt.json
  app/javascript/widget/i18n/locale/da.json
  app/javascript/widget/i18n/locale/fi.json
  app/javascript/widget/i18n/locale/ru.json
  app/javascript/widget/i18n/locale/zh_CN.json
  config/initializers/languages.rb
  config/locales/da.yml
  config/locales/devise.da.yml
  config/locales/devise.zh_TW.yml
  config/locales/fi.yml
Labels: PR: unreviewed

#1448 Label Overflow text-truncate fix 1447
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/components/ChatList.vue
Labels: PR: partially-approved

#1439 feat: Authenticate by sso urls
  app/builders/account_builder.rb
  app/controllers/devise_overrides/sessions_controller.rb
  app/javascript/dashboard/routes/login/Login.vue
  app/javascript/dashboard/routes/login/login.routes.js
  app/models/concerns/sso_authenticatable.rb
  app/models/conversation.rb
  app/models/user.rb
  lib/redis/redis_keys.rb
  spec/controllers/devise/session_controller_spec.rb
  spec/models/user_spec.rb
Labels: PR: unreviewed

#1461 chore: Send typing events on keyup, not on focus
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/shared/components/ResizableTextArea.vue
  app/javascript/widget/components/ChatInputWrap.vue
Labels: PR: partially-approved

#1462 Add branch variable
  deployment/setup_18.04.sh
  deployment/setup_20.04.sh
Labels: PR: reviewed-approved

#1429 GCS credentials dont need to be parsed as JSON
  config/storage.yml
Labels: PR: unreviewed

#1460 Chore UI FIXES
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/assets/scss/_variables.scss
  app/javascript/dashboard/assets/scss/widgets/_conv-header.scss
  app/javascript/dashboard/assets/scss/widgets/_conversation-card.scss
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/assets/scss/widgets/_reply-box.scss
  app/javascript/dashboard/assets/scss/widgets/_tabs.scss
  app/javascript/dashboard/assets/scss/widgets/_woot-tables.scss
  app/javascript/dashboard/components/widgets/conversation/MoreActions.vue
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
  app/javascript/widget/assets/scss/_mixins.scss
Labels: PR: reviewed-approved

#1463 fix: Move integration text to translation file
  app/controllers/api/v1/accounts/base_controller.rb
  app/controllers/api/v1/widget/base_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/switch_locale.rb
  app/controllers/dashboard_controller.rb
  app/models/integrations/app.rb
  config/integration/apps.yml
  config/locales/en.yml
  config/locales/ml.yml
Labels: PR: reviewed-approved
