Repository chatwoot/chatwoot, pull requests merged in 2021-02, with the labels that each got.

#1728 fix: Update flaky notification tests
  app/javascript/shared/helpers/MessageFormatter.js
  app/listeners/notification_listener.rb
  spec/listeners/notification_listener_spec.rb
Labels: PR: reviewed-approved

#1724 feat: Contact Import API
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/accounts/contacts/contact_inboxes_controller.rb
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/jobs/data_import_job.rb
  app/models/account.rb
  app/models/contact_inbox.rb
  app/models/data_import.rb
  app/policies/contact_policy.rb
  config/routes.rb
  db/migrate/20210201150037_create_data_imports.rb
  db/schema.rb
  spec/assets/contacts.csv
  spec/controllers/api/v1/accounts/contacts/contact_inboxes_controller_spec.rb
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
  spec/factories/channel/twilio_sms.rb
  spec/factories/contact_inbox.rb
  spec/factories/data_import.rb
  spec/jobs/data_import_job_spec.rb
  spec/models/data_import_spec.rb
Labels: PR: reviewed-approved

#1727 Chore: Sets up store for teams settings page
  app/javascript/dashboard/api/specs/teams.spec.js
  app/javascript/dashboard/api/teams.js
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/specs/teamMembers/actions.spec.js
  app/javascript/dashboard/store/modules/specs/teamMembers/fixtures.js
  app/javascript/dashboard/store/modules/specs/teamMembers/getters.spec.js
  app/javascript/dashboard/store/modules/specs/teamMembers/mutations.spec.js
  app/javascript/dashboard/store/modules/specs/teams/actions.spec.js
  app/javascript/dashboard/store/modules/specs/teams/fixtures.js
  app/javascript/dashboard/store/modules/specs/teams/getters.spec.js
  app/javascript/dashboard/store/modules/specs/teams/mutations.spec.js
  app/javascript/dashboard/store/modules/teamMembers.js
  app/javascript/dashboard/store/modules/teams/actions.js
  app/javascript/dashboard/store/modules/teams/getters.js
  app/javascript/dashboard/store/modules/teams/index.js
  app/javascript/dashboard/store/modules/teams/mutations.js
  app/javascript/dashboard/store/modules/teams/types.js
Labels: PR: reviewed-approved

#1720 Add name error validation for account setting Profile name #1714
  app/javascript/dashboard/routes/dashboard/settings/agents/AddAgent.vue
  app/javascript/dashboard/routes/dashboard/settings/agents/EditAgent.vue
  app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
  app/models/user.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#1732 fix: Use commonmarker instead of redcarpet
  Gemfile
  Gemfile.lock
  app/views/mailers/conversation_reply_mailer/conversation_transcript.html.erb
  app/views/mailers/conversation_reply_mailer/reply_with_summary.html.erb
  app/views/mailers/conversation_reply_mailer/reply_without_summary.html.erb
Labels: PR: reviewed-approved

#1733 fix: Use encodeURIComponent in generating mention url
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#1735 chore: UI fixes
  app/javascript/dashboard/assets/scss/widgets/_sidemenu.scss
  app/javascript/dashboard/components/layout/SidebarItem.vue
  app/javascript/dashboard/components/widgets/TableFooter.vue
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
Labels: PR: partially-approved

#1670 chore: Add error logging config on the vue package
  app/javascript/packs/application.js
  app/views/layouts/vueapp.html.erb
  package.json
  yarn.lock
Labels: PR: unreviewed

#1736 feat: Save rich content editor state to user.uiSettings
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/mixins/specs/uiSettings.spec.js
  app/javascript/dashboard/mixins/uiSettings.js
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
Labels: PR: unreviewed

#1739 chore: Minor Changes to Bot Message APIs
  app/presenters/conversations/event_data_presenter.rb
  lib/woot_message_seeder.rb
  spec/models/conversation_spec.rb
  spec/presenters/conversations/event_data_presenter_spec.rb
Labels: PR: reviewed-approved

#1726 chore: Add Chatwoot SDK to Chatwoot Dashboard
  app/controllers/dashboard_controller.rb
  app/javascript/dashboard/assets/scss/widgets/_sidemenu.scss
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/sidebarComponents/AccountSelector.vue
  app/javascript/dashboard/components/layout/sidebarComponents/AddAccountModal.vue
  app/javascript/dashboard/components/layout/sidebarComponents/AgentDetails.vue
  app/javascript/dashboard/components/layout/sidebarComponents/NotificationBell.vue
  app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue
  app/javascript/shared/store/globalConfig.js
  app/models/user.rb
  app/views/api/v1/models/_user.json.jbuilder
  app/views/layouts/vueapp.html.erb
  config/installation_config.yml
  spec/models/user_spec.rb
Labels: PR: partially-approved

#1741 fix: Show push notifications settings except Safari
  app/javascript/dashboard/components/Code.vue
  app/javascript/dashboard/routes/dashboard/settings/profile/NotificationSettings.vue
  app/views/layouts/vueapp.html.erb
Labels: PR: reviewed-approved

#1742 feat: Update bot option select button styles
  app/javascript/shared/components/ChatOption.vue
  app/javascript/shared/components/ChatOptions.vue
Labels: PR: reviewed-approved

#1743 fix: Fix bot message rendering in dashboard
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/helpers/botMessageContentHelper.js
  app/javascript/dashboard/components/widgets/conversation/helpers/specs/botMessageContentHelper.spec.js
  app/javascript/dashboard/i18n/locale/en/conversation.json
Labels: PR: reviewed-approved

#1734 chore: Update method for team members
  app/controllers/api/v1/accounts/inbox_members_controller.rb
  app/controllers/api/v1/accounts/team_members_controller.rb
  app/models/team.rb
  app/policies/team_member_policy.rb
  config/routes.rb
  spec/controllers/api/v1/accounts/team_members_controller_spec.rb
Labels: PR: reviewed-approved

#1725 fixed slack channel builder so that the channel list can have more th…
  lib/integrations/slack/channel_builder.rb
Labels: PR: unreviewed

#1748 feat: Show date along with time in messages
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/mixins/specs/time.spec.js
  app/javascript/dashboard/mixins/time.js
  jest.config.js
  jest.setup.js
Labels: PR: partially-approved

#1749 feat: Use audio tag instead of download file button
  app/helpers/file_type_helper.rb
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: reviewed-approved

#1755 chore: Bump rails to 6.0.3.5 to fix CVE-2021-22881
  Gemfile.lock
Labels: PR: reviewed-approved

#1685 chore: Update notification Message Copy
  app/models/notification.rb
  config/locales/en.yml
  spec/models/notification_spec.rb
Labels: PR: unreviewed

#1754 feat: show teams on sidebar
  app/javascript/dashboard/api/inbox/conversation.js
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/i18n/default-sidebar.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
  app/javascript/dashboard/routes/dashboard/conversation/conversation.routes.js
  app/javascript/dashboard/store/modules/specs/teams/fixtures.js
  app/javascript/dashboard/store/modules/specs/teams/getters.spec.js
  app/javascript/dashboard/store/modules/specs/teams/mutations.spec.js
  app/javascript/dashboard/store/modules/teams/getters.js
  app/views/api/v1/models/_team.json.jbuilder
Labels: PR: reviewed-approved

#1765 Include website_token key in the inboxes response
  app/views/api/v1/models/_inbox.json.jbuilder
Labels: PR: reviewed-approved

#1766 fix: Remove teams on account user destroy
  app/models/account_user.rb
  app/services/agents/destroy_service.rb
  spec/models/account_user_spec.rb
  spec/services/agents/destroy_service_spec.rb
Labels: PR: unreviewed

#1771 Fix: Links inside private note is not visible
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: unreviewed

#1772 Fix colors for attachments in private note
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: reviewed-approved

#1775 Fixes link address overflow in webhook.
  app/javascript/dashboard/routes/dashboard/settings/integrations/Webhook.vue
Labels: PR: unreviewed

#1769 feat: Add a pre-chat form on widget
  app/controllers/api/v1/widget/base_controller.rb
  app/controllers/api/v1/widget/conversations_controller.rb
  app/controllers/api/v1/widget/messages_controller.rb
  app/javascript/widget/App.vue
  app/javascript/widget/api/conversation.js
  app/javascript/widget/api/endPoints.js
  app/javascript/widget/components/ChatHeader.vue
  app/javascript/widget/components/ChatHeaderExpanded.vue
  app/javascript/widget/components/Form/Input.vue
  app/javascript/widget/components/Form/TextArea.vue
  app/javascript/widget/components/PreChat/Form.vue
  app/javascript/widget/i18n/locale/en.json
  app/javascript/widget/mixins/configMixin.js
  app/javascript/widget/store/modules/conversation/actions.js
  app/javascript/widget/store/modules/conversation/getters.js
  app/javascript/widget/store/modules/conversation/index.js
  app/javascript/widget/store/modules/conversation/mutations.js
  app/javascript/widget/store/modules/specs/conversation/actions.spec.js
  app/javascript/widget/store/modules/specs/conversation/getters.spec.js
  app/javascript/widget/store/modules/specs/conversation/mutations.spec.js
  app/javascript/widget/views/Home.vue
  app/javascript/widget/views/Router.vue
  app/javascript/widget/views/Unread.vue
  app/models/channel/web_widget.rb
  app/views/api/v1/models/_widget_message.json.jbuilder
  app/views/api/v1/widget/conversations/create.json.jbuilder
  app/views/widgets/show.html.erb
  config/routes.rb
  db/migrate/20210212154240_add_request_for_email_on_channel_web_widget.rb
  db/schema.rb
  spec/controllers/api/v1/widget/conversations_controller_spec.rb
Labels: PR: unreviewed

#1768 chore: Fix push message tag error
  app/models/notification.rb
  app/services/notification/push_notification_service.rb
Labels: PR: reviewed-approved

#1776 feat: Add pre_chat_form_settings in inbox settings page
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/PreChatForm/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/store/modules/inboxes.js
  app/javascript/widget/components/PreChat/Form.vue
  app/javascript/widget/views/Home.vue
  app/views/api/v1/models/_inbox.json.jbuilder
  app/views/widget_tests/index.html.erb
Labels: PR: unreviewed

#1779 fix: Add validations dynamically
  app/controllers/api/v1/widget/conversations_controller.rb
  app/javascript/widget/components/PreChat/Form.vue
Labels: PR: unreviewed

#1784 Fix warning on new inbox page
  app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue
Labels: PR: reviewed-approved

#1783 fix: Twitter inbox creation error
  app/controllers/api/v1/accounts/twitter/authorizations_controller.rb
  app/controllers/concerns/twitter_concern.rb
  app/controllers/twitter/authorizations_controller.rb
  app/controllers/twitter/base_controller.rb
  app/controllers/twitter/callbacks_controller.rb
  app/javascript/dashboard/api/channel/twitterClient.js
  app/javascript/dashboard/api/specs/channel/twitterClient.spec.js
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Twitter.vue
  config/routes.rb
  spec/controllers/api/v1/accounts/twitter/authorizations_controller_spec.rb
Labels: PR: unreviewed

#1791 Bug: Fixes the width issue of time stamp in notification.
  app/javascript/dashboard/routes/dashboard/notifications/components/NotificationTable.vue
Labels: PR: reviewed-approved

#1789 Chore: Changes the mention tag design in the private note.
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: unreviewed

#1687 chore: Generate nginx config using chatwoot installation scripts
  deployment/nginx_chatwoot.conf
  deployment/setup_20.04.sh
Labels: PR: unreviewed

#1797 fix: Remove orphan members from inbox
  db/migrate/20210217154129_remove_orphan_inbox_members_from_inboxes.rb
  db/schema.rb
Labels: PR: reviewed-approved

#1805 Chore: Refactor Edit contact modal to separate form
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactForm.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/EditContact.vue
Labels: PR: reviewed-approved

#1807 chore: Notification cleanups
  app/listeners/notification_listener.rb
  app/models/notification.rb
  app/views/api/v1/accounts/notifications/index.json.jbuilder
  db/migrate/20210219085719_remove_old_notifications.rb
  db/schema.rb
  spec/models/notification_spec.rb
Labels: PR: reviewed-approved

#1813 Enhancement: Changes the dropdown ui
  app/javascript/dashboard/assets/scss/plugins/_multiselect.scss
Labels: PR: reviewed-approved

#1794 Feat: Component for setting business hour availability
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/BusinessDay.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/helpers/businessHour.js
  app/javascript/dashboard/routes/dashboard/settings/inbox/helpers/specs/businessHour.spec.js
Labels: PR: reviewed-approved

#1821 feat: Business hour Inbox APIs
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/models/account.rb
  app/models/concerns/out_of_offisable.rb
  app/models/inbox.rb
  app/models/working_hour.rb
  app/services/message_templates/hook_execution_service.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  db/migrate/20210222131048_change_working_hours_to_zero.rb
  db/migrate/20210222131155_switch_time_zone_from_account_to_inbox.rb
  db/schema.rb
  lib/current.rb
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
  spec/models/concerns/out_of_offisable_spec.rb
  spec/services/message_templates/hook_execution_service_spec.rb
Labels: PR: partially-approved

#1819 Removing unused index method from Widget Controller
  app/controllers/widgets_controller.rb
Labels: PR: reviewed-approved

#1792 fix: Log config env variable typecasting
  config/environments/production.rb
  config/environments/staging.rb
Labels: PR: reviewed-approved

#1826 feat: Add a view to assist user while onboarding
  app/javascript/dashboard/components/widgets/conversation/EmptyState.vue
  app/javascript/dashboard/components/widgets/conversation/OnboardingView.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
Labels: PR: unreviewed

#1828 fix: Upgrade browser gem to fix missing push config in Opera
  Gemfile.lock
Labels: PR: reviewed-approved

#1831 Fix attachment rendering if the message content is empty in private note
  app/listeners/notification_listener.rb
  spec/listeners/notification_listener_spec.rb
Labels: PR: reviewed-approved

#1833 feat: Update UI for edit contact modal
  app/javascript/dashboard/components/Modal.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactForm.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/CreateContact.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/EditContact.vue
Labels: PR: reviewed-approved

#1836 chore: Fix inboxMgmt pt-BR locale typo
  app/javascript/dashboard/i18n/locale/pt_BR/inboxMgmt.json
Labels: PR: unreviewed
