Repository chatwoot/chatwoot, pull requests merged in 2021-06, with the labels that each got.

#2323 feat: Add AgentBot APIs
  app/controllers/api/v1/accounts/agent_bots_controller.rb
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/controllers/api/v1/agent_bots_controller.rb
  app/controllers/platform/api/v1/agent_bots_controller.rb
  app/dashboards/agent_bot_dashboard.rb
  app/javascript/widget/mixins/configMixin.js
  app/javascript/widget/mixins/specs/configMixin.spec.js
  app/javascript/widget/views/Home.vue
  app/models/account.rb
  app/models/agent_bot.rb
  app/policies/agent_bot_policy.rb
  app/policies/inbox_policy.rb
  app/views/api/v1/accounts/agent_bots/create.json.jbuilder
  app/views/api/v1/accounts/agent_bots/index.json.jbuilder
  app/views/api/v1/accounts/agent_bots/show.json.jbuilder
  app/views/api/v1/accounts/agent_bots/update.json.jbuilder
  app/views/api/v1/accounts/inboxes/agent_bot.json.jbuilder
  app/views/api/v1/models/_agent_bot.json.jbuilder
  app/views/platform/api/v1/agent_bots/create.json.jbuilder
  app/views/platform/api/v1/agent_bots/index.json.jbuilder
  app/views/platform/api/v1/agent_bots/show.json.jbuilder
  app/views/platform/api/v1/agent_bots/update.json.jbuilder
  app/views/platform/api/v1/models/_agent_bot.json.jbuilder
  app/views/widgets/show.html.erb
  config/routes.rb
  db/migrate/20210520200729_add_account_id_to_agent_bots.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/agent_bots_controller_spec.rb
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
  spec/controllers/api/v1/agent_bots_controller_spec.rb
  spec/controllers/platform/api/v1/agent_bots_controller_spec.rb
Labels: PR: reviewed-approved

#2356 enhancement: Adds support for canned command key everywhere on rich text editor
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: partially-approved

#2108 enhancement: Current password confirmation in change password
  app/controllers/api/v1/profiles_controller.rb
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/profile/ChangePassword.vue
  app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
  app/javascript/dashboard/store/modules/auth.js
  spec/controllers/api/v1/profiles_controller_spec.rb
Labels: PR: partially-approved

#2324 chore: Universal Linking for Android
  .env.example
  app/controllers/android_app_controller.rb
  app/views/android_app/assetlinks.json.erb
  config/routes.rb
  spec/controllers/android_assetlinks_spec.rb
Labels: PR: reviewed-approved

#2364 fix: Update the translation key for Custom Attributes
  app/javascript/dashboard/routes/dashboard/conversation/ContactCustomAttributes.vue
Labels: PR: unreviewed

#2258 Feat: Creates reminder list component for CRM
  app/javascript/dashboard/routes/dashboard/contacts/components/ReminderItem.stories.js
  app/javascript/dashboard/routes/dashboard/contacts/components/ReminderItem.vue
Labels: PR: unreviewed

#2264 feat: Create add reminder component for CRM
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/contacts/components/AddReminder.stories.js
  app/javascript/dashboard/routes/dashboard/contacts/components/AddReminder.vue
Labels: PR: reviewed-approved

#2291 feat: Creates event timeline card component for CRM
  app/javascript/dashboard/routes/dashboard/contacts/components/TimelineCard.stories.js
  app/javascript/dashboard/routes/dashboard/contacts/components/TimelineCard.vue
Labels: PR: unreviewed

#2372 fix: Retain focus after sending message in rich content editor
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
Labels: PR: reviewed-approved

#2373 chore: Adds new color shades and tints for violet
  app/javascript/shared/assets/stylesheets/colors.scss
Labels: PR: partially-approved

#2379 chore: Remove unused components from dashboard
  app/javascript/dashboard/components/widgets/Button.vue
  app/javascript/dashboard/routes/dashboard/conversation/labels/AddLabelToConversation.vue
Labels: PR: reviewed-approved

#2370 feat: Ask to confirm with name before inbox/team deletion
  app/javascript/dashboard/components/index.js
  app/javascript/dashboard/components/widgets/modal/ConfirmDeleteModal.vue
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/en/teamsSettings.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/teams/Index.vue
Labels: PR: partially-approved

#2374 chore: Add different color for messages from bot
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: reviewed-approved

#2301 feat: Integration hooks UI
  app/javascript/dashboard/api/integrations.js
  app/javascript/dashboard/api/specs/apiSpecHelper.js
  app/javascript/dashboard/api/specs/integrations.spec.js
  app/javascript/dashboard/assets/scss/_formulate.scss
  app/javascript/dashboard/assets/scss/_woot.scss
  app/javascript/dashboard/helper/commons.js
  app/javascript/dashboard/i18n/default-sidebar.js
  app/javascript/dashboard/i18n/locale/en/index.js
  app/javascript/dashboard/i18n/locale/en/integrationApps.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/integrationapps/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/integrationapps/IntegrationHooks.vue
  app/javascript/dashboard/routes/dashboard/settings/integrationapps/IntegrationItem.vue
  app/javascript/dashboard/routes/dashboard/settings/integrationapps/MultipleIntegrationHooks.vue
  app/javascript/dashboard/routes/dashboard/settings/integrationapps/NewHook.vue
  app/javascript/dashboard/routes/dashboard/settings/integrationapps/SingleIntegrationHooks.vue
  app/javascript/dashboard/routes/dashboard/settings/integrationapps/hookMixin.js
  app/javascript/dashboard/routes/dashboard/settings/integrationapps/integrations.routes.js
  app/javascript/dashboard/routes/dashboard/settings/integrationapps/specs/hookMixin.spec.js
  app/javascript/dashboard/routes/dashboard/settings/settings.routes.js
  app/javascript/dashboard/store/modules/inboxes.js
  app/javascript/dashboard/store/modules/integrations.js
  app/javascript/dashboard/store/modules/specs/inboxes/getters.spec.js
  app/javascript/dashboard/store/modules/specs/integrations/actions.spec.js
  app/javascript/dashboard/store/modules/specs/integrations/getters.spec.js
  app/javascript/dashboard/store/modules/specs/integrations/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/packs/application.js
  app/models/integrations/app.rb
  app/views/api/v1/models/_hook.json.jbuilder
  config/integration/apps.yml
  config/locales/en.yml
  package.json
  public/dashboard/images/integrations/fullcontact.png
  yarn.lock
Labels: PR: unreviewed

#2316 feat: Edit webhook URL
  app/javascript/dashboard/i18n/locale/en/integrations.json
  app/javascript/dashboard/routes/dashboard/settings/integrations/EditWebHook.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/NewWebHook.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/Webhook.vue
  app/javascript/dashboard/store/modules/specs/webhooks/actions.spec.js
  app/javascript/dashboard/store/modules/specs/webhooks/mutations.spec.js
  app/javascript/dashboard/store/modules/webhooks.js
  app/javascript/dashboard/store/mutation-types.js
Labels: PR: unreviewed

#2385 fix: Add swagger definition for platform_user_id
  swagger/parameters/index.yml
  swagger/parameters/platform_user_id.yml
  swagger/paths/index.yml
  swagger/swagger.json
Labels: PR: reviewed-approved

#2391 chore: Expose contact identifier in API
  app/views/api/v1/models/_contact.json.jbuilder
Labels: PR: reviewed-approved

#2342 chore: Update Facebook Messenger gem
  Gemfile
  Gemfile.lock
  app/bot/facebook_bot.rb
  app/builders/messages/facebook/message_builder.rb
  app/controllers/api/v1/accounts/facebook_indicators_controller.rb
  app/services/facebook/send_on_facebook_service.rb
  config/initializers/bot.rb
  config/routes.rb
  spec/controllers/api/v1/accounts/facebook_indicators_controller_spec.rb
  spec/services/facebook/send_on_facebook_service_spec.rb
Labels: PR: reviewed-approved

#2345 feat: Improved password security policy
  Gemfile
  Gemfile.lock
  app/builders/account_builder.rb
  app/controllers/api/v1/accounts/agents_controller.rb
  app/controllers/api/v1/accounts_controller.rb
  app/controllers/api/v1/widget/messages_controller.rb
  app/controllers/concerns/access_token_auth_helper.rb
  app/controllers/devise_overrides/confirmations_controller.rb
  app/controllers/devise_overrides/passwords_controller.rb
  app/dashboards/super_admin_dashboard.rb
  app/javascript/dashboard/api/auth.js
  app/javascript/dashboard/routes/auth/Confirmation.vue
  app/javascript/dashboard/routes/auth/PasswordEdit.vue
  app/javascript/dashboard/routes/auth/Signup.vue
  app/javascript/dashboard/routes/dashboard/settings/profile/ChangePassword.vue
  app/models/super_admin.rb
  app/models/user.rb
  app/services/email_templates/db_resolver_service.rb
  app/services/notification/push_notification_service.rb
  config/initializers/liquid_handler.rb
  config/initializers/secure_password.rb
  config/initializers/sidekiq.rb
  config/locales/secure_password.en.yml
  db/migrate/20210527173755_remove_super_admin_access_tokes.rb
  db/schema.rb
  db/seeds.rb
  lib/woot_message_seeder.rb
  spec/controllers/api/v1/accounts_controller_spec.rb
  spec/controllers/api/v1/profiles_controller_spec.rb
  spec/controllers/devise/confirmations_controller_spec.rb
  spec/controllers/devise/session_controller_spec.rb
  spec/controllers/platform/api/v1/users_controller_spec.rb
  spec/controllers/super_admin/access_tokens_controller_spec.rb
  spec/factories/super_admins.rb
  spec/factories/users.rb
  spec/lib/chatwoot_hub_spec.rb
Labels: PR: unreviewed

#2394 chore: Improvements in conversation APIs
  app/controllers/api/v1/accounts/conversations_controller.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
  spec/controllers/api/v1/profiles_controller_spec.rb
  swagger/paths/conversation/index_or_create.yml
  swagger/swagger.json
Labels: PR: unreviewed

#2398 chore: Configure channel name and thumbnail
  app/controllers/dashboard_controller.rb
  app/javascript/dashboard/assets/scss/views/settings/channel.scss
  app/javascript/dashboard/components/widgets/ChannelItem.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue
  app/javascript/shared/store/globalConfig.js
  config/installation_config.yml
Labels: PR: reviewed-approved

#2396 chore: Message API improvements
  app/builders/messages/message_builder.rb
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/models/message.rb
  app/views/api/v1/models/_agent_bot.json.jbuilder
  spec/controllers/api/v1/accounts/conversations/messages_controller_spec.rb
Labels: PR: unreviewed

#2317 feat: Add regex validation on form message input
  .rubocop.yml
  app/javascript/shared/components/ChatForm.vue
  app/javascript/widget/i18n/locale/en.json
  app/models/concerns/content_attribute_validator.rb
  lib/woot_message_seeder.rb
Labels: PR: partially-approved

#2236 chore: Fix emails being sent with the wrong translations
  app/controllers/api/v1/accounts/agents_controller.rb
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/controllers/api/v1/widget/conversations_controller.rb
  app/mailers/application_mailer.rb
  app/models/concerns/reauthorizable.rb
  app/models/user.rb
  app/services/email_templates/db_resolver_service.rb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/workers/conversation_reply_email_worker.rb
  db/seeds.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
  spec/controllers/api/v1/widget/conversations_controller_spec.rb
  spec/lib/email_templates/db_resolver_service_spec.rb
  spec/mailers/confirmation_instructions_spec.rb
  spec/workers/conversation_reply_email_worker_spec.rb
Labels: PR: reviewed-approved, in-QA

#2381 chore: Add validation error for label create/edit modal
  app/javascript/dashboard/i18n/locale/en/labelsMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/labels/AddLabel.vue
  app/javascript/dashboard/routes/dashboard/settings/labels/EditLabel.vue
  app/javascript/dashboard/routes/dashboard/settings/labels/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/labels/specs/validationMixin.spec.js
  app/javascript/dashboard/routes/dashboard/settings/labels/validationMixin.js
Labels: PR: reviewed-approved

#2380 Chore: Refactoring styles for emoji and icon type button
  app/javascript/dashboard/assets/scss/widgets/_buttons.scss
  app/javascript/dashboard/assets/scss/widgets/_reply-box.scss
  app/javascript/dashboard/components/buttons/ResolveAction.vue
  app/javascript/dashboard/components/ui/WootButton.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactNote.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ReminderItem.vue
Labels: PR: partially-approved

#2404 chore: Cleans up style for contact note
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactNote.stories.js
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactNote.vue
Labels: PR: partially-approved

#2406 enhancement: Ability to edit inbox name
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
Labels: PR: partially-approved

#2407 chore: Cleanup page-top-bar style conflicts
  app/javascript/dashboard/assets/scss/views/settings/inbox.scss
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/widgets/SettingIntroBanner.stories.js
  app/javascript/dashboard/components/widgets/SettingIntroBanner.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/AddCampaign.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/EditCampaign.vue
Labels: PR: reviewed-approved

#2399 feat: Add an option to enable/disable email collect box
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/models/inbox.rb
  app/services/message_templates/hook_execution_service.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  config/initializers/devise_token_auth.rb
  db/migrate/20210609133433_add_email_collect_to_inboxes.rb
  db/schema.rb
  spec/services/message_templates/hook_execution_service_spec.rb
Labels: PR: reviewed-approved

#2411 fix: Add missing translation in inbox settings page
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Website.vue
Labels: PR: reviewed-approved

#2224 chore: Ensure privilege validations for API endpoints
  app/controllers/api/base_controller.rb
  app/controllers/api/v1/accounts/contacts/contact_inboxes_controller.rb
  app/controllers/api/v1/accounts/contacts/conversations_controller.rb
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/controllers/api/v1/accounts/conversations/base_controller.rb
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/controllers/api/v1/accounts/inbox_members_controller.rb
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/controllers/api/v1/accounts/integrations/apps_controller.rb
  app/controllers/api/v1/accounts/integrations/slack_controller.rb
  app/controllers/api/v2/accounts/reports_controller.rb
  app/finders/conversation_finder.rb
  app/models/user.rb
  app/policies/conversation_policy.rb
  app/policies/inbox_policy.rb
  spec/controllers/api/v1/accounts/agents_controller_spec.rb
  spec/controllers/api/v1/accounts/contacts/contact_inboxes_controller_spec.rb
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
  spec/controllers/api/v1/accounts/conversations/assignments_controller_spec.rb
  spec/controllers/api/v1/accounts/conversations/labels_controller_spec.rb
  spec/controllers/api/v1/accounts/conversations/messages_controller_spec.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
  spec/controllers/api/v1/accounts/inbox_members_controller_spec.rb
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
  spec/controllers/api/v1/accounts/integrations/apps_controller_spec.rb
  spec/controllers/api/v2/accounts/report_controller_spec.rb
  spec/requests/api/v1/accounts/integrations/slack_request_spec.rb
Labels: PR: reviewed-approved

#2414 feat: Add assign to me button next to assign agents.
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
Labels: PR: unreviewed

#2416 Chore: Refactors sidebar styles
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/assets/scss/_typography.scss
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactConversations.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactCustomAttributes.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactDetailsItem.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfoRow.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/SocialIcons.vue
  app/javascript/dashboard/routes/dashboard/conversation/labels/LabelBox.vue
Labels: PR: unreviewed

#2320 Feat: Show notes panel on crm page
  app/javascript/dashboard/api/contactNotes.js
  app/javascript/dashboard/assets/scss/_foundation-custom.scss
  app/javascript/dashboard/modules/contact/components/ManageLayout.vue
  app/javascript/dashboard/modules/notes/NotesOnContactPage.vue
  app/javascript/dashboard/modules/notes/components/AddNote.vue
  app/javascript/dashboard/modules/notes/components/ContactNote.vue
  app/javascript/dashboard/modules/notes/components/NoteList.vue
  app/javascript/dashboard/modules/notes/stories/AddNote.stories.js
  app/javascript/dashboard/modules/notes/stories/ContactNote.stories.js
  app/javascript/dashboard/modules/notes/stories/NoteList.stories.js
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/contactNotes.js
  app/javascript/dashboard/store/modules/specs/contactNotes/actions.spec.js
  app/javascript/dashboard/store/modules/specs/contactNotes/fixtures.js
  app/javascript/dashboard/store/modules/specs/contactNotes/getters.spec.js
  app/javascript/dashboard/store/modules/specs/contactNotes/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
Labels: PR: unreviewed

#2350 feat: Ability to add label for contact page
  app/javascript/dashboard/api/contacts.js
  app/javascript/dashboard/api/specs/contacts.spec.js
  app/javascript/dashboard/components/widgets/LabelSelector.stories.js
  app/javascript/dashboard/components/widgets/LabelSelector.vue
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactLabels.vue
  app/javascript/dashboard/routes/dashboard/conversation/labels/LabelBox.vue
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/contactLabels.js
  app/javascript/dashboard/store/modules/specs/contactLabels/actions.spec.js
  app/javascript/dashboard/store/modules/specs/contactLabels/getters.spec.js
  app/javascript/dashboard/store/modules/specs/contactLabels/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/shared/components/ui/dropdown/AddLabel.vue
  app/javascript/shared/components/ui/label/LabelDropdown.vue
  app/javascript/shared/components/ui/label/LabelDropdownItem.vue
Labels: PR: unreviewed

#2423 Chore: Update style for new message buton
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
Labels: PR: unreviewed

#2424 chore: Fixes contact panel scroll issue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue
Labels: PR: unreviewed

#2402 feat: Delete campaigns
  app/controllers/api/v1/accounts/campaigns_controller.rb
  app/javascript/dashboard/i18n/locale/en/campaign.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/AddCampaign.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/Campaign.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/CampaignsTable.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/EditCampaign.vue
  app/javascript/dashboard/store/modules/campaigns.js
  app/javascript/dashboard/store/modules/specs/campaigns/actions.spec.js
  app/javascript/dashboard/store/modules/specs/campaigns/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  config/routes.rb
  spec/controllers/api/v1/accounts/campaigns_controller_spec.rb
Labels: PR: unreviewed

#2375 feat: Add Public APIs for API Channel
  .rubocop.yml
  app/builders/contact_builder.rb
  app/controllers/api/v1/widget/messages_controller.rb
  app/controllers/public/api/v1/inboxes/contacts_controller.rb
  app/controllers/public/api/v1/inboxes/conversations_controller.rb
  app/controllers/public/api/v1/inboxes/messages_controller.rb
  app/controllers/public/api/v1/inboxes_controller.rb
  app/controllers/public_controller.rb
  app/models/channel/api.rb
  app/models/channel/web_widget.rb
  app/views/public/api/v1/inboxes/contacts/create.json.jbuilder
  app/views/public/api/v1/inboxes/contacts/show.json.jbuilder
  app/views/public/api/v1/inboxes/contacts/update.json.jbuilder
  app/views/public/api/v1/inboxes/conversations/create.json.jbuilder
  app/views/public/api/v1/inboxes/conversations/index.json.jbuilder
  app/views/public/api/v1/inboxes/messages/create.json.jbuilder
  app/views/public/api/v1/inboxes/messages/index.json.jbuilder
  app/views/public/api/v1/inboxes/messages/update.json.jbuilder
  app/views/public/api/v1/models/_contact.json.jbuilder
  app/views/public/api/v1/models/_conversation.json.jbuilder
  app/views/public/api/v1/models/_message.json.jbuilder
  config/environments/development.rb
  config/environments/production.rb
  config/routes.rb
  db/migrate/20210602182058_add_hmac_to_api_channel.rb
  db/schema.rb
  spec/controllers/platform/api/v1/public/api/v1/inbox/contacts_controller_spec.rb
  spec/controllers/platform/api/v1/public/api/v1/inbox/conversations_controller_spec.rb
  spec/controllers/platform/api/v1/public/api/v1/inbox/messages_controller_spec.rb
Labels: PR: unreviewed

#2335 feat: Create campaign conversation only if user interacts with the bubble
  app/javascript/sdk/IFrameHelper.js
  app/javascript/widget/App.vue
  app/javascript/widget/api/campaign.js
  app/javascript/widget/components/UnreadMessage.vue
  app/javascript/widget/helpers/campaignTimer.js
  app/javascript/widget/store/modules/campaign.js
  app/javascript/widget/store/modules/conversation/getters.js
  app/javascript/widget/store/modules/specs/campaign/actions.spec.js
  app/javascript/widget/store/modules/specs/campaign/getters.spec.js
  app/javascript/widget/store/modules/specs/campaign/mutations.spec.js
  app/javascript/widget/store/modules/specs/conversation/getters.spec.js
  app/javascript/widget/views/Router.vue
  app/javascript/widget/views/Unread.vue
  app/views/api/v1/widget/campaigns/index.json.jbuilder
Labels: PR: unreviewed

#2428 fix: Campaign message is hiding the conversation view after opening the widget
  app/javascript/widget/App.vue
Labels: PR: reviewed-approved

#2432 fix: Disallow unread/campaign view if widget is active
  app/javascript/widget/views/Router.vue
Labels: PR: reviewed-approved

#2417 doc: Swagger documentation for public APIs
  swagger/definitions/index.yml
  swagger/definitions/request/public/contact/create_update_payload.yml
  swagger/definitions/request/public/message/create_payload.yml
  swagger/definitions/request/public/message/update_payload.yml
  swagger/definitions/resource/public/contact.yml
  swagger/definitions/resource/public/conversation.yml
  swagger/definitions/resource/public/message.yml
  swagger/definitions/resource/user.yml
  swagger/index.yml
  swagger/parameters/index.yml
  swagger/parameters/public/contact_identifier.yml
  swagger/parameters/public/inbox_identifier.yml
  swagger/paths/index.yml
  swagger/paths/public/inboxes/contacts/create.yml
  swagger/paths/public/inboxes/contacts/show.yml
  swagger/paths/public/inboxes/contacts/update.yml
  swagger/paths/public/inboxes/conversations/create.yml
  swagger/paths/public/inboxes/conversations/index.yml
  swagger/paths/public/inboxes/messages/create.yml
  swagger/paths/public/inboxes/messages/index.yml
  swagger/paths/public/inboxes/messages/update.yml
  swagger/swagger.json
Labels: PR: reviewed-approved

#2427 chore: Adds support for multiselect in stories
  .storybook/preview.js
  app/javascript/dashboard/assets/scss/plugins/_multiselect.scss
  app/javascript/dashboard/assets/scss/storybook.scss
Labels: PR: unreviewed

#2455 chore: CSAT survey attribute for Inboxes
  app/models/inbox.rb
  db/migrate/20210618095823_add_csat_toggle_for_inbox.rb
  db/schema.rb
Labels: PR: reviewed-approved

#2454 feat: Add contact label filter
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/javascript/dashboard/api/contacts.js
  app/javascript/dashboard/api/specs/contacts.spec.js
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/SidebarItem.vue
  app/javascript/dashboard/i18n/default-sidebar.js
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue
  app/javascript/dashboard/routes/dashboard/contacts/routes.js
  app/javascript/dashboard/routes/dashboard/settings/labels/specs/validationMixin.spec.js
  app/javascript/dashboard/routes/dashboard/settings/labels/validationMixin.js
  app/javascript/dashboard/store/modules/contacts/actions.js
  lib/redis/config.rb
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
Labels: PR: unreviewed

#2421 feat: Improve chat scrolling on agent side
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/helpers/scrollTopCalculationHelper.js
  app/javascript/dashboard/components/widgets/conversation/helpers/specs/scrollTopCalculationHelper.spec.js
Labels: PR: unreviewed

#2453 chore: Disable tooltip for sender in bot messages
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: unreviewed

#2447 chore: Refined attachments preview
  app/javascript/dashboard/components/widgets/AttachmentsPreview.vue
Labels: PR: unreviewed

#2462 chore: Add contact note model
  app/models/account.rb
  app/models/contact.rb
  app/models/note.rb
  app/models/user.rb
  db/migrate/20210618073042_create_notes.rb
  db/schema.rb
  spec/factories/notes.rb
  spec/models/note_spec.rb
Labels: PR: reviewed-approved

#2449 chore: Adds storybook for woot input
  app/javascript/widget/components/Form/Input.stories.js
Labels: PR: reviewed-approved

#2456 feat: Add customer satisfaction component
  .codeclimate.yml
  app/javascript/dashboard/i18n/locale/en/csatMgmt.json
  app/javascript/dashboard/i18n/locale/en/index.js
  app/javascript/shared/components/CustomerSatisfaction.stories.js
  app/javascript/shared/components/CustomerSatisfaction.vue
  app/javascript/shared/constants/messages.js
  app/javascript/widget/components/AgentMessageBubble.vue
  app/javascript/widget/i18n/locale/en.json
  app/models/message.rb
  db/seeds.rb
  lib/woot_message_seeder.rb
Labels: PR: unreviewed

#2485 fix: Adds condition to handle base and mergee contact being same
  app/actions/contact_merge_action.rb
  spec/actions/contact_merge_action_spec.rb
Labels: PR: unreviewed

#2409 chore: Add help-text for slack integration
  app/javascript/dashboard/i18n/locale/en/integrations.json
  app/javascript/dashboard/routes/dashboard/settings/integrations/IntegrationHelpText.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/ShowIntegration.vue
Labels: PR: partially-approved

#2494 feat: Add CSAT Message Template Hooks
  app/models/inbox.rb
  app/services/message_templates/hook_execution_service.rb
  app/services/message_templates/template/csat_survey.rb
  config/locales/en.yml
  spec/services/message_templates/hook_execution_service_spec.rb
  spec/services/message_templates/template/csat_survey_spec.rb
Labels: PR: partially-approved

#2491 feat: Adds inbox info to previous conversations
  app/javascript/dashboard/routes/dashboard/conversation/ContactConversations.vue
Labels: PR: reviewed-approved

#2497 feat: Adds time zone in Business Hours
  app/javascript/dashboard/routes/dashboard/settings/inbox/helpers/specs/businessHour.spec.js
  app/javascript/dashboard/routes/dashboard/settings/inbox/helpers/timezones.json
Labels: PR: partially-approved

#2506 feat: Add CSAT response submit actions
  app/controllers/api/v1/widget/messages_controller.rb
  app/javascript/shared/components/CustomerSatisfaction.vue
  app/javascript/shared/constants/messages.js
  app/javascript/widget/components/AgentMessage.vue
  app/javascript/widget/components/AgentMessageBubble.vue
  app/javascript/widget/i18n/locale/en.json
Labels: PR: partially-approved

#2505 chore: fixes no gutter space between settings page content and right …
  app/javascript/dashboard/assets/scss/_foundation-custom.scss
  app/javascript/dashboard/routes/dashboard/settings/agents/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/canned/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/integrationapps/MultipleIntegrationHooks.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/Webhook.vue
  app/javascript/dashboard/routes/dashboard/settings/labels/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/teams/Index.vue
Labels: PR: partially-approved

#2451 chore: Adds storybook for woot textarea
  app/javascript/widget/components/Form/TextArea.stories.js
Labels: PR: unreviewed

#2511 feat: Show the CSAT response to the agent
  app/controllers/api/v1/widget/messages_controller.rb
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/helpers/botMessageContentHelper.js
  app/javascript/dashboard/components/widgets/conversation/helpers/specs/botMessageContentHelper.spec.js
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/widget/components/AgentMessageBubble.vue
Labels: PR: reviewed-changes-requested

#2444 feat: Adds storybook for search component.
  app/javascript/dashboard/routes/dashboard/conversation/search/ResultItem.stories.js
  app/javascript/dashboard/routes/dashboard/conversation/search/ResultItem.vue
  app/javascript/dashboard/routes/dashboard/conversation/search/SearchMessageItem.stories.js
  app/javascript/dashboard/routes/dashboard/conversation/search/SearchMessageItem.vue
Labels: PR: unreviewed

#2446 feat: Creates new component for multiselect.
  .codeclimate.yml
  app/javascript/dashboard/assets/scss/widgets/_buttons.scss
  app/javascript/dashboard/i18n/locale/en/agentMgmt.json
  app/javascript/shared/components/ui/MultiselectDropdown.stories.js
  app/javascript/shared/components/ui/MultiselectDropdownItems.stories.js
  app/javascript/shared/components/ui/MultiselectDropdownItems.vue
  app/javascript/shared/components/ui/MutiselectDropdown.vue
Labels: PR: partially-approved

#2514 fix: rvm gpg key issue
  deployment/setup_18.04.sh
  deployment/setup_20.04.sh
Labels: PR: partially-approved

#2515 fix: Remove style tags from email content
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/helpers/EmailContentParser.js
  app/javascript/dashboard/components/widgets/conversation/helpers/specs/EmailContentParser.spec.js
Labels: PR: reviewed-approved

#2518 fix: Add missing Cache-Control headers in the production config
  config/environments/production.rb
Labels: PR: reviewed-approved

#2519 feat: Actions and API for deleting message via API
  app/javascript/dashboard/api/inbox/message.js
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
  app/javascript/dashboard/store/mutation-types.js
Labels: PR: partially-approved

#2534 chore: Change the notification text for mention notification type
  app/helpers/message_format_helper.rb
  app/models/notification.rb
  lib/regex_helper.rb
  spec/helpers/message_format_helper_spec.rb
  spec/models/notification_spec.rb
Labels: PR: reviewed-approved

#2510 Chore: Support Github Codespaces
  .circleci/config.yml
  .devcontainer/Dockerfile
  .devcontainer/Dockerfile.base
  .devcontainer/devcontainer.json
  .github/workflows/publish_codespace_image.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  deployment/chatwoot-web.1.service
  deployment/chatwoot-worker.1.service
  deployment/setup_18.04.sh
  deployment/setup_20.04.sh
  docker/Dockerfile
Labels: PR: partially-approved

#2498 feat: Add APIs to create custom views on the dashboard
  app/controllers/api/v1/accounts/custom_filters_controller.rb
  app/models/account.rb
  app/models/custom_filter.rb
  app/models/user.rb
  app/views/api/v1/accounts/custom_filters/create.json.jbuilder
  app/views/api/v1/accounts/custom_filters/index.json.jbuilder
  app/views/api/v1/accounts/custom_filters/show.json.jbuilder
  app/views/api/v1/accounts/custom_filters/update.json.jbuilder
  app/views/api/v1/models/_custom_filter.json.jbuilder
  config/routes.rb
  db/migrate/20210623150613_create_custom_filters.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/custom_filters_controller_spec.rb
  spec/factories/custom_filters.rb
  swagger/definitions/index.yml
  swagger/definitions/request/custom_filter/create_update_payload.yml
  swagger/definitions/resource/custom_filter.yml
  swagger/index.yml
  swagger/parameters/custom_filter_id.yml
  swagger/parameters/index.yml
  swagger/paths/custom_filters/create.yml
  swagger/paths/custom_filters/delete.yml
  swagger/paths/custom_filters/index.yml
  swagger/paths/custom_filters/show.yml
  swagger/paths/custom_filters/update.yml
  swagger/paths/index.yml
  swagger/swagger.json
Labels: PR: partially-approved

#2532 feat: Adds delete option for messages in conversation
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/modules/conversations/components/MessageContextMenu.vue
Labels: PR: unreviewed

#2503 feat: CSAT APIs
  app/builders/csat_surveys/response_builder.rb
  app/builders/v2/report_builder.rb
  app/controllers/api/v1/accounts/csat_survey_responses_controller.rb
  app/controllers/api/v1/widget/messages_controller.rb
  app/dispatchers/async_dispatcher.rb
  app/helpers/date_range_helper.rb
  app/javascript/dashboard/components/widgets/conversation/helpers/botMessageContentHelper.js
  app/javascript/dashboard/components/widgets/conversation/helpers/specs/botMessageContentHelper.spec.js
  app/javascript/widget/components/AgentMessageBubble.vue
  app/listeners/csat_survey_listener.rb
  app/models/account.rb
  app/models/contact.rb
  app/models/conversation.rb
  app/models/csat_survey_response.rb
  app/models/message.rb
  app/models/user.rb
  app/policies/csat_survey_response_policy.rb
  app/views/api/v1/accounts/csat_survey_responses/index.json.jbuilder
  app/views/api/v1/models/_csat_survey_response.json.jbuilder
  config/routes.rb
  db/migrate/20210623155413_create_csat_survey_responses.rb
  db/schema.rb
  spec/builders/csat_surveys/response_builder_spec.rb
  spec/controllers/api/v1/accounts/campaigns_controller_spec.rb
  spec/controllers/api/v1/accounts/csat_survey_responses_controller_spec.rb
  spec/factories/csat_survey_responses.rb
  spec/listeners/csat_survey_listener_spec.rb
  spec/models/csat_survey_response_spec.rb
Labels: PR: unreviewed

#2546 feat: Adds drag and drop for images/files in the agent input box
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/shared/assets/stylesheets/colors.scss
Labels: PR: partially-approved

#2512 feat: Ability to create a new conversation if the previous conversation is resolved
  app/javascript/shared/constants/busEvents.js
  app/javascript/widget/App.vue
  app/javascript/widget/components/ChatFooter.vue
  app/javascript/widget/i18n/locale/en.json
  app/javascript/widget/mixins/configMixin.js
  app/javascript/widget/mixins/specs/configMixin.spec.js
  app/javascript/widget/store/modules/conversation/actions.js
  app/javascript/widget/store/modules/conversationAttributes.js
  app/javascript/widget/store/modules/specs/conversationAttributes/actions.spec.js
  app/javascript/widget/store/modules/specs/conversationAttributes/mutations.spec.js
  app/javascript/widget/store/types.js
  app/javascript/widget/views/Home.vue
  app/views/widgets/show.html.erb
Labels: PR: unreviewed
