Repository chatwoot/chatwoot, pull requests merged in 2021-09, with the labels that each got.

#2893 chore: Security Improvements to the API
  app/builders/messages/message_builder.rb
  app/controllers/api/v1/widget/messages_controller.rb
  app/controllers/public/api/v1/inboxes/messages_controller.rb
  app/helpers/file_type_helper.rb
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/forms/AvatarUploader.vue
  app/models/attachment.rb
  app/models/concerns/avatarable.rb
  config/initializers/devise_token_auth.rb
Labels: PR: partially-approved

#2832 feat: Creates pop out reply box
  app/javascript/dashboard/assets/scss/_woot.scss
  app/javascript/dashboard/components/widgets/WootWriter/ReplyTopPanel.vue
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/shared/assets/stylesheets/z-index.scss
Labels: PR: partially-approved

#2922 Add missing conversation id for first response event
  app/listeners/event_listener.rb
  spec/builders/v2/report_builder_spec.rb
Labels: PR: partially-approved

#2071 Enhancement: Fixes #1940 WCAG support for Web Client
  app/assets/stylesheets/administrate/utilities/_variables.scss
  app/javascript/sdk/IFrameHelper.js
  app/javascript/sdk/bubbleHelpers.js
  app/javascript/sdk/sdk.js
  app/javascript/widget/App.vue
  app/javascript/widget/assets/scss/_mixins.scss
  app/javascript/widget/components/ChatAttachment.vue
  app/javascript/widget/components/ChatFooter.vue
  app/javascript/widget/components/ChatInputWrap.vue
  app/javascript/widget/store/modules/events.js
  app/javascript/widget/views/Home.vue
Labels: PR: unreviewed

#2935 fix: Fixes messages jumping issue for newly created message
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
Labels: PR: unreviewed

#2900 feat: Platform API improvements
  app/controllers/platform/api/v1/accounts_controller.rb
  app/controllers/platform/api/v1/users_controller.rb
  app/jobs/delete_object_job.rb
  app/models/user.rb
  app/views/api/v1/models/_agent.json.jbuilder
  app/views/api/v1/models/_user.json.jbuilder
  app/views/platform/api/v1/models/_user.json.jbuilder
  db/migrate/20210827120929_add_custom_attributes_to_user.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/agents_controller_spec.rb
  spec/controllers/api/v1/profiles_controller_spec.rb
  spec/controllers/platform/api/v1/accounts_controller_spec.rb
  spec/controllers/platform/api/v1/users_controller_spec.rb
  spec/jobs/delete_object_job_spec.rb
  swagger/definitions/request/user/create_update_payload.yml
  swagger/definitions/resource/user.yml
  swagger/index.yml
  swagger/swagger.json
Labels: PR: reviewed-approved

#2934 Enhancement: Add date in agent report file
  app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
  app/javascript/dashboard/store/modules/reports.js
  app/javascript/dashboard/store/modules/specs/reports/actions.spec.js
Labels: PR: partially-approved

#2951 fix: Notification subscription update
  app/builders/notification_subscription_builder.rb
Labels: PR: reviewed-approved

#2948 enhancement: Improves design of conversation sidebar
  app/javascript/dashboard/assets/scss/widgets/_conversation-card.scss
  app/javascript/dashboard/components/Accordion/AccordionItem.stories.js
  app/javascript/dashboard/components/Accordion/AccordionItem.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyTopPanel.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/routes/dashboard/conversation/ContactConversations.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactCustomAttributes.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactItem.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
  app/javascript/dashboard/routes/dashboard/conversation/labels/LabelBox.vue
  app/javascript/shared/components/ui/dropdown/AddLabel.vue
Labels: PR: partially-approved

#2958 New Crowdin updates
  app/javascript/dashboard/i18n/locale/ar/agentMgmt.json
  app/javascript/dashboard/i18n/locale/ar/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/ar/campaign.json
  app/javascript/dashboard/i18n/locale/ar/contact.json
  app/javascript/dashboard/i18n/locale/ar/conversation.json
  app/javascript/dashboard/i18n/locale/ar/csatMgmt.json
  app/javascript/dashboard/i18n/locale/ar/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/ar/settings.json
  app/javascript/dashboard/i18n/locale/tr/agentMgmt.json
  app/javascript/dashboard/i18n/locale/tr/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/tr/campaign.json
  app/javascript/dashboard/i18n/locale/tr/chatlist.json
  app/javascript/dashboard/i18n/locale/tr/contact.json
  app/javascript/dashboard/i18n/locale/tr/conversation.json
  app/javascript/dashboard/i18n/locale/tr/csatMgmt.json
  app/javascript/dashboard/i18n/locale/tr/generalSettings.json
  app/javascript/dashboard/i18n/locale/tr/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/tr/integrationApps.json
  app/javascript/dashboard/i18n/locale/tr/settings.json
  app/javascript/dashboard/i18n/locale/zh_TW/agentMgmt.json
  app/javascript/dashboard/i18n/locale/zh_TW/campaign.json
  app/javascript/dashboard/i18n/locale/zh_TW/cannedMgmt.json
  app/javascript/dashboard/i18n/locale/zh_TW/contact.json
  app/javascript/dashboard/i18n/locale/zh_TW/conversation.json
  app/javascript/dashboard/i18n/locale/zh_TW/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/zh_TW/integrations.json
  app/javascript/dashboard/i18n/locale/zh_TW/labelsMgmt.json
  app/javascript/dashboard/i18n/locale/zh_TW/settings.json
  app/javascript/widget/i18n/locale/ar.json
  app/javascript/widget/i18n/locale/tr.json
  config/locales/tr.yml
Labels: PR: unreviewed

#2839 feat: Convert existing conversation side panel contact sections to an accordion
  app/javascript/dashboard/assets/scss/widgets/_conversation-card.scss
  app/javascript/dashboard/components/Accordion/AccordionItem.stories.js
  app/javascript/dashboard/components/Accordion/AccordionItem.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyTopPanel.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/routes/dashboard/conversation/ContactConversations.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactCustomAttributes.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
  app/javascript/dashboard/routes/dashboard/conversation/labels/LabelBox.vue
  app/javascript/shared/components/ui/dropdown/AddLabel.vue
Labels: PR: unreviewed

#2963 fix: Update actions position if avatar image is unavailable
  app/javascript/widget/components/ChatHeaderExpanded.vue
Labels: PR: partially-approved

#2964 feat: Update design - CSAT survey page
  app/javascript/survey/components/Feedback.vue
  app/javascript/survey/components/Rating.vue
  app/javascript/survey/i18n/locale/en.json
  app/javascript/survey/views/Response.vue
  app/views/public/api/v1/models/_csat_survey.json.jbuilder
Labels: PR: partially-approved

#2969 fix: Remove duplicate emit event
  app/javascript/dashboard/components/Accordion/AccordionItem.vue
Labels: PR: partially-approved

#2959 feat: Send MMS through Twilio Inbox
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/services/twilio/send_on_twilio_service.rb
  spec/services/twilio/send_on_twilio_service_spec.rb
Labels: PR: reviewed-approved

#2953 Mount local storage to host
  docker-compose.production.yaml
Labels: PR: reviewed-approved

#2976 chore: Attachment validation fix
  app/models/attachment.rb
Labels: PR: reviewed-approved

#2975 feat: Configure Chatwoot & Analytics for SaaS app
  app/controllers/dashboard_controller.rb
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue
  app/javascript/dashboard/helper/scriptHelpers.js
  app/javascript/dashboard/store/modules/auth.js
  app/javascript/dashboard/store/utils/api.js
  app/javascript/packs/application.js
  app/views/devise/token.json.jbuilder
  app/views/layouts/vueapp.html.erb
  config/installation_config.yml
  package.json
  yarn.lock
Labels: PR: unreviewed

#2965 New Crowdin updates
  app/javascript/dashboard/i18n/locale/ro/conversation.json
  app/javascript/dashboard/i18n/locale/ru/conversation.json
Labels: PR: unreviewed

#2929 feat: Creates a custom attribute table
  app/javascript/dashboard/api/attributes.js
  app/javascript/dashboard/i18n/locale/en/attributesMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/attributes/AddAttribute.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/CustomAttribute.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/Index.vue
  app/javascript/dashboard/store/modules/attributes.js
  app/javascript/dashboard/store/modules/specs/attributes/actions.spec.js
  app/javascript/dashboard/store/modules/specs/attributes/fixtures.js
  app/javascript/dashboard/store/modules/specs/attributes/getters.spec.js
Labels: PR: reviewed-approved

#2977 fix: Revert translated values in CHAT_STATUS_ITEMS
  app/javascript/dashboard/i18n/locale/ar/chatlist.json
  app/javascript/dashboard/i18n/locale/cs/chatlist.json
  app/javascript/dashboard/i18n/locale/el/chatlist.json
  app/javascript/dashboard/i18n/locale/fa/chatlist.json
  app/javascript/dashboard/i18n/locale/nl/chatlist.json
  app/javascript/dashboard/i18n/locale/pl/chatlist.json
  app/javascript/dashboard/i18n/locale/pt/chatlist.json
  app/javascript/dashboard/i18n/locale/pt_BR/chatlist.json
  app/javascript/dashboard/i18n/locale/ru/chatlist.json
  app/javascript/dashboard/i18n/locale/th/chatlist.json
  app/javascript/dashboard/i18n/locale/zh/chatlist.json
  app/javascript/dashboard/i18n/locale/zh_TW/chatlist.json
Labels: PR: partially-approved

#2952 Feat: Add multiline support for channel greeting message
  app/javascript/dashboard/assets/scss/views/settings/inbox.scss
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Website.vue
  app/javascript/shared/components/GreetingsEditor.vue
  app/services/message_templates/hook_execution_service.rb
  spec/services/message_templates/hook_execution_service_spec.rb
Labels: PR: reviewed-approved

#2924 chore: Strip unnecessary data from push payload
  app/models/notification.rb
  app/services/notification/push_notification_service.rb
Labels: PR: reviewed-approved, QA Review Done

#2901 feat: Telegram Channel
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/controllers/webhooks/telegram_controller.rb
  app/javascript/dashboard/components/widgets/ChannelItem.vue
  app/javascript/dashboard/components/widgets/Thumbnail.vue
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channel-factory.js
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Telegram.vue
  app/jobs/send_reply_job.rb
  app/jobs/webhooks/telegram_events_job.rb
  app/models/account.rb
  app/models/channel/api.rb
  app/models/channel/email.rb
  app/models/channel/telegram.rb
  app/models/channel/web_widget.rb
  app/models/inbox.rb
  app/services/telegram/incoming_message_service.rb
  app/services/telegram/send_on_telegram_service.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  config/routes.rb
  db/migrate/20210828124043_add_telegram_channel.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
  spec/controllers/webhooks/telegram_controller_spec.rb
  spec/factories/channel/channel_telegram.rb
  spec/jobs/send_reply_job_spec.rb
  spec/jobs/webhooks/telegram_events_job_spec.rb
  spec/services/telegram/incoming_message_service_spec.rb
  spec/services/telegram/send_on_telegram_service_spec.rb
Labels: PR: unreviewed

#2904 feat: Line Channel
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/controllers/webhooks/line_controller.rb
  app/javascript/dashboard/components/widgets/ChannelItem.vue
  app/javascript/dashboard/components/widgets/Thumbnail.vue
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channel-factory.js
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Line.vue
  app/javascript/shared/mixins/configMixin.js
  app/jobs/send_reply_job.rb
  app/jobs/webhooks/line_events_job.rb
  app/models/account.rb
  app/models/channel/api.rb
  app/models/channel/email.rb
  app/models/channel/facebook_page.rb
  app/models/channel/line.rb
  app/models/channel/telegram.rb
  app/models/channel/twilio_sms.rb
  app/models/channel/twitter_profile.rb
  app/models/channel/web_widget.rb
  app/models/concerns/channelable.rb
  app/models/inbox.rb
  app/services/line/incoming_message_service.rb
  app/services/line/send_on_line_service.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  config/routes.rb
  db/migrate/20210829124254_add_line_channel.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
  spec/controllers/webhooks/line_controller_spec.rb
  spec/factories/channel/channel_line.rb
  spec/jobs/send_reply_job_spec.rb
  spec/jobs/webhooks/line_events_job_spec.rb
  spec/services/line/incoming_message_service_spec.rb
  spec/services/line/send_on_line_service_spec.rb
Labels: PR: unreviewed

#3001 chore: Update Changelog URL
  app/javascript/dashboard/components/widgets/conversation/OnboardingView.vue
Labels: PR: reviewed-approved

#2997 chore: Support for special characters in password
  Gemfile
  Gemfile.lock
  spec/controllers/devise/session_controller_spec.rb
Labels: PR: reviewed-approved

#2949 fix: Selected agent profile picture in agent multi select
  app/controllers/api/v1/accounts/conversations/assignments_controller.rb
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/models/user.rb
Labels: PR: partially-approved, QA Review Done

#2982 feat: Adds the ability to edit and delete custom attributes
  app/javascript/dashboard/helper/commons.js
  app/javascript/dashboard/helper/specs/commons.spec.js
  app/javascript/dashboard/i18n/locale/en/attributesMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/attributes/AddAttribute.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/CustomAttribute.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/EditAttribute.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/constants.js
  app/javascript/dashboard/store/modules/attributes.js
Labels: PR: unreviewed

#2988 chore: Move Facebook event processing to worker
  app/jobs/webhooks/facebook_events_job.rb
  config/initializers/facebook_messenger.rb
  lib/integrations/facebook/message_creator.rb
  lib/integrations/facebook/message_parser.rb
  spec/builders/messages/facebook/message_builder_spec.rb
  spec/factories/facebook_message/incoming_fb_text_message.rb
  spec/jobs/webhooks/facebook_events_job_spec.rb
Labels: PR: unreviewed

#3002 chore: Update contact sidebar with accordion
  app/javascript/dashboard/components/widgets/LabelSelector.vue
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/mixins/specs/uiSettings.spec.js
  app/javascript/dashboard/mixins/uiSettings.js
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactConversations.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactCustomAttributes.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/labels/LabelBox.vue
Labels: PR: partially-approved

#2981 chore: Upgrade vue router to the latest version
  package.json
  yarn.lock
Labels: PR: unreviewed, in-QA

#3008 Chore: Inbox Members API improvements
  app/controllers/api/v1/accounts/inbox_members_controller.rb
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/request_exception_handler.rb
  app/controllers/platform/api/v1/users_controller.rb
  app/controllers/platform_controller.rb
  app/controllers/public_controller.rb
  app/javascript/dashboard/api/inboxMembers.js
  app/javascript/dashboard/store/modules/inboxMembers.js
  app/models/inbox.rb
  app/views/api/v1/accounts/inbox_members/create.json.jbuilder
  app/views/api/v1/accounts/inbox_members/update.json.jbuilder
  config/routes.rb
  spec/controllers/api/v1/accounts/inbox_members_controller_spec.rb
  swagger/definitions/index.yml
  swagger/definitions/resource/agent.yml
  swagger/parameters/inbox_id.yml
  swagger/parameters/index.yml
  swagger/paths/inboxes/inbox_members/create.yml
  swagger/paths/inboxes/inbox_members/delete.yml
  swagger/paths/inboxes/inbox_members/show.yml
  swagger/paths/inboxes/inbox_members/update.yml
  swagger/paths/inboxes/show.yml
  swagger/paths/index.yml
  swagger/swagger.json
Labels: PR: reviewed-approved

#3009 fix: Hide quoted replies by default from messages
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Text.vue
  app/javascript/dashboard/i18n/locale/en/chatlist.json
  app/javascript/shared/mixins/messageFormatterMixin.js
Labels: PR: partially-approved

#3010 fix: Revert key changes in `it` translation files
  app/javascript/dashboard/i18n/locale/it/chatlist.json
Labels: PR: unreviewed

#3005 chore: Update installation env value for linux script
  deployment/setup_18.04.sh
  deployment/setup_20.04.sh
Labels: PR: unreviewed

#3011 Chore: Release Fixes
  app/controllers/super_admin/dashboard_controller.rb
  app/services/telegram/incoming_message_service.rb
  app/views/super_admin/dashboard/index.html.erb
  spec/services/telegram/incoming_message_service_spec.rb
Labels: PR: unreviewed

#3014 chore: API fixes
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/AddAgents.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/shared/mixins/inboxMixin.js
  app/models/inbox.rb
  app/services/line/incoming_message_service.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
Labels: PR: unreviewed

#3016 chore: Sidebar icons for new inboxes
  app/builders/messages/facebook/message_builder.rb
  app/javascript/dashboard/components/layout/SidebarItem.vue
  app/javascript/dashboard/helper/inbox.js
  app/javascript/shared/mixins/inboxMixin.js
  app/jobs/contact_ip_lookup_job.rb
  config/initializers/rack_attack.rb
  lib/integrations/dialogflow/processor_service.rb
  lib/integrations/slack/send_on_slack_service.rb
Labels: PR: reviewed-approved

#3019 fix: Reject keyboard shortcut listeners if input box is active
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/buttons/ResolveAction.vue
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/SidebarItem.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/sdk/sdk.js
  app/javascript/shared/mixins/eventListenerMixins.js
Labels: PR: partially-approved

#3021 chore: Use the name of the sender from the mail object
  app/mailboxes/support_mailbox.rb
  app/presenters/mail_presenter.rb
  spec/fixtures/files/support_without_sender_name.eml
  spec/mailboxes/support_mailbox_spec.rb
Labels: PR: unreviewed

#3025 chore: Return medium in inbox APIs
  app/builders/messages/facebook/message_builder.rb
  app/models/inbox.rb
  app/views/api/v1/models/_inbox.json.jbuilder
Labels: PR: unreviewed

#2851 feat: Add state and mutations for multiple conversation on widget
  app/javascript/widget/store/modules/conversation/actions.js
  app/javascript/widget/store/modules/conversation/index.js
  app/javascript/widget/store/modules/conversation/mutations.js
  app/javascript/widget/store/modules/conversation_new/index.js
  app/javascript/widget/store/modules/conversation_new/mutations.js
  app/javascript/widget/store/modules/specs/conversation_new/mutation.spec.js
Labels: PR: unreviewed

#3027 fix: Emails not delivered when case does not match
  app/mailboxes/application_mailbox.rb
  app/mailboxes/support_mailbox.rb
  spec/fixtures/files/support_without_sender_name.eml
  spec/mailboxes/support_mailbox_spec.rb
Labels: PR: partially-approved

#2992 Feat: Out of office autoresponder
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/models/working_hour.rb
  app/services/message_templates/hook_execution_service.rb
  spec/models/working_hour_spec.rb
  spec/services/message_templates/hook_execution_service_spec.rb
Labels: PR: unreviewed

#3022 feat: Support sending and receiving attachments in Slack Integration
  app/models/attachment.rb
  lib/integrations/slack/incoming_message_builder.rb
  lib/integrations/slack/send_on_slack_service.rb
  spec/lib/integrations/slack/incoming_message_builder_spec.rb
  spec/lib/integrations/slack/send_on_slack_service_spec.rb
  spec/support/slack_stubs.rb
Labels: PR: unreviewed

#3043 fix: Update title for `out of office message`
  app/javascript/dashboard/i18n/locale/ca/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/cs/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/da/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/fi/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/he/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/hi/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/it/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/ja/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/ml/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/ne/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/nl/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/no/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/ro/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/sk/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/sv/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/ta/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/th/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/tr/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/uk/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/vi/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/zh_CN/inboxMgmt.json
Labels: PR: unreviewed

#3030 Add option button CSS rules
  app/javascript/shared/components/ChatOption.vue
Labels: PR: reviewed-approved

#3051 fix: Outbound messages triggering out of office
  app/services/message_templates/hook_execution_service.rb
  spec/services/message_templates/hook_execution_service_spec.rb
Labels: PR: reviewed-approved

#3046 fix: Update associations when a label is updated
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactLabels.vue
  app/jobs/labels/update_job.rb
  app/models/label.rb
  app/services/labels/update_service.rb
  spec/jobs/labels/update_job_spec.rb
  spec/models/label_spec.rb
  spec/services/labels/update_service_spec.rb
Labels: PR: partially-approved

#3057 fix: Add blank check for file param in Import API
  app/controllers/api/v1/accounts/contacts_controller.rb
  config/locales/en.yml
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
Labels: PR: reviewed-approved

#3024 chore: Conversation custom attribute APIs
  Gemfile
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/models/conversation.rb
  app/views/api/v1/accounts/conversations/custom_attributes.json.jbuilder
  app/views/api/v1/conversations/partials/_conversation.json.jbuilder
  config/routes.rb
  db/migrate/20210916060144_add_custom_attributes_to_conversations.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
Labels: PR: partially-approved

#3020 feat: Add actions for multiple conversation on widget #2851
  app/javascript/widget/api/conversation.js
  app/javascript/widget/store/modules/conversation_new/actions.js
  app/javascript/widget/store/modules/conversation_new/getters.js
  app/javascript/widget/store/modules/conversation_new/helpers.js
  app/javascript/widget/store/modules/conversation_new/index.js
  app/javascript/widget/store/modules/conversation_new/mutations.js
Labels: PR: unreviewed

#2984 feat: Ability to delete a contact
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/javascript/dashboard/helper/actionCable.js
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
  app/javascript/dashboard/store/modules/contactConversations.js
  app/javascript/dashboard/store/modules/contacts/actions.js
  app/javascript/dashboard/store/modules/contacts/index.js
  app/javascript/dashboard/store/modules/contacts/mutations.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/modules/specs/contacts/actions.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/listeners/action_cable_listener.rb
  app/models/contact.rb
  app/policies/contact_policy.rb
  config/locales/en.yml
  config/routes.rb
  lib/events/types.rb
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
  spec/listeners/action_cable_listener_spec.rb
  swagger/paths/contact/crud.yml
  swagger/swagger.json
Labels: PR: unreviewed

#3069 feat: Handle assignee last seen
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/models/conversation.rb
  app/views/api/v1/accounts/conversations/messages/index.json.jbuilder
  app/views/api/v1/conversations/partials/_conversation.json.jbuilder
  db/migrate/20210922082754_add_assignee_last_seen.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
Labels: PR: unreviewed

#3064 fix: Fixes offset issue for Business hours on timezones with DST
  app/views/api/v1/widget/configs/create.json.jbuilder
  app/views/widgets/show.html.erb
Labels: PR: reviewed-approved

#3075 Chores: Refactoring unused memoization in telegram services removed
  app/services/telegram/incoming_message_service.rb
Labels: PR: unreviewed

#3067 bug: fixes error in creating a new one off campaign
  app/javascript/dashboard/routes/dashboard/settings/campaigns/AddCampaign.vue
  app/javascript/dashboard/routes/dashboard/settings/campaigns/EditCampaign.vue
  app/javascript/dashboard/store/modules/inboxes.js
  app/javascript/dashboard/store/modules/specs/inboxes/fixtures.js
  app/javascript/dashboard/store/modules/specs/inboxes/getters.spec.js
Labels: PR: unreviewed

#3066 feat: API to Filter reports by teams
  app/builders/v2/report_builder.rb
  app/controllers/api/v2/accounts/reports_controller.rb
  app/models/team.rb
  app/views/api/v2/accounts/reports/teams.csv.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/api/v2/accounts/report_controller_spec.rb
  swagger/parameters/report_type.yml
  swagger/paths/index.yml
  swagger/swagger.json
Labels: PR: unreviewed

#3013 feat: Adds ability to edit out webhook URL of API Channel
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/shared/helpers/Validators.js
  app/javascript/shared/helpers/specs/ValidatorsHelper.spec.js
Labels: PR: partially-approved

#3080 feat: Ability to close and reopen the chat window via SDK
  app/javascript/packs/sdk.js
  app/javascript/sdk/IFrameHelper.js
Labels: PR: reviewed-approved, QA Review Done, docs-done

#3072 fix: dialogflow integration in docker environments
  Gemfile.lock
  docker/Dockerfile
  docker/entrypoints/rails.sh
Labels: PR: unreviewed

#3026 Feat: ability to import contacts
  app/javascript/dashboard/api/contacts.js
  app/javascript/dashboard/api/specs/contacts.spec.js
  app/javascript/dashboard/assets/scss/_utility-helpers.scss
  app/javascript/dashboard/assets/scss/widgets/_modal.scss
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ImportContacts.vue
  app/javascript/dashboard/store/modules/contacts/actions.js
  public/downloads/import-contacts-sample.csv
Labels: feature, PR: unreviewed, PR: reviewed-changes-requested, PR: partially-approved

#3003 bug: Fixes Incorrect badge for Twilio SMS inbox and adds the ability to differentiate Twitter tweets and chats
  app/javascript/dashboard/assets/images/twitter-chat-badge.png
  app/javascript/dashboard/components/widgets/Thumbnail.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/shared/components/ui/MultiselectDropdown.vue
  app/javascript/shared/mixins/inboxMixin.js
  app/javascript/shared/mixins/specs/inboxMixin.spec.js
Labels: PR: unreviewed

#3093 bug: Adds meaningful alert error message if file upload fails
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/store/modules/conversations/actions.js
Labels: PR: unreviewed

#3102 feat: Add all filter for conversations
  app/finders/conversation_finder.rb
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/widgets/conversation/ChatFilter.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/constants.js
  app/javascript/dashboard/i18n/locale/en/chatlist.json
  app/javascript/dashboard/store/modules/conversations/helpers.js
  app/javascript/dashboard/store/modules/specs/conversations/helpers.spec.js
  spec/finders/conversation_finder_spec.rb
  swagger/paths/conversation/index.yml
  swagger/swagger.json
Labels: PR: unreviewed

#3106 chore: Fix Twilio callback url not appearing until refresh
  app/views/api/v1/accounts/channels/twilio_channels/create.json.jbuilder
Labels: PR: unreviewed

#3028 feat: Display "Snoozed Until" time on conversation header
  app/javascript/dashboard/assets/scss/_woot.scss
  app/javascript/dashboard/assets/scss/widgets/_conv-header.scss
  app/javascript/dashboard/components/widgets/InboxName.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/components/widgets/conversation/MoreActions.vue
  app/javascript/dashboard/components/widgets/conversation/specs/MoreActions.spec.js
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/presenters/conversations/event_data_presenter.rb
  app/views/api/v1/accounts/conversations/toggle_status.json.jbuilder
  app/views/api/v1/conversations/partials/_conversation.json.jbuilder
  spec/models/conversation_spec.rb
  spec/presenters/conversations/event_data_presenter_spec.rb
Labels: PR: unreviewed

#3084 Feature - filter reports by agent, label and inboxes
  app/javascript/dashboard/api/reports.js
  app/javascript/dashboard/api/specs/reports.spec.js
  app/javascript/dashboard/assets/scss/widgets/_report.scss
  app/javascript/dashboard/assets/scss/widgets/_reports.scss
  app/javascript/dashboard/i18n/default-sidebar.js
  app/javascript/dashboard/i18n/locale/en/report.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/i18n/sidebarItems/campaigns.js
  app/javascript/dashboard/i18n/sidebarItems/common.js
  app/javascript/dashboard/i18n/sidebarItems/contacts.js
  app/javascript/dashboard/i18n/sidebarItems/reports.js
  app/javascript/dashboard/i18n/sidebarItems/settings.js
  app/javascript/dashboard/routes/dashboard/Dashboard.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/AgentReports.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/InboxReports.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/LabelReports.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/WootReports.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/reports.routes.js
  app/javascript/dashboard/store/modules/reports.js
  app/javascript/dashboard/store/modules/specs/reports/actions.spec.js
Labels: PR: reviewed-approved

#3117 fix: Update Re-rendering behaviour for lists in conversation view
  app/javascript/dashboard/routes/dashboard/Dashboard.vue
  app/javascript/dashboard/routes/dashboard/settings/Wrapper.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/reports.routes.js
Labels: PR: reviewed-approved

#3119 chore: Add readonly attribute to woot-input component
  app/javascript/dashboard/components/widgets/forms/Input.vue
Labels: PR: reviewed-approved

#3108 feat: Ability to send attachments to telegram
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/shared/mixins/inboxMixin.js
  app/models/channel/telegram.rb
  app/services/telegram/send_on_telegram_service.rb
  spec/assets/attachment.pdf
  spec/models/channel/telegram_spec.rb
Labels: PR: unreviewed
