Repository chatwoot/chatwoot, pull requests merged in 2021-08, with the labels that each got.

#2405 chore: Mark Facebook accounts for reconnection
  .rubocop.yml
  app/builders/messages/facebook/message_builder.rb
  app/mailers/administrator_notifications/channel_notifications_mailer.rb
  app/models/concerns/reauthorizable.rb
  app/views/mailers/administrator_notifications/channel_notifications_mailer/facebook_disconnect.liquid
  spec/builders/messages/facebook/message_builder_spec.rb
  spec/mailers/administrator_notifications/channel_notifications_mailer_spec.rb
  spec/mailers/agent_notifications/conversation_notifications_mailer_spec.rb
  spec/models/channel/facebook_page_spec.rb
Labels: PR: unreviewed

#2730 fix: Avoid flicker while updating the view with new messages
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
Labels: PR: partially-approved

#2699 fix: Render line-breaks properly in messages
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/MailHead.vue
  app/javascript/shared/helpers/MessageFormatter.js
  app/javascript/widget/components/UserMessage.vue
Labels: PR: unreviewed

#2448 chore: Show new account modal if user accounts are empty
  app/javascript/dashboard/App.vue
  app/javascript/dashboard/components/layout/sidebarComponents/AddAccountModal.vue
  app/javascript/dashboard/i18n/locale/en/settings.json
Labels: PR: partially-approved

#2731 fix: Resolve conversation with id instead of current conversation
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/getters.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js
Labels: PR: reviewed-approved, QA Review Done

#2709 fix: Update tweet character count logic
  app/javascript/dashboard/api/inbox/message.js
  app/javascript/dashboard/api/specs/inbox/message.spec.js
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/services/twitter/send_on_twitter_service.rb
  spec/services/twitter/send_on_twitter_service_spec.rb
Labels: PR: unreviewed

#2743 feat: Updates icons to show last message type
  app/javascript/dashboard/assets/scss/widgets/_conversation-card.scss
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
Labels: PR: reviewed-approved

#2740 docs: update chatwoot VDP guidelines
  README.md
  SECURITY.md
Labels: PR: unreviewed

#2685 feat: CSAT response collection public page
  .rubocop.yml
  app/controllers/survey/responses_controller.rb
  app/javascript/packs/survey.js
  app/javascript/shared/components/Branding.vue
  app/javascript/shared/components/Button.vue
  app/javascript/shared/components/TextArea.vue
  app/javascript/survey/App.vue
  app/javascript/survey/assets/scss/woot.scss
  app/javascript/survey/components/Rating.vue
  app/javascript/survey/i18n/index.js
  app/javascript/survey/i18n/locale/en.json
  app/javascript/survey/views/Response.vue
  app/javascript/widget/views/Home.vue
  app/views/survey/responses/show.html.erb
  config/routes.rb
  config/webpack/resolve.js
  spec/controllers/service/responses_controller_spec.rb
  tailwind.config.js
Labels: PR: unreviewed

#2577 feat: Adds support for rich content message editor in Campaigns
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/AddCampaign.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/CampaignsTable.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/EditCampaign.vue
Labels: PR: partially-approved

#2747 fix: Fix and rename pg_database_url.sh helper script
  docker/entrypoints/helpers/pg_database_url.rb
  docker/entrypoints/rails.sh
Labels: PR: reviewed-approved

#2756 fix: Add brand color in csat card component
  app/javascript/shared/components/CustomerSatisfaction.vue
Labels: PR: reviewed-approved

#2753 Fix finnish language
  app/javascript/dashboard/i18n/locale/fi/agentMgmt.json
  app/javascript/dashboard/i18n/locale/fi/campaign.json
  app/javascript/dashboard/i18n/locale/fi/chatlist.json
  app/javascript/dashboard/i18n/locale/fi/contact.json
  app/javascript/dashboard/i18n/locale/fi/conversation.json
  app/javascript/dashboard/i18n/locale/fi/csatMgmt.json
  app/javascript/dashboard/i18n/locale/fi/generalSettings.json
  app/javascript/dashboard/i18n/locale/fi/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/fi/integrationApps.json
  app/javascript/dashboard/i18n/locale/fi/login.json
  app/javascript/dashboard/i18n/locale/fi/report.json
  app/javascript/dashboard/i18n/locale/fi/settings.json
  app/javascript/dashboard/i18n/locale/fi/teamsSettings.json
  app/javascript/widget/i18n/locale/fi.json
  config/locales/fi.yml
Labels: PR: unreviewed

#2755 fix: Broken Docker Builds
  .nvmrc
  docker/Dockerfile
Labels: PR: unreviewed

#2761 Fix: Twilio messages not get sent
  app/services/twilio/oneoff_sms_campaign_service.rb
  app/services/twilio/send_on_twilio_service.rb
Labels: PR: unreviewed

#2764 docs: Update README to add question/support sub-section
  README.md
Labels: PR: reviewed-approved

#2727 fix: Fixes unread view blocking page scroll
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/sdk/IFrameHelper.js
  app/javascript/sdk/sdk.js
  app/javascript/widget/App.vue
  app/javascript/widget/assets/scss/woot.scss
  app/javascript/widget/views/Unread.vue
Labels: PR: reviewed-approved, QA Review Done

#2758 enhancement: Show close button for unread view
  app/javascript/widget/views/Unread.vue
Labels: PR: unreviewed, QA Review Done

#2775 chore: fixes text retain issue in confirm delete modal
  app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/teams/Index.vue
Labels: PR: partially-approved

#2672 feat: Adds keyboard shortcuts for conversation actions
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/buttons/ResolveAction.vue
  app/javascript/dashboard/components/layout/SidebarItem.vue
  app/javascript/dashboard/components/widgets/ChatTypeTabs.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyTopPanel.vue
  app/javascript/dashboard/components/widgets/conversation/ChatFilter.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/routes/dashboard/conversation/labels/LabelBox.vue
  app/javascript/shared/components/ui/MultiselectDropdownItems.vue
  app/javascript/shared/components/ui/dropdown/DropdownItem.vue
  app/javascript/shared/components/ui/dropdown/DropdownMenu.vue
  app/javascript/shared/helpers/KeyboardHelpers.js
  app/javascript/shared/mixins/eventListenerMixins.js
Labels: PR: partially-approved, QA Review Done

#2778 fix: Reduces spacing for custom drop-downs
  app/javascript/shared/components/ui/MultiselectDropdown.vue
Labels: PR: unreviewed

#2774 fix: Save content_type, multipart information to email message model
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/presenters/mail_presenter.rb
  spec/mailboxes/reply_mailbox_spec.rb
  spec/mailboxes/support_mailbox_spec.rb
  spec/presenters/mail_presenter_spec.rb
Labels: PR: reviewed-approved

#2728 feat: Creates a modal showing all the available keyboard shortcuts
  app/javascript/dashboard/components/buttons/ResolveAction.vue
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue
  app/javascript/dashboard/components/widgets/modal/WootKeyShortcutModal.stories.js
  app/javascript/dashboard/components/widgets/modal/WootKeyShortcutModal.vue
  app/javascript/dashboard/components/widgets/modal/constants.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/shared/helpers/KeyboardHelpers.js
Labels: PR: partially-approved

#2763 feat: Creates cc bcc input component story for reply box
  app/javascript/dashboard/assets/scss/plugins/_multiselect.scss
  app/javascript/dashboard/components/widgets/conversation/ReplyEmailHead.vue
  app/javascript/dashboard/components/widgets/conversation/helpers/emailHeadHelper.js
  app/javascript/dashboard/components/widgets/conversation/helpers/specs/emailHeadHelper.spec.js
  app/javascript/dashboard/components/widgets/conversation/stories/ReplyEmailHead.stories.js
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/widget/store/modules/conversation/actions.js
Labels: frontend, PR: unreviewed, PR: reviewed-changes-requested, PR: partially-approved

#2781 chore: Removes the multi-select dropdown from the conversation header
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
Labels: PR: unreviewed

#2733 Enhancement: Updates sidebar to a new design
  app/javascript/dashboard/assets/scss/_foundation-custom.scss
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/assets/scss/_variables.scss
  app/javascript/dashboard/assets/scss/views/settings/inbox.scss
  app/javascript/dashboard/assets/scss/widgets/_sidemenu.scss
  app/javascript/dashboard/components/layout/AvailabilityStatus.vue
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/SidebarItem.vue
  app/javascript/dashboard/components/layout/sidebarComponents/AgentDetails.vue
  app/javascript/dashboard/components/layout/sidebarComponents/NotificationBell.vue
  app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue
  app/javascript/dashboard/components/layout/sidebarComponents/specs/AgentDetails.spec.js
  app/javascript/dashboard/components/layout/sidebarComponents/specs/NotificationBell.spec.js
  app/javascript/dashboard/components/layout/specs/AvailabilityStatus.spec.js
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/i18n/default-sidebar.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/modules/sidebar/components/Logo.vue
  app/javascript/dashboard/modules/sidebar/components/Primary.vue
  app/javascript/dashboard/modules/sidebar/components/PrimaryNavItem.vue
  app/javascript/dashboard/modules/sidebar/components/Secondary.vue
  app/javascript/dashboard/modules/sidebar/components/SecondaryNavItem.vue
  app/javascript/shared/assets/stylesheets/colors.scss
  app/javascript/widget/store/modules/conversation/actions.js
  package.json
  public/brand-assets/logo.svg
  yarn.lock
Labels: frontend, PR: unreviewed, PR: reviewed-approved

#2765 chore: Add down gem for Local file downloads
  Gemfile
  Gemfile.lock
  app/builders/messages/facebook/message_builder.rb
  app/controllers/api/v1/accounts/callbacks_controller.rb
  app/jobs/contact_avatar_job.rb
  app/jobs/contact_ip_lookup_job.rb
  app/services/twilio/incoming_message_service.rb
  lib/chatwoot_hub.rb
  lib/exception_list.rb
  lib/local_resource.rb
  lib/webhooks/trigger.rb
Labels: PR: unreviewed

#2741 feat: Dedicated tab for campaigns
  Gemfile.lock
  app/javascript/dashboard/components/widgets/InboxIconWithName.vue
  app/javascript/dashboard/i18n/default-sidebar.js
  app/javascript/dashboard/i18n/locale/en/campaign.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/campaigns/AddCampaign.vue
  app/javascript/dashboard/routes/dashboard/settings/campaigns/Campaign.vue
  app/javascript/dashboard/routes/dashboard/settings/campaigns/CampaignsTable.vue
  app/javascript/dashboard/routes/dashboard/settings/campaigns/EditCampaign.vue
  app/javascript/dashboard/routes/dashboard/settings/campaigns/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/campaigns/campaigns.routes.js
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/settings.routes.js
  app/javascript/dashboard/store/modules/campaigns.js
  app/javascript/dashboard/store/modules/inboxes.js
  app/javascript/dashboard/store/modules/specs/campaigns/fixtures.js
  app/javascript/dashboard/store/modules/specs/campaigns/getters.spec.js
  app/javascript/dashboard/store/modules/specs/inboxes/fixtures.js
  app/javascript/dashboard/store/modules/specs/inboxes/getters.spec.js
  app/javascript/shared/mixins/campaignMixin.js
  app/javascript/shared/mixins/specs/campaignMixin.spec.js
  jest.config.js
Labels: PR: unreviewed

#2678 2553: fix for contact find exception
  app/builders/contact_builder.rb
  app/presenters/mail_presenter.rb
  spec/builders/contact_builder_spec.rb
  spec/fixtures/files/welcome.eml
  spec/presenters/mail_presenter_spec.rb
Labels: PR: unreviewed

#2793 chore: Handle more RestClient exceptions
  lib/exception_list.rb
Labels: PR: unreviewed

#2183 Fix Timezone and update open_at logic
  app/models/working_hour.rb
Labels: PR: unreviewed

#2779 fix: Reduce size of Docker image
  docker/Dockerfile
Labels: PR: reviewed-approved

#2798 fix: Checks window object for null before focusing
  app/javascript/dashboard/components/widgets/conversation/bubble/File.vue
Labels: PR: reviewed-approved

#2804 Fix: Fixes widget loading issue for safari on iPhone
  app/javascript/sdk/IFrameHelper.js
Labels: PR: unreviewed

#2802 chore: Ability to create contact with identifiers
  app/controllers/api/v1/accounts/contacts_controller.rb
  lib/exception_list.rb
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
  swagger/definitions/request/contact/create.yml
  swagger/definitions/request/contact/update.yml
  swagger/paths/contact/search.yml
  swagger/swagger.json
Labels: PR: unreviewed

#2796 fix: Fixes parsing issue with custom attributes
  app/javascript/dashboard/routes/dashboard/conversation/ContactCustomAttributes.vue
Labels: PR: unreviewed

#2797 fix: Fixes error when dropdown button is focused
  app/javascript/shared/components/ui/dropdown/DropdownMenu.vue
Labels: PR: unreviewed

#2803 Set phone_number through Website SDK
  app/actions/contact_identify_action.rb
  app/controllers/api/v1/widget/contacts_controller.rb
  app/javascript/widget/store/modules/contacts.js
  app/views/widget_tests/index.html.erb
  spec/actions/contact_identify_action_spec.rb
Labels: PR: reviewed-approved

#2788 fix: Use label for "Subscribe to updates" checkbox
  app/javascript/dashboard/assets/scss/super_admin/index.scss
  app/views/installation/onboarding/index.html.erb
Labels: PR: unreviewed

#2809 fix: Fixes external css interference for widget bubble
  app/javascript/sdk/sdk.js
Labels: PR: reviewed-approved

#2789 fix: Smoothens out opening animation for widget
  app/javascript/sdk/IFrameHelper.js
  app/javascript/sdk/sdk.js
  app/javascript/widget/App.vue
  app/javascript/widget/views/Unread.vue
Labels: PR: unreviewed

#2833 enhancement: Removes the focus of the first item in the dropdown when active
  app/javascript/shared/components/ui/dropdown/DropdownMenu.vue
Labels: PR: partially-approved

#2831 feat: include installation method in data to cw hub
  app.json
  deployment/setup_18.04.sh
  deployment/setup_20.04.sh
  docker-compose.production.yaml
  lib/chatwoot_hub.rb
Labels: PR: partially-approved

#2757 feat: Use relay server for self-hosted mobile push notifications
  .env.example
  app/services/notification/push_notification_service.rb
  lib/chatwoot_hub.rb
  spec/services/notification/push_notification_service_spec.rb
Labels: PR: unreviewed

#2838 feat: Add message content to mention email template
  app/drops/message_drop.rb
  app/mailers/agent_notifications/conversation_notifications_mailer.rb
  app/models/application_record.rb
  app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_mention.liquid
  spec/mailers/agent_notifications/conversation_notifications_mailer_spec.rb
Labels: PR: reviewed-approved

#2842 feat: add uptime and response time badges
  README.md
Labels: PR: reviewed-approved

#2855 fix: Fixes agent collision not working on all channels
  .circleci/config.yml
  Gemfile.lock
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: unreviewed

#2749 feat: CSAT for all channels
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/survey/api/endPoints.js
  app/javascript/survey/api/specs/endPoints.spec.js
  app/javascript/survey/api/survey.js
  app/javascript/survey/assets/scss/woot.scss
  app/javascript/survey/components/Banner.vue
  app/javascript/survey/components/Feedback.vue
  app/javascript/survey/components/Rating.vue
  app/javascript/survey/helpers/axios.js
  app/javascript/survey/i18n/locale/en.json
  app/javascript/survey/views/Response.vue
  app/listeners/agent_bot_listener.rb
  app/listeners/hook_listener.rb
  app/listeners/webhook_listener.rb
  app/mailers/conversation_reply_mailer.rb
  app/models/concerns/message_filter_helpers.rb
  app/models/conversation.rb
  app/models/message.rb
  app/services/message_templates/hook_execution_service.rb
  config/locales/en.yml
  lib/integrations/dialogflow/processor_service.rb
  package.json
  spec/services/message_templates/hook_execution_service_spec.rb
Labels: PR: unreviewed

#2841 chore: consider X-original-sender to create contact in case of group mail
  app/mailboxes/support_mailbox.rb
  app/presenters/mail_presenter.rb
  spec/fixtures/files/group_sender_support.eml
  spec/mailboxes/support_mailbox_spec.rb
Labels: PR: reviewed-approved

#2872 chore: Add `description` column in custom attribute model
  app/models/custom_attribute_definition.rb
  db/migrate/20210824152852_add_description_to_custom_attribute_definition.rb
  db/schema.rb
Labels: PR: reviewed-approved

#2871 Fix: 2825 Email conversation mention style fix
  app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_mention.liquid
Labels: PR: partially-approved

#2874 chore: support for APMs
  .env.example
  Gemfile
  Gemfile.lock
  config/initializers/datadog.rb
  config/initializers/sentry.rb
  config/newrelic.yml
Labels: PR: reviewed-approved

#2876 fix: Disable "none" option from team dropdown If team is not selected
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
Labels: PR: partially-approved

#2878 fix: chatwoot_webpack failure due to missing git
  docker/Dockerfile
Labels: PR: reviewed-approved

#2921 fix: Update param name for attachments
  swagger/paths/conversation/messages/create_attachment.yml
  swagger/swagger.json
Labels: PR: unreviewed

#2920 fix: Add missing referer & initiated_at.timestamp to events
  app/javascript/widget/api/endPoints.js
  app/javascript/widget/api/events.js
  app/javascript/widget/api/specs/endPoints.spec.js
Labels: PR: unreviewed

#2903 feat: Creates a modal that adds the ability to create a new custom attribute
  app/javascript/dashboard/api/attributes.js
  app/javascript/dashboard/i18n/locale/en/attributesMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/attributes/AddAttribute.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/Index.vue
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/attributes.js
  app/javascript/dashboard/store/modules/specs/attributes/actions.spec.js
  app/javascript/dashboard/store/modules/specs/attributes/fixtures.js
  app/javascript/dashboard/store/modules/specs/attributes/getters.spec.js
  app/javascript/dashboard/store/modules/specs/attributes/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/models/custom_attribute_definition.rb
Labels: PR: partially-approved

#2885 feat: Ability to remove inbox avatar
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/javascript/dashboard/api/inboxes.js
  app/javascript/dashboard/api/specs/inboxes.spec.js
  app/javascript/dashboard/components/widgets/forms/AvatarUploader.vue
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/store/modules/inboxes.js
  app/javascript/dashboard/store/modules/specs/inboxes/actions.spec.js
  app/policies/inbox_policy.rb
  config/routes.rb
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
Labels: PR: unreviewed

#2812 chore: Merge contact copy over information
  app/actions/contact_merge_action.rb
  app/javascript/widget/helpers/actionCable.js
  app/listeners/action_cable_listener.rb
  app/models/contact.rb
  lib/events/types.rb
  spec/actions/contact_merge_action_spec.rb
Labels: PR: unreviewed, in-QA

#2927 enhancement: Add attachment button for email conversation
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: unreviewed

#2930 fix: Handle more rest client exceptions
  lib/exception_list.rb
Labels: PR: reviewed-approved
