Repository chatwoot/chatwoot, pull requests merged in 2021-10, with the labels that each got.

#3123 fix: CSAT reports page failing to load
  app/views/api/v1/models/_agent.json.jbuilder
  spec/controllers/api/v1/accounts/csat_survey_responses_controller_spec.rb
Labels: PR: reviewed-approved

#3121 fixes: Reply box goes hidden and emoji input header section is broken.
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/shared/components/emoji/EmojiInput.vue
Labels: PR: partially-approved

#2955 Feat: Instagram Channel
  .env.example
  app/builders/messages/facebook/message_builder.rb
  app/builders/messages/instagram/message_builder.rb
  app/builders/messages/messenger/message_builder.rb
  app/controllers/api/v1/accounts/callbacks_controller.rb
  app/controllers/api/v1/instagram_callbacks_controller.rb
  app/javascript/dashboard/assets/images/channels/messenger.png
  app/javascript/dashboard/assets/images/instagram_direct.png
  app/javascript/dashboard/assets/images/messenger_direct.png
  app/javascript/dashboard/components/widgets/ChannelItem.vue
  app/javascript/dashboard/components/widgets/Thumbnail.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Facebook.vue
  app/jobs/send_reply_job.rb
  app/jobs/webhooks/instagram_events_job.rb
  app/models/channel/facebook_page.rb
  app/services/instagram/message_text.rb
  app/services/instagram/send_on_instagram_service.rb
  app/services/instagram/webhooks_base_service.rb
  config/routes.rb
  db/migrate/20210902181438_add_instagram_id_to_facebook_page.rb
  db/schema.rb
  spec/builders/messages/instagram/message_builder_spec.rb
  spec/factories/channel/insatgram_channel.rb
  spec/factories/instagram/instagram_message_create_event.rb
  spec/factories/instagram_message/incoming_messages.rb
  spec/jobs/webhooks/instagram_events_job_spec.rb
  spec/services/instagram/send_on_instagram_service_spec.rb
Labels: PR: unreviewed

#3112 chore: Provider API prototype
  .env.example
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/controllers/webhooks/whatsapp_controller.rb
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/helper/inbox.js
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/360DialogWhatsapp.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Facebook.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Twilio.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Whatsapp.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/facebook/Reauthorize.vue
  app/javascript/shared/mixins/inboxMixin.js
  app/jobs/send_reply_job.rb
  app/jobs/webhooks/whatsapp_events_job.rb
  app/models/account.rb
  app/models/channel/whatsapp.rb
  app/services/contacts/contactable_inboxes_service.rb
  app/services/whatsapp/incoming_message_service.rb
  app/services/whatsapp/send_on_whatsapp_service.rb
  config/routes.rb
  db/migrate/20210916112533_add_whatsapp_channel.rb
  db/schema.rb
  spec/controllers/webhooks/whatsapp_controller_spec.rb
  spec/factories/channel/channel_whatsapp.rb
  spec/jobs/send_reply_job_spec.rb
  spec/services/whatsapp/incoming_message_service_spec.rb
  spec/services/whatsapp/send_on_whatsapp_service_spec.rb
Labels: PR: unreviewed

#3060 fix: set default content type as text for message
  app/models/message.rb
  db/migrate/20210923132659_set_content_type_text_for_the_old_messages.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/conversations/messages_controller_spec.rb
  spec/models/message_spec.rb
Labels: PR: unreviewed

#3152 fix: Add background to inbox channel badges
  app/javascript/dashboard/assets/images/fb-badge.png
  app/javascript/dashboard/assets/images/instagram_direct.png
  app/javascript/dashboard/assets/images/messenger_direct.png
  app/javascript/dashboard/assets/images/twitter-badge.png
  app/javascript/dashboard/assets/images/twitter-chat-badge.png
  app/javascript/dashboard/assets/images/woot-logo.png
  app/javascript/dashboard/assets/images/woot-logo.svg
  app/javascript/dashboard/components/widgets/Thumbnail.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/shared/mixins/inboxMixin.js
  db/schema.rb
  public/integrations/channels/badges/instagram-dm.png
  public/integrations/channels/badges/line.png
  public/integrations/channels/badges/messenger.png
  public/integrations/channels/badges/sms.png
  public/integrations/channels/badges/telegram.png
  public/integrations/channels/badges/twitter-dm.png
  public/integrations/channels/badges/twitter-tweet.png
  public/integrations/channels/badges/whatsapp.png
Labels: PR: reviewed-approved

#3116 feat: Add Reports for teams
  app/builders/v2/report_builder.rb
  app/javascript/dashboard/api/reports.js
  app/javascript/dashboard/api/specs/reports.spec.js
  app/javascript/dashboard/helper/downloadCsvFile.js
  app/javascript/dashboard/helper/specs/downloadCsvFile.spec.js
  app/javascript/dashboard/i18n/locale/en/report.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/i18n/sidebarItems/reports.js
  app/javascript/dashboard/routes/dashboard/settings/reports/TeamReports.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/WootReports.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/reports.routes.js
  app/javascript/dashboard/store/modules/reports.js
  app/javascript/dashboard/store/modules/specs/reports/actions.spec.js
  spec/builders/v2/report_builder_spec.rb
Labels: frontend, PR: unreviewed, PR: reviewed-approved, PR: partially-approved

#3065 feat: Render conversation custom attributes
  .codeclimate.yml
  app/javascript/dashboard/api/inbox/conversation.js
  app/javascript/dashboard/api/specs/inbox/conversation.spec.js
  app/javascript/dashboard/assets/scss/widgets/_forms.scss
  app/javascript/dashboard/components/Accordion/AccordionItem.vue
  app/javascript/dashboard/components/CustomAttribute.vue
  app/javascript/dashboard/i18n/locale/en/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/mixins/attributeMixin.js
  app/javascript/dashboard/mixins/specs/attributeFixtures.js
  app/javascript/dashboard/mixins/specs/attributeMixin.spec.js
  app/javascript/dashboard/routes/dashboard/conversation/ContactConversations.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactCustomAttributes.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactDetailsItem.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/ConversationInfo.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
  app/javascript/dashboard/routes/dashboard/conversation/customAttributes/CustomAttributeDropDown.vue
  app/javascript/dashboard/routes/dashboard/conversation/customAttributes/CustomAttributeDropDownItem.vue
  app/javascript/dashboard/routes/dashboard/conversation/customAttributes/CustomAttributeSelector.vue
  app/javascript/dashboard/routes/dashboard/conversation/customAttributes/CustomAttributes.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/AddAttribute.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/CustomAttribute.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/constants.js
  app/javascript/dashboard/routes/dashboard/settings/settings.routes.js
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/shared/constants/busEvents.js
Labels: PR: partially-approved

#3305 fix: Disallow editing attribute key and type
  app/javascript/dashboard/routes/dashboard/settings/attributes/EditAttribute.vue
Labels: PR: reviewed-approved
