Repository chatwoot/chatwoot, pull requests merged in 2021-07, with the labels that each got.

#2556 chore: Change behaviour of CSAT submit actions
  app/javascript/shared/components/CustomerSatisfaction.vue
Labels: PR: partially-approved

#2551 bug: fixes typing indicator out of position in widget
  app/javascript/widget/components/AgentTypingBubble.vue
Labels: PR: partially-approved

#2531 feat: Enable/disable CSAT in web widget settings
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/views/api/v1/models/_inbox.json.jbuilder
Labels: PR: reviewed-approved

#2415 feat: Add settings for audio alert notifications
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/profile/NotificationSettings.vue
  app/javascript/dashboard/store/modules/conversations/getters.js
  app/javascript/dashboard/store/modules/specs/conversations/getters.spec.js
  app/javascript/shared/helpers/AudioNotificationHelper.js
  app/javascript/shared/helpers/specs/AudioNotificationHelper.spec.js
  app/javascript/widget/store/modules/conversation/actions.js
  app/javascript/widget/store/modules/conversation/helpers.js
  app/javascript/widget/store/modules/specs/conversation/actions.spec.js
Labels: PR: unreviewed

#2562 chore: Expose contact custom attributes in events
  app/models/contact.rb
Labels: PR: reviewed-approved

#2412 feat: Creates component to merge contacts
  .codeclimate.yml
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/modules/contact/components/ContactDropdownItem.vue
  app/javascript/dashboard/modules/contact/components/MergeContact.vue
  app/javascript/dashboard/modules/contact/components/MergeContactSummary.vue
  app/javascript/dashboard/modules/contact/stories/ContactIntro.stories.js
  app/javascript/dashboard/modules/contact/stories/MergeContact.stories.js
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
Labels: PR: unreviewed

#2576 chore: Reduce steps to spin up Codespaces
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/scripts/setup.sh
Labels: PR: reviewed-approved

#2579 feat: Support messages along with the actions in Dialogflow response
  lib/integrations/dialogflow/processor_service.rb
  spec/lib/integrations/dialogflow/processor_service_spec.rb
Labels: PR: reviewed-approved

#2569 chore: Add loader for email and csat submit buttons
  app/javascript/shared/components/CustomerSatisfaction.vue
  app/javascript/widget/components/AgentMessageBubble.vue
  app/javascript/widget/components/template/EmailInput.vue
Labels: PR: unreviewed

#2591 fix: Aligns delete message menu on twitter bubble correctly
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/modules/conversations/components/MessageContextMenu.vue
Labels: PR: reviewed-approved

#2600 chore: Disable delete option for deleted messages
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: partially-approved

#2581 chore: Update availability status everywhere if the user changes the status from the account menu
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/mixins/agentMixin.js
  app/javascript/dashboard/mixins/specs/agentFixtures.js
  app/javascript/dashboard/mixins/specs/agentMixin.spec.js
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
Labels: PR: partially-approved

#2597 feat: Creates custom date range picker component
  app/javascript/dashboard/components/ui/DateRangePicker.vue
  app/javascript/dashboard/components/ui/stories/DateRangePicker.stories.js
  package.json
  yarn.lock
Labels: PR: partially-approved

#2604 fix: Unescape Slack incoming messages
  lib/integrations/slack/incoming_message_builder.rb
  spec/lib/integrations/slack/incoming_message_builder_spec.rb
  spec/support/slack_stubs.rb
Labels: PR: reviewed-approved

#2592 chore: Delete related notifications if a conversation is deleted
  app/models/conversation.rb
  db/migrate/20210708140842_remove_notifications_without_primary_actor.rb
  db/schema.rb
  spec/models/conversation_spec.rb
Labels: PR: unreviewed

#2566 Twilio to individual channels
  app/javascript/dashboard/assets/images/channels/sms.png
  app/javascript/dashboard/components/widgets/ChannelItem.vue
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channel-factory.js
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Sms.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Twilio.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Whatsapp.vue
Labels: PR: partially-approved

#2598 feat: Changes primary nav-bar to new design
  app/javascript/dashboard/assets/scss/_foundation-custom.scss
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/components/layout/AvailabilityStatus.vue
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/sidebarComponents/AgentDetails.vue
  app/javascript/dashboard/components/layout/sidebarComponents/NotificationBell.vue
  app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue
  app/javascript/dashboard/modules/sidebar/components/Logo.vue
  app/javascript/dashboard/modules/sidebar/components/Primary.vue
  app/javascript/dashboard/modules/sidebar/components/PrimaryNavItem.vue
  app/javascript/dashboard/modules/sidebar/components/Secondary.vue
  app/javascript/shared/assets/stylesheets/colors.scss
  package.json
  public/brand-assets/logo.svg
  yarn.lock
Labels: PR: unreviewed

#2612 feat: updates design for secondary navbar
  app/javascript/dashboard/assets/scss/_variables.scss
  app/javascript/dashboard/assets/scss/views/settings/inbox.scss
  app/javascript/dashboard/assets/scss/widgets/_sidemenu.scss
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/SidebarItem.vue
  app/javascript/dashboard/components/layout/sidebarComponents/NotificationBell.vue
  app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/i18n/default-sidebar.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/modules/sidebar/components/Primary.vue
  app/javascript/dashboard/modules/sidebar/components/SecondaryNavItem.vue
  app/javascript/shared/assets/stylesheets/colors.scss
Labels: PR: unreviewed

#2549 feat: Conversation transcript in widget
  app/javascript/shared/components/Button.vue
  app/javascript/shared/constants/busEvents.js
  app/javascript/widget/api/conversation.js
  app/javascript/widget/assets/scss/_variables.scss
  app/javascript/widget/components/Banner.vue
  app/javascript/widget/components/ChatAttachment.vue
  app/javascript/widget/components/ChatFooter.vue
  app/javascript/widget/i18n/locale/en.json
  app/javascript/widget/store/modules/message.js
  app/javascript/widget/store/modules/specs/message/actions.spec.js
  app/javascript/widget/store/modules/specs/message/getters.spec.js
  app/javascript/widget/store/modules/specs/message/mutations.spec.js
  app/javascript/widget/views/Home.vue
Labels: PR: reviewed-approved

#2613 bug: Fixes alignment issue with deleted messages
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: unreviewed

#2602 feat: Adds custom date range component for reports
  app/javascript/dashboard/components/ui/DateRangePicker.vue
  app/javascript/dashboard/i18n/locale/en/report.json
  app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
Labels: PR: partially-approved

#2618 fix: Update styles to fix the image resolution on smaller devices
  app/javascript/dashboard/assets/scss/views/settings/channel.scss
  app/javascript/dashboard/components/widgets/ChannelItem.vue
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/InboxChannels.vue
Labels: PR: partially-approved

#2608 feat: Add CSAT reports
  app/controllers/api/v1/accounts/csat_survey_responses_controller.rb
  app/javascript/dashboard/api/csatReports.js
  app/javascript/dashboard/api/specs/csatReports.spec.js
  app/javascript/dashboard/assets/scss/_foundation-custom.scss
  app/javascript/dashboard/assets/scss/widgets/_report.scss
  app/javascript/dashboard/components/index.js
  app/javascript/dashboard/components/widgets/ReportStatsCard.vue
  app/javascript/dashboard/components/widgets/UserAvatarWithName.vue
  app/javascript/dashboard/components/widgets/chart/HorizontalBarChart.js
  app/javascript/dashboard/i18n/default-sidebar.js
  app/javascript/dashboard/i18n/locale/en/report.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/CampaignsTable.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/CsatResponses.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatMetricCard.stories.js
  app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatMetricCard.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatMetrics.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatTable.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/reports.routes.js
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/csat.js
  app/javascript/dashboard/store/modules/specs/csat/actions.spec.js
  app/javascript/dashboard/store/modules/specs/csat/getters.spec.js
  app/javascript/dashboard/store/modules/specs/csat/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/shared/constants/messages.js
  app/models/message.rb
  app/policies/csat_survey_response_policy.rb
  app/views/api/v1/accounts/csat_survey_responses/metrics.json.jbuilder
  app/views/api/v1/models/_csat_survey_response.json.jbuilder
  config/routes.rb
  package.json
  spec/controllers/api/v1/accounts/csat_survey_responses_controller_spec.rb
  yarn.lock
Labels: PR: partially-approved

#2589 chore: one off SMS campaign APIs
  .devcontainer/devcontainer.json
  app/controllers/api/v1/accounts/campaigns_controller.rb
  app/jobs/campaigns/trigger_oneoff_campaign_job.rb
  app/jobs/trigger_scheduled_items_job.rb
  app/models/campaign.rb
  app/services/twilio/oneoff_sms_campaign_service.rb
  app/views/api/v1/models/_campaign.json.jbuilder
  config/schedule.yml
  db/migrate/20210707142801_add_campaign_type_to_campaigns.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/campaigns_controller_spec.rb
  spec/jobs/campaigns/trigger_oneoff_campaign_job_spec.rb
  spec/jobs/trigger_scheduled_items_job_spec.rb
  spec/models/campaign_spec.rb
  spec/services/twilio/oneoff_sms_campaign_service_spec.rb
Labels: PR: partially-approved

#2606 chore: Suppress the unnecessary CSRF warning
  .devcontainer/scripts/setup.sh
  .env.example
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/controllers/api/v1/accounts/custom_filters_controller.rb
  app/controllers/api/v1/accounts/notifications_controller.rb
  app/controllers/api/v1/accounts_controller.rb
  app/controllers/application_controller.rb
  app/controllers/platform_controller.rb
  app/controllers/public_controller.rb
  config/webpacker.yml
  spec/controllers/public/api/v1/inbox/contacts_controller_spec.rb
  spec/controllers/public/api/v1/inbox/conversations_controller_spec.rb
  spec/controllers/public/api/v1/inbox/messages_controller_spec.rb
Labels: PR: unreviewed, QA Review Done

#2622 feat: Add date-range filter on CSAT Reports
  app/controllers/api/v1/accounts/csat_survey_responses_controller.rb
  app/javascript/dashboard/api/csatReports.js
  app/javascript/dashboard/api/specs/csatReports.spec.js
  app/javascript/dashboard/routes/dashboard/settings/reports/CsatResponses.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatTable.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/DateRangeSelector.vue
  app/javascript/dashboard/store/modules/csat.js
  app/javascript/widget/components/AgentMessage.vue
  app/views/api/v1/models/_csat_survey_response.json.jbuilder
Labels: PR: partially-approved

#2630 chore: Add assigned option to conversation finder API
  Gemfile
  Gemfile.lock
  app/finders/conversation_finder.rb
  config/initializers/sidekiq.rb
  config/schedule.yml
  lib/redis/config.rb
  spec/finders/conversation_finder_spec.rb
  spec/lib/redis/config_spec.rb
  swagger/paths/conversation/create.yml
  swagger/paths/conversation/index.yml
  swagger/paths/index.yml
  swagger/swagger.json
Labels: PR: partially-approved

#2632 fix: Use Dompurify to strip style characters
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/helpers/EmailContentParser.js
  app/javascript/dashboard/components/widgets/conversation/helpers/specs/EmailContentParser.spec.js
  app/javascript/shared/mixins/messageFormatterMixin.js
  app/javascript/shared/mixins/specs/messageFormatterMixin.spec.js
Labels: PR: partially-approved

#2614 fix: Hide deleted messages on widget side
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/widget/components/AgentMessage.vue
  app/javascript/widget/components/UserMessage.vue
  app/javascript/widget/helpers/actionCable.js
  app/javascript/widget/mixins/messageMixin.js
  app/javascript/widget/mixins/specs/messageFixture.js
  app/javascript/widget/mixins/specs/messageMixin.spec.js
  app/javascript/widget/store/modules/conversation/actions.js
  app/javascript/widget/store/modules/conversation/helpers.js
  app/javascript/widget/store/modules/conversation/mutations.js
  app/javascript/widget/store/modules/specs/conversation/actions.spec.js
  app/javascript/widget/store/modules/specs/conversation/helpers.spec.js
  app/javascript/widget/store/modules/specs/conversation/mutations.spec.js
Labels: PR: unreviewed

#2624 Removing duplicate callback to create auth token
  app/models/user.rb
  db/migrate/20210714110714_remove_duplicate_access_tokens_for_existing_users.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: PR: partially-approved, QA Review Done

#2637 fix: Disable sender tooltip and copy button in deleted messages
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: reviewed-approved

#2638 fix: Improve mail content parsing
  app/mailboxes/support_mailbox.rb
  app/presenters/mail_presenter.rb
Labels: PR: reviewed-approved

#2631 chore: Add Telemetry
  app/controllers/installation/onboarding_controller.rb
  lib/chatwoot_hub.rb
  spec/lib/chatwoot_hub_spec.rb
Labels: PR: unreviewed

#2644 fix: Fix HTML only email rendering
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: reviewed-approved

#2662 fix: Update attribute name to conversationsCount
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
Labels: PR: partially-approved

#2665 chore: Add assigned_count to conversation APIs
  app/finders/conversation_finder.rb
  app/models/conversation.rb
  app/views/api/v1/accounts/conversations/index.json.jbuilder
  app/views/api/v1/accounts/conversations/meta.json.jbuilder
  config/schedule.yml
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
  spec/finders/conversation_finder_spec.rb
Labels: PR: unreviewed

#2645 chore: Expose widget config via an API
  app/controllers/api/v1/widget/base_controller.rb
  app/controllers/api/v1/widget/campaigns_controller.rb
  app/controllers/api/v1/widget/configs_controller.rb
  app/controllers/api/v1/widget/inbox_members_controller.rb
  app/controllers/widgets_controller.rb
  app/views/api/v1/widget/configs/create.json.jbuilder
  config/routes.rb
  spec/controllers/api/v1/widget/configs_controller_spec.rb
Labels: PR: unreviewed

#2677 chore: Change the `bot` status to `pending`
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/javascript/dashboard/components/buttons/ResolveAction.vue
  app/javascript/dashboard/constants.js
  app/javascript/dashboard/i18n/locale/en/chatlist.json
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/widget/store/modules/specs/conversationAttributes/actions.spec.js
  app/javascript/widget/store/modules/specs/conversationAttributes/getters.spec.js
  app/javascript/widget/store/modules/specs/conversationAttributes/mutations.spec.js
  app/listeners/notification_listener.rb
  app/models/conversation.rb
  config/locales/en.yml
  lib/integrations/dialogflow/processor_service.rb
  spec/controllers/api/base_controller_spec.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
  spec/lib/integrations/dialogflow/processor_service_spec.rb
  spec/models/concerns/round_robin_handler_spec.rb
  spec/models/conversation_spec.rb
  swagger/definitions/resource/conversation.yml
  swagger/paths/conversation/create.yml
  swagger/paths/conversation/index.yml
  swagger/paths/conversation/toggle_status.yml
  swagger/swagger.json
Labels: PR: unreviewed

#2687 fix: Disable "none" option from agent dropdown If agent is not selected
  app/javascript/dashboard/mixins/agentMixin.js
  app/javascript/dashboard/mixins/specs/agentMixin.spec.js
Labels: PR: reviewed-approved

#2523 Live chat widget preview #2441
  app/javascript/dashboard/modules/widget-preview/components/Widget.vue
  app/javascript/dashboard/modules/widget-preview/components/WidgetBody.vue
  app/javascript/dashboard/modules/widget-preview/components/WidgetFooter.vue
  app/javascript/dashboard/modules/widget-preview/components/WidgetHead.vue
  app/javascript/dashboard/modules/widget-preview/stories/Widget.stories.js
Labels: PR: unreviewed

#2688 chore: switch from addgroup to adduser
  deployment/setup_20.04.sh
Labels: PR: unreviewed

#2682 feat: Ability to snooze conversations
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/javascript/dashboard/api/inbox/conversation.js
  app/javascript/dashboard/api/specs/inbox/conversation.spec.js
  app/javascript/dashboard/components/buttons/ResolveAction.vue
  app/javascript/dashboard/constants.js
  app/javascript/dashboard/i18n/locale/en/chatlist.json
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/shared/components/ui/dropdown/DropdownSubMenu.vue
  app/jobs/conversations/reopen_snoozed_conversations_job.rb
  app/jobs/trigger_scheduled_items_job.rb
  app/models/conversation.rb
  app/models/message.rb
  config/locales/en.yml
  db/migrate/20210721182458_add_snoozed_until_to_conversations.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
  spec/jobs/conversations/reopen_snoozed_conversations_job_spec.rb
  spec/jobs/trigger_scheduled_items_job_spec.rb
  spec/models/conversation_spec.rb
  spec/models/message_spec.rb
Labels: PR: partially-approved

#2607 Cypress testcase - Create label
  app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue
  app/javascript/dashboard/routes/dashboard/settings/labels/AddLabel.vue
  spec/cypress.json
  spec/cypress/integration/happy_paths/admin_dashboard_authentication.js
  spec/cypress/integration/happy_paths/admin_dashboard_create_label.js
Labels: PR: unreviewed

#2689 feat: Add APIs for custom attribute definitions
  app/controllers/api/v1/accounts/custom_attribute_definitions_controller.rb
  app/models/account.rb
  app/models/custom_attribute_definition.rb
  app/views/api/v1/accounts/custom_attribute_definitions/create.json.jbuilder
  app/views/api/v1/accounts/custom_attribute_definitions/index.json.jbuilder
  app/views/api/v1/accounts/custom_attribute_definitions/show.json.jbuilder
  app/views/api/v1/accounts/custom_attribute_definitions/update.json.jbuilder
  app/views/api/v1/models/_custom_attribute_definition.json.jbuilder
  config/routes.rb
  db/migrate/20210722095814_add_custom_attribute_definition.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/custom_attribute_definitions_controller_spec.rb
  spec/factories/custom_attribute_definitions.rb
Labels: PR: reviewed-approved

#2696 chore: Improve search, list performance of contact/conversation APIs
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/finders/conversation_finder.rb
  app/javascript/dashboard/api/contacts.js
  app/javascript/dashboard/api/specs/contacts.spec.js
  app/models/contact.rb
  app/models/conversation.rb
  app/views/api/v1/accounts/contacts/index.json.jbuilder
  app/views/api/v1/accounts/contacts/search.json.jbuilder
  app/views/api/v1/models/_team.json.jbuilder
  db/migrate/20210723094412_add_index_to_conversations.rb
  db/migrate/20210723095657_add_index_to_contacts.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
Labels: PR: unreviewed

#2705 feat: Make "Search Results" in PopOverSearch translateable
  app/javascript/dashboard/i18n/locale/de/conversation.json
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
Labels: PR: reviewed-approved

#2702 Fix: type error trim of undefined#2595
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: reviewed-approved

#2706 chore: Block & throttle abusive requests
  .env.example
  .rubocop.yml
  Gemfile
  Gemfile.lock
  config/initializers/01_redis.rb
  config/initializers/rack_attack.rb
Labels: PR: reviewed-approved

#2708 feat: show mail meta data for conversations
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/MailHead.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
Labels: PR: partially-approved

#2670 feat: CSAT response public APIs
  app/controllers/public/api/v1/csat_survey_controller.rb
  app/views/public/api/v1/csat_survey/show.json.jbuilder
  app/views/public/api/v1/csat_survey/update.json.jbuilder
  app/views/public/api/v1/models/_csat_survey.json.jbuilder
  config/routes.rb
  spec/controllers/public/api/v1/csat_survey_controller.spec.rb
Labels: PR: unreviewed

#2711 fix: external db with non-standard port
  app/models/account.rb
  app/models/channel/web_widget.rb
  app/models/concerns/featurable.rb
  app/models/notification_setting.rb
  config/database.yml
  docker/entrypoints/helpers/pg_database_url.sh
Labels: PR: partially-approved

#2723 enhancemnet: Show links for custom attributes
  app/javascript/dashboard/routes/dashboard/conversation/ContactCustomAttributes.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
Labels: PR: partially-approved

#2720 fix: Appending markdown as HTML into editor
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
Labels: PR: unreviewed, frontend

#2516 feat: Update agent and team multi-select with new multi-select dropdown
  app/javascript/dashboard/i18n/locale/en/agentMgmt.json
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/shared/components/ui/MultiselectDropdown.stories.js
  app/javascript/shared/components/ui/MultiselectDropdown.vue
  app/javascript/shared/components/ui/MultiselectDropdownItems.vue
Labels: PR: partially-approved

#2726 fix: Rename `identity_hash` to `identifier_hash`
  app/javascript/dashboard/i18n/locale/ar/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/ca/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/cs/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/da/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/de/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/el/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/es/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/fi/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/fr/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/he/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/hi/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/hu/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/id/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/it/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/ja/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/ko/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/ml/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/ne/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/nl/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/no/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/pl/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/pt/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/pt_BR/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/ro/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/ru/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/sk/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/sv/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/ta/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/th/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/tr/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/uk/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/vi/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/zh_CN/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/zh_TW/inboxMgmt.json
Labels: PR: partially-approved

#2721 chore: Limit objects returned by conversation API
  app/finders/conversation_finder.rb
  spec/actions/contact_merge_action_spec.rb
  spec/controllers/api/v1/accounts_controller_spec.rb
  spec/finders/conversation_finder_spec.rb
  spec/models/agent_bot_spec.rb
  spec/models/channel/facebook_page_spec.rb
  spec/models/concerns/access_tokenable_shared.rb
  spec/models/concerns/assignment_handler_shared.rb
  spec/models/concerns/out_of_offisable_shared.rb
  spec/models/concerns/reauthorizable_shared.rb
  spec/models/concerns/round_robin_handler_shared.rb
  spec/models/conversation_spec.rb
  spec/models/inbox_spec.rb
  spec/models/platform_app_spec.rb
  spec/models/user_spec.rb
Labels: PR: unreviewed
