Repository chatwoot/chatwoot, pull requests merged in 2021-05, with the labels that each got.

#2187 Feat: Creates add note component for CRM
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/contacts/components/AddNote.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactNote.vue
  stories/Module/AddNote.stories.js
  stories/Module/ContactNote.stories.js
  stories/Module/Note.stories.js
Labels: PR: reviewed-approved

#2199 fix: Change storybook relative path
  .storybook/main.js
  app/javascript/dashboard/routes/dashboard/contacts/components/AddNote.stories.js
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactNote.stories.js
Labels: PR: reviewed-approved

#2192 feat: Campaign conversation builder
  app/builders/campaigns/campaign_conversation_builder.rb
  app/controllers/api/v1/widget/campaigns_controller.rb
  app/controllers/api/v1/widget/events_controller.rb
  app/dispatchers/async_dispatcher.rb
  app/listeners/campaign_listener.rb
  app/views/api/v1/widget/campaigns/index.json.jbuilder
  config/routes.rb
  lib/events/types.rb
  spec/builders/campaigns/campaign_conversation_builder_spec.rb
  spec/controllers/api/v1/widget/campaigns_controller_spec.rb
  spec/controllers/api/v1/widget/events_controller_spec.rb
  spec/controllers/api/v1/widget/inbox_members_controller_spec.rb
  spec/listeners/campaign_listener_spec.rb
Labels: PR: unreviewed

#2203 fix: Use full width for branding
  app/javascript/widget/components/Branding.vue
Labels: PR: reviewed-approved

#2177 feat: Add campaign
  app/javascript/dashboard/api/campaigns.js
  app/javascript/dashboard/i18n/locale/en/campaign.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/AddCampaign.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/Campaign.vue
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/campaigns.js
  app/javascript/dashboard/store/modules/specs/campaigns/actions.spec.js
  app/javascript/dashboard/store/modules/specs/campaigns/fixtures.js
  app/javascript/dashboard/store/modules/specs/campaigns/getters.spec.js
  app/javascript/dashboard/store/modules/specs/campaigns/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  package.json
Labels: PR: reviewed-approved

#2208 fix: Truncates overlapping name in contact table
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
Labels: PR: partially-approved

#2209 fix: Add validation on the message length for Twilio Whatsapp
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/shared/helpers/MessageTypeHelper.js
Labels: PR: reviewed-approved

#2216 fix: undefined WootButton in contact table
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
Labels: PR: partially-approved

#2218 Chore: Removes unused impports in ContactIntro
  app/javascript/dashboard/modules/contact/components/ContactIntro.vue
  app/javascript/dashboard/modules/contact/stories/ContactIntro.stories.js
Labels: PR: unreviewed

#2217 feat: Add a component to display contact attributes in CRM
  .codeclimate.yml
  app/javascript/dashboard/modules/contact/components/ContactAttribute.vue
  app/javascript/dashboard/modules/contact/stories/ContactAttribute.stories.js
  app/javascript/shared/components/EmojiOrIcon.vue
Labels: PR: partially-approved

#2195 Feat: Creates note list component for CRM
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/contacts/components/AddNote.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactNote.stories.js
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactNote.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/NoteList.stories.js
  app/javascript/dashboard/routes/dashboard/contacts/components/NoteList.vue
Labels: PR: reviewed-approved

#2222 Enhancement: Adds story for label component
  app/javascript/dashboard/assets/scss/_foundation-custom.scss
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/components/widgets/Label.stories.js
  app/javascript/dashboard/components/widgets/Label.vue
Labels: PR: reviewed-approved

#2221 chore: Add API documentation for teams
  Gemfile
  Gemfile.lock
  swagger/definitions/index.yml
  swagger/definitions/request/team/create_update_payload.yml
  swagger/definitions/resource/team.yml
  swagger/index.html
  swagger/index.yml
  swagger/parameters/account_id.yml
  swagger/parameters/index.yml
  swagger/parameters/team_id.yml
  swagger/paths/conversation/assignments.yml
  swagger/paths/index.yml
  swagger/paths/teams/create.yml
  swagger/paths/teams/delete.yml
  swagger/paths/teams/index.yml
  swagger/paths/teams/show.yml
  swagger/paths/teams/update.yml
  swagger/swagger.json
Labels: PR: unreviewed

#2155 feat: Dialogflow Integration V1
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/jobs/hook_job.rb
  app/listeners/hook_listener.rb
  app/models/conversation.rb
  app/models/integrations/app.rb
  app/models/integrations/hook.rb
  config/integration/apps.yml
  config/locales/en.yml
  db/migrate/20210425093724_convert_integration_hook_settings_field.rb
  db/schema.rb
  lib/integrations/dialogflow/processor_service.rb
  public/dashboard/images/integrations/dialogflow.svg
  spec/factories/integrations/hooks.rb
  spec/jobs/hook_job_spec.rb
  spec/lib/integrations/dialogflow/processor_service_spec.rb
  spec/listeners/hook_listener_spec.rb
  spec/models/conversation_spec.rb
Labels: PR: unreviewed

#2226 chore: Add color variants to label component
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/components/index.js
  app/javascript/dashboard/components/ui/Label.vue
  app/javascript/dashboard/components/ui/stories/Label.stories.js
  app/javascript/dashboard/components/widgets/Label.vue
  app/javascript/dashboard/routes/dashboard/conversation/labels/AddLabelToConversation.vue
Labels: PR: reviewed-approved

#2212 feat: Campaign table
  app/javascript/dashboard/i18n/locale/en/campaign.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/AddCampaign.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/Campaign.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/CampaignSender.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/CampaignsTable.vue
  app/javascript/dashboard/store/modules/specs/campaigns/actions.spec.js
Labels: PR: reviewed-approved

#2223 feat: Creates add button component for label
  app/javascript/shared/components/ui/dropdown/AddLabel.stories.js
  app/javascript/shared/components/ui/dropdown/AddLabel.vue
Labels: PR: reviewed-approved

#2220 feat: Creates label dropdown component
  app/javascript/dashboard/components/index.js
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/shared/components/ui/dropdown/DropdownItem.vue
  app/javascript/shared/components/ui/label/LabelDropdown.stories.js
  app/javascript/shared/components/ui/label/LabelDropdown.vue
  app/javascript/shared/components/ui/label/LabelDropdownItem.stories.js
  app/javascript/shared/components/ui/label/LabelDropdownItem.vue
Labels: PR: reviewed-approved

#2232 fix: Rename migration for Campaigns
  db/migrate/20210428135041_add_campaigns.rb
Labels: PR: reviewed-approved

#2233 fix: Upgrade rails to fix CVE-2021-22904
  Gemfile.lock
  app/views/super_admin/application/index.html.erb
  app/views/super_admin/users/index.html.erb
Labels: PR: unreviewed

#1978 Fix: text overlaps in contact name
  app/javascript/dashboard/assets/scss/widgets/_conv-header.scss
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
Labels: PR: unreviewed

#2141 fix: plus icon in sidebar items should route to create page
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/SidebarItem.vue
  app/javascript/dashboard/routes/dashboard/settings/labels/AddLabel.vue
Labels: PR: reviewed-approved

#2230 feat: Edit campaigns
  app/javascript/dashboard/i18n/locale/en/campaign.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/Campaign.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/CampaignsTable.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/EditCampaign.vue
  app/javascript/dashboard/store/modules/campaigns.js
  app/javascript/dashboard/store/modules/specs/campaigns/actions.spec.js
  app/javascript/dashboard/store/modules/specs/campaigns/fixtures.js
  app/javascript/dashboard/store/modules/specs/campaigns/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
Labels: PR: reviewed-approved

#2227 feat: Add campaigns in web widget
  app/builders/campaigns/campaign_conversation_builder.rb
  app/javascript/widget/App.vue
  app/javascript/widget/api/campaign.js
  app/javascript/widget/api/endPoints.js
  app/javascript/widget/helpers/campaignTimer.js
  app/javascript/widget/store/index.js
  app/javascript/widget/store/modules/campaign.js
  app/javascript/widget/store/modules/specs/campaign/actions.spec.js
  app/javascript/widget/store/modules/specs/campaign/data.js
  app/javascript/widget/store/modules/specs/campaign/getters.spec.js
  app/javascript/widget/store/modules/specs/campaign/mutations.spec.js
  app/listeners/campaign_listener.rb
  app/services/message_templates/hook_execution_service.rb
  spec/listeners/campaign_listener_spec.rb
  spec/services/message_templates/hook_execution_service_spec.rb
Labels: PR: reviewed-approved, QA Review Done

#2249 chore: Add Message API, cleanup conversation_id param
  swagger/parameters/account_id.yml
  swagger/parameters/conversation_id.yml
  swagger/parameters/index.yml
  swagger/parameters/message_id.yml
  swagger/paths/conversation/assignments.yml
  swagger/paths/conversation/crud.yml
  swagger/paths/conversation/index_or_create.yml
  swagger/paths/conversation/labels.yml
  swagger/paths/conversation/labels/create.yml
  swagger/paths/conversation/labels/index.yml
  swagger/paths/conversation/messages/create.yml
  swagger/paths/conversation/messages/delete.yml
  swagger/paths/conversation/messages/index.yml
  swagger/paths/conversation/messages/index_create.yml
  swagger/paths/conversation/show.yml
  swagger/paths/conversation/toggle_status.yml
  swagger/paths/index.yml
  swagger/paths/teams/delete.yml
  swagger/swagger.json
Labels: PR: reviewed-approved

#2248 chore: Add documentation for APIs
  swagger/definitions/index.yml
  swagger/definitions/resource/contactable_inboxes.yml
  swagger/parameters/index.yml
  swagger/parameters/source_id.yml
  swagger/paths/contact_inboxes/create.yml
  swagger/paths/contactable_inboxes/get.yml
  swagger/paths/conversation/index_or_create.yml
  swagger/paths/conversation/messages/create_attachment.yml
  swagger/paths/index.yml
  swagger/swagger.json
Labels: PR: reviewed-approved

#2234 chore: Refactor contact page button with button component
  app/javascript/dashboard/components/widgets/TableFooter.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue
Labels: PR: reviewed-approved

#1870 feat: Sort Contacts via name, email, phone_number, last_activity
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/javascript/dashboard/api/contacts.js
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
  app/javascript/dashboard/store/modules/contacts/actions.js
  app/javascript/dashboard/store/modules/contacts/getters.js
  app/javascript/dashboard/store/modules/contacts/index.js
  app/javascript/dashboard/store/modules/contacts/mutations.js
  app/javascript/dashboard/store/modules/specs/contacts/getters.spec.js
  app/javascript/dashboard/store/modules/specs/contacts/mutations.spec.js
  app/models/contact.rb
  app/models/message.rb
  app/views/api/v1/models/_contact.json.jbuilder
  db/migrate/20210306170117_add_last_activity_at_to_contacts.rb
  db/schema.rb
  spec/models/message_spec.rb
  swagger/parameters/contact_sort.yml
  swagger/parameters/index.yml
  swagger/parameters/page.yml
  swagger/paths/contact/list_create.yml
  swagger/paths/contact/search.yml
  swagger/swagger.json
Labels: PR: reviewed-approved

#2262 chore: Fixes warnings in jest
  app/javascript/dashboard/components/layout/specs/AvailabilityStatus.spec.js
  app/javascript/dashboard/components/specs/SidemenuIcon.spec.js
  app/javascript/shared/components/specs/DateSeparator.spec.js
  app/javascript/shared/components/specs/Spinner.spec.js
Labels: PR: reviewed-approved

#2261 feat: Remove restrictions on API channel webhook_url
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Api.vue
  app/listeners/webhook_listener.rb
  app/models/channel/api.rb
  db/migrate/20210513083044_remove_not_null_from_webhook_url_channel_api.rb
  db/schema.rb
  spec/listeners/webhook_listener_spec.rb
Labels: PR: reviewed-approved

#2231 chore: Refactor sidebar button with button component
  app/javascript/dashboard/components/layout/AvailabilityStatus.vue
Labels: PR: unreviewed

#2252 feat: Creates component show all contact info
  app/javascript/dashboard/modules/contact/components/ContactIntro.vue
  app/javascript/dashboard/modules/contact/components/ContactPanel.vue
  app/javascript/dashboard/modules/contact/components/ManageLayout.vue
  app/javascript/dashboard/routes/dashboard/contacts/pages/ContactManageView.vue
Labels: PR: unreviewed

#2268 fix: Upgrade chart.js to 2.9.4, fix grid-line option
  app/javascript/dashboard/components/widgets/chart/BarChart.js
  app/javascript/dashboard/i18n/locale/en/report.json
  app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#2250 feat: APIs for Integration Hooks
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/accounts/integrations/hooks_controller.rb
  app/models/integrations/hook.rb
  app/policies/hook_policy.rb
  app/views/api/v1/accounts/integrations/apps/index.json.jbuilder
  app/views/api/v1/accounts/integrations/apps/show.json.jbuilder
  app/views/api/v1/accounts/integrations/hooks/create.json.jbuilder
  app/views/api/v1/accounts/integrations/hooks/update.json.jbuilder
  app/views/api/v1/models/_app.json.jbuilder
  app/views/api/v1/models/_hook.json.jbuilder
  config/integration/apps.yml
  config/routes.rb
  lib/integrations/slack/hook_builder.rb
  spec/controllers/api/v1/accounts/integrations/hooks_controller_spec.rb
  spec/factories/integrations/hooks.rb
  spec/jobs/hook_job_spec.rb
  spec/lib/integrations/dialogflow/processor_service_spec.rb
  spec/models/conversation_spec.rb
  spec/models/integrations/hook_spec.rb
  spec/requests/api/v1/accounts/integrations/slack_request_spec.rb
Labels: PR: unreviewed

#2025 fix: Use reply content if available
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: reviewed-approved

#2243 feat: new label dropdown using dropdown component
  app/javascript/dashboard/components/ui/Label.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/labels/LabelBox.vue
  app/javascript/shared/components/ui/dropdown/AddLabel.vue
Labels: PR: unreviewed

#2278 chore: Add inbox id in get campaigns API
  app/javascript/dashboard/api/inboxes.js
  app/javascript/dashboard/api/specs/campaign.spec.js
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/Campaign.vue
  app/javascript/dashboard/store/modules/campaigns.js
  app/javascript/dashboard/store/modules/specs/campaigns/actions.spec.js
Labels: PR: reviewed-approved

#2277 chore: Add sender details in unread message
  app/javascript/widget/components/UnreadMessage.vue
  app/javascript/widget/i18n/locale/en.json
  app/javascript/widget/views/Unread.vue
Labels: PR: reviewed-approved

#2283 fix: Resolve bot name if sender value is empty
  app/javascript/widget/components/UnreadMessage.vue
  app/javascript/widget/i18n/locale/en.json
Labels: PR: unreviewed

#2290 fix: Resolve infinite loop with campaign API call
  app/javascript/widget/App.vue
  app/javascript/widget/helpers/campaignHelper.js
  app/javascript/widget/helpers/campaignTimer.js
  app/javascript/widget/helpers/specs/campaignHelper.spec.js
  app/javascript/widget/store/modules/campaign.js
  app/javascript/widget/store/modules/specs/campaign/actions.spec.js
  app/javascript/widget/store/modules/specs/campaign/getters.spec.js
  app/javascript/widget/store/modules/specs/campaign/mutations.spec.js
Labels: PR: reviewed-approved

#2259 feat: Refactor button styles
  app/javascript/dashboard/assets/scss/_foundation-custom.scss
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/assets/scss/_woot.scss
  app/javascript/dashboard/assets/scss/app.scss
  app/javascript/dashboard/assets/scss/storybook.scss
  app/javascript/dashboard/assets/scss/widgets/_buttons.scss
  app/javascript/dashboard/assets/scss/widgets/_conv-header.scss
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/layout/AvailabilityStatus.vue
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue
  app/javascript/dashboard/components/ui/WootButton.vue
  app/javascript/dashboard/components/widgets/TableFooter.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfoRow.vue
  app/javascript/dashboard/routes/dashboard/settings/SettingsHeader.vue
  app/javascript/dashboard/routes/dashboard/settings/agents/EditAgent.vue
  app/javascript/dashboard/routes/dashboard/settings/agents/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/canned/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/CampaignsTable.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/Webhook.vue
  app/javascript/dashboard/routes/dashboard/settings/labels/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/teams/Index.vue
  app/javascript/shared/components/ui/dropdown/DropdownItem.vue
  stories/Sections/Button.stories.mdx
Labels: PR: partially-approved

#2300 docs: Adds documentation for Integration APIs
  app/views/api/v1/models/_app.json.jbuilder
  app/views/api/v1/models/_hook.json.jbuilder
  spec/controllers/api/v1/accounts/integrations/hooks_controller_spec.rb
  swagger/definitions/index.yml
  swagger/definitions/request/integrations/hook_create_payload.yml
  swagger/definitions/request/integrations/hook_update_payload.yml
  swagger/definitions/resource/integrations/app.yml
  swagger/definitions/resource/integrations/hook.yml
  swagger/definitions/resource/team.yml
  swagger/parameters/hook_id.yml
  swagger/parameters/index.yml
  swagger/parameters/team_id.yml
  swagger/paths/contact/conversations.yml
  swagger/paths/contact/crud.yml
  swagger/paths/contact_inboxes/create.yml
  swagger/paths/conversation/update_last_seen.yml
  swagger/paths/index.yml
  swagger/paths/integrations/apps/show.yml
  swagger/paths/integrations/hooks/create.yml
  swagger/paths/integrations/hooks/delete.yml
  swagger/paths/integrations/hooks/update.yml
  swagger/paths/teams/show.yml
  swagger/swagger.json
Labels: PR: unreviewed

#2308 Chore: Refactor add note component to use foundation card
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/routes/dashboard/contacts/components/AddNote.vue
Labels: PR: unreviewed

#2310 Chore: Refactors view note component
  app/javascript/dashboard/assets/scss/_foundation-custom.scss
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/routes/dashboard/contacts/components/AddNote.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactNote.vue
Labels: PR: unreviewed

#2309 fix: Slack integration redirect url missing client ID
  app/views/api/v1/models/_app.json.jbuilder
  spec/controllers/api/v1/accounts/integrations/apps_controller_spec.rb
Labels: PR: unreviewed

#2319 fix: Broken Docker production config
  docker-compose.production.yaml
Labels: PR: reviewed-approved

#2299 feat: Create custom attributes for a contact from CRM
  .storybook/preview.js
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/modules/contact/components/AddCustomAttribute.vue
  app/javascript/dashboard/modules/contact/components/ContactAttribute.vue
  app/javascript/dashboard/modules/contact/components/ContactFields.vue
  app/javascript/dashboard/modules/contact/components/ContactPanel.vue
  app/javascript/dashboard/modules/contact/components/ManageLayout.vue
  app/javascript/dashboard/modules/contact/stories/AddCustomAttribute.stories.js
  app/javascript/dashboard/modules/contact/stories/ContactFields.stories.js
  app/javascript/dashboard/routes/dashboard/contacts/pages/ContactManageView.vue
Labels: PR: reviewed-approved

#2322 Chore: Fixes style issue of webhook button
  app/javascript/dashboard/routes/dashboard/settings/integrations/Webhook.vue
Labels: PR: reviewed-approved

#2307 chore: Add chatwoot utils package
  app/javascript/dashboard/components/ui/Label.vue
  app/javascript/shared/helpers/ColorHelper.js
  app/javascript/widget/components/PreChat/Form.vue
  app/javascript/widget/components/TeamAvailability.vue
  package.json
  yarn.lock
Labels: PR: partially-approved

#2331 fix: Fixes email overflow issue in conversation.
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
Labels: PR: unreviewed

#2329 chore: Add missing frontend specs
  app/javascript/dashboard/api/specs/account.spec.js
  app/javascript/dashboard/api/specs/apiSpecHelper.js
  app/javascript/dashboard/api/specs/channel/fbChannel.spec.js
  app/javascript/dashboard/api/specs/channel/twilioChannel.spec.js
  app/javascript/dashboard/api/specs/channel/twitterClient.spec.js
  app/javascript/dashboard/api/specs/channel/webChannel.spec.js
  app/javascript/dashboard/api/specs/contacts.spec.js
  app/javascript/dashboard/api/specs/conversations.spec.js
  app/javascript/dashboard/api/specs/endPoints.spec.js
  app/javascript/dashboard/api/specs/inbox/conversation.spec.js
  app/javascript/dashboard/api/specs/inbox/message.spec.js
  app/javascript/dashboard/api/specs/inboxes.spec.js
  app/javascript/dashboard/api/specs/notifications.spec.js
  app/javascript/dashboard/api/specs/reports.spec.js
  app/javascript/dashboard/api/specs/teams.spec.js
  app/javascript/dashboard/api/specs/webhook.spec.js
  app/javascript/dashboard/components/layout/sidebarComponents/specs/AccountSelector.spec.js
  app/javascript/dashboard/components/layout/sidebarComponents/specs/AgentDetails.spec.js
  app/javascript/dashboard/components/layout/sidebarComponents/specs/NotificationBell.spec.js
  app/javascript/dashboard/components/widgets/Thumbnail.spec.js
  app/javascript/dashboard/mixins/specs/conversationFixtures.js
  app/javascript/dashboard/mixins/specs/conversaton.spec.js
  app/javascript/dashboard/mixins/specs/isAdmin.spec.js
Labels: PR: unreviewed

#2332 chore: Upgrade @sentry/vue to 6.4.1
  app/javascript/packs/application.js
  package.json
  yarn.lock
Labels: PR: unreviewed

#2338 chore: Add select field example to woot seeder
  lib/woot_message_seeder.rb
Labels: PR: reviewed-approved

#2337 fix: Uses label component for add label button
  app/javascript/dashboard/components/ui/Label.vue
  app/javascript/shared/components/ui/dropdown/AddLabel.vue
Labels: PR: unreviewed

#2344 chore: ability to run Chatwoot as API only server
  .env.example
  Gemfile
  Gemfile.lock
  config/environments/development.rb
  config/environments/production.rb
  config/routes.rb
  spec/controllers/dashboard_controller_spec.rb
  spec/rails_helper.rb
Labels: PR: reviewed-approved

#2347 chore: Adjust Chatwoot Config to deploy frontend as a separate app
  app/javascript/dashboard/assets/scss/_woot.scss
  app/javascript/dashboard/components/widgets/InboxListItem.vue
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/constants.js
  app/javascript/dashboard/helper/APIHelper.js
  app/javascript/dashboard/helper/actionCable.js
  app/javascript/dashboard/routes/auth/Confirmation.vue
  app/javascript/dashboard/routes/auth/PasswordEdit.vue
  app/javascript/dashboard/routes/auth/ResetPassword.vue
  app/javascript/dashboard/routes/auth/Signup.vue
  app/javascript/dashboard/routes/dashboard/settings/canned/EditCanned.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/New.vue
  app/javascript/dashboard/routes/index.js
  app/javascript/dashboard/routes/index.spec.js
  app/javascript/dashboard/store/modules/auth.js
  app/javascript/shared/helpers/BaseActionCableConnector.js
Labels: PR: partially-approved

#2296 feat: Create section header component
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/contacts/components/SectionHeader.stories.js
  app/javascript/dashboard/routes/dashboard/contacts/components/SectionHeader.vue
Labels: PR: reviewed-approved
