Repository chatwoot/chatwoot, pull requests merged in 2021-03, with the labels that each got.

#1842 fix: greeting messages not sent
  app/services/message_templates/hook_execution_service.rb
  spec/services/message_templates/hook_execution_service_spec.rb
Labels: PR: reviewed-approved

#1846 Chore: Follow brand guidelines for brand icon colors and also its easy to id…
  app/javascript/dashboard/components/layout/SidebarItem.vue
  app/javascript/shared/assets/stylesheets/colors.scss
Labels: PR: reviewed-approved

#1835 chore: Move conversation header above sidebar
  app/javascript/dashboard/assets/scss/widgets/_conv-header.scss
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/components/widgets/conversation/EmptyState.vue
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
Labels: PR: reviewed-approved

#1761 Revised Spanish translation
  app/javascript/dashboard/i18n/locale/es/agentMgmt.json
  app/javascript/dashboard/i18n/locale/es/cannedMgmt.json
  app/javascript/dashboard/i18n/locale/es/chatlist.json
  app/javascript/dashboard/i18n/locale/es/contact.json
  app/javascript/dashboard/i18n/locale/es/conversation.json
  app/javascript/dashboard/i18n/locale/es/generalSettings.json
  app/javascript/dashboard/i18n/locale/es/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/es/integrations.json
  app/javascript/dashboard/i18n/locale/es/login.json
  app/javascript/dashboard/i18n/locale/es/report.json
  app/javascript/dashboard/i18n/locale/es/resetPassword.json
  app/javascript/dashboard/i18n/locale/es/settings.json
  app/javascript/dashboard/i18n/locale/es/signup.json
  config/locales/devise.es.yml
Labels: PR: unreviewed

#1851 chore: Enable email channel
  app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue
  app/mailboxes/application_mailbox.rb
  app/mailboxes/support_mailbox.rb
  app/mailers/conversation_reply_mailer.rb
  app/models/account.rb
  app/models/channel/email.rb
  app/presenters/mail_presenter.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  config/features.yml
  db/migrate/20210303192243_rename_channel_email_forward_address.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/channel/channel_email.rb
  spec/mailboxes/application_mailbox_spec.rb
  spec/mailers/conversation_reply_mailer_spec.rb
Labels: PR: reviewed-approved

#1738 fix: Add alert for incoming messages on dashboard
  app/javascript/dashboard/helper/actionCable.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/profile/NotificationSettings.vue
  app/javascript/packs/application.js
  app/javascript/shared/helpers/AudioNotificationHelper.js
  public/dashboard/audios/ding.mp3
Labels: PR: reviewed-approved

#1860 chore: add postmessage event for sending cookie to react native widget
  app/javascript/widget/App.vue
Labels: PR: unreviewed

#1485 Use name for the sender email id
  app/mailers/application_mailer.rb
Labels: PR: unreviewed

#1859 Fix: apply alert conditions while document is hidden
  app/javascript/shared/helpers/AudioNotificationHelper.js
  app/javascript/shared/helpers/specs/AudioNotificationHelper.spec.js
Labels: PR: unreviewed

#1856 Chore: Responsive fixes for common screen widths
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
Labels: PR: reviewed-approved

#1873 Fix: emoji box not showing up
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
Labels: PR: unreviewed

#1881 Fix: Short code table width breaking
  app/javascript/dashboard/routes/dashboard/settings/canned/Index.vue
Labels: PR: reviewed-approved

#1857 chore: Conversation item redesign
  app/javascript/dashboard/assets/scss/widgets/_conversation-card.scss
  app/javascript/dashboard/assets/scss/widgets/_sidemenu.scss
  app/javascript/dashboard/components/layout/SidebarItem.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/helper/inbox.js
  app/javascript/dashboard/helper/specs/inbox.spec.js
Labels: PR: unreviewed

#1885 Fix: Conversation timestamp and thumbnail position issue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
Labels: PR: reviewed-approved

#1896 Chore: Reply panel emoji button size fixes
  app/javascript/dashboard/assets/scss/widgets/_buttons.scss
  app/javascript/dashboard/assets/scss/widgets/_reply-box.scss
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
Labels: PR: unreviewed

#1893 feat: Activity messages for team assignments
  app/listeners/action_cable_listener.rb
  app/models/concerns/assignment_handler.rb
  app/models/concerns/round_robin_handler.rb
  app/models/conversation.rb
  config/locales/en.yml
  lib/events/types.rb
  spec/models/concerns/assignment_handler_spec.rb
  spec/models/concerns/round_robin_handler_spec.rb
  spec/models/conversation_spec.rb
Labels: PR: unreviewed

#1868 chore: Make SMTP environment variables configurable
  .env.example
  app/mailers/conversation_reply_mailer.rb
  app/models/account.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/initializers/devise.rb
  config/initializers/mailer.rb
  spec/mailers/conversation_reply_mailer_spec.rb
Labels: PR: unreviewed

#1812 Feat: business hours settings page
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/BusinessDay.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/WeeklyAvailability.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/helpers/businessHour.js
  app/javascript/dashboard/routes/dashboard/settings/inbox/helpers/specs/businessHour.spec.js
  app/javascript/dashboard/routes/dashboard/settings/inbox/helpers/timezones.json
  app/models/concerns/out_of_offisable.rb
Labels: PR: unreviewed

#1823 Feat: Show working hours on widget
  app/javascript/shared/helpers/DateHelper.js
  app/javascript/shared/helpers/specs/DateHelper.spec.js
  app/javascript/widget/components/ChatHeader.vue
  app/javascript/widget/components/TeamAvailability.vue
  app/javascript/widget/mixins/configMixin.js
  app/javascript/widget/mixins/teamAvailabilityMixin.js
  app/views/widgets/show.html.erb
  spec/models/working_hour_spec.rb
Labels: PR: unreviewed

#1898 Chore: Make prechat message minimum length to 1
  app/javascript/widget/components/PreChat/Form.vue
Labels: PR: partially-approved

#1879 Fix: Update offline message in widget by availability
  app/javascript/shared/helpers/DateHelper.js
  app/javascript/widget/components/ChatHeader.vue
  app/javascript/widget/components/TeamAvailability.vue
  app/javascript/widget/mixins/availability.js
  app/javascript/widget/mixins/configMixin.js
Labels: PR: unreviewed

#1905 chore: Added hover styles
  app/javascript/dashboard/components/layout/SidebarItem.vue
  app/javascript/dashboard/helper/inbox.js
  app/javascript/dashboard/helper/specs/inbox.spec.js
Labels: PR: reviewed-approved

#1907 chore: fix empty user_name. & password
  config/initializers/mailer.rb
Labels: PR: unreviewed

#1689 feat: Set up store for teams
  app/javascript/dashboard/api/specs/teams.spec.js
  app/javascript/dashboard/api/teams.js
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/i18n/default-sidebar.js
  app/javascript/dashboard/i18n/locale/en/index.js
  app/javascript/dashboard/i18n/locale/en/teamsSettings.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/settings.routes.js
  app/javascript/dashboard/routes/dashboard/settings/teams/AgentSelector.vue
  app/javascript/dashboard/routes/dashboard/settings/teams/Create/AddAgents.vue
  app/javascript/dashboard/routes/dashboard/settings/teams/Create/CreateTeam.vue
  app/javascript/dashboard/routes/dashboard/settings/teams/Create/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/teams/Edit/EditAgents.vue
  app/javascript/dashboard/routes/dashboard/settings/teams/Edit/EditTeam.vue
  app/javascript/dashboard/routes/dashboard/settings/teams/Edit/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/teams/FinishSetup.vue
  app/javascript/dashboard/routes/dashboard/settings/teams/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/teams/TeamForm.vue
  app/javascript/dashboard/routes/dashboard/settings/teams/helpers/validations.js
  app/javascript/dashboard/routes/dashboard/settings/teams/teams.routes.js
  app/javascript/dashboard/store/modules/specs/teamMembers/actions.spec.js
  app/javascript/dashboard/store/modules/specs/teams/actions.spec.js
  app/javascript/dashboard/store/modules/teamMembers.js
  app/javascript/dashboard/store/modules/teams/actions.js
  yarn.lock
Labels: PR: unreviewed

#1849 Feat: Assign conversations to teams.
  app/javascript/dashboard/api/inbox/conversation.js
  app/javascript/dashboard/api/specs/inbox/conversation.spec.js
  app/javascript/dashboard/assets/scss/plugins/_multiselect.scss
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/views/api/v1/conversations/partials/_conversation.json.jbuilder
Labels: PR: unreviewed

#1845 Enhancement: Redesigned search UI
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
  app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
  app/javascript/dashboard/routes/dashboard/conversation/search/ResultItem.vue
  app/javascript/dashboard/routes/dashboard/conversation/search/Search.vue
  app/javascript/dashboard/routes/dashboard/conversation/search/SearchMessageItem.vue
  app/views/api/v1/accounts/conversations/search.json.jbuilder
Labels: PR: unreviewed

#1912 Fixes conversation name overflow
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
Labels: PR: unreviewed

#1913 Chore: Migration to enable email channel
  app/controllers/platform/api/v1/users_controller.rb
  app/views/platform/api/v1/models/_user.json.jbuilder
  app/views/platform/api/v1/users/create.json.jbuilder
  app/views/platform/api/v1/users/show.json.jbuilder
  app/views/platform/api/v1/users/update.json.jbuilder
  config/features.yml
  db/migrate/20210315101919_enable_email_channel.rb
  db/schema.rb
Labels: PR: unreviewed

#1910 chore: enable close button in react-native widget
  app/javascript/widget/App.vue
  app/javascript/widget/components/HeaderActions.vue
  app/javascript/widget/helpers/utils.js
Labels: PR: reviewed-approved

#1923 chore: fix smtp_domain mailer config
  config/initializers/mailer.rb
Labels: PR: reviewed-approved

#1921 fix: Use team conversationURL in team section
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/helper/URLHelper.js
  app/javascript/dashboard/helper/specs/URLHelper.spec.js
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
Labels: PR: unreviewed

#1926 Fix: Error when assigns a conversation to user
  app/javascript/dashboard/helper/actionCable.js
Labels: PR: unreviewed

#1906 Chore: Hover color for status dropdown
  app/javascript/dashboard/assets/scss/_animations.scss
  app/javascript/dashboard/assets/scss/plugins/_dropdown.scss
  app/javascript/dashboard/assets/scss/widgets/_sidemenu.scss
  app/javascript/dashboard/components/layout/AvailabilityStatus.vue
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue
  app/javascript/dashboard/components/widgets/conversation/MoreActions.vue
  app/javascript/shared/components/ui/dropdown/DropdownItem.vue
  app/javascript/shared/components/ui/dropdown/DropdownMenu.vue
Labels: PR: reviewed-approved

#1947 Fix: Refactors error prone checks
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
Labels: PR: unreviewed

#1938 Fix: sidebar filters not applying bug for chatlist
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/store/modules/conversations/getters.js
  app/javascript/dashboard/store/modules/conversations/helpers.js
  app/javascript/dashboard/store/modules/specs/conversations/getters.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/helpers.spec.js
Labels: PR: reviewed-approved

#1914 Fix: Hide prechat for sessions inititated with setUser
  app/controllers/api/v1/widget/contacts_controller.rb
  app/javascript/widget/App.vue
  app/javascript/widget/api/contacts.js
  app/javascript/widget/store/modules/contacts.js
  app/javascript/widget/store/modules/specs/contact/actions.spec.js
  app/javascript/widget/store/modules/specs/contact/getters.spec.js
  app/javascript/widget/store/modules/specs/contact/mutations.spec.js
  app/javascript/widget/views/Home.vue
  app/views/api/v1/widget/contacts/show.json.jbuilder
  config/routes.rb
Labels: PR: unreviewed

#1945 Fix error messages during login for non-verified users
  app/javascript/dashboard/routes/login/Login.vue
Labels: PR: unreviewed

#1966 Fix: Add check for id on update conversation
  app/javascript/dashboard/helper/actionCable.js
Labels: PR: partially-approved

#1995 Chore: Sort labels in conversation label edit modal
  app/javascript/dashboard/routes/dashboard/conversation/labels/AddLabelToConversation.vue
Labels: PR: reviewed-approved

#1932 Enhancement: button component
  app/javascript/dashboard/components/ui/WootButton.vue
  app/javascript/packs/application.js
Labels: PR: unreviewed

#1998 chore: update rails to 6.0.3.6
  Gemfile.lock
Labels: PR: unreviewed

#1982 chore: fix application errors in sentry
  app/actions/contact_identify_action.rb
  app/controllers/api/v1/widget/base_controller.rb
  app/mailboxes/application_mailbox.rb
  app/models/notification.rb
  lib/exception_list.rb
  spec/actions/contact_identify_action_spec.rb
  spec/controllers/api/v1/widget/conversations_controller_spec.rb
  spec/models/notification_spec.rb
Labels: PR: reviewed-approved

#2001 Chore: Change widget offline message
  app/javascript/widget/components/ChatHeaderExpanded.vue
  app/javascript/widget/components/TeamAvailability.vue
  app/javascript/widget/i18n/locale/en.json
Labels: PR: reviewed-approved

#1987 fix: Handle rendering HTML only email in UI
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: unreviewed

#2003 fix: Revert quoted text styles
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: unreviewed

#2004 fix: Show inbox name only if more > 1 inbox present
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
Labels: PR: reviewed-approved

#2005 Docs: docker pull count badge
  README.md
Labels: PR: unreviewed

#2014 chore: Remove validation on team name
  app/models/team.rb
Labels: PR: unreviewed

#2016 chore: Add fail safes for Redis connections
  config/initializers/redis.rb
  lib/redis/config.rb
  spec/lib/redis/config_spec.rb
Labels: PR: unreviewed

#2017 fix: Add missing translations in agent reports
  app/views/api/v2/accounts/reports/agents.csv.erb
  config/locales/en.yml
  config/locales/ml.yml
Labels: PR: reviewed-approved

#2020 chore: Handle Sentry Errors
  app/mailers/application_mailer.rb
  lib/exception_list.rb
Labels: PR: reviewed-approved

#2024 chore: Add timeouts to requests
  app/mailers/agent_notifications/conversation_notifications_mailer.rb
  lib/local_resource.rb
  lib/webhooks/trigger.rb
  spec/lib/webhooks/trigger_spec.rb
  spec/mailers/agent_notifications/conversation_notifications_mailer_spec.rb
Labels: PR: reviewed-approved
