Repository chatwoot/chatwoot, pull requests merged in 2021-04, with the labels that each got.

#2036 Fixes: Responsive issue in chat list
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/SidemenuIcon.vue
  app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
Labels: PR: reviewed-approved

#2034 Fixes: Reply box overflow issue
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
Labels: PR: unreviewed

#2026 fix: Use exisiting bubble nodes if available
  app/javascript/sdk/IFrameHelper.js
Labels: PR: reviewed-approved, in-QA

#2046 fix: Invalidate session if user cookie is absent
  app/javascript/dashboard/api/auth.js
Labels: PR: reviewed-approved

#2028 fix: Allow text overflow in a conversation for wide emails
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/components/widgets/conversation/bubble/Text.vue
Labels: PR: unreviewed

#2051 fix: Alert mixin in profile settings page
  app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
Labels: PR: reviewed-approved

#2059 Enhancement: Added hover effect for conversations
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
Labels: PR: reviewed-approved

#1996 chore: Improve button component styles
  app/assets/stylesheets/administrate/utilities/_variables.scss
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/assets/scss/_variables.scss
  app/javascript/dashboard/components/index.js
  app/javascript/dashboard/components/ui/WootButton.vue
  app/javascript/dashboard/components/widgets/conversation/MoreActions.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
  app/javascript/packs/application.js
  app/javascript/widget/components/PreChat/Form.vue
  app/javascript/widget/components/TeamAvailability.vue
Labels: PR: unreviewed

#1997 feat: Add a dropdown to change status to "bot"
  app/javascript/dashboard/api/inbox/conversation.js
  app/javascript/dashboard/assets/scss/widgets/_conv-header.scss
  app/javascript/dashboard/components/buttons/ResolveAction.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/store/modules/conversations/actions.js
  config/locales/en.yml
Labels: PR: unreviewed

#2027 chore: Change size of assignee dropdown in header
  app/javascript/dashboard/assets/scss/plugins/_multiselect.scss
  app/javascript/dashboard/assets/scss/widgets/_conv-header.scss
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
Labels: PR: unreviewed

#2054 enhancement: Profile settings accessibility improvements
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
Labels: PR: reviewed-approved

#2065 chore: Refactors shouldShowInboxes to a generic name
  app/javascript/dashboard/components/layout/Sidebar.vue
Labels: PR: reviewed-approved

#2066 Enhancement: Adds a new button that redirect to inbox config page
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue
Labels: PR: reviewed-approved

#2069 chore: Add huntr.dev badge
  README.md
Labels: PR: reviewed-approved

#2057 Fixes: Alignment issue in activity message
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
Labels: PR: unreviewed

#2048 Fixes: Dropdown width issue fixes by using fit-content
  app/javascript/dashboard/assets/scss/plugins/_dropdown.scss
  app/javascript/dashboard/assets/scss/widgets/_sidemenu.scss
  app/javascript/dashboard/components/layout/AvailabilityStatus.vue
  app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue
  app/javascript/dashboard/components/widgets/conversation/MoreActions.vue
Labels: PR: unreviewed

#2060 Fix: Populate only agents part of the inbox in conversations
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/store/modules/inboxMembers.js
  app/javascript/dashboard/store/modules/specs/inboxMembers/actions.spec.js
  app/javascript/dashboard/store/modules/specs/inboxMembers/fixtures.js
  app/javascript/dashboard/store/modules/specs/inboxMembers/getters.spec.js
  app/javascript/dashboard/store/modules/specs/inboxMembers/mutations.spec.js
Labels: PR: reviewed-approved

#2080 Fix: Dropdown width issue in safari browser.
  app/javascript/dashboard/assets/scss/plugins/_dropdown.scss
Labels: PR: reviewed-approved

#2082 enhancement: Enable reply box for whatsapp template message
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/i18n/locale/el/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/i18n/locale/id/inboxMgmt.json
  app/javascript/shared/constants/links.js
Labels: PR: reviewed-approved, in-QA

#2088 Fix: Twilio whatsapp attachment messages not working
  app/models/message.rb
Labels: PR: reviewed-approved

#2092 fix: Type error in auth validity check action
  app/javascript/dashboard/store/modules/auth.js
Labels: PR: reviewed-approved

#2093 fix: Refresh user teams after creating a new team
  app/javascript/dashboard/routes/dashboard/settings/teams/Create/AddAgents.vue
  app/javascript/dashboard/routes/dashboard/settings/teams/Edit/EditAgents.vue
Labels: PR: unreviewed

#2079 Enhancement: Adds favicon badge for notification alert.
  app/javascript/packs/application.js
  app/javascript/shared/helpers/AudioNotificationHelper.js
  app/javascript/shared/helpers/faviconHelper.js
  app/views/layouts/vueapp.html.erb
  public/favicon-badge-16x16.png
  public/favicon-badge-32x32.png
  public/favicon-badge-96x96.png
Labels: PR: unreviewed

#2091 Enhancement: Changes contact location flag position
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
Labels: PR: reviewed-approved

#2090 Enhancement: Responsive issue in activity message
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: reviewed-approved

#2097 Fixes: Order list number break issue
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Text.vue
Labels: PR: reviewed-approved

#2101 feat: Contactable Inboxes API
  app/builders/contact_inbox_builder.rb
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/controllers/api/v1/accounts/conversations/messages_controller.rb
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/models/contact.rb
  app/models/contact_inbox.rb
  app/policies/contact_policy.rb
  app/services/contacts/contactable_inboxes_service.rb
  app/views/api/v1/accounts/contacts/contactable_inboxes.json.jbuilder
  config/routes.rb
  spec/builders/contact_inbox_builder_spec.rb
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
  spec/services/contacts/contactable_inboxes_service_spec.rb
Labels: PR: unreviewed

#1975 fix: Check uploaded file size in widget and dashboard
  app/javascript/dashboard/components/widgets/AttachmentsPreview.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/helper/files.js
  app/javascript/dashboard/helper/specs/files.spec.js
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/shared/constants/busEvents.js
  app/javascript/shared/constants/messages.js
  app/javascript/shared/helpers/FileHelper.js
  app/javascript/shared/helpers/specs/FileHelper.spec.js
  app/javascript/widget/components/ChatAttachment.vue
  app/javascript/widget/i18n/locale/en.json
  app/javascript/widget/views/Home.vue
Labels: PR: unreviewed, in-QA

#2105 Chore: Add validation for contact phone field
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactForm.vue
  app/javascript/shared/helpers/Validators.js
Labels: PR: reviewed-approved

#2102 Fix: Hides rich editor for unsupported channels
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: unreviewed

#2019 feat: Create a new conversation from the contact panel
  app/javascript/dashboard/api/contacts.js
  app/javascript/dashboard/components/ui/WootButton.vue
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/NewConversation.vue
  app/javascript/dashboard/store/modules/contactConversations.js
  app/javascript/dashboard/store/modules/contacts/actions.js
  app/javascript/dashboard/store/modules/contacts/index.js
  app/javascript/dashboard/store/modules/inboxes.js
  app/javascript/dashboard/store/modules/specs/contactConversations/actions.spec.js
  app/javascript/dashboard/store/modules/specs/contactConversations/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/services/contacts/contactable_inboxes_service.rb
  app/views/api/v1/models/_contact_inbox.json.jbuilder
Labels: PR: reviewed-approved

#2113 Fix: Fetch contactable inboxes on new conversion
  app/javascript/dashboard/routes/dashboard/conversation/contact/NewConversation.vue
Labels: PR: unreviewed

#2112 Chore: Upgrade v-tooltip version
  app/javascript/packs/application.js
  package.json
  yarn.lock
Labels: PR: unreviewed, QA Review Done

#2130 Chore: fix the resolve button padding issue.
  app/javascript/dashboard/components/buttons/ResolveAction.vue
Labels: PR: reviewed-approved

#2121 chore: Snackbar duplicate key warnings
  app/javascript/dashboard/components/SnackbarContainer.vue
Labels: PR: reviewed-approved

#2047 Fixes: Agent name overflow in dropdown menu
  app/javascript/dashboard/assets/scss/plugins/_multiselect.scss
  app/javascript/dashboard/assets/scss/widgets/_conv-header.scss
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
Labels: PR: reviewed-approved

#2133 chore: Update reset password error message
  app/javascript/dashboard/routes/auth/ResetPassword.vue
Labels: PR: reviewed-approved

#2103 chore: add SECURITY.md
  SECURITY.md
Labels: PR: reviewed-approved

#2131 feat: Assignable agents API
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/policies/inbox_policy.rb
  app/views/api/v1/accounts/inboxes/assignable_agents.json.jbuilder
  config/routes.rb
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
Labels: PR: partially-approved, PR: unreviewed

#2136 Chore: fixes issue with status badge.
  app/javascript/dashboard/components/widgets/conversation/AvailabilityStatusBadge.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
Labels: PR: reviewed-approved

#2135 chore: Enable the languages no, zh-CN, hu
  app/javascript/dashboard/i18n/index.js
  app/javascript/dashboard/i18n/locale/no/index.js
  app/javascript/dashboard/i18n/locale/zh_CN/index.js
  app/javascript/widget/i18n/index.js
  config/initializers/languages.rb
  config/locales/devise.zh_CN.yml
  config/locales/zh_CN.yml
Labels: PR: reviewed-approved

#2134 chore: Contact builder should Identify contacts based on phone number
  app/builders/contact_builder.rb
  spec/builders/contact_builder_spec.rb
Labels: PR: unreviewed, in-QA

#2140 Chore: Availability badge shape issue.
  app/javascript/dashboard/components/widgets/conversation/AvailabilityStatusBadge.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
Labels: PR: unreviewed

#2122 enhancement: Show agent availability status in conversation assignee select list
  app/javascript/dashboard/components/layout/AvailabilityStatus.vue
  app/javascript/dashboard/components/widgets/conversation/AvailabilityStatusBadge.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
Labels: PR: reviewed-approved

#2143 Fixes: Text break issue in multiselect and availability badge spacing issue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
Labels: PR: reviewed-approved

#2061 Fix: clear search input
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
  app/javascript/dashboard/store/modules/conversationPage.js
  app/javascript/dashboard/store/modules/specs/conversationPage/getters.spec.js
Labels: PR: partially-approved, QA Review Done

#2142 Enhancement: Ability to assign administrators as conversation assignees
  app/javascript/dashboard/api/inboxes.js
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/inboxAssignableAgents.js
  app/javascript/dashboard/store/modules/specs/inboxAssignableMembers/actions.spec.js
  app/javascript/dashboard/store/modules/specs/inboxAssignableMembers/fixtures.js
  app/javascript/dashboard/store/modules/specs/inboxAssignableMembers/getters.spec.js
  app/javascript/dashboard/store/modules/specs/inboxAssignableMembers/mutations.spec.js
Labels: PR: unreviewed

#2158 Fix: console error message when setting assigned team of contact to none
  app/javascript/dashboard/store/modules/conversations/helpers.js
Labels: PR: partially-approved

#2161 chore: Add font-display: swap to Ionicons
  app/javascript/shared/assets/stylesheets/ionicons.scss
Labels: PR: reviewed-approved

#2144 chore: inbox member clean up
  app/javascript/dashboard/store/modules/inboxMembers.js
  app/javascript/dashboard/store/modules/specs/inboxMembers/actions.spec.js
  app/javascript/dashboard/store/modules/specs/inboxMembers/fixtures.js
  app/javascript/dashboard/store/modules/specs/inboxMembers/getters.spec.js
  app/javascript/dashboard/store/modules/specs/inboxMembers/mutations.spec.js
Labels: PR: unreviewed

#2164 fix: Handle email with no subject line and no body
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/i18n/locale/en/chatlist.json
  app/presenters/mail_presenter.rb
  spec/fixtures/files/mail_with_no_subject.eml
  spec/presenters/mail_presenter_spec.rb
Labels: PR: unreviewed, QA Review Done

#2168 Enhancement: Create route for contact details page
  app/javascript/dashboard/i18n/default-sidebar.js
  app/javascript/dashboard/routes/dashboard/contacts/pages/ContactManageView.vue
  app/javascript/dashboard/routes/dashboard/contacts/routes.js
Labels: PR: partially-approved

#2173 chore: Add campaign empty page
  app/javascript/dashboard/i18n/locale/en/campaign.json
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/en/index.js
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/Campaign.vue
Labels: PR: reviewed-approved

#2167 chore: Add event for conversations transferred to Bot
  app/javascript/dashboard/helper/actionCable.js
  app/javascript/widget/helpers/actionCable.js
  app/listeners/action_cable_listener.rb
  app/listeners/webhook_listener.rb
  app/models/conversation.rb
  app/presenters/conversations/event_data_presenter.rb
  db/migrate/20210426191914_migration_remove_locked_from_conversation.rb
  db/schema.rb
  db/seeds.rb
  lib/events/types.rb
  spec/factories/conversations.rb
  spec/models/conversation_spec.rb
  spec/presenters/conversations/event_data_presenter_spec.rb
Labels: PR: partially-approved

#2179 chore: Upgrade rexml to 3.2.5 to fix CVE-2021-28965
  Gemfile.lock
Labels: PR: reviewed-approved

#2139 chore: Setup storybook for Chatwoot
  .storybook/main.js
  .storybook/preview.js
  app/javascript/dashboard/assets/scss/storybook.scss
  app/javascript/dashboard/components/ui/stories/Button.stories.js
  package.json
  stories/Sections/Introduction.stories.mdx
  yarn.lock
Labels: PR: unreviewed

#2175 feat: Campaign APIs
  app/controllers/api/v1/accounts/campaigns_controller.rb
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/models/account.rb
  app/models/campaign.rb
  app/models/conversation.rb
  app/models/inbox.rb
  app/policies/campaign_policy.rb
  app/policies/inbox_policy.rb
  app/views/api/v1/accounts/campaigns/create.json.jbuilder
  app/views/api/v1/accounts/campaigns/index.json.jbuilder
  app/views/api/v1/accounts/campaigns/show.json.jbuilder
  app/views/api/v1/accounts/campaigns/update.json.jbuilder
  app/views/api/v1/accounts/inboxes/campaigns.json.jbuilder
  app/views/api/v1/models/_campaign.json.jbuilder
  config/routes.rb
  db/migrate/20210428135041_campaigns.rb
  db/migrate/20210428151147_create_triggers_accounts_insert_or_campaigns_insert.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/campaigns_controller_spec.rb
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
  spec/factories/campaigns.rb
  spec/models/campaign_spec.rb
  spec/models/conversation_spec.rb
Labels: PR: reviewed-approved

#2181 Feat: Creates note component for CRM
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactNote.vue
  stories/Module/Note.stories.js
Labels: PR: reviewed-approved

#2188 chore: Add i18n and components into storybook
  .storybook/preview.js
  app/javascript/shared/store/globalConfig.js
Labels: PR: reviewed-approved

#2189 chore: Campaign ID migration for existing accounts
  app/controllers/api/v1/accounts/campaigns_controller.rb
  app/models/campaign.rb
  app/views/api/v1/models/_campaign.json.jbuilder
  db/migrate/20210430095748_add_camp_dp_id_seq_for_existing_accounts.rb
  db/migrate/20210430100138_rename_campaign_content_to_message.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/campaigns_controller_spec.rb
  spec/factories/campaigns.rb
Labels: PR: reviewed-approved

#2191 fix: Set babel/preset-env to 7.13.15
  package.json
  yarn.lock
Labels: PR: reviewed-approved
