Repository chatwoot/chatwoot, pull requests merged in 2021-01, with the labels that each got.

#1575 chore: Update license year and update company name
  LICENSE
  README.md
Labels: PR: reviewed-approved

#1563 feat: API to add label to contacts
  app/controllers/api/v1/accounts/contacts/labels_controller.rb
  app/controllers/api/v1/accounts/conversations/labels_controller.rb
  app/controllers/concerns/label_concern.rb
  app/models/concerns/labelable.rb
  app/models/contact.rb
  app/models/conversation.rb
  app/views/api/v1/accounts/contacts/labels/create.json.jbuilder
  app/views/api/v1/accounts/contacts/labels/index.json.jbuilder
  config/routes.rb
  spec/controllers/api/v1/accounts/contacts/labels_controller_spec.rb
Labels: PR: reviewed-approved

#1597 feat: Add link to the Twitter profile of the sender
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: reviewed-approved

#1602 security: Update azure-storage-blob to fix CVE-2020-26247
  Gemfile.lock
Labels: PR: reviewed-approved

#1412 chore: Automate conversation display_id generation with db triggers
  Gemfile
  Gemfile.lock
  app/models/account.rb
  app/models/conversation.rb
  db/migrate/20201125121240_create_triggers_accounts_insert_or_conversations_insert.rb
  db/migrate/20201125123131_conv_dpid_seq_for_existing_accnts.rb
  db/schema.rb
  spec/factories/conversations.rb
  spec/models/conversation_spec.rb
  spec/models/message_spec.rb
Labels: PR: partially-approved

#1610 chore: Sync the schema and migrations
  app/models/conversation.rb
  db/migrate/20210105185632_enable_pg_stats_extention.rb
  db/schema.rb
Labels: PR: reviewed-approved

#1562 feat: Add preview for attachment messages
  app/javascript/dashboard/api/inbox/message.js
  app/javascript/dashboard/assets/scss/app.scss
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/components/widgets/AttachmentsPreview.vue
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Text.vue
  app/javascript/dashboard/helper/commons.js
  app/javascript/dashboard/helper/files.js
  app/javascript/dashboard/helper/specs/commons.spec.js
  app/javascript/dashboard/helper/specs/files.spec.js
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/shared/assets/stylesheets/border-radius.scss
  app/javascript/widget/components/AgentMessage.vue
  app/javascript/widget/views/Unread.vue
  app/services/facebook/send_on_facebook_service.rb
  spec/services/facebook/send_on_facebook_service_spec.rb
Labels: PR: partially-approved

#1614 chore: Add steps to enable inbound_emails in the account
  docs/development/project-setup/conversation-continuity.md
Labels: PR: reviewed-approved

#1620 Chore: UI: Add shadow utility variables
  app/javascript/dashboard/assets/scss/app.scss
  app/javascript/shared/assets/stylesheets/shadows.scss
Labels: PR: unreviewed

#1611 chore: Enable updating conversation additional attributes
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/controllers/api/v1/widget/messages_controller.rb
  app/models/conversation.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
  swagger/paths/conversation/index_or_create.yml
  swagger/swagger.json
Labels: PR: reviewed-approved

#1631 fix: Add missing switch_locale on DashboardController
  app/controllers/dashboard_controller.rb
  spec/controllers/dashboard_controller_spec.rb
Labels: PR: unreviewed

#1628 chore: Update translations, enable Swedish
  app/javascript/dashboard/i18n/locale/sv/agentMgmt.json
  app/javascript/dashboard/i18n/locale/sv/cannedMgmt.json
  app/javascript/dashboard/i18n/locale/sv/chatlist.json
  app/javascript/dashboard/i18n/locale/sv/conversation.json
  app/javascript/dashboard/i18n/locale/sv/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/sv/labelsMgmt.json
  app/javascript/dashboard/i18n/locale/sv/login.json
  app/javascript/dashboard/i18n/locale/sv/settings.json
  app/javascript/widget/i18n/locale/sv.json
  config/initializers/languages.rb
Labels: PR: reviewed-approved

#1635 feat: Save UI state in the database
  app/controllers/api/v1/profiles_controller.rb
  app/javascript/dashboard/api/auth.js
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
  app/javascript/dashboard/store/modules/auth.js
  app/javascript/dashboard/store/modules/specs/auth/actions.spec.js
  app/javascript/dashboard/store/modules/specs/auth/getters.spec.js
  app/javascript/dashboard/store/modules/specs/auth/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/models/user.rb
  app/views/api/v1/models/_user.json.jbuilder
  db/migrate/20210109211805_add_ui_settings_to_users.rb
  db/schema.rb
  spec/controllers/api/v1/profiles_controller_spec.rb
Labels: PR: reviewed-approved

#1630 feat: Cron Jobs In Chatwoot
  Gemfile
  Gemfile.lock
  app/jobs/internal/check_new_versions_job.rb
  app/workers/conversation_reply_email_worker.rb
  config/initializers/sidekiq.rb
  config/routes.rb
  config/schedule.yml
  config/sidekiq.yml
  lib/chatwoot_hub.rb
  lib/redis/redis_keys.rb
  spec/jobs/internal/check_new_versions_job_spec.rb
  spec/lib/chatwoot_hub_spec.rb
Labels: PR: unreviewed

#1605 Improve sidebar UI
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactConversations.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactCustomAttributes.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactDetailsItem.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfoRow.vue
  app/javascript/dashboard/routes/dashboard/conversation/labels/LabelBox.vue
  app/javascript/shared/components/EmojiOrIcon.vue
  app/javascript/shared/helpers/emoji.js
Labels: PR: reviewed-approved

#1644 fix: Labels cannot be added to conversations
  app/controllers/api/v1/accounts/contacts/labels_controller.rb
  app/controllers/api/v1/accounts/conversations/labels_controller.rb
  spec/controllers/api/v1/accounts/contacts/labels_controller_spec.rb
  spec/controllers/api/v1/accounts/conversations/labels_controller_spec.rb
Labels: PR: reviewed-approved

#1619 chore: add count and current page in notification meta details
  app/controllers/api/v1/accounts/notifications_controller.rb
  app/views/api/v1/accounts/notifications/index.json.jbuilder
  spec/controllers/api/v1/accounts/notifications_controller_spec.rb
Labels: PR: partially-approved

#1623 Updates reply box UI 👀
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/assets/scss/widgets/_reply-box.scss
  app/javascript/dashboard/components/widgets/AttachmentsPreview.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyTopPanel.vue
  app/javascript/dashboard/components/widgets/WootWriter/constants.js
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/shared/assets/stylesheets/colors.scss
  app/javascript/shared/components/emoji/EmojiInput.vue
Labels: PR: partially-approved

#1634 Adds character count to reply box 😳
  app/javascript/dashboard/components/widgets/WootWriter/ReplyTopPanel.vue
  app/javascript/dashboard/components/widgets/WootWriter/constants.js
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: unreviewed

#1649 fix: Resolve name only if assignee exists during unassignment
  app/models/conversation.rb
  spec/controllers/api/v1/accounts/conversations/assignments_controller_spec.rb
Labels: PR: reviewed-approved

#1456 feat: Platform APIs
  .rubocop.yml
  .rubocop_todo.yml
  app/controllers/application_controller.rb
  app/controllers/platform/api/v1/account_users_controller.rb
  app/controllers/platform/api/v1/accounts_controller.rb
  app/controllers/platform/api/v1/users_controller.rb
  app/controllers/platform_controller.rb
  app/models/inbox.rb
  app/models/platform_app.rb
  app/models/platform_app_permissible.rb
  config/routes.rb
  db/migrate/20201123195011_create_platform_apps.rb
  db/migrate/20201124101124_create_platform_app_permissibles.rb
  db/schema.rb
  lib/current.rb
  spec/controllers/platform/api/v1/account_users_controller_spec.rb
  spec/controllers/platform/api/v1/accounts_controller_spec.rb
  spec/controllers/platform/api/v1/users_controller_spec.rb
  spec/factories/platform_apps.rb
  spec/factories/platform_apps_permissibles.rb
  spec/models/agent_bot_spec.rb
  spec/models/concerns/access_tokenable_spec.rb
  spec/models/platform_app_permissible_spec.rb
  spec/models/platform_app_spec.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#1650 chore: Update Contact Inbox create API
  swagger/paths/contact_inboxes/create.yml
  swagger/swagger.json
Labels: PR: unreviewed

#1641 feat: installation config in super admin console
  .gitignore
  app/controllers/super_admin/installation_configs_controller.rb
  app/dashboards/installation_config_dashboard.rb
  app/fields/serialized_field.rb
  app/models/installation_config.rb
  app/views/fields/serialized_field/_form.html.erb
  app/views/fields/serialized_field/_index.html.erb
  app/views/fields/serialized_field/_show.html.erb
  app/views/super_admin/application/_navigation.html.erb
  config/installation_config.yml
  config/routes.rb
  db/migrate/20210113045116_add_locked_attribute_to_installation_config.rb
  db/schema.rb
  lib/config_loader.rb
  spec/controllers/super_admin/installation_configs_controller_spec.rb
  spec/factories/installation_config.rb
Labels: PR: partially-approved

#1656 feat: remove un-necessary lock attribute in config
  config/installation_config.yml
Labels: PR: reviewed-approved

#1642 Adds support for markdown
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Text.vue
  app/javascript/dashboard/routes/dashboard/conversation/search/Search.vue
  app/javascript/shared/helpers/MessageFormatter.js
  app/javascript/shared/helpers/specs/MessageFormatter.spec.js
  app/javascript/shared/mixins/messageFormatterMixin.js
  app/javascript/shared/mixins/specs/messageFormatterMixin.spec.js
  app/javascript/widget/components/AgentMessageBubble.vue
  app/javascript/widget/components/UserMessage.vue
  app/javascript/widget/components/UserMessageBubble.vue
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#1640 feat: Installation On-boarding flow
  .env.example
  app.json
  app/builders/account_builder.rb
  app/controllers/dashboard_controller.rb
  app/controllers/installation/onboarding_controller.rb
  app/javascript/dashboard/assets/scss/super_admin/index.scss
  app/views/installation/onboarding/index.html.erb
  config/routes.rb
  db/seeds.rb
  lib/chatwoot_hub.rb
  lib/redis/redis_keys.rb
  spec/controllers/installation/onboarding_controller_spec.rb
Labels: PR: unreviewed

#1659 fix: Add correct thread message_id to the email message
  .rubocop.yml
  app/mailboxes/support_mailbox.rb
  app/mailers/conversation_reply_mailer.rb
  app/models/channel/email.rb
  app/models/message.rb
  app/workers/conversation_reply_email_worker.rb
Labels: PR: reviewed-approved

#1643 feat: HMAC verification for web widget
  app/controllers/api/v1/widget/base_controller.rb
  app/controllers/api/v1/widget/contacts_controller.rb
  app/javascript/dashboard/components/SettingsSection.vue
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/packs/sdk.js
  app/javascript/specs/packs/sdk.spec.js
  app/javascript/widget/store/modules/contacts.js
  app/javascript/widget/store/modules/conversation.js
  app/javascript/widget/store/modules/conversation/actions.js
  app/javascript/widget/store/modules/conversation/getters.js
  app/javascript/widget/store/modules/conversation/helpers.js
  app/javascript/widget/store/modules/conversation/index.js
  app/javascript/widget/store/modules/conversation/mutations.js
  app/javascript/widget/store/modules/specs/conversation/actions.spec.js
  app/javascript/widget/store/modules/specs/conversation/getters.spec.js
  app/javascript/widget/store/modules/specs/conversation/helpers.spec.js
  app/javascript/widget/store/modules/specs/conversation/mutations.spec.js
  app/models/channel/web_widget.rb
  app/models/contact_inbox.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  app/views/widget_tests/index.html.erb
  db/migrate/20210112174124_add_hmac_token_to_inbox.rb
  db/schema.rb
  docs/channels/identity-validation.md
  docs/channels/website-sdk.md
Labels: PR: unreviewed

#1646 chore: notification unread count api
  app/controllers/api/v1/accounts/notifications_controller.rb
  config/routes.rb
  spec/controllers/api/v1/accounts/notifications_controller_spec.rb
Labels: PR: unreviewed

#1654 feat: Team APIs
  app/controllers/api/v1/accounts/team_members_controller.rb
  app/controllers/api/v1/accounts/teams_controller.rb
  app/models/account.rb
  app/models/conversation.rb
  app/models/team.rb
  app/models/team_member.rb
  app/models/user.rb
  app/policies/team_member_policy.rb
  app/policies/team_policy.rb
  app/views/api/v1/accounts/inbox_members/show.json.jbuilder
  app/views/api/v1/accounts/team_members/create.json.jbuilder
  app/views/api/v1/accounts/team_members/index.json.jbuilder
  app/views/api/v1/accounts/teams/create.json.jbuilder
  app/views/api/v1/accounts/teams/index.json.jbuilder
  app/views/api/v1/accounts/teams/show.json.jbuilder
  app/views/api/v1/accounts/teams/update.json.jbuilder
  app/views/api/v1/models/_team.json.jbuilder
  config/routes.rb
  db/migrate/20210114202310_create_teams.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/team_members_controller_spec.rb
  spec/controllers/api/v1/accounts/teams_controller_spec.rb
  spec/factories/team_members.rb
  spec/factories/teams.rb
  spec/models/account_spec.rb
  spec/models/conversation_spec.rb
  spec/models/team_member_spec.rb
  spec/models/team_spec.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#1660 feat: Update notification in account settings
  app/controllers/api/v1/accounts_controller.rb
  app/javascript/dashboard/i18n/locale/en/generalSettings.json
  app/javascript/dashboard/routes/dashboard/settings/account/Index.vue
  app/javascript/shared/store/globalConfig.js
  app/views/api/v1/accounts/show.json.jbuilder
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#1662 chore: Update homebrew installation command
  docs/development/environment-setup/mac-os.md
Labels: PR: unreviewed

#1633 chore: Standardize button element
  app/javascript/dashboard/assets/scss/_foundation-custom.scss
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/assets/scss/widgets/_buttons.scss
  app/javascript/dashboard/assets/scss/widgets/_conv-header.scss
  app/javascript/dashboard/components/buttons/ResolveAction.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyTopPanel.vue
Labels: PR: reviewed-approved

#1657 feat: Markdown editor support
  app/javascript/dashboard/assets/scss/_woot.scss
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  package.json
  yarn.lock
Labels: PR: partially-approved

#1663 feat: Enable Markdown Parsing in emails
  Gemfile
  Gemfile.lock
  app/builders/contact_builder.rb
  app/mailers/conversation_reply_mailer.rb
  app/views/mailers/conversation_reply_mailer/conversation_transcript.html.erb
  app/views/mailers/conversation_reply_mailer/reply_with_summary.html.erb
  app/views/mailers/conversation_reply_mailer/reply_without_summary.html.erb
Labels: PR: reviewed-approved

#1665 fix: Avoid list-style none in message-content
  app/javascript/widget/assets/scss/woot.scss
Labels: PR: reviewed-approved

#1668 chore: Fix db:prepare error in deployments
  Procfile
  app.json
  lib/tasks/db_enhancements.rake
Labels: PR: unreviewed

#1671 feat: Add "Enter to send" option on format mode
  app/javascript/dashboard/assets/scss/widgets/_reply-box.scss
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/conversation/CannedResponse.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
Labels: PR: partially-approved

#1674 Contact.find_by should be Current.account.contacts.find_by
  app/controllers/api/v1/accounts/contacts_controller.rb
Labels: PR: unreviewed

#1677 chore: update identity verification docs
  docs/channels/website-sdk.md
Labels: PR: reviewed-approved

#1676 chore: Seeder for Bot Messages
  app/views/widget_tests/index.html.erb
  db/seeds.rb
  lib/woot_message_seeder.rb
Labels: PR: reviewed-approved

#1681 chore: Move Canned Responses list to a separate component
  app/javascript/dashboard/assets/scss/widgets/_reply-box.scss
  app/javascript/dashboard/components/widgets/conversation/CannedResponse.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/mentions/MentionBox.vue
Labels: PR: reviewed-approved

#1612 feat: notification center
  app/controllers/api/v1/accounts/notifications_controller.rb
  app/javascript/dashboard/api/notifications.js
  app/javascript/dashboard/api/specs/notifications.spec.js
  app/javascript/dashboard/assets/scss/widgets/_sidemenu.scss
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/widgets/TableFooter.vue
  app/javascript/dashboard/i18n/default-sidebar.js
  app/javascript/dashboard/i18n/locale/en/generalSettings.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
  app/javascript/dashboard/routes/dashboard/dashboard.routes.js
  app/javascript/dashboard/routes/dashboard/notifications/components/NotificationTable.vue
  app/javascript/dashboard/routes/dashboard/notifications/components/NotificationsView.vue
  app/javascript/dashboard/routes/dashboard/notifications/routes.js
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/notifications/actions.js
  app/javascript/dashboard/store/modules/notifications/getters.js
  app/javascript/dashboard/store/modules/notifications/index.js
  app/javascript/dashboard/store/modules/notifications/mutations.js
  app/javascript/dashboard/store/modules/specs/notifications/actions.spec.js
  app/javascript/dashboard/store/modules/specs/notifications/getters.spec.js
  app/javascript/dashboard/store/modules/specs/notifications/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
Labels: PR: reviewed-approved

#1688 feat: Tag agents in a private note
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/conversation/TagAgents.vue
  app/javascript/dashboard/i18n/locale/en/generalSettings.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/notifications/components/NotificationTable.vue
  app/javascript/dashboard/routes/dashboard/settings/profile/NotificationSettings.vue
  app/javascript/dashboard/store/modules/notifications/mutations.js
  app/javascript/dashboard/store/modules/specs/notifications/mutations.spec.js
  app/javascript/shared/helpers/MessageFormatter.js
  app/listeners/notification_listener.rb
  app/mailers/agent_notifications/conversation_notifications_mailer.rb
  app/models/notification.rb
  app/views/api/v1/accounts/notifications/index.json.jbuilder
  app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_mention.liquid
  package.json
  spec/listeners/notification_listener_spec.rb
  spec/mailers/agent_notifications/conversation_notifications_mailer_spec.rb
  yarn.lock
Labels: PR: unreviewed

#1701 docs: fixed typos
  Gemfile
  app/controllers/api/v1/widget/contacts_controller.rb
  app/javascript/dashboard/routes/login/Login.vue
  app/mailers/application_mailer.rb
  app/models/concerns/reauthorizable.rb
  spec/actions/contact_identify_action_spec.rb
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
Labels: PR: reviewed-approved

#1695 feat: Improvements to Team APIs
  app/controllers/api/v1/accounts/team_members_controller.rb
  app/models/team.rb
  app/models/team_member.rb
  app/views/api/v1/accounts/team_members/create.json.jbuilder
  db/migrate/20210126121313_addunique_index_to_team_members.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/team_members_controller_spec.rb
  spec/controllers/api/v1/accounts/teams_controller_spec.rb
Labels: PR: reviewed-approved

#1703 feat: Add support for Clever cloud deployments
  clevercloud/ruby.json
  lib/tasks/db_enhancements.rake
Labels: PR: reviewed-approved

#1712 feat: Team Assignment & Filter APIs
  app/controllers/api/v1/accounts/conversations/assignments_controller.rb
  app/finders/conversation_finder.rb
  spec/controllers/api/v1/accounts/conversations/assignments_controller_spec.rb
  spec/finders/conversation_finder_spec.rb
Labels: PR: reviewed-approved

#1683 Chore: Fix Deserialisation Error in Jobs
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/i18n/locale/en/chatlist.json
  app/jobs/application_job.rb
  app/views/api/v1/conversations/partials/_conversation.json.jbuilder
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
Labels: PR: reviewed-approved
