Repository chatwoot/chatwoot, pull requests merged in 2021-11, with the labels that each got.

#3306 bug: Escape html tags from the slack messages
  lib/integrations/slack/send_on_slack_service.rb
Labels: PR: unreviewed

#3303 Added private flag for typing indicator status
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/javascript/dashboard/api/inbox/conversation.js
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/store/modules/conversationTypingStatus.js
  app/javascript/widget/helpers/actionCable.js
  app/listeners/action_cable_listener.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
  spec/listeners/action_cable_listener_spec.rb
Labels: PR: unreviewed

#3264 Feat: Filter APIs for Contacts and Conversations
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/services/contacts/filter_service.rb
  app/services/conversations/filter_service.rb
  app/services/filter_service.rb
  app/views/api/v1/accounts/conversations/filter.json.jbuilder
  config/routes.rb
  lib/filters/conversation_filters.json
  lib/filters/filter_keys.json
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
  spec/services/contacts/filter_service_spec.rb
  spec/services/conversations/filter_service_spec.rb
Labels: PR: partially-approved

#3296 bug: Fixes the height issue of attachment image preview.
  app/javascript/dashboard/assets/scss/_foundation-custom.scss
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
Labels: PR: unreviewed

#3293 feat: Adds support for paste attachment with keys.
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: partially-approved

#3288 feat: add GlobalConfigService to support env vars migration
  app/controllers/api/v1/accounts_controller.rb
  app/controllers/dashboard_controller.rb
  app/views/layouts/vueapp.html.erb
  lib/global_config.rb
  lib/global_config_service.rb
  spec/controllers/api/v1/accounts_controller_spec.rb
  spec/lib/global_config_service_spec.rb
Labels: PR: partially-approved

#3319 Chore: Fcm notification priority
  app/services/notification/push_notification_service.rb
Labels: PR: reviewed-approved

#3333 Update Twilio SMS MSG Limit to 320 characters
  app/javascript/shared/helpers/MessageTypeHelper.js
Labels: PR: unreviewed

#3324 TEAM_AVAILABILITY dutch translation issue fixed
  app/javascript/widget/i18n/locale/nl.json
Labels: PR: reviewed-approved

#3337 fix: Revert translated keys in conversation status
  app/javascript/dashboard/i18n/locale/ar/chatlist.json
  app/javascript/dashboard/i18n/locale/cs/chatlist.json
  app/javascript/dashboard/i18n/locale/el/chatlist.json
  app/javascript/dashboard/i18n/locale/fa/chatlist.json
  app/javascript/dashboard/i18n/locale/nl/chatlist.json
  app/javascript/dashboard/i18n/locale/pl/chatlist.json
  app/javascript/dashboard/i18n/locale/pt/chatlist.json
  app/javascript/dashboard/i18n/locale/pt_BR/chatlist.json
  app/javascript/dashboard/i18n/locale/ru/chatlist.json
  app/javascript/dashboard/i18n/locale/th/chatlist.json
  app/javascript/dashboard/i18n/locale/tr/chatlist.json
  app/javascript/dashboard/i18n/locale/zh_TW/chatlist.json
Labels: PR: unreviewed

#3128 feat: Autogenerate vapid keys for push notifications
  app/controllers/dashboard_controller.rb
  app/javascript/shared/mixins/specs/campaignMixin.spec.js
  app/javascript/widget/store/modules/events.js
  app/services/notification/push_notification_service.rb
  app/views/layouts/vueapp.html.erb
  lib/vapid_service.rb
  spec/lib/vapid_service_spec.rb
Labels: PR: partially-approved, in-QA

#3292 feat: Add Null values at the last while sorting
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
  app/models/contact.rb
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
Labels: PR: unreviewed

#3313 Bug: Instagram render template message twice
  app/builders/messages/instagram/message_builder.rb
  app/services/instagram/send_on_instagram_service.rb
  spec/services/instagram/send_on_instagram_service_spec.rb
Labels: PR: partially-approved

#3350 fix: Add missing condition checking if hmac is mandatory
  app/controllers/api/v1/widget/contacts_controller.rb
  spec/controllers/api/v1/widget/contacts_controller_spec.rb
Labels: PR: reviewed-approved

#3299 chore: Handle attachments in Whatsapp Channel
  Gemfile
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue
  app/models/channel/telegram.rb
  app/models/channel/whatsapp.rb
  app/services/whatsapp/incoming_message_service.rb
  app/services/whatsapp/send_on_whatsapp_service.rb
  spec/actions/contact_identify_action_spec.rb
  spec/assets/sample.mov
  spec/assets/sample.mp3
  spec/assets/sample.ogg
  spec/assets/sample.pdf
  spec/assets/sample.png
  spec/builders/contact_inbox_builder_spec.rb
  spec/builders/messages/facebook/message_builder_spec.rb
  spec/builders/messages/instagram/message_builder_spec.rb
  spec/controllers/api/v1/accounts/callbacks_controller_spec.rb
  spec/factories/bot_message/bot_message_card.rb
  spec/factories/twitter/twitter_message_create_event.rb
  spec/jobs/send_reply_job_spec.rb
  spec/jobs/webhooks/instagram_events_job_spec.rb
  spec/lib/integrations/slack/incoming_message_builder_spec.rb
  spec/mailers/administrator_notifications/channel_notifications_mailer_spec.rb
  spec/models/campaign_spec.rb
  spec/models/channel/facebook_page_spec.rb
  spec/models/conversation_spec.rb
  spec/services/contacts/contactable_inboxes_service_spec.rb
  spec/services/instagram/send_on_instagram_service_spec.rb
  spec/services/telegram/incoming_message_service_spec.rb
  spec/services/whatsapp/incoming_message_service_spec.rb
  spec/services/whatsapp/send_on_whatsapp_service_spec.rb
  spec/spec_helper.rb
  spec/support/slack_stubs.rb
Labels: PR: unreviewed

#3354 Limit redis and postgres access to localhost
  docker-compose.production.yaml
Labels: PR: reviewed-approved

#3310 feat: Render contact custom attributes in contact/conversation sidebar
  .rubocop.yml
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/controllers/api/v1/accounts/custom_attribute_definitions_controller.rb
  app/javascript/dashboard/api/attributes.js
  app/javascript/dashboard/api/contacts.js
  app/javascript/dashboard/api/specs/contacts.spec.js
  app/javascript/dashboard/components/CustomAttribute.vue
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/i18n/locale/en/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/i18n/sidebarItems/settings.js
  app/javascript/dashboard/mixins/attributeMixin.js
  app/javascript/dashboard/mixins/specs/attributeMixin.spec.js
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/customAttributes/CustomAttributeDropDown.vue
  app/javascript/dashboard/routes/dashboard/conversation/customAttributes/CustomAttributeSelector.vue
  app/javascript/dashboard/routes/dashboard/conversation/customAttributes/CustomAttributes.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/AddAttribute.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/CustomAttribute.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/EditAttribute.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/attributes.routes.js
  app/javascript/dashboard/routes/dashboard/settings/attributes/constants.js
  app/javascript/dashboard/store/modules/attributes.js
  app/javascript/dashboard/store/modules/contacts/actions.js
  app/javascript/dashboard/store/modules/specs/contacts/actions.spec.js
  app/models/custom_attribute_definition.rb
  app/policies/contact_policy.rb
  app/views/api/v1/accounts/contacts/destroy_custom_attributes.json.jbuilder
  config/routes.rb
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
  spec/controllers/api/v1/accounts/custom_attribute_definitions_controller_spec.rb
Labels: PR: partially-approved

#3215 feat: Show pre-chat form before triggering the campaign
  app/javascript/widget/App.vue
  app/javascript/widget/components/PreChat/Form.vue
  app/javascript/widget/i18n/locale/en.json
  app/javascript/widget/store/modules/campaign.js
  app/javascript/widget/store/modules/specs/campaign/actions.spec.js
  app/javascript/widget/store/modules/specs/campaign/getters.spec.js
  app/javascript/widget/store/modules/specs/campaign/mutations.spec.js
  app/javascript/widget/views/Home.vue
  app/javascript/widget/views/Router.vue
Labels: PR: unreviewed

#3360 fix: make GlobalConfig migrated from .env editable from UI
  lib/global_config_service.rb
Labels: PR: reviewed-approved

#3361 Feat: Update custom filter for present/not_present operator
  app/services/filter_service.rb
  lib/filters/filter_keys.json
  spec/services/conversations/filter_service_spec.rb
Labels: PR: unreviewed

#3366 fix: Remove * as import from conversation module
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
Labels: PR: reviewed-approved

#3364 chore: Fix conversation status in webhooks
  app/jobs/conversations/activity_message_job.rb
  app/listeners/action_cable_listener.rb
  app/models/concerns/activity_message_handler.rb
  app/models/concerns/assignment_handler.rb
  app/models/conversation.rb
  app/models/message.rb
  spec/controllers/api/v1/accounts/conversations/assignments_controller_spec.rb
  spec/models/concerns/assignment_handler_shared.rb
  spec/models/conversation_spec.rb
  spec/services/message_templates/hook_execution_service_spec.rb
  swagger/paths/application/agents/create.yml
  swagger/paths/application/agents/update.yml
  swagger/swagger.json
Labels: PR: unreviewed

#3285 feat: enable Dialogflow integration all inboxes except email
  app/javascript/dashboard/routes/dashboard/settings/integrationapps/NewHook.vue
  app/javascript/dashboard/store/modules/inboxes.js
  app/javascript/dashboard/store/modules/specs/inboxes/getters.spec.js
  app/listeners/hook_listener.rb
  spec/factories/integrations/hooks.rb
  spec/jobs/hook_job_spec.rb
  spec/lib/integrations/dialogflow/processor_service_spec.rb
  spec/models/conversation_spec.rb
Labels: PR: unreviewed, QA Review Done

#3367 Feat: Swagger updated for the custom filter endpoint
  app/services/filter_service.rb
  spec/services/conversations/filter_service_spec.rb
  swagger/paths/application/conversation/filter.yml
  swagger/paths/index.yml
  swagger/swagger.json
Labels: PR: unreviewed

#3374 chore: Fix translations breaking the chat filter
  app/javascript/dashboard/components/widgets/conversation/ChatFilter.vue
  app/javascript/dashboard/i18n/locale/en/chatlist.json
Labels: PR: reviewed-approved

#3375 New Crowdin updates
  app/javascript/dashboard/i18n/locale/ar/chatlist.json
  app/javascript/dashboard/i18n/locale/ca/chatlist.json
  app/javascript/dashboard/i18n/locale/cs/chatlist.json
  app/javascript/dashboard/i18n/locale/da/chatlist.json
  app/javascript/dashboard/i18n/locale/de/chatlist.json
  app/javascript/dashboard/i18n/locale/el/chatlist.json
  app/javascript/dashboard/i18n/locale/es/chatlist.json
  app/javascript/dashboard/i18n/locale/fa/chatlist.json
  app/javascript/dashboard/i18n/locale/fi/chatlist.json
  app/javascript/dashboard/i18n/locale/fr/chatlist.json
  app/javascript/dashboard/i18n/locale/he/chatlist.json
  app/javascript/dashboard/i18n/locale/hi/chatlist.json
  app/javascript/dashboard/i18n/locale/hu/chatlist.json
  app/javascript/dashboard/i18n/locale/id/chatlist.json
  app/javascript/dashboard/i18n/locale/it/chatlist.json
  app/javascript/dashboard/i18n/locale/ja/chatlist.json
  app/javascript/dashboard/i18n/locale/ko/chatlist.json
  app/javascript/dashboard/i18n/locale/ml/chatlist.json
  app/javascript/dashboard/i18n/locale/ne/chatlist.json
  app/javascript/dashboard/i18n/locale/nl/chatlist.json
  app/javascript/dashboard/i18n/locale/no/chatlist.json
  app/javascript/dashboard/i18n/locale/pl/chatlist.json
  app/javascript/dashboard/i18n/locale/pt/chatlist.json
  app/javascript/dashboard/i18n/locale/pt_BR/chatlist.json
  app/javascript/dashboard/i18n/locale/ro/chatlist.json
  app/javascript/dashboard/i18n/locale/ru/chatlist.json
  app/javascript/dashboard/i18n/locale/sk/chatlist.json
  app/javascript/dashboard/i18n/locale/sv/chatlist.json
  app/javascript/dashboard/i18n/locale/ta/chatlist.json
  app/javascript/dashboard/i18n/locale/th/chatlist.json
  app/javascript/dashboard/i18n/locale/tr/chatlist.json
  app/javascript/dashboard/i18n/locale/uk/chatlist.json
  app/javascript/dashboard/i18n/locale/vi/chatlist.json
  app/javascript/dashboard/i18n/locale/zh_CN/chatlist.json
  app/javascript/dashboard/i18n/locale/zh_TW/chatlist.json
  app/javascript/widget/i18n/locale/ru.json
Labels: PR: reviewed-approved

#3362 feat: Add the option for changing the contact/conversation sidebar items order
  app/javascript/dashboard/mixins/specs/uiSettings.spec.js
  app/javascript/dashboard/mixins/uiSettings.js
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/ConversationAction.vue
  package.json
  yarn.lock
Labels: PR: unreviewed

#3381 chore: Update conversation sidebar items default order
  app/javascript/dashboard/mixins/specs/uiSettings.spec.js
  app/javascript/dashboard/mixins/uiSettings.js
Labels: PR: reviewed-approved

#3382 chore: Add the option to edit custom attribute display name
  app/javascript/dashboard/i18n/locale/en/attributesMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/attributes/AddAttribute.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/EditAttribute.vue
  app/javascript/dashboard/store/modules/attributes.js
Labels: PR: reviewed-approved

#3334 chore: Update `deleteCustomAttribute` method in SDK
  app/controllers/api/v1/widget/contacts_controller.rb
  app/javascript/dashboard/components/CustomAttribute.vue
  app/javascript/dashboard/helper/actionCable.js
  app/javascript/dashboard/mixins/attributeMixin.js
  app/javascript/dashboard/mixins/specs/attributeMixin.spec.js
  app/javascript/dashboard/store/modules/contacts/actions.js
  app/javascript/dashboard/store/modules/specs/contacts/actions.spec.js
  app/javascript/widget/App.vue
  app/javascript/widget/api/contacts.js
  app/javascript/widget/store/modules/contacts.js
  config/routes.rb
  spec/controllers/api/v1/widget/contacts_controller_spec.rb
Labels: PR: partially-approved

#3384 New Crowdin updates
  app/javascript/dashboard/i18n/locale/ar/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/ar/login.json
  app/javascript/dashboard/i18n/locale/ca/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/cs/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/da/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/de/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/de/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/de/integrationApps.json
  app/javascript/dashboard/i18n/locale/el/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/es/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/fa/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/fi/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/fr/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/he/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/hi/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/hu/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/id/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/it/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/ja/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/ko/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/ml/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/ne/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/nl/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/no/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/pl/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/pt/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/pt_BR/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/ro/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/ru/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/sk/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/sv/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/ta/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/th/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/tr/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/uk/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/vi/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/zh_CN/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/zh_TW/attributesMgmt.json
  app/javascript/widget/i18n/locale/nl.json
Labels: PR: reviewed-approved

#3352 feat: Add Command bar for improved productivity
  app/javascript/dashboard/components/buttons/ResolveAction.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/components/widgets/conversation/MoreActions.vue
  app/javascript/dashboard/components/widgets/conversation/specs/MoreActions.spec.js
  app/javascript/dashboard/i18n/locale/en/generalSettings.json
  app/javascript/dashboard/mixins/agentMixin.js
  app/javascript/dashboard/mixins/conversation/labelMixin.js
  app/javascript/dashboard/mixins/conversation/teamMixin.js
  app/javascript/dashboard/routes/dashboard/Dashboard.vue
  app/javascript/dashboard/routes/dashboard/commands/CommandBarIcons.js
  app/javascript/dashboard/routes/dashboard/commands/commandBarBusEvents.js
  app/javascript/dashboard/routes/dashboard/commands/commandbar.vue
  app/javascript/dashboard/routes/dashboard/commands/conversationHotKeys.js
  app/javascript/dashboard/routes/dashboard/commands/goToCommandHotKeys.js
  app/javascript/dashboard/routes/dashboard/commands/specs/conversationHotKeys.spec.js
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/ConversationAction.vue
  app/javascript/dashboard/routes/dashboard/conversation/labels/LabelBox.vue
  app/javascript/dashboard/store/modules/conversations/index.js
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#3386 chore: Prevent notification email loop
  app/mailboxes/mailbox_helper.rb
  app/mailboxes/support_mailbox.rb
  spec/fixtures/files/notification.eml
  spec/mailboxes/support_mailbox_spec.rb
Labels: PR: reviewed-approved

#3387 fix: Set cc, bcc default to empty string if unavailable
  app/javascript/dashboard/api/inbox/message.js
  app/javascript/dashboard/api/specs/inbox/message.spec.js
Labels: PR: unreviewed

#3400 chore: Add the support for list and checkbox in custom attribute model
  app/models/custom_attribute_definition.rb
  db/migrate/20211116131740_add_values_to_custom_attribute_definitions.rb
  db/schema.rb
Labels: PR: unreviewed

#3385 Feat: Include previous messages in mention/assign notifications email
  app/drops/conversation_drop.rb
  app/models/conversation.rb
  app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_assignment.liquid
  app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_mention.liquid
  spec/models/conversation_spec.rb
Labels: PR: reviewed-approved

#3406 fix: Set default value of sortBy to empty string
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
Labels: PR: reviewed-approved

#3394 Fix: Make swagger doc compliant to OpenAPI
  .circleci/config.yml
  swagger/definitions/request/contact/create.yml
  swagger/definitions/request/conversation/create_message.yml
  swagger/definitions/resource/conversation.yml
  swagger/definitions/resource/custom_filter.yml
  swagger/definitions/resource/integrations/app.yml
  swagger/definitions/resource/public/conversation.yml
  swagger/definitions/resource/public/message.yml
  swagger/index.yml
  swagger/parameters/account_id.yml
  swagger/parameters/agent_bot_id.yml
  swagger/parameters/contact_sort.yml
  swagger/parameters/conversation_id.yml
  swagger/parameters/custom_filter_id.yml
  swagger/parameters/hook_id.yml
  swagger/parameters/inbox_id.yml
  swagger/parameters/message_id.yml
  swagger/parameters/page.yml
  swagger/parameters/platform_user_id.yml
  swagger/parameters/public/contact_identifier.yml
  swagger/parameters/public/inbox_identifier.yml
  swagger/parameters/report_metric.yml
  swagger/parameters/report_type.yml
  swagger/parameters/source_id.yml
  swagger/parameters/team_id.yml
  swagger/paths/application/agent_bots/index.yml
  swagger/paths/application/agents/create.yml
  swagger/paths/application/agents/delete.yml
  swagger/paths/application/agents/update.yml
  swagger/paths/application/contact_inboxes/create.yml
  swagger/paths/application/contacts/crud.yml
  swagger/paths/application/conversation/create.yml
  swagger/paths/application/conversation/filter.yml
  swagger/paths/application/conversation/index.yml
  swagger/paths/application/conversation/labels/create.yml
  swagger/paths/application/conversation/messages/create_attachment.yml
  swagger/paths/application/conversation/messages/index.yml
  swagger/paths/application/conversation/toggle_status.yml
  swagger/paths/application/inboxes/create.yml
  swagger/paths/application/inboxes/inbox_members/create.yml
  swagger/paths/application/inboxes/inbox_members/delete.yml
  swagger/paths/application/inboxes/inbox_members/update.yml
  swagger/paths/application/inboxes/set_agent_bot.yml
  swagger/paths/application/inboxes/update.yml
  swagger/paths/index.yml
  swagger/paths/platform/account_users/create.yml
  swagger/paths/platform/account_users/delete.yml
  swagger/paths/platform/users/login.yml
  swagger/paths/public/inboxes/contacts/create.yml
  swagger/paths/public/inboxes/contacts/show.yml
  swagger/paths/public/inboxes/contacts/update.yml
  swagger/paths/public/inboxes/conversations/create.yml
  swagger/paths/public/inboxes/messages/create.yml
  swagger/paths/public/inboxes/messages/update.yml
  swagger/swagger.json
Labels: PR: unreviewed

#3403 Fix 3396: Mention the env variables SMTP_TLS and SMTP_SSL in .env.example
  .env.example
Labels: PR: unreviewed

#3249 Chore: Replaced dependent: destroy with dependent: :destroy_async in all models
  app/models/account.rb
  app/models/agent_bot.rb
  app/models/concerns/access_tokenable.rb
  app/models/concerns/channelable.rb
  app/models/concerns/out_of_offisable.rb
  app/models/concerns/reportable.rb
  app/models/contact.rb
  app/models/contact_inbox.rb
  app/models/conversation.rb
  app/models/inbox.rb
  app/models/kbase/category.rb
  app/models/kbase/portal.rb
  app/models/message.rb
  app/models/platform_app.rb
  app/models/platform_app_permissible.rb
  app/models/team.rb
  app/models/telegram_bot.rb
  app/models/user.rb
  spec/models/account_spec.rb
  spec/models/channel/facebook_page_spec.rb
  spec/models/contact_spec.rb
  spec/models/inbox_spec.rb
  spec/models/user_spec.rb
Labels: PR: unreviewed

#3410 feat: Add automation route
  app/javascript/dashboard/i18n/locale/en/automation.json
  app/javascript/dashboard/i18n/locale/en/index.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/i18n/sidebarItems/settings.js
  app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/automation.routes.js
Labels: PR: reviewed-approved

#3402 feat: Remove ionicons v2 dependency on widget
  app/javascript/shared/components/CustomerSatisfaction.vue
  app/javascript/shared/components/FluentIcon/Index.vue
  app/javascript/shared/components/FluentIcon/icons.json
  app/javascript/survey/assets/scss/woot.scss
  app/javascript/widget/assets/scss/_utilities.scss
  app/javascript/widget/assets/scss/_variables.scss
  app/javascript/widget/assets/scss/woot.scss
  app/javascript/widget/components/ChatAttachment.vue
  app/javascript/widget/components/ChatInputWrap.vue
  app/javascript/widget/components/ChatSendButton.vue
  app/javascript/widget/components/FileBubble.vue
  app/javascript/widget/components/HeaderActions.vue
  app/javascript/widget/components/template/Article.vue
  app/javascript/widget/components/template/EmailInput.vue
  app/javascript/widget/views/Unread.vue
Labels: PR: unreviewed

#3413 choore: Change `values` to `attribute_values` in custom attributes
  app/controllers/api/v1/accounts/custom_attribute_definitions_controller.rb
  app/models/custom_attribute_definition.rb
  app/views/api/v1/models/_custom_attribute_definition.json.jbuilder
  db/migrate/20211118100301_change_values_to_attribute_values_in_custom_attribute_definitions.rb
  db/schema.rb
Labels: PR: reviewed-approved

#3239 feat: Add advanced Conversation Filters
  .codeclimate.yml
  app/javascript/dashboard/api/inbox/conversation.js
  app/javascript/dashboard/api/specs/inbox/conversation.spec.js
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/assets/scss/widgets/_modal.scss
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationAdvancedFilter.vue
  app/javascript/dashboard/components/widgets/conversation/advancedFilterItems/countries.js
  app/javascript/dashboard/components/widgets/conversation/advancedFilterItems/index.js
  app/javascript/dashboard/components/widgets/conversation/advancedFilterItems/languages.js
  app/javascript/dashboard/components/widgets/conversation/components/FilterInput.vue
  app/javascript/dashboard/helper/filterQueryGenerator.js
  app/javascript/dashboard/helper/specs/filterQueryGenerator.spec.js
  app/javascript/dashboard/i18n/locale/en/advancedFilters.json
  app/javascript/dashboard/i18n/locale/en/index.js
  app/javascript/dashboard/store/modules/campaigns.js
  app/javascript/dashboard/store/modules/conversationPage.js
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/getters.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/modules/specs/campaigns/getters.spec.js
  app/javascript/dashboard/store/modules/specs/conversationPage/mutations.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/getters.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/testConversationResponse.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/shared/assets/stylesheets/font-size.scss
  app/javascript/shared/assets/stylesheets/spacing.scss
  app/javascript/shared/assets/stylesheets/z-index.scss
Labels: frontend, feature, PR: unreviewed, PR: reviewed-changes-requested

#3411 chore: Update dropdown z-index to be on top of contact details pane
  app/javascript/dashboard/assets/scss/plugins/_dropdown.scss
  app/javascript/shared/assets/stylesheets/z-index.scss
Labels: PR: reviewed-approved

#3418 Fix: Filter with label name
  app/services/conversations/filter_service.rb
  spec/services/conversations/filter_service_spec.rb
Labels: PR: reviewed-approved

#3422 chore: Move unscoped styles to global stylesheet
  app/javascript/widget/assets/scss/views/_conversation.scss
  app/javascript/widget/assets/scss/woot.scss
  app/javascript/widget/components/AgentMessage.vue
  app/javascript/widget/components/AgentMessageBubble.vue
  app/javascript/widget/components/ChatAttachment.vue
  app/javascript/widget/components/ConversationWrap.vue
  app/javascript/widget/components/UserMessage.vue
  app/javascript/widget/components/UserMessageBubble.vue
  app/javascript/widget/views/Unread.vue
Labels: PR: reviewed-approved

#3344 feat: Updates widget conversation state to support multiple conversations
  app/javascript/widget/store/modules/conversation/actions.js
  app/javascript/widget/store/modules/conversation/getters.js
  app/javascript/widget/store/modules/conversation/helpers.js
  app/javascript/widget/store/modules/conversation/index.js
  app/javascript/widget/store/modules/conversation/mutations.js
Labels: PR: partially-approved

#3345 feat: Updates widget contact state to support multiple conversations
  app/javascript/widget/store/modules/contact/index.js
Labels: PR: unreviewed

#3346 feat: Updates widget message state to support multiple conversations
  app/javascript/widget/store/modules/message.js
  app/javascript/widget/store/modules/message/actions.js
  app/javascript/widget/store/modules/message/getters.js
  app/javascript/widget/store/modules/message/helpers.js
  app/javascript/widget/store/modules/message/index.js
  app/javascript/widget/store/modules/message/mutations.js
Labels: PR: unreviewed

#3432 fix: Pass label title instead of id to filter API
  app/javascript/dashboard/components/widgets/conversation/ConversationAdvancedFilter.vue
Labels: PR: partially-approved

#3421 chore: add DigitialOcean 1-click deployment button
  README.md
Labels: PR: unreviewed

#3433 chore: Move referrerHost to appConfig store
  app/javascript/sdk/IFrameHelper.js
  app/javascript/sdk/bubbleHelpers.js
  app/javascript/shared/components/Branding.vue
  app/javascript/shared/constants/busEvents.js
  app/javascript/widget/App.vue
  app/javascript/widget/helpers/IframeEventHelper.js
  app/javascript/widget/store/modules/appConfig.js
  app/javascript/widget/store/modules/specs/appConfig/actions.spec.js
  app/javascript/widget/store/modules/specs/appConfig/getters.spec.js
  app/javascript/widget/store/modules/specs/appConfig/mutations.spec.js
  app/javascript/widget/store/types.js
Labels: PR: unreviewed

#3434 chore: Migrate PubSub Token to contact inbox
  app/actions/contact_merge_action.rb
  app/channels/room_channel.rb
  app/controllers/widgets_controller.rb
  app/finders/conversation_finder.rb
  app/javascript/dashboard/assets/scss/_utility-helpers.scss
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
  app/javascript/widget/helpers/actionCable.js
  app/javascript/widget/helpers/campaignHelper.js
  app/javascript/widget/helpers/specs/campaignHelper.spec.js
  app/javascript/widget/store/modules/contacts.js
  app/javascript/widget/store/modules/conversation/actions.js
  app/javascript/widget/store/modules/message.js
  app/listeners/action_cable_listener.rb
  app/models/concerns/pubsubable.rb
  app/models/contact.rb
  app/models/contact_inbox.rb
  app/presenters/conversations/event_data_presenter.rb
  app/views/api/v1/conversations/partials/_conversation.json.jbuilder
  app/views/api/v1/widget/configs/create.json.jbuilder
  app/views/public/api/v1/inboxes/contacts/create.json.jbuilder
  app/views/public/api/v1/inboxes/contacts/show.json.jbuilder
  app/views/public/api/v1/inboxes/contacts/update.json.jbuilder
  app/views/public/api/v1/models/_contact.json.jbuilder
  app/views/widgets/show.html.erb
  config/app.yml
  db/migrate/20211122061012_add_pub_sub_token_to_contact_inbox.rb
  db/schema.rb
  package.json
  spec/channels/room_channel_spec.rb
  spec/controllers/api/v1/widget/configs_controller_spec.rb
  spec/controllers/public/api/v1/inbox/contacts_controller_spec.rb
  spec/listeners/action_cable_listener_spec.rb
  spec/models/contact_inbox_spec.rb
  spec/models/contact_spec.rb
  spec/models/conversation_spec.rb
  spec/presenters/conversations/event_data_presenter_spec.rb
Labels: PR: unreviewed

#3442 fix: Required check for Conversation filters
  app/javascript/dashboard/components/widgets/conversation/ConversationAdvancedFilter.vue
Labels: PR: partially-approved

#3447 fix: Link in campaign editor
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
Labels: PR: partially-approved

#3438 Update schema files
  db/migrate/20211122112607_remove_invalid_migration.rb
  db/schema.rb
Labels: PR: unreviewed

#3435 Feat: Added support changes for contact filters
  lib/filters/filter_keys.json
  spec/services/contacts/filter_service_spec.rb
Labels: PR: reviewed-approved

#3445 fix: Use role permissions from accounts instead of role attribute
  app/javascript/dashboard/routes/index.js
  app/javascript/dashboard/routes/index.spec.js
  app/javascript/dashboard/store/modules/auth.js
Labels: PR: unreviewed

#3439 feat: Adds support for List and Checkbox type in Custom Attributes
  app/javascript/dashboard/components/CustomAttribute.vue
  app/javascript/dashboard/i18n/locale/en/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/conversation/customAttributes/CustomAttributes.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/AddAttribute.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/EditAttribute.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/constants.js
  app/javascript/shared/components/ui/MultiselectDropdown.vue
  app/javascript/shared/components/ui/MultiselectDropdownItems.vue
Labels: PR: partially-approved

#3453 fix: Render checkbox if string value passed
  app/javascript/dashboard/components/CustomAttribute.vue
Labels: PR: reviewed-approved

#3456 Fix: contact filter values
  app/services/contacts/filter_service.rb
Labels: PR: reviewed-approved

#3423 fix: Refactors code and design improvements for filters
  app/javascript/dashboard/assets/scss/_foundation-custom.scss
  app/javascript/dashboard/assets/scss/widgets/_buttons.scss
  app/javascript/dashboard/assets/scss/widgets/_modal.scss
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/Modal.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationAdvancedFilter.vue
  app/javascript/dashboard/components/widgets/conversation/components/FilterInput.vue
  app/javascript/dashboard/i18n/locale/en/advancedFilters.json
  app/javascript/shared/assets/stylesheets/font-size.scss
  app/javascript/shared/assets/stylesheets/spacing.scss
Labels: PR: reviewed-approved, on-hold

#3369 feat: migrate facebook env vars to globalConfig
  app/controllers/api/v1/accounts/callbacks_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/webhooks/instagram_controller.rb
  app/models/installation_config.rb
  app/services/instagram/send_on_instagram_service.rb
  config/initializers/facebook_messenger.rb
  lib/integrations/facebook/message_parser.rb
  spec/lib/vapid_service_spec.rb
Labels: PR: unreviewed

#3463 Feat: Fix contact filter pagination
  app/controllers/api/v1/accounts/contacts_controller.rb
Labels: PR: reviewed-approved

#3390 Enhancement: Show unread marker
  app/javascript/sdk/IFrameHelper.js
  app/javascript/sdk/sdk.js
  app/javascript/widget/App.vue
Labels: PR: reviewed-approved

#3466 chore: fixes filter input multiselect height issue
  app/javascript/dashboard/components/widgets/conversation/components/FilterInput.vue
Labels: PR: partially-approved

#3469 Chore: API Improvements
  .rubocop.yml
  app/controllers/api/v1/accounts/canned_responses_controller.rb
  app/presenters/agent_bot_presenter.rb
  app/views/api/v1/accounts/agent_bots/create.json.jbuilder
  app/views/api/v1/accounts/agent_bots/index.json.jbuilder
  app/views/api/v1/accounts/agent_bots/show.json.jbuilder
  app/views/api/v1/accounts/agent_bots/update.json.jbuilder
  app/views/api/v1/models/_agent_bot.json.jbuilder
  app/views/platform/api/v1/models/_agent_bot.json.jbuilder
  db/seeds.rb
  lib/seeders/account_seeder.rb
  lib/seeders/message_seeder.rb
  spec/controllers/api/v1/accounts/agent_bots_controller_spec.rb
Labels: PR: unreviewed

#3156 feat: ability to remove user profile picture
  app/controllers/api/v1/profiles_controller.rb
  app/javascript/dashboard/api/auth.js
  app/javascript/dashboard/api/endPoints.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
  app/javascript/dashboard/store/modules/auth.js
  app/javascript/dashboard/store/modules/specs/auth/actions.spec.js
  config/routes.rb
  spec/controllers/api/v1/profiles_controller_spec.rb
Labels: PR: unreviewed

#3365 Display account id in account settings
  app/javascript/dashboard/i18n/locale/ar/generalSettings.json
  app/javascript/dashboard/i18n/locale/ca/generalSettings.json
  app/javascript/dashboard/i18n/locale/cs/generalSettings.json
  app/javascript/dashboard/i18n/locale/da/generalSettings.json
  app/javascript/dashboard/i18n/locale/de/generalSettings.json
  app/javascript/dashboard/i18n/locale/el/generalSettings.json
  app/javascript/dashboard/i18n/locale/en/generalSettings.json
  app/javascript/dashboard/i18n/locale/es/generalSettings.json
  app/javascript/dashboard/i18n/locale/fa/generalSettings.json
  app/javascript/dashboard/i18n/locale/fi/generalSettings.json
  app/javascript/dashboard/i18n/locale/fr/generalSettings.json
  app/javascript/dashboard/i18n/locale/he/generalSettings.json
  app/javascript/dashboard/i18n/locale/hi/generalSettings.json
  app/javascript/dashboard/i18n/locale/hu/generalSettings.json
  app/javascript/dashboard/i18n/locale/id/generalSettings.json
  app/javascript/dashboard/i18n/locale/it/generalSettings.json
  app/javascript/dashboard/i18n/locale/ja/generalSettings.json
  app/javascript/dashboard/i18n/locale/ko/generalSettings.json
  app/javascript/dashboard/i18n/locale/ml/generalSettings.json
  app/javascript/dashboard/i18n/locale/ne/generalSettings.json
  app/javascript/dashboard/i18n/locale/nl/generalSettings.json
  app/javascript/dashboard/i18n/locale/no/generalSettings.json
  app/javascript/dashboard/i18n/locale/pl/generalSettings.json
  app/javascript/dashboard/i18n/locale/pt/generalSettings.json
  app/javascript/dashboard/i18n/locale/pt_BR/generalSettings.json
  app/javascript/dashboard/i18n/locale/ro/generalSettings.json
  app/javascript/dashboard/i18n/locale/ru/generalSettings.json
  app/javascript/dashboard/i18n/locale/sk/generalSettings.json
  app/javascript/dashboard/i18n/locale/sv/generalSettings.json
  app/javascript/dashboard/i18n/locale/ta/generalSettings.json
  app/javascript/dashboard/i18n/locale/th/generalSettings.json
  app/javascript/dashboard/i18n/locale/tr/generalSettings.json
  app/javascript/dashboard/i18n/locale/uk/generalSettings.json
  app/javascript/dashboard/i18n/locale/vi/generalSettings.json
  app/javascript/dashboard/i18n/locale/zh/generalSettings.json
  app/javascript/dashboard/i18n/locale/zh_CN/generalSettings.json
  app/javascript/dashboard/i18n/locale/zh_TW/generalSettings.json
  app/javascript/dashboard/routes/dashboard/settings/account/Index.vue
Labels: PR: unreviewed, on-hold

#3405 Chore: Improve conversation auto resolution
  app/jobs/account/conversations_resolution_scheduler_job.rb
  app/jobs/auto_resolve_conversations_job.rb
  app/jobs/conversations/resolution_job.rb
  app/jobs/trigger_scheduled_items_job.rb
  app/models/concerns/activity_message_handler.rb
  app/models/conversation.rb
  spec/jobs/account/conversations_resolution_scheduler_job_spec.rb
  spec/jobs/auto_resolve_conversations_job_spec.rb
  spec/jobs/conversations/resolution_job_spec.rb
  spec/jobs/trigger_scheduled_items_job_spec.rb
  spec/models/conversation_spec.rb
Labels: PR: unreviewed

#3393 Fix: Outgoing email sender header translation issue
  app/mailers/conversation_reply_mailer.rb
  config/locales/en.yml
Labels: PR: unreviewed

#3414 Feat: Include recent customer messages for new conversation
  app/drops/conversation_drop.rb
  app/drops/inbox_drop.rb
  app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_creation.liquid
Labels: PR: unreviewed

#3473 chore: fix scheduled jobs
  config/schedule.yml
Labels: PR: unreviewed

#3478 fix: Use bus.$off to remove listeners on destroy
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/javascript/dashboard/components/SidemenuIcon.vue
  app/javascript/dashboard/components/SnackbarContainer.vue
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/routes/dashboard/Dashboard.vue
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
  app/javascript/shared/constants/busEvents.js
Labels: PR: reviewed-approved

#3479 chore: Whatsapp templates fix for 360 dialog
  app/builders/contact_inbox_builder.rb
  app/models/channel/whatsapp.rb
  app/services/whatsapp/send_on_whatsapp_service.rb
  db/migrate/20211129120040_add_templates_to_whatsapp_channel.rb
  db/schema.rb
  spec/factories/channel/channel_whatsapp.rb
  spec/services/whatsapp/send_on_whatsapp_service_spec.rb
Labels: PR: unreviewed

#3480 chore: validation spec for schedules
  config/schedule.yml
  spec/configs/schedule_spec.rb
Labels: PR: unreviewed

#3481 fix: Update missing method onNewToastMessage
  app/javascript/dashboard/components/SnackbarContainer.vue
Labels: PR: unreviewed
