Repository chatwoot/chatwoot, pull requests merged in 2021-12, with the labels that each got.

#3416 feat: Updates sidebar to accomodate sub menu
  app/javascript/dashboard/assets/scss/_animations.scss
  app/javascript/dashboard/assets/scss/_foundation-custom.scss
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/assets/scss/_variables.scss
  app/javascript/dashboard/assets/scss/plugins/_dropdown.scss
  app/javascript/dashboard/assets/scss/views/settings/inbox.scss
  app/javascript/dashboard/assets/scss/widgets/_sidemenu.scss
  app/javascript/dashboard/components/layout/AvailabilityStatus.vue
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/SidebarItem.vue
  app/javascript/dashboard/components/layout/sidebarComponents/AgentDetails.vue
  app/javascript/dashboard/components/layout/sidebarComponents/NotificationBell.vue
  app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue
  app/javascript/dashboard/components/layout/sidebarComponents/specs/AgentDetails.spec.js
  app/javascript/dashboard/components/layout/sidebarComponents/specs/NotificationBell.spec.js
  app/javascript/dashboard/components/layout/specs/AvailabilityStatus.spec.js
  app/javascript/dashboard/components/widgets/Thumbnail.vue
  app/javascript/dashboard/components/widgets/conversation/AvailabilityStatusBadge.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/File.vue
  app/javascript/dashboard/i18n/default-sidebar.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/i18n/sidebarItems/campaigns.js
  app/javascript/dashboard/i18n/sidebarItems/common.js
  app/javascript/dashboard/i18n/sidebarItems/notifications.js
  app/javascript/dashboard/i18n/sidebarItems/reports.js
  app/javascript/dashboard/modules/sidebar/components/Logo.vue
  app/javascript/dashboard/modules/sidebar/components/Primary.vue
  app/javascript/dashboard/modules/sidebar/components/PrimaryNavItem.vue
  app/javascript/dashboard/modules/sidebar/components/Secondary.vue
  app/javascript/dashboard/modules/sidebar/components/SecondaryNavItem.vue
  app/javascript/dashboard/modules/sidebar/mixins/routes.mixin.js
  app/javascript/dashboard/routes/dashboard/Dashboard.vue
  app/javascript/shared/assets/stylesheets/colors.scss
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/javascript/shared/components/ui/dropdown/DropdownDivider.vue
  app/javascript/shared/components/ui/dropdown/DropdownHeader.vue
  app/javascript/shared/components/ui/dropdown/DropdownItem.vue
Labels: PR: unreviewed

#3483 fix: Changes thumbnail colors to new color scheme
  app/javascript/dashboard/components/Accordion/AccordionItem.vue
  app/javascript/dashboard/components/widgets/Avatar.vue
  app/javascript/dashboard/components/widgets/Thumbnail.vue
  app/javascript/dashboard/routes/dashboard/conversation/ConversationInfo.vue
  app/javascript/dashboard/routes/dashboard/conversation/customAttributes/CustomAttributes.vue
  app/javascript/shared/assets/stylesheets/colors.scss
Labels: PR: partially-approved

#3494 chore: Fixes issue with reply box
  app/javascript/dashboard/components/widgets/conversation/MoreActions.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: unreviewed

#3496 chore: Add survey pack translation in crowdin
  crowdin.yml
Labels: PR: reviewed-approved

#3499 fix: Update route permissions in the new primary menu
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/config/default-sidebar.js
  app/javascript/dashboard/components/layout/config/sidebarItems/campaigns.js
  app/javascript/dashboard/components/layout/config/sidebarItems/contacts.js
  app/javascript/dashboard/components/layout/config/sidebarItems/conversations.js
  app/javascript/dashboard/components/layout/config/sidebarItems/notifications.js
  app/javascript/dashboard/components/layout/config/sidebarItems/primaryMenu.js
  app/javascript/dashboard/components/layout/config/sidebarItems/profileSettings.js
  app/javascript/dashboard/components/layout/config/sidebarItems/reports.js
  app/javascript/dashboard/components/layout/config/sidebarItems/settings.js
  app/javascript/dashboard/components/layout/sidebarComponents/Logo.vue
  app/javascript/dashboard/components/layout/sidebarComponents/NotificationBell.vue
  app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue
  app/javascript/dashboard/components/layout/sidebarComponents/Primary.vue
  app/javascript/dashboard/components/layout/sidebarComponents/PrimaryNavItem.vue
  app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryChildNavItem.vue
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/i18n/default-sidebar.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/i18n/sidebarItems/common.js
  app/javascript/dashboard/modules/sidebar/mixins/routes.mixin.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: PR: unreviewed

#3502 bug: Fixes missing icon of Twillio SMS channel.
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: PR: partially-approved

#3500 Fix: Update contact validation messages
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/controllers/concerns/request_exception_handler.rb
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactForm.vue
  app/javascript/dashboard/store/modules/contacts/actions.js
  app/javascript/dashboard/store/modules/specs/contacts/actions.spec.js
  app/javascript/shared/helpers/specs/CustomErrors.spec.js
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
Labels: PR: reviewed-approved

#3509 fix: Conversation status change event in web widget
  app/listeners/action_cable_listener.rb
Labels: PR: unreviewed

#3506 bug: Fixes cannot copy text content from sidebar
  app/javascript/dashboard/components/Accordion/AccordionItem.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
Labels: PR: partially-approved

#3507 enhancement: Improves sidebar open/close toggle design
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: PR: partially-approved

#3512 fix: Fixes sidebar toggle icon breaking message view
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
Labels: PR: unreviewed

#3516 fix: Index custom attribute uniqueness on account
  app/models/custom_attribute_definition.rb
  db/migrate/20211207113102_remove_attribute_key_index_on_custom_attribute_definition.rb
  db/schema.rb
Labels: PR: unreviewed

#3515 fix: Fixes cc bcc being sent when mail head is empty
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyEmailHead.vue
Labels: PR: unreviewed

#3514 chore: Updates icon for network disconnect alert
  app/javascript/dashboard/components/NetworkNotification.vue
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: PR: unreviewed

#3524 bug: Fixes throwing error with secondary sidebar while switching to profile settings
  app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue
Labels: PR: partially-approved

#3518 Fix: Added facebook login scope with new advanced access for page read
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Facebook.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/facebook/Reauthorize.vue
Labels: PR: reviewed-approved

#3527 Fix: Add foreign key with delete cascade for destroy_async
  db/migrate/20211208085931_update_contact_inbox_foreign_key.rb
  db/schema.rb
Labels: PR: unreviewed

#3526 chore: Add the ability to use same key for conversation and contact
  app/models/custom_attribute_definition.rb
  db/migrate/20211208081344_add_attribute_model_index_on_custom_attribute_definition.rb
  db/schema.rb
Labels: PR: reviewed-approved

#3525 chore: Fix pre-commit hooks
  .eslintrc.js
  .husky/pre-commit
  .husky/pre-push
  app/javascript/dashboard/components/Snackbar.vue
  app/javascript/dashboard/components/ui/Switch.vue
  app/javascript/dashboard/components/widgets/EmptyState.vue
  app/javascript/dashboard/components/widgets/LoadingState.vue
  app/javascript/dashboard/components/widgets/conversation/OnboardingView.vue
  app/javascript/dashboard/components/widgets/forms/AvatarUploader.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Line.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Sms.vue
  app/javascript/dashboard/routes/dashboard/settings/profile/NotificationSettings.vue
  app/javascript/dashboard/routes/login/Login.vue
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/shared/components/GreetingsEditor.vue
  app/javascript/shared/components/TextArea.vue
  package.json
  yarn.lock
Labels: PR: unreviewed

#3519 Chore: Improve confirmation flow for agents
  app/controllers/devise_overrides/confirmations_controller.rb
  app/views/devise/mailer/confirmation_instructions.html.erb
  spec/mailers/confirmation_instructions_spec.rb
Labels: PR: unreviewed

#3505 feat: Add a view for mentions
  app/finders/conversation_finder.rb
  app/javascript/dashboard/api/inbox/conversation.js
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/layout/config/sidebarItems/conversations.js
  app/javascript/dashboard/components/specs/SidemenuIcon.spec.js
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/components/widgets/conversation/specs/MoreActions.spec.js
  app/javascript/dashboard/helper/URLHelper.js
  app/javascript/dashboard/helper/actionCable.js
  app/javascript/dashboard/i18n/locale/en/chatlist.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
  app/javascript/dashboard/routes/dashboard/conversation/conversation.routes.js
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/helpers/actionHelpers.js
  app/javascript/dashboard/store/modules/conversations/helpers/specs/actionHelpers.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/jobs/conversations/user_mention_job.rb
  app/listeners/action_cable_listener.rb
  app/listeners/notification_listener.rb
  app/models/account.rb
  app/models/conversation.rb
  app/models/mention.rb
  app/models/user.rb
  db/migrate/20211201224513_create_mentions.rb
  db/schema.rb
  lib/events/types.rb
Labels: PR: unreviewed

#3522 fix: Add fixes for sentry errors
  app/controllers/api/v1/widget/contacts_controller.rb
  app/drops/conversation_drop.rb
  app/drops/message_drop.rb
  app/helpers/message_format_helper.rb
  app/javascript/dashboard/components/widgets/conversation/MoreActions.vue
  app/javascript/sdk/IFrameHelper.js
  app/views/api/v1/widget/contacts/update.json.jbuilder
  app/views/layouts/mailer/base.liquid
  app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_mention.liquid
  spec/controllers/api/v1/widget/contacts_controller_spec.rb
  spec/helpers/message_format_helper_spec.rb
Labels: PR: unreviewed

#3209 chore: Introduce enterprise edition, license
  LICENSE
  app/controllers/api/v1/accounts/agents_controller.rb
  app/controllers/concerns/request_exception_handler.rb
  app/models/account.rb
  config/application.rb
  config/initializers/01_inject_enterprise_edition_module.rb
  db/migrate/20211012135050_add_limits_to_accounts.rb
  db/schema.rb
  enterprise/LICENSE
  enterprise/app/models/enterprise/account.rb
  enterprise/lib/enterprise.rb
  lib/chatwoot_app.rb
  lib/custom_exceptions/account.rb
  spec/enterprise/models/account_spec.rb
  spec/models/account_spec.rb
Labels: PR: unreviewed

#3535 Updates Enterprise Licence
  enterprise/LICENSE
Labels: PR: reviewed-approved

#3451 Fix: fixing mail to and in_reply_to issues
  app/mailboxes/application_mailbox.rb
  app/mailboxes/reply_mailbox.rb
  app/presenters/mail_presenter.rb
  spec/fixtures/files/forwarder_email.eml
  spec/fixtures/files/in_reply_to.eml
  spec/mailboxes/application_mailbox_spec.rb
  spec/mailboxes/reply_mailbox_spec.rb
Labels: PR: unreviewed

#3537 bug: Fixes expanded reply box is not closing after the message is sent
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: unreviewed

#3552 add line messenger in readme
  README.md
Labels: PR: unreviewed

#3555 Chore: Fixes icon size in button
  app/javascript/dashboard/assets/scss/widgets/_buttons.scss
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/buttons/ResolveAction.vue
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/components/ui/WootButton.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyTopPanel.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationAdvancedFilter.vue
  app/javascript/dashboard/components/widgets/conversation/MoreActions.vue
  app/javascript/dashboard/modules/conversations/components/MessageContextMenu.vue
  app/javascript/dashboard/modules/notes/components/ContactNote.vue
  app/javascript/dashboard/routes/dashboard/conversation/ConversationAction.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfoRow.vue
Labels: PR: unreviewed

#3528 feat: allow users to select components to install when using linux script
  deployment/setup_20.04.sh
Labels: PR: reviewed-approved

#3566 fix: Fixes wrong color for note tab in reply box
  app/javascript/dashboard/assets/scss/widgets/_buttons.scss
  app/javascript/dashboard/components/widgets/WootWriter/ReplyTopPanel.vue
Labels: PR: unreviewed

#3582 Fix: Add max retries for all jobs
  Gemfile.lock
  app/jobs/inboxes/fetch_imap_emails_job.rb
  app/workers/email_reply_worker.rb
  config/schedule.yml
  config/sidekiq.yml
Labels: PR: reviewed-approved

#3562 bug: Fixes space missing issue with message bubbles after sending mes…
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
Labels: PR: unreviewed

#3353 Feat: Manage conversation for tweets based on the tweet flag
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/models/channel/twitter_profile.rb
  app/models/inbox.rb
  app/services/twitter/tweet_parser_service.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  db/migrate/20211109143122_add_tweet_enabled_flag_to_twitter_channel.rb
  db/schema.rb
  lib/webhooks/twitter.rb
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
  spec/lib/webhooks/twitter_spec.rb
Labels: PR: unreviewed

#3553 enhancement: Changes button design for tables in settings page
  app/javascript/dashboard/assets/scss/_foundation-custom.scss
  app/javascript/dashboard/routes/dashboard/settings/agents/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/CustomAttribute.vue
  app/javascript/dashboard/routes/dashboard/settings/canned/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/integrationapps/MultipleIntegrationHooks.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/Webhook.vue
  app/javascript/dashboard/routes/dashboard/settings/labels/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/teams/Index.vue
Labels: PR: unreviewed

#3593 bug: Fixes irregular padding on agent selector in report page
  app/javascript/dashboard/assets/scss/plugins/_multiselect.scss
  app/javascript/dashboard/assets/scss/widgets/_reports.scss
  app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue
Labels: PR: unreviewed

#3613 chore: Clean up migrations
  .rubocop.yml
  app/models/account_user.rb
  app/models/agent_bot.rb
  app/models/campaign.rb
  app/models/contact_inbox.rb
  app/models/conversation.rb
  app/models/csat_survey_response.rb
  app/models/data_import.rb
  app/models/mention.rb
  app/models/note.rb
  app/models/team.rb
  app/models/team_member.rb
  db/migrate/20211219031453_update_foreign_keys_on_delete.rb
  db/schema.rb
Labels: PR: unreviewed

#3571 chore: Contact builder ignores custom attributes
  app/builders/contact_builder.rb
  spec/builders/contact_builder_spec.rb
Labels: PR: unreviewed

#3614 chore: Enable Slovak Language
  config/initializers/languages.rb
Labels: PR: unreviewed

#3610 bug: Fixes pressing enter key not submitting email in widget.
  app/javascript/widget/components/template/EmailInput.vue
Labels: PR: unreviewed

#3630 Fix: Editable attrs presence check for the channel class
  app/controllers/api/v1/accounts/inboxes_controller.rb
Labels: PR: reviewed-approved

#3557 chore: allow more filetypes in uploads
  app/helpers/file_type_helper.rb
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Image.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/shared/constants/messages.js
  app/javascript/widget/components/ChatAttachment.vue
  app/models/attachment.rb
Labels: PR: unreviewed

#3585 feat: Show errors for message bubbles
  .codeclimate.yml
  app/javascript/dashboard/components/ui/WootButton.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: PR: unreviewed

#3604 bug: Fixes issue towards animated running numbers
  app/javascript/dashboard/components/ui/Tabs/TabsItem.vue
  package.json
  yarn.lock
Labels: PR: unreviewed

#3594 feat: Shows error message with retry for messages
  app/javascript/shared/components/FluentIcon/icons.json
  app/javascript/widget/assets/scss/views/_conversation.scss
  app/javascript/widget/components/AgentMessage.vue
  app/javascript/widget/components/ImageBubble.vue
  app/javascript/widget/components/UserMessage.vue
  app/javascript/widget/i18n/locale/en.json
  app/javascript/widget/store/modules/conversation/actions.js
  app/javascript/widget/store/modules/conversation/mutations.js
  app/javascript/widget/store/modules/specs/conversation/actions.spec.js
Labels: PR: unreviewed

#3635 chore: Add display id in conversation related push payload
  app/models/notification.rb
  spec/models/notification_spec.rb
Labels: PR: unreviewed

#3637 chore: API improvements
  app/controllers/api/v1/accounts/inbox_members_controller.rb
  app/controllers/api/v1/accounts/team_members_controller.rb
  app/dispatchers/async_dispatcher.rb
  app/dispatchers/sync_dispatcher.rb
  app/jobs/inboxes/fetch_imap_email_inboxes_job.rb
  app/models/concerns/activity_message_handler.rb
  app/models/inbox_member.rb
  app/models/team_member.rb
  db/migrate/20211221125545_add_unique_index_on_inbox_members.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/inbox_members_controller_spec.rb
  spec/controllers/api/v1/accounts/team_members_controller_spec.rb
  spec/models/concerns/assignment_handler_shared.rb
Labels: PR: unreviewed

#3611 chore: Improve email parsing using email trimmer gem
  Gemfile
  Gemfile.lock
  app/presenters/html_parser.rb
  app/presenters/mail_presenter.rb
  spec/fixtures/files/mail_with_quote.eml
  spec/fixtures/files/welcome_html.eml
  spec/mailboxes/reply_mailbox_spec.rb
  spec/presenters/html_parser_spec.rb
  spec/presenters/mail_presenter_spec.rb
Labels: PR: unreviewed

#3641 bug: NoMethodError: undefined method `match' for in_reply_to
  app/mailboxes/reply_mailbox.rb
  spec/fixtures/files/forwarder_email.eml
  spec/fixtures/files/reply.eml
  spec/fixtures/files/reply_mail_without_uuid.eml
Labels: PR: unreviewed

#3645 chore: Minor API cleanups
  app/presenters/mail_presenter.rb
  lib/exception_list.rb
  spec/mailboxes/reply_mailbox_spec.rb
Labels: PR: unreviewed

#3654 chore: Fix `Eslint` warnings
  .eslintrc.js
  app/javascript/dashboard/components/Snackbar.vue
  app/javascript/dashboard/components/ui/Switch.vue
  app/javascript/dashboard/components/widgets/EmptyState.vue
  app/javascript/dashboard/components/widgets/LoadingState.vue
  app/javascript/dashboard/components/widgets/ReportStatsCard.vue
  app/javascript/dashboard/components/widgets/modal/DeleteModal.vue
  app/javascript/dashboard/routes/auth/PasswordEdit.vue
  app/javascript/dashboard/routes/dashboard/settings/SettingsSubPageHeader.vue
  app/javascript/dashboard/routes/dashboard/settings/Wrapper.vue
  app/javascript/dashboard/routes/dashboard/settings/canned/EditCanned.vue
  app/javascript/dashboard/routes/dashboard/settings/integrationapps/IntegrationItem.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/Integration.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/ShowIntegration.vue
  app/javascript/shared/components/GreetingsEditor.vue
  app/javascript/widget/components/ImageBubble.vue
  app/javascript/widget/components/UserAvatar.vue
Labels: PR: reviewed-approved

#3661 chore: Fix issue with conversation assignment notifications
  app/listeners/notification_listener.rb
  app/models/conversation.rb
  spec/models/concerns/assignment_handler_shared.rb
  spec/models/conversation_spec.rb
Labels: PR: unreviewed

#3665 feat: Adds multiple path support for icons
  app/javascript/shared/components/FluentIcon/DashboardIcon.vue
  app/javascript/shared/components/FluentIcon/Icon.vue
  app/javascript/shared/components/FluentIcon/Index.vue
Labels: PR: unreviewed

#3667 chore: Updates design of resolve context menu
  app/javascript/dashboard/components/buttons/ResolveAction.vue
  app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/javascript/shared/components/ui/dropdown/DropdownSubMenu.vue
Labels: PR: partially-approved
