Repository chatwoot/chatwoot, pull requests merged in 2022-09, with the labels that each got.

#5319 feat: Add the ability to delete/archive articles
  app/javascript/dashboard/api/helpCenter/articles.js
  app/javascript/dashboard/api/specs/article.spec.js
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalPopover.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ArticleSettings.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
  app/javascript/dashboard/store/modules/helpCenterArticles/actions.js
  app/javascript/dashboard/store/modules/helpCenterArticles/getters.js
  app/javascript/dashboard/store/modules/helpCenterArticles/specs/action.spec.js
Labels: PR: partially-approved

#5305 feat: Adds the ability to delete a portal
  app/javascript/dashboard/api/helpCenter/portals.js
  app/javascript/dashboard/assets/scss/widgets/_modal.scss
  app/javascript/dashboard/components/ModalHeader.vue
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/components/ui/WootButton.vue
  app/javascript/dashboard/components/widgets/modal/DeleteModal.vue
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
  app/javascript/dashboard/routes/dashboard/customviews/DeleteCustomViews.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/EditArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/ListAllPortals.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/PortalCustomization.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/PortalDetails.vue
  app/javascript/dashboard/routes/dashboard/settings/agents/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/canned/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/labels/Index.vue
  app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
Labels: PR: partially-approved

#5368 Fix/set default locale
  app/controllers/api/v1/accounts/portals_controller.rb
  app/models/portal.rb
Labels: PR: reviewed-approved

#5370 chore: Add feature flag for branding
  app/javascript/shared/components/Branding.vue
  app/javascript/widget/components/layouts/ViewWithHeader.vue
  app/views/widgets/show.html.erb
  config/features.yml
Labels: PR: unreviewed

#5318 feat: Displayed Identifier in the contacts info panel
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: PR: unreviewed

#5369 chore: Feature toggle for Account seeding
  app/views/super_admin/accounts/_seed_data.html.erb
Labels: PR: unreviewed

#5371 fix: Account seeder error on staging
  Gemfile
  app/controllers/super_admin/accounts_controller.rb
  app/jobs/internal/seed_account_job.rb
  app/views/super_admin/accounts/_seed_data.html.erb
  lib/seeders/account_seeder.rb
  lib/seeders/inbox_seeder.rb
  lib/seeders/seed_data.yml
Labels: PR: unreviewed

#5363 feat: Adds the ability to add new locale in portal
  app/javascript/dashboard/api/helpCenter/portals.js
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/AddLocale.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/AddPortal.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/EditArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/Sidebar.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/ListAllPortals.vue
  app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
  app/javascript/dashboard/store/modules/helpCenterPortals/specs/actions.spec.js
Labels: PR: unreviewed

#5377 feat: Add the ability update/edit locale in portal
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItemTable.vue
Labels: PR: reviewed-approved

#5381 chore: Portal update fixes
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSettingsCustomizationForm.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/EditPortalBasic.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/EditPortalCustomization.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/PortalCustomization.vue
  app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
Labels: PR: reviewed-approved

#5365 feat: Adds the ability to publish an article
  app/javascript/dashboard/constants.js
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/EditArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
  app/javascript/dashboard/store/modules/helpCenterArticles/getters.js
  app/javascript/dashboard/store/modules/helpCenterArticles/specs/getters.spec.js
Labels: PR: unreviewed

#5382 chore: Update security guidelines
  SECURITY.md
Labels: PR: reviewed-approved

#5383 Design: Fixes to make portal page design close to figma mockups
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/components/ui/Label.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleEditor.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/ArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalPopover.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSwitch.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/SidebarHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue
Labels: PR: partially-approved

#5385 feat: Adds the ability to edit/delete category
  app/javascript/dashboard/api/helpCenter/categories.js
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSwitch.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/helpcenter.routes.js
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/AddCategory.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/CategoryListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/EditCategory.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/ListAllCategories.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/EditPortal.vue
  app/javascript/dashboard/store/modules/helpCenterCategories/actions.js
  app/javascript/dashboard/store/modules/helpCenterCategories/getters.js
  app/javascript/dashboard/store/modules/helpCenterCategories/mutations.js
  app/javascript/dashboard/store/modules/helpCenterCategories/specs/actions.spec.js
  app/javascript/dashboard/store/modules/helpCenterCategories/specs/getters.spec.js
  app/javascript/dashboard/store/mutation-types.js
Labels: PR: partially-approved

#5389 chore: Improve rack-attack configuration
  config/initializers/rack_attack.rb
Labels: PR: unreviewed

#5384 fix: Validations for updating team members
  app/controllers/api/v1/accounts/team_members_controller.rb
  spec/controllers/api/v1/accounts/team_members_controller_spec.rb
Labels: PR: unreviewed

#5388 chore: Final touches for portals
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/assets/scss/plugins/_multiselect.scss
  app/javascript/dashboard/assets/scss/widgets/_buttons.scss
  app/javascript/dashboard/components/widgets/TableFooter.vue
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/modules/widget-preview/components/WidgetHead.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleEditor.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/EditArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItemTable.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalPopover.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSwitch.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/Sidebar.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/SidebarHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ArticleSettings.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/ListAllPortals.vue
  app/javascript/dashboard/routes/dashboard/notifications/components/NotificationPanelList.vue
  app/javascript/shared/components/ui/MultiselectDropdown.vue
  app/javascript/widget/components/AgentMessageBubble.vue
  app/javascript/widget/components/UserMessageBubble.vue
Labels: PR: unreviewed, helpcenter

#5386 feat: Add locales under portal settings
  app/javascript/dashboard/routes/dashboard/helpcenter/helpcenter.routes.js
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/EditPortal.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/EditPortalLocales.vue
Labels: PR: unreviewed, helpcenter

#5390 fix: Alignment issue of edit article dropdown
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/EditArticleHeader.vue
Labels: PR: unreviewed, helpcenter

#5253 feat: Adds the ability to update conversation timeframe automatically
  app/javascript/dashboard/components/ui/TimeAgo.vue
  app/javascript/dashboard/components/ui/stories/TimeAgo.stories.js
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
Labels: PR: unreviewed

#5366 fix: Adding a private note clears the CC field in an Email inbox
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: unreviewed

#5398 fix: Emoji picker is not working on the expanded layout
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/widget/components/ChatInputWrap.vue
Labels: PR: partially-approved

#5400 chore: Sidebar improvements in small screens
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/sidebarComponents/AccountContext.vue
  app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue
  app/javascript/dashboard/routes/dashboard/Dashboard.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/Sidebar.vue
  app/javascript/dashboard/routes/dashboard/notifications/routes.js
  app/javascript/dashboard/routes/dashboard/settings/SettingsHeader.vue
  app/javascript/dashboard/routes/dashboard/settings/Wrapper.vue
Labels: PR: partially-approved

#5399 chore: Add feature flag for conversation continuity in API
  app/models/message.rb
  config/features.yml
Labels: PR: unreviewed

#2810 chore: parallel runs in circle
  .circleci/config.yml
  README.md
Labels: PR: unreviewed, on-hold

#5397 fix: Track Imap exceptions
  app/helpers/api/v1/inboxes_helper.rb
Labels: PR: partially-approved

#5249 feat: Fetching the portal data related to a specific custom domain
  app/controllers/dashboard_controller.rb
  app/controllers/public/api/v1/portals/articles_controller.rb
  app/controllers/public/api/v1/portals/categories_controller.rb
  app/controllers/public/api/v1/portals_controller.rb
  app/controllers/public_controller.rb
  app/views/public/api/v1/models/_category.json.jbuilder
  app/views/public/api/v1/models/_portal.json.jbuilder
  config/routes.rb
  spec/controllers/public/api/v1/portals/articles_controller_spec.rb
  spec/controllers/public/api/v1/portals/categories_controller_spec.rb
  spec/controllers/public/api/v1/portals_controller_spec.rb
Labels: PR: reviewed-approved, helpcenter

#5407 chore: Fixes height issues with seconday sidebar
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/Sidebar.vue
Labels: PR: partially-approved

#5309 feat: Sets up portal public views with rails ERB and tailwind
  app/controllers/public/api/v1/portals/articles_controller.rb
  app/controllers/public/api/v1/portals/categories_controller.rb
  app/controllers/public/api/v1/portals_controller.rb
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/EditArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/Sidebar.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
  app/javascript/packs/portal.js
  app/javascript/portal/application.scss
  app/javascript/portal/portalHelpers.js
  app/javascript/portal/specs/portal.spec.js
  app/views/layouts/portal.html.erb
  app/views/public/api/v1/portals/_category-block.html.erb
  app/views/public/api/v1/portals/_footer.html.erb
  app/views/public/api/v1/portals/_header.html.erb
  app/views/public/api/v1/portals/_hero.html.erb
  app/views/public/api/v1/portals/articles/index.html.erb
  app/views/public/api/v1/portals/articles/show.html.erb
  app/views/public/api/v1/portals/categories/_category-block.html.erb
  app/views/public/api/v1/portals/categories/_hero.html.erb
  app/views/public/api/v1/portals/categories/index.html.erb
  app/views/public/api/v1/portals/categories/show.html.erb
  app/views/public/api/v1/portals/show.html.erb
  config/routes.rb
  package.json
  spec/controllers/public/api/v1/portals/articles_controller_spec.rb
  spec/controllers/public/api/v1/portals_controller_spec.rb
  yarn.lock
Labels: PR: reviewed-approved, helpcenter

#5421 fix: Not able to create a new category through the sidebar
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/AddCategory.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/EditPortalLocales.vue
Labels: PR: partially-approved

#5358 Use "create!" and "save!" bang methods when not checking the result
  app/builders/notification_subscription_builder.rb
  app/controllers/api/v1/accounts/automation_rules_controller.rb
  app/controllers/api/v1/accounts/channels/twilio_channels_controller.rb
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/controllers/api/v1/widget/conversations_controller.rb
  app/controllers/devise_overrides/sessions_controller.rb
  app/controllers/twitter/callbacks_controller.rb
  app/jobs/conversations/activity_message_job.rb
  app/jobs/conversations/user_mention_job.rb
  app/listeners/reporting_event_listener.rb
  app/mailboxes/mailbox_helper.rb
  app/models/channel/facebook_page.rb
  app/services/line/incoming_message_service.rb
  app/services/sms/incoming_message_service.rb
  app/services/telegram/incoming_message_service.rb
  app/services/twilio/incoming_message_service.rb
  app/services/twitter/direct_message_parser_service.rb
  app/services/twitter/tweet_parser_service.rb
  lib/chatwoot_hub.rb
  lib/integrations/csml/processor_service.rb
  lib/integrations/dialogflow/processor_service.rb
  lib/integrations/slack/incoming_message_builder.rb
  spec/controllers/api/v1/widget/labels_controller_spec.rb
  spec/listeners/automation_rule_listener_spec.rb
  spec/mailboxes/reply_mailbox_spec.rb
  spec/mailboxes/support_mailbox_spec.rb
  spec/mailers/conversation_reply_mailer_spec.rb
  spec/models/campaign_spec.rb
  spec/models/conversation_spec.rb
  spec/workers/conversation_reply_email_worker_spec.rb
Labels: PR: unreviewed

#5357 chore: Default to rich content editor in website and email channel
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/modal/constants.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/mixins/specs/uiSettings.spec.js
  app/javascript/shared/helpers/KeyboardHelpers.js
Labels: PR: reviewed-approved

#5426 fix: Fixes bug with locale switching from popover
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalPopover.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSwitch.vue
Labels: PR: unreviewed

#5442 chore: fix gh nightly failure
  .github/workflows/nightly_installer.yml
Labels: PR: reviewed-approved

#5435 chore: Enable Help Center on Sidebar
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/config/sidebarItems/primaryMenu.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/store/modules/accounts.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  config/features.yml
Labels: PR: unreviewed

#5455 feat: Ability to manage account features from super admin
  app/controllers/super_admin/accounts_controller.rb
  app/dashboards/account_dashboard.rb
  app/fields/enterprise/account_features_field.rb
  app/views/fields/account_features_field/_form.html.erb
  app/views/fields/account_features_field/_show.html.erb
Labels: PR: unreviewed

#5454 fix: Read status not updated in widget popout mode
  app/javascript/widget/App.vue
Labels: PR: partially-approved

#5456 chore: Improve Help Center custom domains
  .env.example
  app/controllers/dashboard_controller.rb
  app/controllers/public/api/v1/portals/articles_controller.rb
  app/controllers/public/api/v1/portals/categories_controller.rb
  app/controllers/public/api/v1/portals_controller.rb
  app/controllers/public_controller.rb
  app/models/portal.rb
  app/views/public/api/v1/portals/show.html.erb
  db/migrate/20220919225556_make_help_center_custom_domain_unique.rb
  db/schema.rb
Labels: PR: unreviewed

#5417 fix: un-assign agent from conversation after removal
  app/services/agents/destroy_service.rb
  spec/services/agents/destroy_service_spec.rb
Labels: PR: merged

#5458 chore: Enable help center for self-hosted accounts
  db/migrate/20220920014549_enable_help_center.rb
  db/schema.rb
Labels: PR: unreviewed

#5460 Chore: Helpcenter routing and UI fixes
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/Sidebar.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue
Labels: PR: unreviewed

#5459 chore: Update design of the help-center articles
  app/javascript/portal/application.scss
  app/views/layouts/portal.html.erb
  app/views/public/api/v1/portals/_category-block.html.erb
  app/views/public/api/v1/portals/_footer.html.erb
  app/views/public/api/v1/portals/_header.html.erb
  app/views/public/api/v1/portals/_hero.html.erb
  app/views/public/api/v1/portals/articles/index.html.erb
  app/views/public/api/v1/portals/articles/show.html.erb
  app/views/public/api/v1/portals/categories/_category-block.html.erb
  app/views/public/api/v1/portals/categories/_hero.html.erb
  app/views/public/api/v1/portals/categories/index.html.erb
  app/views/public/api/v1/portals/categories/show.html.erb
  app/views/public/api/v1/portals/show.html.erb
  package.json
  tailwind.config.js
  yarn.lock
Labels: PR: unreviewed

#5461 chore: Remove static URLs from the documentation
  app/javascript/dashboard/helper/portalHelper.js
  app/javascript/dashboard/i18n/locale/ar/helpCenter.json
  app/javascript/dashboard/i18n/locale/bg/helpCenter.json
  app/javascript/dashboard/i18n/locale/ca/helpCenter.json
  app/javascript/dashboard/i18n/locale/cs/helpCenter.json
  app/javascript/dashboard/i18n/locale/da/helpCenter.json
  app/javascript/dashboard/i18n/locale/de/helpCenter.json
  app/javascript/dashboard/i18n/locale/el/helpCenter.json
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/i18n/locale/es/helpCenter.json
  app/javascript/dashboard/i18n/locale/fa/helpCenter.json
  app/javascript/dashboard/i18n/locale/fi/helpCenter.json
  app/javascript/dashboard/i18n/locale/fr/helpCenter.json
  app/javascript/dashboard/i18n/locale/he/helpCenter.json
  app/javascript/dashboard/i18n/locale/hi/helpCenter.json
  app/javascript/dashboard/i18n/locale/hu/helpCenter.json
  app/javascript/dashboard/i18n/locale/id/helpCenter.json
  app/javascript/dashboard/i18n/locale/it/helpCenter.json
  app/javascript/dashboard/i18n/locale/ja/helpCenter.json
  app/javascript/dashboard/i18n/locale/ka/helpCenter.json
  app/javascript/dashboard/i18n/locale/ko/helpCenter.json
  app/javascript/dashboard/i18n/locale/lv/helpCenter.json
  app/javascript/dashboard/i18n/locale/ml/helpCenter.json
  app/javascript/dashboard/i18n/locale/ms/helpCenter.json
  app/javascript/dashboard/i18n/locale/ne/helpCenter.json
  app/javascript/dashboard/i18n/locale/nl/helpCenter.json
  app/javascript/dashboard/i18n/locale/no/helpCenter.json
  app/javascript/dashboard/i18n/locale/pl/helpCenter.json
  app/javascript/dashboard/i18n/locale/pt/helpCenter.json
  app/javascript/dashboard/i18n/locale/pt_BR/helpCenter.json
  app/javascript/dashboard/i18n/locale/ro/helpCenter.json
  app/javascript/dashboard/i18n/locale/ru/helpCenter.json
  app/javascript/dashboard/i18n/locale/sk/helpCenter.json
  app/javascript/dashboard/i18n/locale/sr/helpCenter.json
  app/javascript/dashboard/i18n/locale/sv/helpCenter.json
  app/javascript/dashboard/i18n/locale/ta/helpCenter.json
  app/javascript/dashboard/i18n/locale/th/helpCenter.json
  app/javascript/dashboard/i18n/locale/tr/helpCenter.json
  app/javascript/dashboard/i18n/locale/uk/helpCenter.json
  app/javascript/dashboard/i18n/locale/ur/helpCenter.json
  app/javascript/dashboard/i18n/locale/ur_IN/helpCenter.json
  app/javascript/dashboard/i18n/locale/vi/helpCenter.json
  app/javascript/dashboard/i18n/locale/zh_CN/helpCenter.json
  app/javascript/dashboard/i18n/locale/zh_TW/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSettingsBasicForm.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/ListAllPortals.vue
  app/views/api/v1/accounts/articles/_article.json.jbuilder
  app/views/layouts/vueapp.html.erb
  tailwind.config.js
Labels: PR: unreviewed

#5465 Bug: Adds support multiline text input on article edit page
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleEditor.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue
  app/views/public/api/v1/portals/_category-block.html.erb
Labels: PR: partially-approved

#5467 Fix: Redirect to portal with default locale
  app/controllers/public/api/v1/portals_controller.rb
  app/views/public/api/v1/portals/show.html.erb
  config/routes.rb
Labels: PR: unreviewed

#5469 fix: Hide conversation links in input_csat message in non-website cha…
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: unreviewed

#5470 chore: Fix link generation logic in help-center
  app/controllers/public/api/v1/portals_controller.rb
  app/javascript/dashboard/helper/portalHelper.js
  app/javascript/dashboard/helper/specs/portalHelper.spec.js
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
  app/views/api/v1/accounts/articles/_article.json.jbuilder
  app/views/public/api/v1/portals/_category-block.html.erb
  app/views/public/api/v1/portals/_header.html.erb
Labels: PR: partially-approved

#5473 fix: Macros not_found_status
  app/controllers/api/v1/accounts/macros_controller.rb
  spec/controllers/api/v1/accounts/macros_controller_spec.rb
Labels: PR: partially-approved

#5487 chore: Normalize portal slug to nil
  app/models/application_record.rb
  app/models/portal.rb
  spec/models/portal_spec.rb
Labels: PR: unreviewed

#5500 fix: Add slug to articles
  app/controllers/api/v1/accounts/articles_controller.rb
  app/models/article.rb
  db/migrate/20220926164441_add_slug_to_article.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/articles_controller_spec.rb
  spec/factories/articles.rb
  spec/models/article_spec.rb
Labels: PR: partially-approved

#5497 fix: Add all articles count to article API
  app/views/api/v1/accounts/articles/index.json.jbuilder
  spec/controllers/api/v1/accounts/articles_controller_spec.rb
Labels: PR: unreviewed

#5510 fix: Remove the notification subscription if present
  app/controllers/api/v1/notification_subscriptions_controller.rb
Labels: PR: unreviewed

#5515 chore: Set locale in default_locale
  app/controllers/dashboard_controller.rb
Labels: PR: reviewed-approved

#5509 fix: contact is not available for inaccessible sender
  app/services/instagram/message_text.rb
  spec/factories/instagram/instagram_message_create_event.rb
  spec/jobs/webhooks/instagram_events_job_spec.rb
Labels: PR: reviewed-approved

#5353 fixing attachment not sending to bots message creation
  app/services/telegram/incoming_message_service.rb
Labels: PR: unreviewed

#5451 fix: "wa_source_id" function return value
  app/builders/contact_inbox_builder.rb
  app/models/contact_inbox.rb
  lib/regex_helper.rb
  spec/builders/contact_inbox_builder_spec.rb
  spec/factories/contact_inbox.rb
  spec/models/contact_inbox_spec.rb
Labels: PR: unreviewed

#5524 fix: Article slug auto saves
  app/models/article.rb
  db/migrate/20220930025317_add_unique_index_to_slug.rb
  db/schema.rb
  spec/factories/articles.rb
  spec/models/article_spec.rb
Labels: PR: unreviewed

#5532 Allow setting "users.display_name" in Platform API
  app/controllers/platform/api/v1/users_controller.rb
  spec/controllers/platform/api/v1/users_controller_spec.rb
Labels: PR: reviewed-approved

#5520 fix: Updated IMAP errors add method
  app/models/message.rb
  spec/models/message_spec.rb
Labels: PR: unreviewed

#5533 bug: Fixes editor formatting issues when canned response text is edited
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/helper/localStorage.js
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleEditor.vue
Labels: PR: reviewed-approved
