Repository chatwoot/chatwoot, pull requests merged in 2022-11, with the labels that each got.

#5743 fix: db/seeds.rb field contact_inbox is undefined
  db/seeds.rb
Labels: PR: unreviewed

#5775 fix: Filename issue while editing a macro with attachment action
  app/javascript/dashboard/helper/specs/macrosFixtures.js
  app/javascript/dashboard/helper/specs/macrosHelper.spec.js
  app/javascript/dashboard/i18n/locale/en/automation.json
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroForm.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroNode.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroNodes.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/macroHelper.js
Labels: bug, frontend, PR: unreviewed, PR: reviewed-approved, PR: partially-approved

#5783 fix: Unsupported message type
  app/services/whatsapp/incoming_message_base_service.rb
  spec/services/whatsapp/incoming_message_service_spec.rb
Labels: PR: reviewed-approved

#5574 chore: Use multiple connections in Redis connection pool
  config/initializers/01_redis.rb
Labels: PR: unreviewed

#5773 fix: Text colour is getting merged with the light background colour
  app/javascript/shared/components/CardButton.vue
  app/javascript/shared/components/ChatForm.vue
  app/javascript/shared/components/CustomerSatisfaction.vue
  app/javascript/widget/components/UserMessageBubble.vue
  app/javascript/widget/components/template/EmailInput.vue
Labels: PR: partially-approved

#5786 fix: flaky test whatsapp_cloud_service_spec.rb:17
  lib/regex_helper.rb
  spec/models/contact_inbox_spec.rb
Labels: PR: unreviewed

#5628 fix: Autoloading during initialization deprecation warning (#4012)
  config/initializers/01_redis.rb
  config/initializers/sidekiq.rb
Labels: PR: reviewed-approved

#5751 chore: send bot reply for resolved conversations when a bot is assigned
  app/models/conversation.rb
  app/models/inbox.rb
  app/models/message.rb
  spec/models/message_spec.rb
Labels: PR: unreviewed

#5768 fix: Ensure Automation rule executions are account scoped
  app/listeners/automation_rule_listener.rb
  spec/listeners/automation_rule_listener_spec.rb
Labels: PR: unreviewed

#5790 chore: Use connection_pool for redis
  config/initializers/01_redis.rb
  config/initializers/rack_attack.rb
  lib/global_config.rb
  lib/redis/alfred.rb
  spec/controllers/api/v1/accounts/csat_survey_responses_controller_spec.rb
Labels: PR: unreviewed

#5549 feat: Add inbox details endpoint
  app/controllers/public/api/v1/inboxes_controller.rb
  app/views/public/api/v1/inboxes/show.json.jbuilder
  app/views/public/api/v1/models/_inbox.json.jbuilder
  spec/controllers/public/api/v1/inbox/inboxes_controller_spec.rb
  swagger/definitions/index.yml
  swagger/definitions/resource/public/inbox.yml
  swagger/paths/index.yml
  swagger/paths/public/inboxes/show.yml
  swagger/swagger.json
Labels: PR: unreviewed

#4422 fix: GCP Redis managed don't support redis client setname command
  config/initializers/actioncable.rb
Labels: PR: unreviewed

#5791 fix: Fixes widget thumbnails not rendering background colors
  app/javascript/dashboard/components/widgets/Thumbnail.vue
  app/javascript/widget/assets/scss/woot.scss
  app/javascript/widget/components/ConversationWrap.vue
Labels: PR: reviewed-approved

#5793 fix: Allow ending the conversation if snoozed or pending
  app/javascript/shared/constants/messages.js
  app/javascript/widget/components/HeaderActions.vue
Labels: PR: reviewed-approved

#5796 feat: Adds component for grouped thumbnails
  app/javascript/dashboard/components/widgets/ThumbnailGroup.vue
  app/javascript/dashboard/components/widgets/stories/ThumbnailGroup.stories.js
Labels: PR: partially-approved

#5800 Update .env.example
  .env.example
Labels: PR: unreviewed

#5805 Feat/5733 Add private note action in macros
  app/javascript/dashboard/routes/dashboard/conversation/Macros/MacroPreview.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/constants.js
  app/models/macro.rb
  app/services/macros/execution_service.rb
  spec/controllers/api/v1/accounts/macros_controller_spec.rb
Labels: PR: partially-approved

#5802 fix: Update invalid payload for template messages
  app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
Labels: PR: reviewed-approved

#5804 fix: Identifier not persisted on customer created via Inbox API Channel
  app/controllers/public/api/v1/inboxes/contacts_controller.rb
  spec/controllers/public/api/v1/inbox/contacts_controller_spec.rb
Labels: PR: unreviewed

#5779 fix: Macros authorizations
  app/controllers/api/v1/accounts/macros_controller.rb
  app/models/macro.rb
  app/models/user.rb
  app/policies/macro_policy.rb
  db/migrate/20221102082737_change_macros_created_by_to_null.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/macros_controller_spec.rb
  spec/models/macro_spec.rb
Labels: PR: unreviewed

#5718 chore: Update data format for platform API feature management
  app/controllers/platform/api/v1/accounts_controller.rb
  app/models/concerns/featurable.rb
  spec/controllers/platform/api/v1/accounts_controller_spec.rb
Labels: PR: unreviewed

#5809 feat: Adds component to show location based messages
  app/javascript/dashboard/components/widgets/conversation/bubble/Location.vue
  app/javascript/dashboard/components/widgets/conversation/stories/LocationBubble.stories.js
  app/javascript/dashboard/i18n/locale/en/settings.json
Labels: PR: partially-approved

#5742 feat: Ability to receive location on whatsapp inbox
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Location.vue
  app/services/whatsapp/incoming_message_base_service.rb
  db/seeds.rb
  spec/services/whatsapp/incoming_message_service_spec.rb
Labels: PR: unreviewed

#5808 feat: Adds store for conversation watchers
  app/javascript/dashboard/api/inbox/conversation.js
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/conversationWatchers.js
  app/javascript/dashboard/store/modules/specs/conversationWatchers/actions.spec.js
  app/javascript/dashboard/store/modules/specs/conversationWatchers/fixtures.js
  app/javascript/dashboard/store/modules/specs/conversationWatchers/getters.spec.js
  app/javascript/dashboard/store/modules/specs/conversationWatchers/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
Labels: PR: unreviewed

#5824 fix: SocketError: getaddrinfo: for imap channels
  app/jobs/inboxes/fetch_imap_emails_job.rb
  lib/exception_list.rb
Labels: PR: unreviewed

#5823 feat: Improves image loading for thumbnails
  app/javascript/dashboard/components/widgets/Thumbnail.spec.js
  app/javascript/dashboard/components/widgets/Thumbnail.vue
Labels: PR: partially-approved

#5797 chore: Add feature flag for mobile v2
  config/features.yml
Labels: PR: partially-approved

#5821 Feat: add agents in macros
  app/javascript/dashboard/helper/specs/macrosFixtures.js
  app/javascript/dashboard/helper/specs/macrosHelper.spec.js
  app/javascript/dashboard/mixins/macrosMixin.js
  app/javascript/dashboard/mixins/specs/macros.spec.js
  app/javascript/dashboard/routes/dashboard/conversation/Macros/MacroPreview.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroEditor.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroNode.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/constants.js
  app/javascript/dashboard/routes/dashboard/settings/macros/macroHelper.js
Labels: PR: partially-approved

#5814 feat: Add a loader till dashboard app is loaded
  app/javascript/dashboard/components/widgets/DashboardApp/Frame.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/i18n/locale/en/generalSettings.json
Labels: frontend, feature-request, PR: unreviewed, PR: partially-approved

#5822 chore: Design improvements for Thumbnails and dropdown
  app/javascript/dashboard/components/widgets/Avatar.vue
  app/javascript/dashboard/components/widgets/Thumbnail.vue
  app/javascript/dashboard/components/widgets/ThumbnailGroup.vue
  app/javascript/shared/components/ui/MultiselectDropdownItems.vue
Labels: PR: partially-approved

#5830 bug: Fixes broken dropdown issue
  app/javascript/shared/components/ui/MultiselectDropdownItems.vue
Labels: PR: unreviewed

#4548 feat: Custom attributes in automations and refactor
  .vscode/settings.json
  app/javascript/dashboard/components/widgets/AutomationActionInput.vue
  app/javascript/dashboard/components/widgets/FilterInput/Index.vue
  app/javascript/dashboard/helper/actionQueryGenerator.js
  app/javascript/dashboard/helper/automationHelper.js
  app/javascript/dashboard/helper/filterQueryGenerator.js
  app/javascript/dashboard/helper/specs/filterQueryGenerator.spec.js
  app/javascript/dashboard/i18n/locale/en/automation.json
  app/javascript/dashboard/i18n/locale/en/generalSettings.json
  app/javascript/dashboard/mixins/automations/methodsMixin.js
  app/javascript/dashboard/mixins/automations/validationsMixin.js
  app/javascript/dashboard/routes/dashboard/settings/automation/AddAutomationRule.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/EditAutomationRule.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
  app/javascript/dashboard/routes/dashboard/settings/automation/operators.js
  app/javascript/shared/mixins/specs/automationFixtures.js
  app/javascript/shared/mixins/specs/automationHelper.spec.js
  app/javascript/shared/mixins/specs/automationMixin.spec.js
  app/listeners/automation_rule_listener.rb
  app/models/concerns/activity_message_handler.rb
  app/models/conversation.rb
  app/presenters/conversations/event_data_presenter.rb
  app/services/action_service.rb
  app/services/automation_rules/action_service.rb
  app/services/filter_service.rb
  spec/listeners/action_cable_listener_spec.rb
  spec/listeners/automation_rule_listener_spec.rb
  spec/models/conversation_spec.rb
  spec/presenters/conversations/event_data_presenter_spec.rb
Labels: PR: reviewed-approved

#5837 fix: Single select for agents and teams in Macros actions
  .gitignore
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroEditor.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/constants.js
Labels: PR: partially-approved

#5846 fix: Activity message generation for team assignment automation
  app/models/concerns/activity_message_handler.rb
Labels: PR: partially-approved

#5832 fix: Full name update when creating a conversation without an email id
  app/controllers/api/v1/widget/base_controller.rb
  spec/controllers/api/v1/widget/conversations_controller_spec.rb
Labels: PR: unreviewed

#5853 fix: send label list not object in event data presenter
  app/presenters/conversations/event_data_presenter.rb
  spec/listeners/action_cable_listener_spec.rb
Labels: PR: reviewed-approved

#5827 fix: Assign agent action changes
  app/javascript/dashboard/mixins/macrosMixin.js
  app/javascript/dashboard/mixins/specs/macros.spec.js
  app/javascript/dashboard/routes/dashboard/conversation/Macros/MacroPreview.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/constants.js
  app/models/automation_rule.rb
  app/models/macro.rb
  app/services/action_service.rb
  spec/controllers/api/v1/accounts/macros_controller_spec.rb
  spec/factories/automation_rules.rb
  spec/listeners/automation_rule_listener_spec.rb
  spec/models/automation_rule_spec.rb
Labels: PR: partially-approved

#5858 chore: Enable Macros for all accounts
  config/features.yml
  db/migrate/20221116000514_enable_macros_for_all_accounts.rb
  db/schema.rb
Labels: PR: unreviewed

#5852 chore: Cleanup the design in the widget builder
  app/javascript/dashboard/modules/widget-preview/components/Widget.vue
  app/javascript/dashboard/modules/widget-preview/components/WidgetBody.vue
  app/javascript/dashboard/modules/widget-preview/components/WidgetHead.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/WidgetBuilder.vue
Labels: PR: reviewed-approved

#5861 feat: Add support for `after` param in messages API
  app/finders/message_finder.rb
  spec/finders/message_finder_spec.rb
Labels: PR: partially-approved

#5864 feat: Show last non-activity messages in the chat list
  app/controllers/api/v1/accounts/contacts/conversations_controller.rb
  app/javascript/dashboard/mixins/conversations.js
  app/javascript/dashboard/mixins/specs/conversation.spec.js
  app/javascript/dashboard/mixins/specs/conversaton.spec.js
  app/models/message.rb
  app/views/api/v1/conversations/partials/_conversation.json.jbuilder
Labels: PR: partially-approved

#5875 feat: Remove labels in macro
  app/javascript/dashboard/mixins/macrosMixin.js
  app/javascript/dashboard/routes/dashboard/conversation/Macros/MacroPreview.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/constants.js
  app/models/macro.rb
  app/services/action_service.rb
  spec/controllers/api/v1/accounts/macros_controller_spec.rb
Labels: PR: partially-approved

#5871 feat: Assign team with teams none option
  app/javascript/dashboard/routes/dashboard/conversation/Macros/MacroPreview.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroEditor.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroForm.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/constants.js
  app/models/macro.rb
  app/services/action_service.rb
  spec/controllers/api/v1/accounts/macros_controller_spec.rb
Labels: PR: partially-approved

#4153 feat: Allow agent-bots to be created from the UI
  app/controllers/dashboard_controller.rb
  app/javascript/dashboard/components/widgets/ShowMore.vue
  app/javascript/dashboard/i18n/locale/en/agentBots.json
  app/javascript/dashboard/routes/dashboard/settings/agentBots/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/agentBots/components/AgentBotRow.vue
  app/javascript/dashboard/routes/dashboard/settings/agentBots/components/AgentBotType.vue
  app/javascript/dashboard/routes/dashboard/settings/agentBots/components/CSMLBotEditor.vue
  app/javascript/dashboard/routes/dashboard/settings/agentBots/components/CSMLMonacoEditor.vue
  app/javascript/dashboard/routes/dashboard/settings/agentBots/csml/Edit.vue
  app/javascript/dashboard/routes/dashboard/settings/agentBots/csml/New.vue
  app/javascript/dashboard/store/modules/accounts.js
  app/javascript/dashboard/store/modules/agentBots.js
  app/javascript/shared/store/globalConfig.js
  config/installation_config.yml
  public/dashboard/images/agent-bots/csml.png
  public/dashboard/images/agent-bots/webhook.svg
  yarn.lock
Labels: PR: unreviewed, on-hold

#5885 feat: Bulk assign teams
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/AgentSelector.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/Index.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/LabelActions.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/TeamActions.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/UpdateActions.vue
  app/javascript/dashboard/i18n/locale/en/bulkActions.json
  app/javascript/dashboard/mixins/bulkActionsMixin.js
  app/javascript/dashboard/mixins/specs/bulkActions.spec.js
Labels: frontend, feature-request, PR: unreviewed, PR: partially-approved

#5895 chore: Allow admins to choose the agent bot from the UI
  app/javascript/dashboard/api/inboxes.js
  app/javascript/dashboard/api/specs/inboxes.spec.js
  app/javascript/dashboard/i18n/locale/en/agentBots.json
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/BotConfiguration.vue
  app/javascript/dashboard/store/modules/agentBots.js
  app/javascript/dashboard/store/modules/specs/agentBots/actions.spec.js
  app/javascript/dashboard/store/modules/specs/agentBots/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  yarn.lock
Labels: PR: unreviewed

#5917 fix: Sidebar missing at 1200px width
  app/javascript/dashboard/routes/dashboard/Dashboard.vue
Labels: PR: partially-approved

#5920 chore: Enable Latvian (lv) language
  app/javascript/dashboard/i18n/index.js
  app/javascript/dashboard/i18n/locale/en/generalSettings.json
  app/javascript/survey/i18n/index.js
  app/javascript/widget/i18n/index.js
  config/initializers/languages.rb
Labels: PR: unreviewed

#5924 feat: Allow users to mark a conversation as unread
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/javascript/dashboard/api/inbox/conversation.js
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/contextMenu/Index.vue
  app/javascript/dashboard/helper/URLHelper.js
  app/javascript/dashboard/helper/specs/URLHelper.spec.js
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/mixins/conversations.js
  app/javascript/dashboard/mixins/specs/conversation.spec.js
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/actions/messageReadActions.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/views/api/v1/accounts/conversations/unread.json.jbuilder
  config/routes.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
Labels: PR: partially-approved

#5929 chore: Add reauthorization prompt for Whatsapp Channel
  app/jobs/webhooks/whatsapp_events_job.rb
  app/mailers/administrator_notifications/channel_notifications_mailer.rb
  app/models/channel/whatsapp.rb
  app/models/concerns/reauthorizable.rb
  app/services/whatsapp/incoming_message_base_service.rb
  app/services/whatsapp/incoming_message_whatsapp_cloud_service.rb
  app/views/mailers/administrator_notifications/channel_notifications_mailer/whatsapp_disconnect.liquid
  spec/jobs/webhooks/whatsapp_events_job_spec.rb
  spec/mailers/administrator_notifications/channel_notifications_mailer_spec.rb
  spec/models/channel/whatsapp_spec.rb
  spec/services/whatsapp/incoming_message_whatsapp_cloud_service_spec.rb
Labels: PR: reviewed-approved

#5932 chore: add ph-no-capture css class to messages
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
Labels: PR: partially-approved

#5881 feat: Ability to lock to single conversation
  .rubocop.yml
  app/builders/conversation_builder.rb
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/store/modules/contactConversations.js
  app/models/inbox.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  db/migrate/20221109065043_add_lock_conversation_to_single_thread.rb
  db/schema.rb
  spec/builders/conversation_builder_spec.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
Labels: PR: reviewed-approved

#5921 fix: destroy bulk service
  app/jobs/agents/destroy_job.rb
  app/models/account_user.rb
  app/services/agents/destroy_service.rb
  spec/builders/notification_builder_spec.rb
  spec/jobs/agents/destroy_job_spec.rb
  spec/models/account_user_spec.rb
Labels: PR: partially-approved

#5899 feat: use sendmail for email as default
  .env.example
  config/initializers/mailer.rb
Labels: PR: reviewed-approved

#5969 fix: unassign team activity message
  app/models/concerns/activity_message_handler.rb
  spec/controllers/api/v1/accounts/bulk_actions_controller_spec.rb
Labels: PR: partially-approved

#5157 feat: Read/Delivery status for Whatsapp Cloud API
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
  app/javascript/dashboard/i18n/locale/en/chatlist.json
  app/javascript/shared/constants/messages.js
  app/models/message.rb
  app/services/whatsapp/incoming_message_base_service.rb
  app/views/api/v1/models/_message.json.jbuilder
  spec/services/whatsapp/incoming_message_service_spec.rb
Labels: PR: partially-approved

#5880 fix: Updates logic to insert canned response into editor
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
Labels: PR: partially-approved

#5890 feat: Adds sidebar view for unattended conversations
  app/finders/conversation_finder.rb
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/layout/config/sidebarItems/conversations.js
  app/javascript/dashboard/helper/URLHelper.js
  app/javascript/dashboard/i18n/locale/en/chatlist.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/conversation/conversation.routes.js
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/helpers.js
  app/javascript/dashboard/store/modules/conversations/helpers/actionHelpers.js
  app/javascript/dashboard/store/modules/specs/conversations/helpers.spec.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/listeners/reporting_event_listener.rb
  app/models/conversation.rb
  app/presenters/conversations/event_data_presenter.rb
  app/views/api/v1/conversations/partials/_conversation.json.jbuilder
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
  spec/finders/conversation_finder_spec.rb
  spec/models/conversation_spec.rb
  spec/presenters/conversations/event_data_presenter_spec.rb
Labels: PR: unreviewed

#5981 fix: Update inbox json, removing password
  app/views/api/v1/models/_inbox.json.jbuilder
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
Labels: PR: reviewed-approved
