Repository chatwoot/chatwoot, pull requests merged in 2022-05, with the labels that each got.

#4493 fix: unable to send audio messages on Telegram
  app/javascript/dashboard/assets/scss/widgets/_reply-box.scss
  app/javascript/dashboard/components/widgets/WootWriter/AudioRecorder.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/models/channel/telegram.rb
  config/webpack/environment.js
  package.json
Labels: PR: reviewed-approved

#4618 chore: Sentry Issue fixes
  app/models/inbox_member.rb
  lib/integrations/slack/incoming_message_builder.rb
  spec/models/inbox_member_spec.rb
Labels: PR: unreviewed

#4627 chore: Update missing packages in yarn.lock
  config/schedule.yml
  yarn.lock
Labels: PR: unreviewed

#4626 chore: update newrelic gem to support log forwarding
  .env.example
  Gemfile.lock
  config/newrelic.yml
Labels: PR: reviewed-approved

#4530 fix: Pre chat custom fields drag and drop
  app/javascript/dashboard/components/ui/Switch.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/PreChatForm/PreChatFields.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/PreChatForm/Settings.vue
Labels: PR: partially-approved

#4623 chore: Sentry issues
  app/builders/contact_builder.rb
  app/builders/messages/facebook/message_builder.rb
  app/channels/room_channel.rb
  app/controllers/api/v1/accounts/channels/twilio_channels_controller.rb
  app/controllers/api/v1/accounts/conversations/base_controller.rb
  app/finders/message_finder.rb
  app/jobs/hook_job.rb
  lib/webhooks/trigger.rb
Labels: PR: unreviewed

#4613 Open "Switch Account" modal when clicking account name on dashboard
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/sidebarComponents/AccountContext.vue
  app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue
  app/javascript/dashboard/i18n/locale/en/settings.json
Labels: PR: reviewed-approved

#3640 chore: Update puma config as per recommendations
  config/puma.rb
Labels: PR: unreviewed, on-hold

#4223 Feat - Programatically toggle live chat widget
  app/javascript/packs/sdk.js
  app/javascript/sdk/IFrameHelper.js
  app/javascript/sdk/bubbleHelpers.js
  app/javascript/sdk/sdk.js
  app/javascript/shared/constants/sharedFrameEvents.js
  app/javascript/widget/App.vue
  app/javascript/widget/store/modules/appConfig.js
  app/javascript/widget/store/modules/specs/appConfig/actions.spec.js
  app/javascript/widget/store/modules/specs/appConfig/mutations.spec.js
  app/javascript/widget/store/types.js
Labels: PR: partially-approved

#4637 chore: Use different files for widget and dashboard audio alert
  app/javascript/sdk/IFrameHelper.js
  app/javascript/shared/helpers/AudioNotificationHelper.js
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/test.rb
  public/audio/dashboard/ding.mp3
  public/audio/widget/ding.mp3
Labels: PR: reviewed-approved

#4188 chore: "Channel::TwilioSms" to be unique on account_sid+phone_number
  app/models/channel/twilio_sms.rb
  db/migrate/20220315204137_add_account_sid_unique_index_to_channel_twilio_sms.rb
  db/schema.rb
Labels: PR: unreviewed

#4607 Fix: Campaign triggers first_response reporting event
  app/builders/campaigns/campaign_conversation_builder.rb
  app/builders/messages/message_builder.rb
  app/models/message.rb
  db/migrate/20220506163839_add_additional_attributes_to_message.rb
  db/schema.rb
  spec/builders/campaigns/campaign_conversation_builder_spec.rb
Labels: PR: partially-approved

#4638 chore: Upgrade Exception tracking
  Gemfile
  Gemfile.lock
  app/builders/messages/facebook/message_builder.rb
  app/builders/messages/instagram/message_builder.rb
  app/builders/messages/messenger/message_builder.rb
  app/controllers/api/v1/accounts/callbacks_controller.rb
  app/controllers/api/v1/webhooks_controller.rb
  app/controllers/concerns/request_exception_handler.rb
  app/jobs/inboxes/fetch_imap_emails_job.rb
  app/services/automation_rules/action_service.rb
  app/services/facebook/send_on_facebook_service.rb
  app/services/instagram/message_text.rb
  app/services/instagram/send_on_instagram_service.rb
  app/services/message_templates/template/email_collect.rb
  app/services/message_templates/template/greeting.rb
  app/services/message_templates/template/out_of_office.rb
  app/services/twilio/send_on_twilio_service.rb
  config/initializers/sentry.rb
  lib/chatwoot_exception_tracker.rb
  lib/chatwoot_hub.rb
  lib/integrations/facebook/message_creator.rb
  lib/webhooks/trigger.rb
  package.json
  spec/lib/chatwoot_exception_tracker_spec.rb
  yarn.lock
Labels: PR: unreviewed

#4610 Fix: slack repeated callback event message for attached files
  lib/integrations/slack/incoming_message_builder.rb
  spec/lib/integrations/slack/incoming_message_builder_spec.rb
Labels: PR: unreviewed

#4656 Fix: sentry issue for slack incoming files check
  lib/integrations/slack/incoming_message_builder.rb
  spec/lib/integrations/slack/incoming_message_builder_spec.rb
Labels: PR: unreviewed

#4659 chore: Ability to update user email via Platform APIs
  app/controllers/platform/api/v1/users_controller.rb
  spec/controllers/platform/api/v1/users_controller_spec.rb
Labels: PR: unreviewed

#4654 Fix: Make version changeable from the environment vars
  app/controllers/dashboard_controller.rb
  app/javascript/dashboard/helper/scriptGenerator.js
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Facebook.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/facebook/Reauthorize.vue
  app/views/layouts/vueapp.html.erb
Labels: PR: unreviewed

#4671 chore: Remove unused method scriptGenerator
  app/javascript/dashboard/helper/scriptGenerator.js
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
Labels: PR: reviewed-approved

#4664 chore: Split Inbox Settings Page Component
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/CollaboratorsPage.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/ConfigurationPage.vue
  lib/seeders/account_seeder.rb
Labels: PR: unreviewed

#4668 Fix: Creating contacts for already outgoing/echo messages
  app/services/instagram/message_text.rb
Labels: PR: reviewed-approved

#4663 Fix: Agent Reports counts when they have access to multiple accounts
  app/helpers/report_helper.rb
  spec/controllers/api/v2/accounts/report_controller_spec.rb
Labels: PR: unreviewed

#4679 chore: Update the note of Personal message signature
  app/javascript/dashboard/i18n/locale/bg/settings.json
Labels: PR: reviewed-approved

#4675 feat: Control sidekiq log level via rails LOG_LEVEL env variable
  config/initializers/sidekiq.rb
Labels: PR: reviewed-approved

#4685 fix: Render links with target attribute
  app/javascript/packs/application.js
  app/javascript/packs/widget.js
  app/javascript/shared/helpers/HTMLSanitizer.js
  app/javascript/shared/helpers/MessageFormatter.js
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#4682 New Crowdin updates
  app/javascript/dashboard/i18n/locale/ar/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/ar/settings.json
Labels: PR: reviewed-approved

#4681 chore: Enable New Message Button on Contact Panel
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/EditContact.vue
Labels: PR: reviewed-approved

#4697 fix: Update report method to fix issues with special characters
  app/javascript/dashboard/helper/downloadHelper.js
  app/javascript/dashboard/helper/specs/downloadHelper.spec.js
  app/javascript/dashboard/store/modules/specs/reports/actions.spec.js
  app/views/api/v1/accounts/csat_survey_responses/download.csv.erb
  app/views/api/v2/accounts/reports/agents.csv.erb
  app/views/api/v2/accounts/reports/inboxes.csv.erb
  app/views/api/v2/accounts/reports/labels.csv.erb
  app/views/api/v2/accounts/reports/teams.csv.erb
Labels: PR: unreviewed

#4576 chore: Add first_reply_created event in conversation
  app/jobs/migration/conversations_first_reply_scheduler_job.rb
  app/listeners/reporting_event_listener.rb
  app/models/conversation.rb
  db/migrate/20220513145010_add_first_reply_activity_at_to_conversation.rb
  db/schema.rb
  spec/jobs/migration/conversations_first_reply_scheduler_job_spec.rb
Labels: PR: partially-approved

#4703 chore: Update the documentation for configuring webhooks in the account
  swagger/definitions/index.yml
  swagger/definitions/request/webhooks/create_update_payload.yml
  swagger/definitions/resource/webhook.yml
  swagger/index.yml
  swagger/parameters/index.yml
  swagger/parameters/webhook_id.yml
  swagger/paths/application/webhooks/create.yml
  swagger/paths/application/webhooks/delete.yml
  swagger/paths/application/webhooks/index.yml
  swagger/paths/application/webhooks/update.yml
  swagger/paths/index.yml
  swagger/swagger.json
Labels: PR: partially-approved

#4708 chore: Update conversations API to include unattended conversations.
  app/finders/conversation_finder.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
Labels: PR: partially-approved

#4720 chore: Enable Ukrainian language (uk)
  config/initializers/languages.rb
Labels: PR: unreviewed

#4722 chore: Add Assignable Agents API
  app/controllers/api/v1/accounts/assignable_agents_controller.rb
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/javascript/dashboard/api/assignableAgents.js
  app/javascript/dashboard/api/inboxes.js
  app/javascript/dashboard/api/specs/assignableAgents.spec.js
  app/javascript/dashboard/api/specs/inboxes.spec.js
  app/javascript/dashboard/store/modules/inboxAssignableAgents.js
  app/views/api/v1/accounts/assignable_agents/index.json.jbuilder
  config/routes.rb
  spec/controllers/api/v1/accounts/assignable_agents_controller_spec.rb
Labels: PR: partially-approved

#4738 chore: Update cache name in Circle CI builds
  .circleci/config.yml
Labels: PR: unreviewed

#4713 feat: Improve Linux installation experience
  deployment/setup_20.04.sh
Labels: PR: unreviewed, infrastructure

#4741 fix: Revert changes to fix name updation from pre-chat form
  app/controllers/api/v1/widget/base_controller.rb
  app/controllers/api/v1/widget/conversations_controller.rb
  spec/controllers/api/v1/widget/conversations_controller_spec.rb
Labels: PR: unreviewed

#4748 fix: Remove translated keys from locale files
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/i18n/locale/ar/chatlist.json
  app/javascript/dashboard/i18n/locale/bg/chatlist.json
  app/javascript/dashboard/i18n/locale/ca/chatlist.json
  app/javascript/dashboard/i18n/locale/cs/chatlist.json
  app/javascript/dashboard/i18n/locale/da/chatlist.json
  app/javascript/dashboard/i18n/locale/de/chatlist.json
  app/javascript/dashboard/i18n/locale/el/chatlist.json
  app/javascript/dashboard/i18n/locale/en/chatlist.json
  app/javascript/dashboard/i18n/locale/es/chatlist.json
  app/javascript/dashboard/i18n/locale/fa/chatlist.json
  app/javascript/dashboard/i18n/locale/fi/chatlist.json
  app/javascript/dashboard/i18n/locale/fr/chatlist.json
  app/javascript/dashboard/i18n/locale/he/chatlist.json
  app/javascript/dashboard/i18n/locale/hi/chatlist.json
  app/javascript/dashboard/i18n/locale/hu/chatlist.json
  app/javascript/dashboard/i18n/locale/id/chatlist.json
  app/javascript/dashboard/i18n/locale/it/chatlist.json
  app/javascript/dashboard/i18n/locale/ja/chatlist.json
  app/javascript/dashboard/i18n/locale/ko/chatlist.json
  app/javascript/dashboard/i18n/locale/lv/chatlist.json
  app/javascript/dashboard/i18n/locale/ml/chatlist.json
  app/javascript/dashboard/i18n/locale/ne/chatlist.json
  app/javascript/dashboard/i18n/locale/nl/chatlist.json
  app/javascript/dashboard/i18n/locale/no/chatlist.json
  app/javascript/dashboard/i18n/locale/pl/chatlist.json
  app/javascript/dashboard/i18n/locale/pt/chatlist.json
  app/javascript/dashboard/i18n/locale/pt_BR/chatlist.json
  app/javascript/dashboard/i18n/locale/ro/chatlist.json
  app/javascript/dashboard/i18n/locale/ru/chatlist.json
  app/javascript/dashboard/i18n/locale/sk/chatlist.json
  app/javascript/dashboard/i18n/locale/sr/chatlist.json
  app/javascript/dashboard/i18n/locale/sv/chatlist.json
  app/javascript/dashboard/i18n/locale/ta/chatlist.json
  app/javascript/dashboard/i18n/locale/th/chatlist.json
  app/javascript/dashboard/i18n/locale/tr/chatlist.json
  app/javascript/dashboard/i18n/locale/uk/chatlist.json
  app/javascript/dashboard/i18n/locale/ur/chatlist.json
  app/javascript/dashboard/i18n/locale/ur_IN/chatlist.json
  app/javascript/dashboard/i18n/locale/vi/chatlist.json
  app/javascript/dashboard/i18n/locale/zh/chatlist.json
  app/javascript/dashboard/i18n/locale/zh_CN/chatlist.json
  app/javascript/dashboard/i18n/locale/zh_TW/chatlist.json
Labels: PR: partially-approved

#4751 New Crowdin updates
  app/javascript/dashboard/i18n/locale/cs/chatlist.json
  app/javascript/dashboard/i18n/locale/de/report.json
  app/javascript/dashboard/i18n/locale/es/chatlist.json
  app/javascript/dashboard/i18n/locale/it/report.json
  app/javascript/dashboard/i18n/locale/pl/chatlist.json
  app/javascript/dashboard/i18n/locale/sk/report.json
  app/javascript/dashboard/i18n/locale/sr/chatlist.json
  app/javascript/dashboard/i18n/locale/zh_CN/advancedFilters.json
  app/javascript/dashboard/i18n/locale/zh_CN/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/zh_CN/automation.json
  app/javascript/dashboard/i18n/locale/zh_CN/contact.json
  app/javascript/dashboard/i18n/locale/zh_CN/contactFilters.json
  app/javascript/dashboard/i18n/locale/zh_CN/generalSettings.json
  config/locales/it.yml
Labels: PR: unreviewed

#4674 feat: Add business hours in downloadable reports
  app/controllers/api/v2/accounts/reports_controller.rb
  app/helpers/api/v2/accounts/reports_helper.rb
  app/javascript/dashboard/api/reports.js
  app/javascript/dashboard/api/specs/reports.spec.js
  app/javascript/dashboard/helper/downloadHelper.js
  app/javascript/dashboard/helper/specs/downloadHelper.spec.js
  app/javascript/dashboard/routes/dashboard/settings/reports/components/WootReports.vue
  app/javascript/dashboard/store/modules/reports.js
  app/views/api/v2/accounts/reports/agents.csv.erb
  app/views/api/v2/accounts/reports/inboxes.csv.erb
  app/views/api/v2/accounts/reports/labels.csv.erb
  app/views/api/v2/accounts/reports/teams.csv.erb
  config/locales/en.yml
Labels: PR: unreviewed

#4702 Destructuring response.data sometimes throws an exception
  app/javascript/widget/store/modules/contacts.js
Labels: PR: reviewed-approved

#4693 chore: Update ruby and docker base image to 3.0.4
  .circleci/config.yml
  .github/workflows/run_foss_spec.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  deployment/chatwoot-web.1.service
  deployment/chatwoot-worker.1.service
  deployment/setup_18.04.sh
  deployment/setup_20.04.sh
  docker/Dockerfile
  package.json
  yarn.lock
Labels: PR: unreviewed

#4755 New Crowdin updates
  app/javascript/dashboard/i18n/locale/cs/conversation.json
  app/javascript/dashboard/i18n/locale/cs/setNewPassword.json
  app/javascript/dashboard/i18n/locale/pt/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/pt/automation.json
  app/javascript/dashboard/i18n/locale/pt/chatlist.json
  config/locales/ar.yml
  config/locales/bg.yml
  config/locales/ca.yml
  config/locales/cs.yml
  config/locales/da.yml
  config/locales/de.yml
  config/locales/el.yml
  config/locales/es.yml
  config/locales/fa.yml
  config/locales/fi.yml
  config/locales/fr.yml
  config/locales/he.yml
  config/locales/hi.yml
  config/locales/hu.yml
  config/locales/id.yml
  config/locales/it.yml
  config/locales/ja.yml
  config/locales/ko.yml
  config/locales/lv.yml
  config/locales/ml.yml
  config/locales/ne.yml
  config/locales/nl.yml
  config/locales/no.yml
  config/locales/pl.yml
  config/locales/pt.yml
  config/locales/pt_BR.yml
  config/locales/ro.yml
  config/locales/ru.yml
  config/locales/sk.yml
  config/locales/sr.yml
  config/locales/sv.yml
  config/locales/ta.yml
  config/locales/th.yml
  config/locales/tr.yml
  config/locales/uk.yml
  config/locales/ur.yml
  config/locales/ur_IN.yml
  config/locales/vi.yml
  config/locales/zh_CN.yml
  config/locales/zh_TW.yml
Labels: PR: reviewed-approved
