Repository chatwoot/chatwoot, pull requests merged in 2022-01, with the labels that each got.

#3676 Fixes #3656 Updates tile and placeholder
  app/javascript/dashboard/i18n/locale/en/settings.json
Labels: PR: unreviewed

#3688 chore: Show scrollbar for sidebar only on hover
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
Labels: PR: unreviewed

#3685 General updates and add CODEOWNERS
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: PR: unreviewed

#3703 chore: Notification subscription delete API
  app/controllers/api/v1/notification_subscriptions_controller.rb
  config/routes.rb
  spec/controllers/api/v1/notification_subscriptions_controller_spec.rb
Labels: PR: partially-approved

#3706 chore: Use logo thumbnail instead of logo in the sidebar
  app/javascript/dashboard/components/layout/Sidebar.vue
  public/favicon.ico
Labels: PR: unreviewed

#3710 Chore/update ninja keys
  app/javascript/dashboard/routes/dashboard/commands/commandbar.vue
  package.json
  yarn.lock
Labels: PR: unreviewed

#3718 Fix: Error with plurals in Invite members onboarding guide.
  app/javascript/dashboard/i18n/locale/en/conversation.json
Labels: PR: reviewed-approved

#3716 Cloes #3669 Unnecessary spacing removed
  app/javascript/dashboard/i18n/locale/en/cannedMgmt.json
Labels: PR: reviewed-approved

#3717 Fixed spacing issue as per - Issue 3669
  app/javascript/dashboard/i18n/locale/en/cannedMgmt.json
Labels: PR: unreviewed

#3359 feat: Save automation rules
  app/builders/messages/message_builder.rb
  app/controllers/api/v1/accounts/automation_rules_controller.rb
  app/dispatchers/async_dispatcher.rb
  app/listeners/automation_rule_listener.rb
  app/mailers/team_notifications/automation_notification_mailer.rb
  app/models/account.rb
  app/models/automation_rule.rb
  app/models/concerns/labelable.rb
  app/policies/automation_rule_policy.rb
  app/services/automation_rules/action_service.rb
  app/services/automation_rules/conditions_filter_service.rb
  app/services/instagram/send_on_instagram_service.rb
  app/views/api/v1/accounts/automation_rules/create.json.jbuilder
  app/views/api/v1/accounts/automation_rules/index.json.jbuilder
  app/views/api/v1/accounts/automation_rules/partials/_automation_rule.json.jbuilder
  app/views/mailers/team_notifications/automation_notification_mailer/conversation_creation.liquid
  config/routes.rb
  db/migrate/20211110101046_create_automation_rules.rb
  db/schema.rb
  lib/automation_rules/conditions.json
  spec/controllers/api/v1/accounts/automation_rules_controller_spec.rb
  spec/factories/automation_rules.rb
  spec/listeners/automation_rule_listener_spec.rb
  spec/models/automation_rule_spec.rb
Labels: feature, PR: unreviewed, PR: partially-approved

#3605 feat: Toggle to disallow users to send messages after a conversation is resolved
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/widget/components/ChatFooter.vue
  app/models/inbox.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  app/views/widgets/show.html.erb
  db/migrate/20211216110209_add_allow_messages_after_resolved_to_inbox.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
Labels: PR: partially-approved

#3724 Fix german translations
  config/locales/de.yml
Labels: PR: reviewed-approved

#3730 chore: Prevent null in Contact JSONB attributes
  .rubocop.yml
  app/models/contact.rb
  db/migrate/20220111200105_update_nil_contact_attributes_to_empty_hash.rb
  db/schema.rb
  spec/models/contact_spec.rb
Labels: PR: unreviewed

#3708 Closes #3672 Updated short code typo
  app/javascript/dashboard/i18n/locale/en/cannedMgmt.json
Labels: PR: unreviewed

#3733 chore: SuperAdmin Improvements
  app/dashboards/agent_bot_dashboard.rb
  app/fields/avatar_field.rb
  app/models/platform_app_permissible.rb
  app/views/fields/avatar_field/_index.html.erb
  app/views/fields/avatar_field/_show.html.erb
  app/views/super_admin/application/_navigation.html.erb
  app/views/super_admin/application/index.html.erb
  app/views/super_admin/users/index.html.erb
  db/migrate/20220111223630_remove_platform_app_permissible_access_tokens.rb
  db/schema.rb
  public/admin/avatar.png
  public/admin/avatar_square.png
Labels: PR: unreviewed

#3702 chore: revert GlobalConfig changes
  app/controllers/api/v1/accounts_controller.rb
  lib/global_config_service.rb
  spec/controllers/api/v1/accounts_controller_spec.rb
  spec/lib/global_config_service_spec.rb
Labels: PR: unreviewed

#3415 feat: Use vue-router on widget route management
  app/javascript/dashboard/components/widgets/Avatar.vue
  app/javascript/packs/widget.js
  app/javascript/sdk/IFrameHelper.js
  app/javascript/shared/components/FluentIcon/icons.json
  app/javascript/widget/App.vue
  app/javascript/widget/assets/scss/woot.scss
  app/javascript/widget/components/ChatFooter.vue
  app/javascript/widget/components/ChatHeader.vue
  app/javascript/widget/components/ChatHeaderExpanded.vue
  app/javascript/widget/components/ChatInputWrap.vue
  app/javascript/widget/components/HeaderActions.vue
  app/javascript/widget/components/PreChat/Form.vue
  app/javascript/widget/components/TeamAvailability.vue
  app/javascript/widget/components/UnreadMessage.vue
  app/javascript/widget/components/UnreadMessageList.vue
  app/javascript/widget/components/layouts/ViewWithHeader.vue
  app/javascript/widget/constants/widgetBusEvents.js
  app/javascript/widget/helpers/actionCable.js
  app/javascript/widget/i18n/locale/en.json
  app/javascript/widget/mixins/configMixin.js
  app/javascript/widget/mixins/routerMixin.js
  app/javascript/widget/router.js
  app/javascript/widget/store/modules/appConfig.js
  app/javascript/widget/store/modules/campaign.js
  app/javascript/widget/store/modules/events.js
  app/javascript/widget/store/modules/specs/agent/mutations.spec.js
  app/javascript/widget/store/modules/specs/appConfig/actions.spec.js
  app/javascript/widget/store/modules/specs/appConfig/mutations.spec.js
  app/javascript/widget/store/modules/specs/campaign/actions.spec.js
  app/javascript/widget/store/modules/specs/campaign/getters.spec.js
  app/javascript/widget/store/modules/specs/campaign/mutations.spec.js
  app/javascript/widget/store/types.js
  app/javascript/widget/views/Campaigns.vue
  app/javascript/widget/views/Home.vue
  app/javascript/widget/views/Messages.vue
  app/javascript/widget/views/PreChatForm.vue
  app/javascript/widget/views/Router.vue
  app/javascript/widget/views/UnreadMessages.vue
Labels: PR: unreviewed

#3658 fix: Fixes widget unread view blocking parent page
  app/javascript/sdk/IFrameHelper.js
  app/javascript/sdk/sdk.js
  app/javascript/widget/App.vue
  app/javascript/widget/helpers/IframeEventHelper.js
Labels: PR: unreviewed

#3750 chore: Fix 360Dialog template message breakage
  app/services/whatsapp/send_on_whatsapp_service.rb
  spec/factories/channel/channel_whatsapp.rb
  spec/services/whatsapp/send_on_whatsapp_service_spec.rb
Labels: PR: unreviewed

#3751 chore: Support Whatsapp Interactive messages (360Dialog)
  app/services/whatsapp/incoming_message_service.rb
  spec/services/whatsapp/incoming_message_service_spec.rb
Labels: PR: unreviewed

#3564 Feat: Automations Actions
  app/controllers/api/v1/accounts/automation_rules_controller.rb
  app/listeners/automation_rule_listener.rb
  app/models/automation_rule.rb
  app/services/automation_rules/action_service.rb
  app/services/automation_rules/conditions_filter_service.rb
  app/services/filter_service.rb
  app/views/api/v1/accounts/automation_rules/index.json.jbuilder
  app/views/api/v1/accounts/automation_rules/partials/_automation_rule.json.jbuilder
  db/migrate/20220110090126_add_active_flag_to_automation_rule.rb
  db/schema.rb
  lib/filters/filter_keys.json
  spec/controllers/api/v1/accounts/automation_rules_controller_spec.rb
  spec/listeners/automation_rule_listener_spec.rb
Labels: PR: unreviewed

#3756 fix: Update broken CSS Styles in liquid template
  app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_assignment.liquid
  app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_creation.liquid
  app/views/mailers/conversation_reply_mailer/reply_with_summary.html.erb
Labels: PR: unreviewed

#3754 fix: fixes private note not getting added on twitter channel
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: unreviewed

#3753 fix: Contact bio overflow issue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
Labels: PR: unreviewed

#3711 Chore: Add redirect link to conversation in success message
  app/javascript/dashboard/assets/scss/widgets/_snackbar.scss
  app/javascript/dashboard/components/Snackbar.vue
  app/javascript/dashboard/components/SnackbarContainer.vue
  app/javascript/dashboard/components/widgets/conversation/specs/MoreActions.spec.js
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/NewConversation.vue
  app/javascript/dashboard/store/modules/contactConversations.js
  app/javascript/shared/mixins/alertMixin.js
Labels: PR: unreviewed

#3763 chore: Clean up Assignment logic
  app/models/concerns/assignment_handler.rb
  app/models/notification.rb
Labels: PR: unreviewed

#3666 feat: Adds the ability to save, render it on the sidebar and shows conversations when the user clicks the sidebar.
  app/javascript/dashboard/api/customViews.js
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/config/sidebarItems/conversations.js
  app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/helper/URLHelper.js
  app/javascript/dashboard/i18n/locale/en/advancedFilters.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
  app/javascript/dashboard/routes/dashboard/conversation/conversation.routes.js
  app/javascript/dashboard/routes/dashboard/customviews/AddCustomViews.vue
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/customViews.js
  app/javascript/dashboard/store/modules/specs/customViews/actions.spec.js
  app/javascript/dashboard/store/modules/specs/customViews/fixtures.js
  app/javascript/dashboard/store/modules/specs/customViews/getters.spec.js
  app/javascript/dashboard/store/modules/specs/customViews/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: PR: partially-approved

#3747 Fix: Pagination bug with filters payload
  app/javascript/dashboard/components/widgets/conversation/ConversationAdvancedFilter.vue
  app/javascript/dashboard/helper/filterQueryGenerator.js
  app/javascript/dashboard/helper/specs/filterQueryGenerator.spec.js
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsAdvancedFilters.vue
Labels: PR: partially-approved

#3774 fix: Background inconsistencies with campaigns table
  app/javascript/dashboard/routes/dashboard/settings/campaigns/CampaignsTable.vue
Labels: PR: reviewed-approved

#3780 feat: Adds the ability to delete the saved custom views
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/i18n/locale/en/advancedFilters.json
  app/javascript/dashboard/routes/dashboard/customviews/DeleteCustomViews.vue
Labels: PR: partially-approved

#3778 Enhancement: Add background color to draggable blocks in the sidebar
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
Labels: PR: reviewed-approved

#3806 fix: Fixes alignment of widget unread view close button
  app/javascript/widget/components/UnreadMessageList.vue
Labels: PR: reviewed-approved

#3651 chore: Account auto resolution time validation
  app/javascript/dashboard/i18n/locale/bg/generalSettings.json
  app/javascript/dashboard/i18n/locale/en/generalSettings.json
  app/javascript/dashboard/i18n/locale/hi/generalSettings.json
  app/javascript/dashboard/i18n/locale/it/generalSettings.json
  app/javascript/dashboard/i18n/locale/ja/generalSettings.json
  app/javascript/dashboard/i18n/locale/ml/generalSettings.json
  app/javascript/dashboard/i18n/locale/ne/generalSettings.json
  app/javascript/dashboard/i18n/locale/nl/generalSettings.json
  app/javascript/dashboard/i18n/locale/ta/generalSettings.json
  app/javascript/dashboard/i18n/locale/th/generalSettings.json
  app/javascript/dashboard/i18n/locale/uk/generalSettings.json
  app/javascript/dashboard/i18n/locale/vi/generalSettings.json
  app/javascript/dashboard/i18n/locale/zh/generalSettings.json
  app/javascript/dashboard/i18n/locale/zh_TW/generalSettings.json
  app/javascript/dashboard/routes/dashboard/settings/account/Index.vue
  app/models/account.rb
  spec/models/account_spec.rb
Labels: PR: partially-approved

#3803 fix: File and emoji pickers are disabled by default
  app/javascript/dashboard/store/modules/inboxes.js
Labels: PR: partially-approved

#3808 feat: Display saved filter in the sidebar under segments section
  app/javascript/dashboard/api/customViews.js
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/config/sidebarItems/contacts.js
  app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue
  app/javascript/dashboard/routes/dashboard/contacts/routes.js
  app/javascript/dashboard/store/modules/customViews.js
  app/javascript/dashboard/store/modules/specs/customViews/fixtures.js
  app/javascript/dashboard/store/modules/specs/customViews/getters.spec.js
Labels: PR: partially-approved

#3782 feat: Clone and update automation rules
  app/controllers/api/v1/accounts/automation_rules_controller.rb
  app/listeners/automation_rule_listener.rb
  app/policies/automation_rule_policy.rb
  app/views/api/v1/accounts/automation_rules/clone.json.jbuilder
  app/views/api/v1/accounts/automation_rules/show.json.jbuilder
  app/views/api/v1/accounts/automation_rules/update.json.jbuilder
  config/routes.rb
  lib/filters/filter_keys.json
  spec/controllers/api/v1/accounts/automation_rules_controller_spec.rb
Labels: PR: partially-approved

#3659 Fix: Email Parsing for html fix
  app/presenters/mail_presenter.rb
  spec/fixtures/files/mail_with_quote.eml
  spec/mailboxes/reply_mailbox_spec.rb
Labels: PR: unreviewed

#3823 feat: Support 360Dialog Interactive Templates
  app/services/whatsapp/incoming_message_service.rb
  spec/services/whatsapp/incoming_message_service_spec.rb
Labels: PR: unreviewed

#3791 feat: Add the ability to save filters for contact
  app/javascript/dashboard/api/customViews.js
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/config/sidebarItems/contacts.js
  app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue
  app/javascript/dashboard/routes/dashboard/contacts/routes.js
  app/javascript/dashboard/store/modules/customViews.js
  app/javascript/dashboard/store/modules/specs/customViews/fixtures.js
  app/javascript/dashboard/store/modules/specs/customViews/getters.spec.js
Labels: PR: partially-approved

#3832 fix: Fixes typo in documentation for sidebar
  app/javascript/dashboard/i18n/locale/en/teamsSettings.json
Labels: PR: reviewed-approved

#3836 feat: Adds the ability to delete a segment
  app/javascript/dashboard/api/customViews.js
  app/javascript/dashboard/i18n/locale/en/advancedFilters.json
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue
  app/javascript/dashboard/routes/dashboard/customviews/DeleteCustomViews.vue
  app/javascript/dashboard/store/modules/customViews.js
  app/javascript/dashboard/store/modules/specs/customViews/actions.spec.js
Labels: PR: unreviewed

#3748 feat: Support multiple file upload on dashboard
  app/javascript/dashboard/api/inbox/message.js
  app/javascript/dashboard/api/specs/inbox/message.spec.js
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: unreviewed

#3847 fix: Return if window.$chatwoot is already defined
  app/javascript/packs/sdk.js
Labels: PR: reviewed-approved

#3830 feat: Unify user and super admin credentials
  app/builders/account_builder.rb
  app/controllers/installation/onboarding_controller.rb
  app/controllers/super_admin/devise/sessions_controller.rb
  app/controllers/super_admin/super_admins_controller.rb
  app/controllers/super_admin/users_controller.rb
  app/dashboards/super_admin_dashboard.rb
  app/dashboards/user_dashboard.rb
  app/models/concerns/avatarable.rb
  app/models/super_admin.rb
  app/models/user.rb
  app/views/fields/belongs_to/_form.html.erb
  app/views/fields/belongs_to/_index.html.erb
  app/views/fields/belongs_to/_show.html.erb
  app/views/fields/polymorphic/_form.html.erb
  app/views/fields/polymorphic/_index.html.erb
  app/views/fields/polymorphic/_show.html.erb
  app/views/super_admin/application/_navigation.html.erb
  app/views/super_admin/users/_collection.html.erb
  config/initializers/rack_attack.rb
  config/routes.rb
  db/migrate/20220121055444_add_type_to_users.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/super_admin/access_tokens_controller_spec.rb
  spec/controllers/super_admin/account_users_controller_spec.rb
  spec/controllers/super_admin/accounts_controller_spec.rb
  spec/controllers/super_admin/agent_bots_controller_spec.rb
  spec/controllers/super_admin/app_config_controller_spec.rb
  spec/controllers/super_admin/installation_configs_controller_spec.rb
  spec/controllers/super_admin/platform_apps_controller_spec.rb
  spec/controllers/super_admin/super_admins_controller_spec.rb
  spec/controllers/super_admin/users_controller_spec.rb
  spec/controllers/super_admin_controller_spec.rb
  spec/factories/super_admins.rb
Labels: PR: partially-approved

#3817 feat: Ability to toggle conversation continuity via email
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/models/channel/web_widget.rb
  app/models/message.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  config/routes.rb
  db/migrate/20220119051739_enable_conversation_continuity.rb
  db/schema.rb
  spec/models/message_spec.rb
Labels: PR: unreviewed

#3849 bug: validate avatar only if it has changed
  app/models/concerns/avatarable.rb
Labels: PR: unreviewed

#3858 fix: Fix email template to render the chat bubble properly
  app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_assignment.liquid
  app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_creation.liquid
  app/views/mailers/agent_notifications/conversation_notifications_mailer/conversation_mention.liquid
Labels: PR: reviewed-approved

#3838 enhancement: Custom views
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/layout/config/sidebarItems/contacts.js
  app/javascript/dashboard/components/layout/config/sidebarItems/conversations.js
  app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/helper/URLHelper.js
  app/javascript/dashboard/i18n/locale/en/advancedFilters.json
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue
  app/javascript/dashboard/routes/dashboard/contacts/routes.js
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
  app/javascript/dashboard/routes/dashboard/conversation/conversation.routes.js
  app/javascript/dashboard/routes/dashboard/customviews/AddCustomViews.vue
  app/javascript/dashboard/routes/dashboard/customviews/DeleteCustomViews.vue
Labels: PR: unreviewed

#3768 feat: Activestorage direct upload
  app/builders/messages/message_builder.rb
  app/controllers/api/v1/widget/messages_controller.rb
  app/javascript/dashboard/api/inbox/message.js
  app/javascript/dashboard/components/widgets/AttachmentsPreview.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/widget/api/endPoints.js
  app/javascript/widget/components/ChatAttachment.vue
  package.json
Labels: PR: partially-approved

#3841 update deployment scripts to install sudo
  deployment/setup_18.04.sh
  deployment/setup_20.04.sh
Labels: PR: reviewed-approved

#3861 bug: Fixes sidebar does not show an active page for settings page
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
Labels: PR: partially-approved

#3864 Fix: parse verification mail
  app/mailboxes/mailbox_helper.rb
  app/presenters/html_parser.rb
  app/presenters/mail_presenter.rb
Labels: PR: reviewed-approved

#3866 Feat/3567 direct uploads
  yarn.lock
Labels: PR: partially-approved
