Repository chatwoot/chatwoot, pull requests merged in 2022-04, with the labels that each got.

#4137 feat: Dark mode for the widget
  app/controllers/widget_tests_controller.rb
  app/javascript/dashboard/routes/dashboard/settings/agents/Index.vue
  app/javascript/packs/sdk.js
  app/javascript/sdk/IFrameHelper.js
  app/javascript/sdk/constants.js
  app/javascript/sdk/settingsHelper.js
  app/javascript/shared/components/ChatCard.vue
  app/javascript/shared/components/ChatForm.vue
  app/javascript/shared/components/ChatOption.vue
  app/javascript/shared/components/ChatOptions.vue
  app/javascript/shared/components/CustomerSatisfaction.vue
  app/javascript/shared/components/DateSeparator.vue
  app/javascript/shared/components/ResizableTextArea.vue
  app/javascript/shared/components/specs/DateSeparator.spec.js
  app/javascript/shared/components/specs/__snapshots__/DateSeparator.spec.js.snap
  app/javascript/widget/assets/scss/views/_conversation.scss
  app/javascript/widget/components/AgentMessage.vue
  app/javascript/widget/components/AgentMessageBubble.vue
  app/javascript/widget/components/AgentTypingBubble.vue
  app/javascript/widget/components/ChatHeader.vue
  app/javascript/widget/components/ChatHeaderExpanded.vue
  app/javascript/widget/components/ChatInputWrap.vue
  app/javascript/widget/components/Form/Input.vue
  app/javascript/widget/components/Form/TextArea.vue
  app/javascript/widget/components/HeaderActions.vue
  app/javascript/widget/components/PreChat/Form.vue
  app/javascript/widget/components/TeamAvailability.vue
  app/javascript/widget/components/UnreadMessage.vue
  app/javascript/widget/components/layouts/ViewWithHeader.vue
  app/javascript/widget/components/template/Article.vue
  app/javascript/widget/components/template/EmailInput.vue
  app/javascript/widget/mixins/darkModeMixin.js
  app/javascript/widget/mixins/specs/darkModeMixin.spec.js
  app/javascript/widget/store/modules/appConfig.js
  app/views/widget_tests/index.html.erb
  tailwind.config.js
Labels: PR: partially-approved

#4332 fixes: Login button is missing issue in Safari browser
  app/javascript/dashboard/components/buttons/FormSubmitButton.vue
Labels: PR: partially-approved

#4360 chore: Fix brand name in survey translations
  app/javascript/survey/i18n/locale/ar.json
Labels: PR: unreviewed

#4373 fix: Unread notification count in multiple accounts
  app/listeners/base_listener.rb
  app/models/user.rb
Labels: PR: reviewed-approved

#4357 Fix test failure in action_cable_listener_spec.rb due to ordering
  spec/listeners/action_cable_listener_spec.rb
Labels: PR: unreviewed

#4342 feat: add gh action to run CE edition tests
  .github/workflows/run-foss-spec.yml
Labels: PR: partially-approved

#4387 fix: Skip `contact_last_seen_at` in empty conversation payload
  app/views/api/v1/widget/messages/index.json.jbuilder
  spec/controllers/api/v1/widget/messages_controller_spec.rb
Labels: PR: partially-approved

#4385 feat: Ability to customize the online presence duration
  lib/online_status_tracker.rb
Labels: PR: reviewed-approved

#4370 Fix/381 automation validation
  app/javascript/dashboard/components/widgets/AutomationActionInput.vue
  app/javascript/dashboard/helper/actionQueryGenerator.js
  app/javascript/dashboard/routes/dashboard/settings/automation/AddAutomationRule.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/EditAutomationRule.vue
  app/models/automation_rule.rb
Labels: bug, PR: unreviewed, PR: reviewed-approved, PR: partially-approved

#4384 Fix: handling UTF encoded mail
  app/presenters/mail_presenter.rb
  spec/fixtures/files/non_utf_encoded_mail.eml
  spec/presenters/mail_presenter_spec.rb
Labels: PR: unreviewed

#4352 feat: Add an option to disable endConversation button
  app/controllers/api/v1/widget/conversations_controller.rb
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/widget/components/HeaderActions.vue
  app/javascript/widget/mixins/configMixin.js
  app/javascript/widget/mixins/specs/configMixin.spec.js
  app/models/channel/web_widget.rb
  db/migrate/20220405092033_update_web_widget_feature_flags.rb
  db/schema.rb
  spec/controllers/api/v1/widget/conversations_controller_spec.rb
Labels: PR: reviewed-approved

#4405 Fix
  app/javascript/dashboard/i18n/locale/en/teamsSettings.json
Labels: PR: reviewed-approved

#4406 feat: add gh action to build foss docker
  .github/workflows/publish_foss_docker.yml
  .github/workflows/run_foss_spec.yml
Labels: PR: partially-approved

#4403 chore: Remove unnecessary fields from notification payload
  app/models/notification.rb
Labels: PR: reviewed-approved

#4404 chore: fix scroll bar color in the dark mode
  app/javascript/widget/App.vue
Labels: PR: unreviewed

#4383 Feat - Sort inboxes alphabetically
  app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue
Labels: PR: unreviewed

#4303 fix: Audio notification would not work without action on the dashboard
  app/javascript/shared/helpers/AudioNotificationHelper.js
  app/javascript/shared/helpers/specs/AudioNotificationHelper.spec.js
Labels: PR: unreviewed

#4382 doc: Swagger for custom attribute APIs
  swagger/definitions/index.yml
  swagger/definitions/request/custom_attribute/create_update_payload.yml
  swagger/definitions/resource/custom_attribute.yml
  swagger/index.yml
  swagger/paths/application/custom_attributes/create.yml
  swagger/paths/application/custom_attributes/delete.yml
  swagger/paths/application/custom_attributes/index.yml
  swagger/paths/application/custom_attributes/show.yml
  swagger/paths/application/custom_attributes/update.yml
  swagger/paths/index.yml
  swagger/swagger.json
Labels: PR: reviewed-approved

#4205 feat: Adds support for draft in conversation reply box
  app/javascript/dashboard/components/app/UpdateBanner.vue
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/helper/localStorage.js
  app/javascript/dashboard/store/modules/auth.js
  app/javascript/dashboard/store/modules/conversations/helpers.js
  app/javascript/dashboard/store/modules/specs/conversations/helpers.spec.js
  app/javascript/dashboard/store/utils/api.js
  app/javascript/shared/helpers/TimeHelpers.js
  app/javascript/shared/helpers/specs/TimeHelpers.spec.js
Labels: PR: unreviewed

#4416 fix: Background colour issue in the unread message view
  app/javascript/widget/App.vue
  app/javascript/widget/components/ConversationWrap.vue
Labels: PR: partially-approved

#4372 Fix: Find mailbox with cc email
  app/finders/email_channel_finder.rb
  app/mailboxes/application_mailbox.rb
  app/mailboxes/mailbox_helper.rb
  app/mailboxes/support_mailbox.rb
  spec/finders/email_channel_finder_spec.rb
  spec/fixtures/files/in_reply_to.eml
  spec/fixtures/files/reply_cc.eml
  spec/mailboxes/application_mailbox_spec.rb
  spec/mailboxes/support_mailbox_spec.rb
Labels: PR: unreviewed

#4330 feat: Consider business hours while generating the reports
  Gemfile
  Gemfile.lock
  app/controllers/api/v2/accounts/reports_controller.rb
  app/helpers/report_helper.rb
  app/helpers/reporting_event_helper.rb
  app/javascript/dashboard/api/reports.js
  app/javascript/dashboard/assets/scss/widgets/_report.scss
  app/javascript/dashboard/assets/scss/widgets/_reports.scss
  app/javascript/dashboard/i18n/locale/en/report.json
  app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/FilterSelector.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/WootReports.vue
  app/javascript/dashboard/store/modules/reports.js
  app/listeners/reporting_event_listener.rb
  app/models/reporting_event.rb
  db/migrate/20220329131401_add_value_in_business_hours_to_reporting_event.rb
  db/schema.rb
  spec/listeners/reporting_event_listener_spec.rb
Labels: PR: partially-approved

#4419 feat: Add toggle button component
  app/javascript/dashboard/components/buttons/ToggleButton.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue
Labels: PR: reviewed-approved

#4421 feat: Add `phone_number` & `custom_attributes` in create conversation end point
  app/controllers/api/v1/widget/base_controller.rb
  app/controllers/api/v1/widget/conversations_controller.rb
  app/javascript/widget/api/endPoints.js
Labels: PR: partially-approved

#4425 Revert "feat: Adds support for draft in conversation reply box (#4205)"
  app/javascript/dashboard/components/app/UpdateBanner.vue
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/helper/localStorage.js
  app/javascript/dashboard/store/modules/auth.js
  app/javascript/dashboard/store/modules/conversations/helpers.js
  app/javascript/dashboard/store/modules/specs/conversations/helpers.spec.js
  app/javascript/dashboard/store/utils/api.js
  app/javascript/shared/helpers/TimeHelpers.js
  app/javascript/shared/helpers/specs/TimeHelpers.spec.js
Labels: PR: unreviewed

#4427 feat: Remove duplicate Switch Component
  app/javascript/dashboard/components/buttons/ToggleButton.vue
  app/javascript/dashboard/components/ui/Switch.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/FilterSelector.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue
Labels: PR: reviewed-approved

#4428 fix: SMTP shouldn't be configurable without IMAP enabled
  app/javascript/dashboard/components/SettingsSection.vue
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/ImapSettings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
Labels: PR: partially-approved

#4438 chore: Add missing test cases in `conversations_controller_spec`
  app/views/api/v1/widget/conversations/create.json.jbuilder
  spec/controllers/api/v1/widget/conversations_controller_spec.rb
Labels: PR: reviewed-approved

#4431 feat: Support additional authentication mechanisms for SMTP
  app/helpers/api/v1/inboxes_helper.rb
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/SmtpSettings.vue
  app/models/channel/email.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
Labels: PR: unreviewed

#4391 fix: Yellow color shades are inconsistent
  app/javascript/dashboard/assets/scss/_utility-helpers.scss
  app/javascript/dashboard/components/ui/Banner.vue
  app/javascript/dashboard/components/ui/Label.vue
  app/javascript/dashboard/components/widgets/Thumbnail.vue
  app/javascript/dashboard/components/widgets/conversation/AvailabilityStatusBadge.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
Labels: PR: reviewed-approved

#4435 fix: Remove IMAP and SMTP email validation
  app/helpers/api/v1/inboxes_helper.rb
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/ImapSettings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/SmtpSettings.vue
  app/jobs/inboxes/fetch_imap_emails_job.rb
  app/mailers/conversation_reply_mailer.rb
  app/mailers/conversation_reply_mailer_helper.rb
  app/models/channel/email.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  config/schedule.yml
  db/migrate/20220409044943_rename_imap_email_and_smtp_email_columns.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
  spec/jobs/inboxes/fetch_imap_email_inboxes_job_spec.rb
  spec/jobs/inboxes/fetch_imap_emails_job_spec.rb
  spec/mailboxes/imap/imap_mailbox_spec.rb
  spec/mailers/conversation_reply_mailer_spec.rb
Labels: PR: partially-approved

#4392 chore: Report improvements
  app/javascript/dashboard/i18n/locale/en/report.json
  app/javascript/dashboard/mixins/specs/reportMixin.spec.js
  app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/WootReports.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/constants.js
  app/javascript/dashboard/store/modules/reports.js
  package.json
  yarn.lock
Labels: PR: merged

#4441 feat: Adds the ability to validate password at signup
  app/javascript/dashboard/i18n/locale/en/signup.json
  app/javascript/dashboard/routes/auth/Signup.vue
  app/javascript/shared/helpers/Validators.js
  app/javascript/shared/helpers/specs/ValidatorsHelper.spec.js
Labels: PR: unreviewed

#4448 Fix: nokogiri bundle update
  Gemfile.lock
Labels: PR: reviewed-approved

#4429 Feat: twitter image support
  app/services/twitter/direct_message_parser_service.rb
  app/services/twitter/webhook_subscribe_service.rb
  spec/factories/twitter/twitter_dm_image_event.rb
  spec/lib/webhooks/twitter_spec.rb
Labels: PR: unreviewed

#4414 enhancement: Remove clickaway for expanded reply box
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
Labels: PR: unreviewed

#4423 enhancement: New Automation Actions
  app/controllers/api/v1/accounts/automation_rules_controller.rb
  app/javascript/dashboard/components/widgets/AutomationActionInput.vue
  app/javascript/dashboard/components/widgets/AutomationActionTeamMessageInput.vue
  app/javascript/dashboard/i18n/locale/en/automation.json
  app/javascript/dashboard/routes/dashboard/settings/automation/AddAutomationRule.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/EditAutomationRule.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
  app/listeners/automation_rule_listener.rb
  app/mailers/team_notifications/automation_notification_mailer.rb
  app/models/automation_rule.rb
  app/services/automation_rules/action_service.rb
  app/services/automation_rules/conditions_filter_service.rb
  spec/controllers/api/v1/accounts/automation_rules_controller_spec.rb
  spec/listeners/automation_rule_listener_spec.rb
Labels: PR: reviewed-approved

#4462 feat: add chatwoot_edition variable for CE docker images
  .github/workflows/publish_foss_docker.yml
  lib/chatwoot_hub.rb
Labels: PR: unreviewed

#4475 fix: Allow users to login even if they have access to more than 15 accounts
  app/javascript/dashboard/App.vue
  app/javascript/dashboard/api/auth.js
  app/javascript/dashboard/components/layout/AvailabilityStatus.vue
  app/javascript/dashboard/helper/APIHelper.js
  app/javascript/dashboard/helper/URLHelper.js
  app/javascript/dashboard/helper/actionCable.js
  app/javascript/dashboard/helper/pushHelper.js
  app/javascript/dashboard/helper/specs/URLHelper.spec.js
  app/javascript/dashboard/routes/dashboard/Dashboard.vue
  app/javascript/dashboard/routes/index.js
  app/javascript/dashboard/routes/index.spec.js
  app/javascript/dashboard/store/modules/auth.js
  app/javascript/dashboard/store/modules/conversations/getters.js
  app/javascript/dashboard/store/modules/specs/auth/actions.spec.js
  app/javascript/dashboard/store/modules/specs/auth/getters.spec.js
  app/javascript/dashboard/store/modules/specs/auth/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/dashboard/store/utils/api.js
  app/javascript/packs/application.js
Labels: PR: partially-approved

#4492 Fix: Changes report_type to type in report API docs
  swagger/parameters/report_type.yml
  swagger/swagger.json
Labels: PR: reviewed-approved

#4456 chore: Sync pre-chat fields after custom attribute destroy
  app/jobs/inboxes/sync_widget_pre_chat_custom_fields_job.rb
  app/models/custom_attribute_definition.rb
  spec/jobs/inboxes/sync_widget_pre_chat_custom_fields_job_spec.rb
Labels: PR: unreviewed

#4496 fix: Update between business hour calculation
  app/javascript/shared/helpers/DateHelper.js
  app/javascript/shared/helpers/specs/DateHelper.spec.js
  app/javascript/widget/components/TeamAvailability.vue
  app/javascript/widget/mixins/availability.js
  app/javascript/widget/mixins/specs/availabilityMixin.spec.js
  package.json
  yarn.lock
Labels: PR: partially-approved

#4495 fix: Agent typing indicator for website widget
  app/jobs/data_import_job.rb
  app/listeners/action_cable_listener.rb
  app/models/contact.rb
  db/migrate/20220418094715_remove_contact_pubsub_token.rb
  db/schema.rb
  spec/jobs/data_import_job_spec.rb
  spec/listeners/action_cable_listener_spec.rb
Labels: PR: unreviewed

#4439 Feat: send fb message outside of standard messaging window
  app/models/channel/facebook_page.rb
  app/models/conversation.rb
  app/services/facebook/send_on_facebook_service.rb
  spec/jobs/webhooks/instagram_events_job_spec.rb
  spec/models/conversation_spec.rb
  spec/services/facebook/send_on_facebook_service_spec.rb
Labels: PR: unreviewed

#4189 feat: Custom fields in pre-chat form
  app/javascript/dashboard/components/ui/Switch.vue
  app/javascript/dashboard/helper/preChat.js
  app/javascript/dashboard/helper/specs/inboxFixture.js
  app/javascript/dashboard/helper/specs/preChat.spec.js
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/PreChatForm/PreChatFields.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/PreChatForm/Settings.vue
  app/javascript/dashboard/store/modules/attributes.js
  app/javascript/dashboard/store/modules/specs/attributes/getters.spec.js
  app/javascript/packs/widget.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/javascript/widget/App.vue
  app/javascript/widget/components/PreChat/Form.vue
  app/javascript/widget/i18n/locale/en.json
  app/javascript/widget/mixins/configMixin.js
  app/javascript/widget/mixins/specs/configMixin.spec.js
  app/javascript/widget/views/Home.vue
  app/javascript/widget/views/PreChatForm.vue
  app/models/channel/web_widget.rb
  app/models/custom_attribute_definition.rb
  app/views/api/v1/widget/contacts/show.json.jbuilder
  app/views/api/v1/widget/contacts/update.json.jbuilder
  db/migrate/20220316054933_add_custom_fields_to_pre_chat_form.rb
  spec/models/channel/web_widget_spec.rb
  spec/models/channel/widget_test.rb
Labels: PR: unreviewed

#4463 chore: Add `custom attributes` in `campaign.triggered` event
  app/builders/campaigns/campaign_conversation_builder.rb
  app/javascript/widget/App.vue
  app/javascript/widget/api/campaign.js
  app/javascript/widget/api/endPoints.js
  app/javascript/widget/store/modules/campaign.js
  app/javascript/widget/views/PreChatForm.vue
  app/listeners/campaign_listener.rb
  spec/listeners/campaign_listener_spec.rb
Labels: PR: partially-approved

#4224 feat: Message Read Indicator
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
  app/javascript/dashboard/helper/actionCable.js
  app/javascript/dashboard/i18n/locale/en/chatlist.json
  app/javascript/dashboard/mixins/conversations.js
  app/javascript/dashboard/mixins/specs/conversaton.spec.js
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/getters.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/getters.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: PR: partially-approved

#4507 Chore: Provide fixed attachment URLs for Channels
  app/models/attachment.rb
  app/models/channel/telegram.rb
  app/models/channel/whatsapp.rb
  app/services/facebook/send_on_facebook_service.rb
  app/services/instagram/send_on_instagram_service.rb
  app/services/twilio/send_on_twilio_service.rb
  config/environments/test.rb
  lib/integrations/slack/send_on_slack_service.rb
  spec/models/attachment_spec.rb
  spec/services/facebook/send_on_facebook_service_spec.rb
  spec/services/sms/send_on_sms_service_spec.rb
Labels: PR: unreviewed

#4498 chore: Sanitize html content
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Text.vue
  app/javascript/dashboard/modules/contact/components/MergeContactSummary.vue
  app/javascript/dashboard/modules/notes/components/ContactNote.vue
  app/javascript/dashboard/routes/auth/Signup.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactCustomAttributes.vue
  app/javascript/dashboard/routes/dashboard/conversation/search/SearchMessageItem.vue
  app/javascript/dashboard/routes/dashboard/settings/SettingsSubPageHeader.vue
  app/javascript/dashboard/routes/dashboard/settings/agents/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/CustomAttribute.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/canned/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/integrationapps/MultipleIntegrationHooks.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/IntegrationHelpText.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/Webhook.vue
  app/javascript/dashboard/routes/dashboard/settings/labels/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/teams/Index.vue
  app/javascript/packs/application.js
  app/javascript/packs/widget.js
  app/javascript/shared/components/emoji/EmojiInput.vue
  app/javascript/widget/components/AgentMessageBubble.vue
  app/javascript/widget/components/ChatHeader.vue
  app/javascript/widget/components/ChatHeaderExpanded.vue
  app/javascript/widget/components/UnreadMessage.vue
  app/javascript/widget/components/UserMessageBubble.vue
  package.json
  yarn.lock
Labels: PR: partially-approved

#4521 fix: Issue with closed all hours
  app/javascript/widget/mixins/availability.js
  app/javascript/widget/mixins/specs/availabilityMixin.spec.js
Labels: PR: unreviewed

#4518 feat: Add support for conversation attribute automation conditions in message event
  app/builders/messages/message_builder.rb
  app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
  app/listeners/automation_rule_listener.rb
  app/models/automation_rule.rb
  app/services/automation_rules/action_service.rb
  app/services/automation_rules/conditions_filter_service.rb
  spec/listeners/automation_rule_listener_spec.rb
Labels: PR: reviewed-approved

#4480 Fix: Attachment endpoint to save file against automation rule
  app/controllers/api/v1/accounts/automation_rules_controller.rb
  app/javascript/dashboard/api/automation.js
  app/javascript/dashboard/components/widgets/AutomationActionInput.vue
  app/javascript/dashboard/components/widgets/AutomationFileInput.vue
  app/javascript/dashboard/helper/actionQueryGenerator.js
  app/javascript/dashboard/i18n/locale/en/automation.json
  app/javascript/dashboard/routes/dashboard/settings/automation/EditAutomationRule.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
  app/javascript/dashboard/store/modules/automations.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/models/attachment.rb
  app/models/automation_rule.rb
  app/policies/automation_rule_policy.rb
  app/services/automation_rules/action_service.rb
  app/views/api/v1/accounts/automation_rules/partials/_automation_rule.json.jbuilder
  config/routes.rb
  spec/controllers/api/v1/accounts/automation_rules_controller_spec.rb
  spec/listeners/automation_rule_listener_spec.rb
Labels: PR: partially-approved

#4519 fix: Bypass invalid values in contact patch end point
  app/models/contact.rb
  spec/controllers/api/v1/widget/contacts_controller_spec.rb
Labels: PR: unreviewed

#4540 feat: Add event subscription option to webhooks
  app/controllers/api/v1/accounts/webhooks_controller.rb
  app/javascript/dashboard/assets/scss/_utility-helpers.scss
  app/javascript/dashboard/components/widgets/ShowMore.vue
  app/javascript/dashboard/i18n/locale/en/integrations.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/integrations/EditWebHook.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/NewWebHook.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/Webhooks/EditWebHook.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/Webhooks/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/Webhooks/NewWebHook.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/Webhooks/WebhookForm.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/Webhooks/WebhookRow.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/Webhooks/specs/webhookMixin.spec.js
  app/javascript/dashboard/routes/dashboard/settings/integrations/Webhooks/webhookMixin.js
  app/javascript/dashboard/routes/dashboard/settings/integrations/integrations.routes.js
  app/javascript/dashboard/store/modules/webhooks.js
  app/listeners/webhook_listener.rb
  app/models/webhook.rb
  app/views/api/v1/accounts/webhooks/_webhook.json.jbuilder
  config/locales/en.yml
  db/migrate/20220424081117_add_subscriptions_to_webhooks.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/webhook_controller_spec.rb
  spec/factories/webhooks.rb
  spec/listeners/webhook_listener_spec.rb
Labels: PR: partially-approved

#4537 feat: Add reports about live agent load
  app/builders/v2/report_builder.rb
  app/controllers/api/v2/accounts/reports_controller.rb
  app/javascript/dashboard/api/reports.js
  app/javascript/dashboard/api/specs/reports.spec.js
  app/javascript/dashboard/components/layout/config/sidebarItems/reports.js
  app/javascript/dashboard/helper/actionCable.js
  app/javascript/dashboard/i18n/locale/en/generalSettings.json
  app/javascript/dashboard/i18n/locale/en/report.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/commands/CommandBarIcons.js
  app/javascript/dashboard/routes/dashboard/commands/goToCommandHotKeys.js
  app/javascript/dashboard/routes/dashboard/settings/reports/LiveReports.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/overview/AgentTable.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/overview/MetricCard.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/constants.js
  app/javascript/dashboard/routes/dashboard/settings/reports/reports.routes.js
  app/javascript/dashboard/store/modules/agents.js
  app/javascript/dashboard/store/modules/reports.js
  app/javascript/dashboard/store/modules/specs/agents/actions.spec.js
  app/javascript/dashboard/store/modules/specs/agents/getters.spec.js
  app/javascript/dashboard/store/modules/specs/agents/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/shared/helpers/vuex/mutationHelpers.js
  app/javascript/widget/store/modules/specs/agent/mutations.spec.js
  app/listeners/action_cable_listener.rb
  spec/controllers/api/v2/accounts/report_controller_spec.rb
  swagger/definitions/resource/reports/conversation/agent.yml
  swagger/swagger.json
Labels: PR: partially-approved

#4453 feat: Adds support for canned responses in contact messages
  app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
Labels: PR: unreviewed

#4551 fix: Check `phone_number` and `email` changes are exist before validation
  app/models/contact.rb
  spec/models/contact_spec.rb
Labels: PR: reviewed-approved

#4557 fix: Update agent metrics query to show data from current account
  app/builders/v2/report_builder.rb
  app/javascript/dashboard/i18n/locale/en/report.json
  app/javascript/dashboard/routes/dashboard/settings/reports/components/overview/AgentTable.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/constants.js
  spec/controllers/api/v2/accounts/report_controller_spec.rb
Labels: PR: partially-approved

#4545 Fix positioning of read ticks on attachment message bubbles
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
Labels: PR: partially-approved

#4570 chore: Upgrade rails to 6.1.5.1
  Gemfile.lock
Labels: PR: partially-approved

#4568 fix: Unattended conversation count in agent metrics
  app/builders/v2/report_builder.rb
  spec/controllers/api/v2/accounts/report_controller_spec.rb
Labels: PR: partially-approved

#4571 fix: Disable automation on tweets
  app/services/automation_rules/action_service.rb
  spec/listeners/automation_rule_listener_spec.rb
Labels: PR: unreviewed

#4511 chore: Allow Facebook channel to receive standby messages
  app/models/channel/facebook_page.rb
  lib/integrations/facebook/message_parser.rb
  lib/integrations/slack/incoming_message_builder.rb
Labels: PR: unreviewed

#4577 fix: Add index in conversation and reporting event
  app/models/conversation.rb
  app/models/reporting_event.rb
  db/migrate/20220428101325_add_index_to_conversation_and_reporting_event.rb
  db/schema.rb
Labels: PR: unreviewed

#4494 Fix: Slack update for file upload
  spec/support/slack_stubs.rb
Labels: PR: unreviewed

#4581 Fix: sidekiq cron deprecation warnings
  Gemfile
  Gemfile.lock
Labels: PR: reviewed-approved

#4580 Fix: Accept phone number in public contact api
  app/controllers/public/api/v1/inboxes/contacts_controller.rb
  app/views/public/api/v1/models/_contact.json.jbuilder
  spec/controllers/public/api/v1/inbox/contacts_controller_spec.rb
  swagger/definitions/request/public/contact/create_update_payload.yml
  swagger/swagger.json
Labels: PR: reviewed-approved
