Repository chatwoot/chatwoot, pull requests merged in 2022-02, with the labels that each got.

#3880 Fixes #3879 Fixes the inclusive lang
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
Labels: PR: reviewed-approved

#3871 chore: Use globalConfig in NetworkNotification
  app/javascript/dashboard/components/NetworkNotification.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/widget/components/ChatAttachment.vue
Labels: PR: unreviewed

#3851 feature: Filtering conversations and contacts with custom attributes
  .codeclimate.yml
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/ui/DateTimePicker.vue
  app/javascript/dashboard/components/widgets/FilterInput/FilterOperatorTypes.js
  app/javascript/dashboard/components/widgets/FilterInput/Index.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationAdvancedFilter.vue
  app/javascript/dashboard/components/widgets/conversation/advancedFilterItems/index.js
  app/javascript/dashboard/i18n/locale/en/advancedFilters.json
  app/javascript/dashboard/i18n/locale/en/contactFilters.json
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsAdvancedFilters.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
  app/javascript/dashboard/routes/dashboard/contacts/contactFilterItems/index.js
  app/javascript/shared/mixins/filterMixin.js
  app/javascript/shared/mixins/specs/MockComponent.vue
  app/javascript/shared/mixins/specs/filterFixtures.js
  app/javascript/shared/mixins/specs/filterMixin.spec.js
Labels: PR: partially-approved, in-QA

#3812 chore: add aws rds root cert for tls connection
  config/rds-ca-2019-root.pem
Labels: PR: unreviewed

#3884 feat: Shows agent avatar for message sent by agent
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
Labels: PR: unreviewed

#3459 feat: Add the ability to add new automation rule
  .codeclimate.yml
  app/javascript/dashboard/api/automation.js
  app/javascript/dashboard/api/specs/automation.spec.js
  app/javascript/dashboard/components/layout/config/sidebarItems/settings.js
  app/javascript/dashboard/components/widgets/AutomationActionInput.vue
  app/javascript/dashboard/components/widgets/FilterInput/Index.vue
  app/javascript/dashboard/helper/actionQueryGenerator.js
  app/javascript/dashboard/helper/specs/actionQueryGenerator.spec.js
  app/javascript/dashboard/i18n/locale/en/automation.json
  app/javascript/dashboard/routes/dashboard/settings/automation/AddAutomationRule.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/automation.routes.js
  app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
  app/javascript/dashboard/routes/dashboard/settings/settings.routes.js
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/automations.js
  app/javascript/dashboard/store/modules/specs/automations/actions.spec.js
  app/javascript/dashboard/store/modules/specs/automations/fixtures.js
  app/javascript/dashboard/store/modules/specs/automations/getters.spec.js
  app/javascript/dashboard/store/modules/specs/automations/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/listeners/automation_rule_listener.rb
Labels: frontend, PR: unreviewed, PR: partially-approved

#3874 feat: Email signature API support
  app/controllers/api/v1/profiles_controller.rb
  app/models/super_admin.rb
  app/models/user.rb
  app/views/api/v1/models/_user.json.jbuilder
  app/views/platform/api/v1/models/_user.json.jbuilder
  db/migrate/20220131081750_add_email_signature_to_user.rb
  db/schema.rb
  spec/controllers/api/v1/profiles_controller_spec.rb
Labels: PR: partially-approved

#3878 Fix: Added the backend validation for name
  app/models/account.rb
  app/models/contact.rb
  app/models/message.rb
  app/models/user.rb
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
  spec/controllers/api/v1/accounts/conversations/messages_controller_spec.rb
  spec/controllers/api/v1/accounts_controller_spec.rb
  spec/controllers/api/v1/profiles_controller_spec.rb
  spec/controllers/api/v1/widget/messages_controller_spec.rb
  spec/controllers/public/api/v1/inbox/messages_controller_spec.rb
Labels: PR: partially-approved

#3893 Feat: Clone automation
  app/javascript/dashboard/api/automation.js
  app/javascript/dashboard/api/specs/automation.spec.js
  app/javascript/dashboard/i18n/locale/en/automation.json
  app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue
  app/javascript/dashboard/store/modules/automations.js
  app/javascript/dashboard/store/modules/specs/automations/actions.spec.js
Labels: PR: partially-approved

#3839 chore: Add custom attributes in conversation webhook payload
  app/presenters/conversations/event_data_presenter.rb
  spec/models/conversation_spec.rb
  spec/presenters/conversations/event_data_presenter_spec.rb
Labels: PR: unreviewed

#3894 fix: Update font-size/width to fix iOS input zoom
  app/javascript/widget/assets/scss/_forms.scss
  app/javascript/widget/components/ChatInputWrap.vue
  app/javascript/widget/components/template/EmailInput.vue
Labels: PR: reviewed-approved

#3900 chore: Add resolve action in Dialogflow Integration
  lib/integrations/dialogflow/processor_service.rb
  spec/lib/integrations/dialogflow/processor_service_spec.rb
Labels: PR: reviewed-approved

#3898 fix: Shows tooltip and avatar for template messages
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: reviewed-approved

#3895 Fix: Custom filter distinct select
  app/services/contacts/filter_service.rb
  spec/services/contacts/filter_service_spec.rb
Labels: PR: unreviewed, post-planning

#3889 chore: Provider APIs for SMS Channel - Bandwidth
  app/builders/contact_inbox_builder.rb
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/controllers/webhooks/sms_controller.rb
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/campaigns/AddCampaign.vue
  app/javascript/dashboard/routes/dashboard/settings/campaigns/EditCampaign.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/BandwidthSms.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Sms.vue
  app/javascript/dashboard/store/modules/inboxes.js
  app/javascript/dashboard/store/modules/specs/inboxes/fixtures.js
  app/javascript/dashboard/store/modules/specs/inboxes/getters.spec.js
  app/javascript/shared/mixins/inboxMixin.js
  app/jobs/send_reply_job.rb
  app/jobs/webhooks/sms_events_job.rb
  app/models/account.rb
  app/models/campaign.rb
  app/models/channel/sms.rb
  app/models/channel/whatsapp.rb
  app/models/inbox.rb
  app/services/contacts/contactable_inboxes_service.rb
  app/services/sms/incoming_message_service.rb
  app/services/sms/oneoff_sms_campaign_service.rb
  app/services/sms/send_on_sms_service.rb
  config/routes.rb
  db/migrate/20220129024443_add_sms_channel.rb
  db/schema.rb
  spec/builders/contact_inbox_builder_spec.rb
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
  spec/controllers/webhooks/sms_controller_spec.rb
  spec/factories/channel/channel_sms.rb
  spec/jobs/send_reply_job_spec.rb
  spec/jobs/webhooks/sms_events_job_spec.rb
  spec/models/campaign_spec.rb
  spec/services/contacts/contactable_inboxes_service_spec.rb
  spec/services/sms/incoming_message_service_spec.rb
  spec/services/sms/oneoff_sms_campaign_service_spec.rb
  spec/services/sms/send_on_sms_service_spec.rb
Labels: PR: unreviewed

#3908 Fix: Conversation filter permissions
  app/finders/conversation_finder.rb
  spec/finders/conversation_finder_spec.rb
Labels: PR: unreviewed

#3907 Allow Self Hosted Instances to use Support Inbox within Dashboard for Agents
  app/views/layouts/vueapp.html.erb
Labels: PR: reviewed-approved

#3892 feat: Add date custom filter
  app/services/contacts/filter_service.rb
  app/services/conversations/filter_service.rb
  app/services/filter_service.rb
  lib/filters/filter_keys.json
  spec/services/contacts/filter_service_spec.rb
  spec/services/conversations/filter_service_spec.rb
Labels: PR: partially-approved

#3890 fix: Ongoing campaign URL validation
  app/controllers/api/v1/accounts/campaigns_controller.rb
  app/models/campaign.rb
  spec/builders/campaigns/campaign_conversation_builder_spec.rb
  spec/controllers/api/v1/accounts/campaigns_controller_spec.rb
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
  spec/controllers/api/v1/widget/campaigns_controller_spec.rb
  spec/listeners/campaign_listener_spec.rb
  spec/models/campaign_spec.rb
Labels: PR: unreviewed

#3867 feat: Shows an alert while replying if chats are not assigned to them
  app/javascript/dashboard/components/ui/Banner.vue
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
Labels: PR: partially-approved

#3765 Update sv.json
  app/javascript/widget/i18n/locale/sv.json
Labels: PR: unreviewed

#3921 fix: Omit invalid urls in custom attributes
  app/javascript/dashboard/components/CustomAttribute.vue
  app/javascript/dashboard/helper/URLHelper.js
  app/javascript/dashboard/helper/specs/URLHelper.spec.js
  app/javascript/dashboard/mixins/attributeMixin.js
  app/javascript/dashboard/mixins/specs/attributeMixin.spec.js
Labels: PR: reviewed-approved

#3924 chore: Assign to agent who create new message from contact panel
  app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
  app/javascript/dashboard/store/modules/contactConversations.js
Labels: PR: partially-approved

#3926 Fix filter payload issue on conversation pagniation
  app/javascript/dashboard/helper/actionQueryGenerator.js
  app/javascript/dashboard/helper/filterQueryGenerator.js
  app/javascript/dashboard/helper/specs/filterQueryGenerator.spec.js
Labels: bug, PR: unreviewed, PR: reviewed-changes-requested, PR: partially-approved

#3929 fix: URL encode params on Platform API call
  app/controllers/platform/api/v1/users_controller.rb
  app/javascript/dashboard/routes/login/Login.vue
  spec/controllers/platform/api/v1/users_controller_spec.rb
Labels: PR: reviewed-approved

#3932 Fixes API call failing after opening the saved filter
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
Labels: PR: partially-approved

#3928 New Crowdin updates
  app/javascript/dashboard/i18n/locale/de/conversation.json
Labels: PR: unreviewed

#3933 feat: Show assignee name in folder view
  app/javascript/dashboard/components/ChatList.vue
Labels: PR: reviewed-approved

#3925 chore: Assign the conversation to agent who opens the conversation
  app/controllers/api/v1/accounts/conversations_controller.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
Labels: PR: partially-approved

#3885 Add openssl verify mode and email encryption for smtp configuration
  app/helpers/api/v1/inboxes_helper.rb
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/SmtpSettings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/InputRadioGroup.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/SingleSelectDropdown.vue
  app/mailers/conversation_reply_mailer_helper.rb
  app/models/channel/email.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  db/migrate/20220116103902_add_open_ssl_verify_mode_to_channel_email.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
Labels: PR: unreviewed

#3948 fix: Blank page after deleting contact
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
Labels: PR: partially-approved

#3955 fix: Fixes console error with image component in widget
  app/javascript/widget/components/ImageBubble.vue
Labels: PR: unreviewed

#3837 Prefer reply-to over from
  app/presenters/mail_presenter.rb
Labels: PR: partially-approved

#3957 fix: Icon colors are not recognizable in bubble
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
Labels: PR: unreviewed

#3960 chore: Reduces clutter in inbox settings page
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
Labels: PR: unreviewed

#3949 feat: Add `conversation_created` event in webhooks
  app/listeners/webhook_listener.rb
  spec/listeners/webhook_listener_spec.rb
Labels: PR: unreviewed

#3968 fix: campaign scheduled at json format
  app/views/api/v1/models/_campaign.json.jbuilder
  spec/controllers/api/v1/accounts/campaigns_controller_spec.rb
Labels: PR: unreviewed

#3974 feat: Show the sender email address
  app/javascript/dashboard/components/widgets/conversation/bubble/MailHead.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
Labels: PR: partially-approved

#3965 fix: Custom attribute not getting changed on conversations
  app/javascript/dashboard/components/CustomAttribute.vue
Labels: PR: partially-approved

#3946 feat: Ability for super admin to define account limits
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/controllers/super_admin/accounts_controller.rb
  app/dashboards/account_dashboard.rb
  app/fields/enterprise/account_limits_field.rb
  app/models/account.rb
  app/views/fields/account_limits_field/_form.html.erb
  app/views/fields/account_limits_field/_index.html.erb
  app/views/fields/account_limits_field/_show.html.erb
  enterprise/app/models/enterprise/account.rb
Labels: PR: reviewed-approved

#3977 fix: Use default from attribute if undefined
  app/javascript/dashboard/components/widgets/conversation/bubble/MailHead.vue
Labels: PR: reviewed-approved

#3964 fix: html content is available and mail_part empty
  app/presenters/mail_presenter.rb
  spec/fixtures/files/support_1.eml
  spec/mailboxes/support_mailbox_spec.rb
Labels: PR: unreviewed, post-planning

#3959 feat: add specs for reply-to
  app/presenters/mail_presenter.rb
  spec/fixtures/files/reply_to.eml
  spec/mailboxes/reply_mailbox_spec.rb
  spec/mailboxes/support_mailbox_spec.rb
Labels: PR: partially-approved

#3906 feat: Adds email signature form to profile settings
  app/javascript/dashboard/api/auth.js
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/profile/MessageSignature.vue
  app/javascript/dashboard/store/modules/auth.js
  app/javascript/dashboard/store/modules/specs/auth/getters.spec.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: PR: unreviewed

#3982 chore: Remove message_signature_enabled from users
  app/controllers/api/v1/profiles_controller.rb
  app/javascript/dashboard/api/auth.js
  app/javascript/dashboard/routes/dashboard/settings/profile/MessageSignature.vue
  app/models/super_admin.rb
  app/models/user.rb
  app/views/api/v1/models/_user.json.jbuilder
  app/views/platform/api/v1/models/_user.json.jbuilder
  db/migrate/20220215060751_remove_message_signature_enabled.rb
  db/schema.rb
  spec/controllers/api/v1/profiles_controller_spec.rb
Labels: PR: reviewed-approved

#3966 Chore/delayed deploy of direct uploads
  app/builders/messages/message_builder.rb
  app/controllers/api/v1/widget/messages_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/widgets_controller.rb
  app/javascript/dashboard/components/widgets/AttachmentsPreview.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/shared/store/globalConfig.js
  app/javascript/widget/api/endPoints.js
  app/javascript/widget/components/ChatAttachment.vue
  config/installation_config.yml
  db/migrate/20220207124741_add_direct_uploads_to_installation_config.rb
Labels: PR: partially-approved

#3973 feat: Group by filter in reports
  .codeclimate.yml
  app/builders/v2/report_builder.rb
  app/controllers/api/v2/accounts/reports_controller.rb
  app/javascript/dashboard/api/reports.js
  app/javascript/dashboard/i18n/locale/en/report.json
  app/javascript/dashboard/routes/dashboard/settings/reports/CsatResponses.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/FilterSelector.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/WootReports.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/constants.js
  app/javascript/dashboard/store/modules/reports.js
  config/locales/en.yml
  spec/builders/v2/report_builder_spec.rb
Labels: PR: partially-approved

#3985 fix: Auto reply on email inbox
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/models/message.rb
  app/workers/email_reply_worker.rb
  spec/models/message_spec.rb
Labels: PR: partially-approved

#3986 revert: "fix: html content is available and mail_part empty "
  app/presenters/mail_presenter.rb
  spec/fixtures/files/support_1.eml
  spec/mailboxes/support_mailbox_spec.rb
Labels: PR: reviewed-approved

#3989 chore: Discard activities from email notifiable messages
  app/models/message.rb
  spec/models/message_spec.rb
Labels: PR: unreviewed

#3978 fix: Throwing NavigationDuplicated error
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
Labels: PR: unreviewed

#3936 fix: Automation Bugs and minor enhancements
  app/javascript/dashboard/components/layout/config/sidebarItems/settings.js
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/i18n/locale/en/automation.json
  app/javascript/dashboard/routes/dashboard/settings/automation/AddAutomationRule.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/EditAutomationRule.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
  app/javascript/dashboard/store/modules/automations.js
  app/javascript/dashboard/store/modules/specs/automations/actions.spec.js
  app/javascript/dashboard/store/modules/specs/automations/fixtures.js
  app/javascript/dashboard/store/modules/specs/automations/mutations.spec.js
  app/listeners/automation_rule_listener.rb
  app/models/conversation.rb
  app/services/automation_rules/conditions_filter_service.rb
  app/views/api/v1/accounts/automation_rules/partials/_automation_rule.json.jbuilder
  lib/events/types.rb
  spec/listeners/automation_rule_listener_spec.rb
Labels: PR: partially-approved

#4009 fix: Lock icon colour issue in private messages
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/EditAutomationRule.vue
Labels: PR: partially-approved

#3764 fixes: New message created does not auto-scroll to the bottom
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: partially-approved

#4010 feat: Show refresh modal on action cable disconnect
  app/javascript/dashboard/components/NetworkNotification.vue
  app/javascript/shared/constants/busEvents.js
  app/javascript/shared/helpers/BaseActionCableConnector.js
Labels: PR: unreviewed

#4017 feat: Add hCaptcha for public forms
  app/controllers/api/v1/accounts_controller.rb
  app/controllers/dashboard_controller.rb
  app/javascript/dashboard/api/auth.js
  app/javascript/dashboard/routes/auth/Signup.vue
  app/javascript/shared/store/globalConfig.js
  config/installation_config.yml
  db/migrate/20220218120357_add_h_captcha_key.rb
  db/schema.rb
  lib/chatwoot_captcha.rb
  package.json
  spec/controllers/api/v1/accounts_controller_spec.rb
  spec/lib/chatwoot_captcha_spec.rb
  yarn.lock
Labels: PR: unreviewed

#3998 feat: Add `chatwoot:error` sdk event
  app/javascript/packs/sdk.js
  app/javascript/sdk/IFrameHelper.js
  app/javascript/sdk/cookieHelpers.js
  app/javascript/sdk/specs/cookieHelpers.spec.js
  app/javascript/shared/helpers/CustomEventHelper.js
  app/javascript/shared/helpers/specs/CustomEventHelper.spec.js
  app/javascript/specs/packs/sdk.spec.js
  app/javascript/widget/constants/errorTypes.js
  app/javascript/widget/constants/sdkEvents.js
  app/javascript/widget/store/modules/contacts.js
  app/javascript/widget/store/modules/specs/contact/actions.spec.js
  app/views/widget_tests/index.html.erb
Labels: PR: partially-approved

#4018 Fix: add option to choose 24 hour working slot
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/BusinessDay.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/helpers/businessHour.js
  app/javascript/dashboard/routes/dashboard/settings/inbox/helpers/specs/businessHour.spec.js
  app/javascript/widget/mixins/availability.js
  app/models/concerns/out_of_offisable.rb
  app/models/working_hour.rb
  db/migrate/20220216151613_add_open_all_day_to_working_hour.rb
  db/schema.rb
  spec/models/working_hour_spec.rb
Labels: PR: partially-approved

#4049 fix: Throwing error when click load more conversation
  app/javascript/dashboard/components/ChatList.vue
Labels: PR: partially-approved

#3934 feat: bulk actions to update status
  app/controllers/api/v1/accounts/bulk_actions_controller.rb
  app/jobs/bulk_actions_job.rb
  config/routes.rb
  spec/controllers/api/v1/accounts/bulk_actions_controller_spec.rb
  spec/jobs/bulk_actions_job_spec.rb
  spec/services/contacts/filter_service_spec.rb
Labels: PR: partially-approved

#4060 fix: nokogiri gem build failure in docker
  docker/Dockerfile
Labels: PR: unreviewed

#4030 Fix: show empty emails in chat screen
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: partially-approved

#4065 feat: Add `flat` design for widget
  app/controllers/widget_tests_controller.rb
  app/javascript/packs/sdk.js
  app/javascript/sdk/IFrameHelper.js
  app/javascript/sdk/bubbleHelpers.js
  app/javascript/sdk/constants.js
  app/javascript/sdk/cookieHelpers.js
  app/javascript/sdk/sdk.js
  app/javascript/sdk/settingsHelper.js
  app/javascript/sdk/specs/bubbleHelpers.spec.js
  app/javascript/sdk/specs/cookieHelpers.spec.js
  app/javascript/sdk/specs/settingsHelpers.spec.js
  app/javascript/specs/packs/sdk.spec.js
  app/javascript/widget/App.vue
  app/javascript/widget/assets/scss/woot.scss
  app/javascript/widget/components/ChatFooter.vue
  app/javascript/widget/components/layouts/ViewWithHeader.vue
  app/javascript/widget/store/modules/appConfig.js
  app/views/widget_tests/index.html.erb
Labels: PR: partially-approved

#4024 fix: Message signature going with other channels message
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
Labels: PR: unreviewed

#4071 fix: Automation loop on conversation_update
  app/models/conversation.rb
  spec/models/conversation_spec.rb
Labels: PR: reviewed-approved

#4027 fix: Consider timezone in the reports
  app/builders/v2/report_builder.rb
  app/controllers/api/v2/accounts/reports_controller.rb
  app/javascript/dashboard/api/reports.js
  app/javascript/dashboard/api/specs/reports.spec.js
  app/javascript/dashboard/routes/dashboard/settings/reports/components/FilterSelector.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue
  app/javascript/dashboard/store/modules/reports.js
Labels: PR: unreviewed

#3958 feat: Add additional attributes in `setUser` method
  app/actions/contact_identify_action.rb
  app/controllers/api/v1/widget/contacts_controller.rb
  app/javascript/widget/store/modules/contacts.js
  spec/actions/contact_identify_action_spec.rb
Labels: PR: unreviewed

#4079 fix: Add resetTriggered flag to fix reset loop
  app/javascript/packs/sdk.js
  app/javascript/sdk/IFrameHelper.js
Labels: PR: reviewed-approved

#4080 chore: Add webhook URL validation
  app/models/webhook.rb
  spec/controllers/api/v1/accounts/webhook_controller_spec.rb
Labels: PR: unreviewed

#4072 feat: Format time in reports
  app/javascript/dashboard/assets/scss/widgets/_report.scss
  app/javascript/dashboard/store/modules/reports.js
  package.json
  yarn.lock
Labels: PR: partially-approved

#4044 Chore: clean up Reporting Events
  app/builders/v2/report_builder.rb
  app/dispatchers/async_dispatcher.rb
  app/helpers/api/v1/reports_helper.rb
  app/listeners/reporting_event_listener.rb
  app/listeners/reporting_listener.rb
  app/models/concerns/reportable.rb
  app/models/label.rb
  app/models/reporting_event.rb
  app/models/team.rb
  db/migrate/20210513143021_rename_events_to_report_events.rb
  db/schema.rb
  lib/reports/update_account_identity.rb
  lib/reports/update_agent_identity.rb
  lib/reports/update_identity.rb
  spec/builders/v2/report_builder_spec.rb
  spec/factories/reporting_events.rb
  spec/listeners/reporting_event_listener_spec.rb
  spec/models/account_spec.rb
  spec/models/inbox_spec.rb
  spec/models/reporting_event_spec.rb
  spec/models/user_spec.rb
Labels: PR: unreviewed

#4082 chore: Upgrade chatwoot utils to v0.0.5
  package.json
  yarn.lock
Labels: PR: unreviewed

#4081 fix: Handle invalid country code in contact details
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
Labels: PR: reviewed-approved

#3983 feat: Show cc from last email on reply editor
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyEmailHead.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/MailHead.vue
  app/javascript/dashboard/store/modules/conversations/getters.js
  app/javascript/dashboard/store/modules/specs/conversations/getters.spec.js
Labels: PR: unreviewed

#3956 fix: AudioContext warning when loading widget on Chrome
  app/javascript/packs/application.js
  app/javascript/packs/widget.js
  app/javascript/sdk/IFrameHelper.js
  app/javascript/shared/helpers/AudioNotificationHelper.js
Labels: PR: unreviewed
