Repository chatwoot/chatwoot, pull requests merged in 2022-12, with the labels that each got.

#6001 fix: Avoid conversationId getting undefined in unattended view
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: partially-approved

#5978 fix: Custom attr filter on conversations
  app/services/filter_service.rb
  spec/services/conversations/filter_service_spec.rb
Labels: PR: partially-approved

#6009 fix: Conversation View bugs
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/helper/URLHelper.js
  app/javascript/dashboard/routes/dashboard/commands/conversationHotKeys.js
Labels: PR: unreviewed

#5865 fix: Unable to add emoji exactly where the cursor is at
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: partially-approved

#5943 fix: Support audio in safari browser
  app/javascript/dashboard/components/widgets/WootWriter/AudioRecorder.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/shared/constants/messages.js
Labels: PR: unreviewed

#5349 fix: update heroku app.json to use premium plans
  app.json
Labels: PR: unreviewed, post-planning, on-hold, ready-for-pickup

#5928 feat: Adds the ability to search emojis and render
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/i18n/locale/en/emoji.json
  app/javascript/dashboard/i18n/locale/en/index.js
  app/javascript/shared/components/emoji/EmojiInput.vue
  app/javascript/shared/components/emoji/emojis.json
  app/javascript/shared/components/emoji/emojisGroup.json
  app/javascript/widget/components/ChatInputWrap.vue
  app/javascript/widget/i18n/locale/en.json
Labels: PR: unreviewed

#5994 Escape search term before building regular expression
  app/javascript/dashboard/routes/dashboard/conversation/search/SearchMessageItem.vue
Labels: PR: reviewed-approved

#5937 fix: Confirmation mail template on email update
  app/views/devise/mailer/confirmation_instructions.html.erb
  spec/mailers/confirmation_instructions_spec.rb
Labels: PR: reviewed-approved

#5961 fix: Send message with "enter" also do new line
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleEditor.vue
  app/javascript/shared/helpers/KeyboardHelpers.js
Labels: PR: partially-approved

#6006 fix: Filters are not applied unless I'm on the All Conversations screen
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryChildNavItem.vue
Labels: PR: unreviewed

#6037 chore: Add business email validation on signup
  app/javascript/dashboard/i18n/locale/en/signup.json
  app/javascript/dashboard/routes/auth/Signup.vue
  app/javascript/dashboard/routes/auth/auth.routes.js
  package.json
  yarn.lock
Labels: PR: unreviewed

#6002 feat: Update Signup screen
  app/javascript/dashboard/api/testimonials.js
  app/javascript/dashboard/constants.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/i18n/locale/en/signup.json
  app/javascript/dashboard/routes/auth/Signup.vue
  app/javascript/dashboard/routes/auth/auth.routes.js
  app/javascript/dashboard/routes/auth/components/AuthInput.vue
  app/javascript/dashboard/routes/auth/components/AuthSubmitButton.vue
  app/javascript/dashboard/routes/auth/components/Signup/Form.vue
  app/javascript/dashboard/routes/auth/components/Testimonials/Index.vue
  app/javascript/dashboard/routes/auth/components/Testimonials/TestimonialCard.vue
  app/javascript/dashboard/routes/auth/components/Testimonials/TestimonialFooter.vue
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/views/installation/onboarding/index.html.erb
  public/assets/images/auth/auth--bg.svg
  public/assets/images/auth/bottom-right.svg
  public/assets/images/auth/top-left.svg
Labels: PR: unreviewed

#6039 fix: Remove duplicate submit action
  app/javascript/dashboard/routes/auth/components/Signup/Form.vue
Labels: PR: unreviewed

#5300 fix: story mention
  app/builders/messages/messenger/message_builder.rb
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
  app/models/attachment.rb
  app/models/channel/facebook_page.rb
  app/models/concerns/message_filter_helpers.rb
  app/models/inbox.rb
  app/models/message.rb
  spec/builders/messages/instagram/message_builder_spec.rb
  spec/factories/channel/instagram_channel.rb
  spec/factories/messages.rb
  spec/jobs/webhooks/instagram_events_job_spec.rb
  spec/models/attachment_spec.rb
  spec/models/message_spec.rb
Labels: PR: unreviewed

#6050 chore: Update analytics events
  app/controllers/dashboard_controller.rb
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/helper/AnalyticsHelper/events.js
  app/javascript/dashboard/helper/AnalyticsHelper/index.js
  app/javascript/dashboard/helper/scriptHelpers.js
  app/javascript/dashboard/modules/contact/ContactMergeModal.vue
  app/javascript/dashboard/modules/conversations/components/MessageContextMenu.vue
  app/javascript/dashboard/routes/dashboard/conversation/Macros/MacroItem.vue
  app/javascript/dashboard/routes/index.js
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/inboxes.js
  app/javascript/packs/application.js
  app/views/layouts/vueapp.html.erb
  config/installation_config.yml
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#6052 fix: Unable to save automation "send email to team"
  app/javascript/dashboard/helper/actionQueryGenerator.js
Labels: PR: partially-approved

#6043 feat: Adds number validation for WhatsApp inbox at the creation step
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/360DialogWhatsapp.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/CloudWhatsapp.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Twilio.vue
  app/javascript/shared/helpers/Validators.js
  app/javascript/shared/helpers/specs/ValidatorsHelper.spec.js
Labels: PR: partially-approved

#6033 fix: Wrong color in widget see new message button
  app/javascript/dashboard/components/widgets/ColorPicker.vue
  app/javascript/dashboard/routes/auth/components/Testimonials/Index.vue
  app/javascript/sdk/IFrameHelper.js
  app/javascript/sdk/bubbleHelpers.js
  app/javascript/sdk/sdk.js
  app/javascript/shared/components/Spinner.vue
  app/javascript/shared/helpers/colorHelper.js
  app/javascript/shared/helpers/specs/colorHelper.spec.js
  app/javascript/widget/components/FileBubble.vue
  app/javascript/widget/components/UnreadMessageList.vue
  app/javascript/widget/components/UserMessage.vue
Labels: PR: unreviewed

#5778 chore: feature flags for campaigns and website channel
  app/javascript/dashboard/components/layout/config/sidebarItems/primaryMenu.js
  app/javascript/dashboard/components/widgets/ChannelItem.vue
  config/features.yml
  db/migrate/20221029202300_add_two_features_to_accounts.rb
  spec/controllers/platform/api/v1/accounts_controller_spec.rb
Labels: PR: unreviewed

#5959 fix issue in platform API accounts features update and show
  app/controllers/platform/api/v1/accounts_controller.rb
  app/models/concerns/featurable.rb
  app/views/platform/api/v1/models/_account.json.jbuilder
  spec/controllers/platform/api/v1/accounts_controller_spec.rb
Labels: PR: unreviewed

#6075 [Snyk] Fix for 7 vulnerabilities
  Gemfile
  Gemfile.lock
Labels: PR: unreviewed

#6067 fix: Allow editing label and placeholder for standard attributes in pre chat form
  app/javascript/dashboard/helper/preChat.js
  app/javascript/dashboard/routes/dashboard/settings/inbox/PreChatForm/PreChatFields.vue
  app/javascript/widget/components/PreChat/Form.vue
Labels: PR: partially-approved

#6081 fix: Helpcenter improvements
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalPopover.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSettingsBasicForm.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSwitch.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/ListAllCategories.vue
  app/javascript/dashboard/store/modules/helpCenterArticles/actions.js
Labels: PR: partially-approved

#6079 feat: Allow users to disable marking offline automatically
  app/controllers/api/v1/profiles_controller.rb
  app/javascript/dashboard/api/auth.js
  app/javascript/dashboard/api/endPoints.js
  app/javascript/dashboard/components/layout/AvailabilityStatus.vue
  app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue
  app/javascript/dashboard/components/ui/Switch.vue
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/store/modules/auth.js
  app/javascript/dashboard/store/modules/specs/auth/actions.spec.js
  app/javascript/shared/components/ui/dropdown/DropdownHeader.vue
  app/views/api/v1/profiles/auto_offline.jbuilder
  config/integration/apps.yml
  config/routes.rb
  spec/controllers/api/v1/profiles_controller_spec.rb
Labels: PR: unreviewed

#6088 feat: Display labels in the conversation card
  app/javascript/dashboard/components/ui/Label.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/components/widgets/conversation/conversationCardComponents/CardLabels.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
Labels: PR: unreviewed

#6093 fix: Update Slack integration to fix message delivery issues
  lib/integrations/slack/incoming_message_builder.rb
  lib/integrations/slack/send_on_slack_service.rb
  public/integrations/slack/contact.png
  public/integrations/slack/user.png
  spec/lib/integrations/slack/incoming_message_builder_spec.rb
  spec/lib/integrations/slack/send_on_slack_service_spec.rb
Labels: PR: unreviewed

#6061 Fix: automation email improvement
  app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
  app/models/automation_rule.rb
  lib/automation_rules/conditions.json
  spec/listeners/automation_rule_listener_spec.rb
Labels: PR: partially-approved

#5945 chore: Enable prototyping classes for foundation
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/assets/scss/_woot.scss
  app/javascript/dashboard/routes/dashboard/conversation/Macros/MacroItem.vue
  app/javascript/dashboard/routes/dashboard/conversation/Macros/MacroPreview.vue
  app/javascript/dashboard/routes/dashboard/conversation/labels/LabelBox.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/ActionButton.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroForm.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroNode.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroNodes.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/Pill.vue
  app/javascript/shared/assets/stylesheets/spacing.scss
Labels: PR: partially-approved

#6097 fix: Hide show more labels button when there's no overflow
  app/javascript/dashboard/assets/scss/widgets/_buttons.scss
  app/javascript/dashboard/components/ui/Label.vue
  app/javascript/dashboard/components/widgets/conversation/conversationCardComponents/CardLabels.vue
Labels: PR: unreviewed

#6096 chore: Cleanup feature flags
  app/javascript/dashboard/components/layout/config/sidebarItems/primaryMenu.js
  app/javascript/dashboard/components/layout/config/sidebarItems/settings.js
  app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/featureFlags.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/commands/goToCommandHotKeys.js
  app/javascript/dashboard/routes/dashboard/settings/account/Index.vue
  app/javascript/dashboard/store/modules/accounts.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/views/api/v1/models/_user.json.jbuilder
  config/features.yml
  db/migrate/20221219162759_enabled_new_features.rb
  db/schema.rb
Labels: PR: unreviewed

#6115 chore: Hide inbox name only has one inbox
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
Labels: PR: partially-approved

#6109 fix: Use canned response menu from the editor in contact messages
  app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
Labels: PR: partially-approved

#6107 fix: Update the logic to show read status for web
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Text.vue
  app/javascript/dashboard/mixins/conversations.js
Labels: PR: partially-approved

#6108 feat: Send audio longer than 10 seconds
  app/javascript/dashboard/components/widgets/WootWriter/AudioRecorder.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  config/webpack/environment.js
Labels: PR: reviewed-approved

#6098 chore: Helpcenter improvements
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSwitch.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue
Labels: PR: partially-approved

#6118 feat: Adds the ability to toggle the secondary sidebar in all display breakpoints
  app/javascript/dashboard/assets/scss/widgets/_sidemenu.scss
  app/javascript/dashboard/components/SidemenuIcon.vue
  app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue
  app/javascript/dashboard/components/specs/__snapshots__/SidemenuIcon.spec.js.snap
  app/javascript/dashboard/routes/dashboard/Dashboard.vue
  app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
Labels: PR: unreviewed

#6113 New Crowdin updates
  app/javascript/dashboard/i18n/locale/ar/settings.json
  app/javascript/dashboard/i18n/locale/bg/settings.json
  app/javascript/dashboard/i18n/locale/ca/settings.json
  app/javascript/dashboard/i18n/locale/cs/settings.json
  app/javascript/dashboard/i18n/locale/da/settings.json
  app/javascript/dashboard/i18n/locale/de/settings.json
  app/javascript/dashboard/i18n/locale/el/settings.json
  app/javascript/dashboard/i18n/locale/es/settings.json
  app/javascript/dashboard/i18n/locale/fa/settings.json
  app/javascript/dashboard/i18n/locale/fi/settings.json
  app/javascript/dashboard/i18n/locale/fr/advancedFilters.json
  app/javascript/dashboard/i18n/locale/fr/chatlist.json
  app/javascript/dashboard/i18n/locale/fr/contact.json
  app/javascript/dashboard/i18n/locale/fr/contactFilters.json
  app/javascript/dashboard/i18n/locale/fr/settings.json
  app/javascript/dashboard/i18n/locale/fr/signup.json
  app/javascript/dashboard/i18n/locale/he/settings.json
  app/javascript/dashboard/i18n/locale/hi/settings.json
  app/javascript/dashboard/i18n/locale/hu/settings.json
  app/javascript/dashboard/i18n/locale/id/settings.json
  app/javascript/dashboard/i18n/locale/is/settings.json
  app/javascript/dashboard/i18n/locale/it/settings.json
  app/javascript/dashboard/i18n/locale/ja/settings.json
  app/javascript/dashboard/i18n/locale/ka/settings.json
  app/javascript/dashboard/i18n/locale/ko/settings.json
  app/javascript/dashboard/i18n/locale/lt/settings.json
  app/javascript/dashboard/i18n/locale/lv/conversation.json
  app/javascript/dashboard/i18n/locale/lv/settings.json
  app/javascript/dashboard/i18n/locale/ml/settings.json
  app/javascript/dashboard/i18n/locale/ms/settings.json
  app/javascript/dashboard/i18n/locale/ne/settings.json
  app/javascript/dashboard/i18n/locale/nl/settings.json
  app/javascript/dashboard/i18n/locale/no/settings.json
  app/javascript/dashboard/i18n/locale/pl/settings.json
  app/javascript/dashboard/i18n/locale/pt/settings.json
  app/javascript/dashboard/i18n/locale/pt_BR/settings.json
  app/javascript/dashboard/i18n/locale/ro/settings.json
  app/javascript/dashboard/i18n/locale/ru/settings.json
  app/javascript/dashboard/i18n/locale/sk/settings.json
  app/javascript/dashboard/i18n/locale/sr/settings.json
  app/javascript/dashboard/i18n/locale/sv/settings.json
  app/javascript/dashboard/i18n/locale/ta/settings.json
  app/javascript/dashboard/i18n/locale/th/settings.json
  app/javascript/dashboard/i18n/locale/tr/settings.json
  app/javascript/dashboard/i18n/locale/uk/settings.json
  app/javascript/dashboard/i18n/locale/ur/settings.json
  app/javascript/dashboard/i18n/locale/ur_IN/settings.json
  app/javascript/dashboard/i18n/locale/vi/settings.json
  app/javascript/dashboard/i18n/locale/zh_CN/settings.json
  app/javascript/dashboard/i18n/locale/zh_TW/settings.json
  config/locales/fr.yml
Labels: PR: reviewed-approved

#6103 fix: Expand title height of textarea on load
  app/javascript/shared/components/ResizableTextArea.vue
Labels: PR: unreviewed

#6136 chore: Fixes issue showing the CSAT error message
  app/javascript/survey/views/Response.vue
Labels: PR: partially-approved

#6129 New Crowdin updates
  app/javascript/dashboard/i18n/locale/da/agentBots.json
  app/javascript/dashboard/i18n/locale/da/bulkActions.json
  app/javascript/dashboard/i18n/locale/da/conversation.json
  app/javascript/dashboard/i18n/locale/da/emoji.json
  app/javascript/dashboard/i18n/locale/da/generalSettings.json
  app/javascript/dashboard/i18n/locale/da/helpCenter.json
  app/javascript/dashboard/i18n/locale/da/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/da/macros.json
  app/javascript/dashboard/i18n/locale/da/settings.json
  app/javascript/dashboard/i18n/locale/da/signup.json
  app/javascript/dashboard/i18n/locale/es/signup.json
  app/javascript/widget/i18n/locale/da.json
  config/locales/da.yml
Labels: PR: unreviewed

#6141 feat: Adds new audio alert options
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/profile/NotificationSettings.vue
  app/javascript/shared/assets/audio/bell.mp3
  app/javascript/shared/helpers/AudioNotificationHelper.js
  public/audio/dashboard/bell.mp3
Labels: PR: reviewed-approved

#6149 fix: Update account limit selection logic
  enterprise/app/models/enterprise/account.rb
  spec/enterprise/models/account_spec.rb
Labels: PR: unreviewed

#6148 chore: Refactor audio notification helper
  app/javascript/dashboard/helper/AudioAlerts/DashboardAudioNotificationHelper.js
  app/javascript/dashboard/helper/AudioAlerts/faviconHelper.js
  app/javascript/dashboard/helper/actionCable.js
  app/javascript/dashboard/helper/scriptHelpers.js
  app/javascript/packs/application.js
  app/javascript/sdk/IFrameHelper.js
  app/javascript/shared/helpers/AudioNotificationHelper.js
  app/javascript/shared/helpers/specs/AudioNotificationHelper.spec.js
  app/javascript/widget/helpers/WidgetAudioNotificationHelper.js
  app/javascript/widget/helpers/actionCable.js
Labels: PR: unreviewed

#6150 feat: Adds the ability to play audio alert every 30 sec
  app/javascript/dashboard/helper/AudioAlerts/DashboardAudioNotificationHelper.js
  app/javascript/dashboard/helper/scriptHelpers.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/profile/NotificationSettings.vue
Labels: PR: unreviewed

#6151 chore: Refactor shortcuts modal to use modal component
  app/javascript/dashboard/components/widgets/modal/WootKeyShortcutModal.vue
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/Dashboard.vue
Labels: PR: unreviewed

#6154 fix: Update unread_messages count in WhatsApp inboxes
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js
  app/models/message.rb
Labels: PR: unreviewed
