Repository chatwoot/chatwoot, pull requests merged in 2022-06, with the labels that each got.

#4761 feat: Dashboard apps
  app/controllers/api/v1/accounts/dashboard_apps_controller.rb
  app/javascript/dashboard/api/dashboardApps.js
  app/javascript/dashboard/api/specs/dashboardApps.spec.js
  app/javascript/dashboard/components/widgets/DashboardApp/Frame.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/dashboardApps.js
  app/javascript/dashboard/store/modules/specs/dashboardApps/actions.spec.js
  app/javascript/dashboard/store/modules/specs/dashboardApps/getters.spec.js
  app/javascript/dashboard/store/modules/specs/dashboardApps/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/widget/store/modules/contacts.js
  app/models/account.rb
  app/models/dashboard_app.rb
  app/models/user.rb
  app/views/api/v1/accounts/dashboard_apps/create.json.jbuilder
  app/views/api/v1/accounts/dashboard_apps/index.json.jbuilder
  app/views/api/v1/accounts/dashboard_apps/show.json.jbuilder
  app/views/api/v1/accounts/dashboard_apps/update.json.jbuilder
  app/views/api/v1/models/_dashboard_app.json.jbuilder
  config/routes.rb
  db/migrate/20220525141844_create_dashboard_apps.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/dashboard_apps_controller_spec.rb
  spec/factories/dashboard_app.rb
Labels: PR: partially-approved

#4764 fix: Disable marking IMAP connection as invalid for Standard Errors
  app/jobs/inboxes/fetch_imap_emails_job.rb
  lib/chatwoot_exception_tracker.rb
  spec/lib/chatwoot_exception_tracker_spec.rb
Labels: PR: partially-approved

#4783 fix: command execution in heredoc comment
  deployment/setup_20.04.sh
Labels: PR: reviewed-approved

#4647 Feat: Bulk actions
  app/javascript/dashboard/api/bulkActions.js
  app/javascript/dashboard/api/specs/bulkAction.spec.js
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/Actions.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/AgentSelector.vue
  app/javascript/dashboard/i18n/locale/en/bulkActions.json
  app/javascript/dashboard/i18n/locale/en/index.js
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/bulkActions.js
  app/javascript/dashboard/store/modules/inboxAssignableAgents.js
  app/javascript/dashboard/store/modules/specs/bulkActions/actions.spec.js
  app/javascript/dashboard/store/modules/specs/bulkActions/fixtures.js
  app/javascript/dashboard/store/modules/specs/bulkActions/getters.spec.js
  app/javascript/dashboard/store/modules/specs/bulkActions/mutations.spec.js
  app/javascript/dashboard/store/modules/specs/inboxAssignableMembers/actions.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/shared/assets/stylesheets/colors.scss
  app/javascript/shared/assets/stylesheets/shadows.scss
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: frontend, feature, PR: unreviewed, PR: reviewed-changes-requested, PR: partially-approved

#4795 chore: Remove flay, rspec from development/test group
  Gemfile
  Gemfile.lock
Labels: PR: reviewed-approved

#4621 feat: Attribute changed filter for automations
  app/controllers/api/v1/accounts/automation_rules_controller.rb
  app/listeners/automation_rule_listener.rb
  app/services/automation_rules/conditions_filter_service.rb
  spec/listeners/automation_rule_listener_spec.rb
Labels: PR: partially-approved

#4711 feat: Add support for Whatsapp template messages in the UI
  app/builders/messages/message_builder.rb
  app/javascript/dashboard/api/inbox/message.js
  app/javascript/dashboard/components/Modal.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/conversation/WhatsappTemplates/Modal.vue
  app/javascript/dashboard/components/widgets/conversation/WhatsappTemplates/TemplateParser.vue
  app/javascript/dashboard/components/widgets/conversation/WhatsappTemplates/TemplatesPicker.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
  app/javascript/dashboard/components/widgets/forms/Input.vue
  app/javascript/dashboard/i18n/locale/en/index.js
  app/javascript/dashboard/i18n/locale/en/whatsappTemplates.json
  app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/WhatsappTemplates.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/store/modules/inboxes.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/models/channel/whatsapp.rb
  app/models/inbox.rb
  app/services/whatsapp/send_on_whatsapp_service.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  spec/services/whatsapp/send_on_whatsapp_service_spec.rb
Labels: frontend, PR: unreviewed, PR: draft

#4695 fix: Facebook reauthorization mailer
  app/builders/messages/facebook/message_builder.rb
  app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryChildNavItem.vue
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/helper/inbox.js
  app/javascript/dashboard/helper/specs/inbox.spec.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  spec/builders/messages/facebook/message_builder_spec.rb
  spec/models/channel/facebook_page_spec.rb
Labels: PR: unreviewed

#4790 Make "apk" commands consistent in Dockerfile
  docker/Dockerfile
Labels: PR: reviewed-approved

#4822 New Crowdin updates
  app/javascript/dashboard/i18n/locale/de/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/de/whatsappTemplates.json
  app/javascript/dashboard/i18n/locale/it/bulkActions.json
  app/javascript/dashboard/i18n/locale/it/settings.json
  app/javascript/dashboard/i18n/locale/it/whatsappTemplates.json
Labels: PR: unreviewed

#4820 fix: validations for whatsapp templates with no params
  app/javascript/dashboard/components/widgets/conversation/WhatsappTemplates/TemplateParser.vue
  app/javascript/shared/mixins/specs/whatsappTemplates/fixtures.js
  app/javascript/shared/mixins/specs/whatsappTemplates/whatsappTemplates.spec.js
Labels: PR: reviewed-approved

#4834 chore: upgrade FB api version
  app/controllers/dashboard_controller.rb
Labels: PR: reviewed-approved

#4835 chore: Add support for message_templates in API inbox
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/store/modules/inboxes.js
  app/models/channel/api.rb
  app/models/message.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  db/migrate/20220610091206_add_additional_attributes_to_api_channel.rb
  db/schema.rb
Labels: PR: partially-approved

#4838 New Crowdin updates
  app/javascript/dashboard/i18n/locale/es/advancedFilters.json
  app/javascript/dashboard/i18n/locale/es/automation.json
  app/javascript/dashboard/i18n/locale/es/bulkActions.json
  app/javascript/dashboard/i18n/locale/es/chatlist.json
  app/javascript/dashboard/i18n/locale/es/contactFilters.json
  app/javascript/dashboard/i18n/locale/es/conversation.json
  app/javascript/dashboard/i18n/locale/es/generalSettings.json
  app/javascript/dashboard/i18n/locale/es/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/es/integrations.json
  app/javascript/dashboard/i18n/locale/es/report.json
  app/javascript/dashboard/i18n/locale/es/settings.json
  app/javascript/dashboard/i18n/locale/es/signup.json
  app/javascript/dashboard/i18n/locale/es/teamsSettings.json
  app/javascript/dashboard/i18n/locale/es/whatsappTemplates.json
  app/javascript/dashboard/i18n/locale/ru/bulkActions.json
  app/javascript/dashboard/i18n/locale/ru/conversation.json
  app/javascript/dashboard/i18n/locale/ru/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/ru/report.json
  app/javascript/dashboard/i18n/locale/ru/settings.json
  app/javascript/dashboard/i18n/locale/ru/whatsappTemplates.json
  app/javascript/widget/i18n/locale/es.json
  config/locales/es.yml
Labels: PR: reviewed-approved

#4843 chore: Remove partner signup link
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/360DialogWhatsapp.vue
Labels: PR: unreviewed

#4830 Fix: backend changes for custom attribute
  app/controllers/api/v1/accounts/automation_rules_controller.rb
  app/javascript/dashboard/components/widgets/FilterInput/Index.vue
  app/services/automation_rules/conditions_filter_service.rb
  app/services/contacts/filter_service.rb
  app/services/conversations/filter_service.rb
  app/services/filter_service.rb
  spec/controllers/api/v1/accounts/automation_rules_controller_spec.rb
  spec/listeners/automation_rule_listener_spec.rb
Labels: PR: unreviewed

#4831 feat: Add snooze, reopen option to bulk actions
  app/javascript/dashboard/assets/scss/_utility-helpers.scss
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/AgentSelector.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/Index.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/UpdateActions.vue
  app/javascript/dashboard/i18n/locale/en/bulkActions.json
  app/javascript/shared/assets/stylesheets/z-index.scss
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: PR: unreviewed

#4777 feat: Article search
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/accounts/articles_controller.rb
  app/controllers/api/v1/accounts/categories_controller.rb
  app/models/article.rb
  app/models/category.rb
  app/models/user.rb
  app/views/api/v1/accounts/articles/_article.json.jbuilder
  app/views/api/v1/accounts/articles/create.json.jbuilder
  app/views/api/v1/accounts/articles/edit.json.jbuilder
  app/views/api/v1/accounts/articles/index.json.jbuilder
  app/views/api/v1/accounts/articles/show.json.jbuilder
  app/views/api/v1/accounts/articles/update.json.jbuilder
  app/views/api/v1/accounts/categories/_category.json.jbuilder
  config/routes.rb
  db/migrate/20220527080906_add_reference_for_author_id.rb
  db/migrate/20220527120826_add_index_on_category_slug_and_locale.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/articles_controller_spec.rb
  spec/controllers/api/v1/accounts/categories_controller_spec.rb
  spec/factories/articles.rb
  spec/models/article_spec.rb
  spec/models/category_spec.rb
Labels: PR: partially-approved

#4672 Feat: APIs to configure an auto assignment limit for inboxes
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/controllers/application_controller.rb
  app/controllers/dashboard_controller.rb
  app/helpers/api/v1/inboxes_helper.rb
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/CollaboratorsPage.vue
  app/javascript/shared/mixins/configMixin.js
  app/models/account.rb
  app/models/concerns/round_robin_handler.rb
  app/models/inbox.rb
  app/services/round_robin/manage_service.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  app/views/layouts/vueapp.html.erb
  db/migrate/20220527040433_add_auto_assignment_configuration_to_inboxes.rb
  db/schema.rb
  enterprise/app/controllers/enterprise/api/v1/accounts/inboxes_controller.rb
  enterprise/app/models/enterprise/inbox.rb
  spec/enterprise/controllers/api/v1/accounts/inboxes_controller_spec.rb
  spec/enterprise/models/inbox_spec.rb
  spec/services/round_robin/manage_service_spec.rb
Labels: PR: unreviewed, Enterprise

#4852 Chore: Automation rule api
  swagger/definitions/index.yml
  swagger/definitions/request/automation_rule/create_update_payload.yml
  swagger/definitions/resource/automation_rule.yml
  swagger/definitions/resource/contact.yml
  swagger/definitions/resource/conversation.yml
  swagger/index.yml
  swagger/paths/application/automation_rule/create.yml
  swagger/paths/application/automation_rule/delete.yml
  swagger/paths/application/automation_rule/index.yml
  swagger/paths/application/automation_rule/show.yml
  swagger/paths/application/automation_rule/update.yml
  swagger/paths/application/conversation/index.yml
  swagger/paths/application/custom_attributes/delete.yml
  swagger/paths/application/custom_attributes/show.yml
  swagger/paths/application/team_members/index.yml
  swagger/paths/index.yml
  swagger/swagger.json
Labels: PR: unreviewed

#4856 fix: Update profile settings header title
  app/javascript/dashboard/routes/dashboard/settings/profile/profile.routes.js
Labels: PR: unreviewed

#4854 feat: Bulk assign labels to conversations
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/AgentSelector.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/Index.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/LabelActions.vue
  app/javascript/dashboard/i18n/locale/en/bulkActions.json
Labels: PR: unreviewed

#4863 chore: Fix sentry issues
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/helpers/api/v1/inboxes_helper.rb
  app/javascript/dashboard/routes/dashboard/settings/inbox/ImapSettings.vue
  app/javascript/dashboard/store/modules/inboxes.js
  app/mailboxes/mailbox_helper.rb
  config/locales/en.yml
Labels: PR: partially-approved

#4727 chore: Copy change for automatic greeting message
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
Labels: PR: unreviewed

#4874 fix: Bulk actions agent loading
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/AgentSelector.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/LabelActions.vue
  app/javascript/shared/assets/stylesheets/spacing.scss
Labels: PR: reviewed-approved

#4867 chore: Codespace Improvements
  .devcontainer/Dockerfile
  .devcontainer/Dockerfile.base
  .devcontainer/devcontainer.json
  .devcontainer/scripts/setup.sh
Labels: PR: unreviewed

#4887 chore: Codespace Webpacker fix
  .devcontainer/scripts/setup.sh
Labels: PR: unreviewed

#4692 chore: Sync pre-chat fields after custom attribute update
  app/jobs/inboxes/update_widget_pre_chat_custom_fields_job.rb
  app/models/custom_attribute_definition.rb
  spec/jobs/inboxes/sync_widget_pre_chat_custom_fields_job_spec.rb
  spec/jobs/inboxes/update_widget_pre_chat_custom_fields_job_spec.rb
Labels: PR: unreviewed

#4325 feat: Changes theme of labels to smooth
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/components/ui/Label.vue
  app/javascript/dashboard/components/widgets/LabelSelector.vue
  app/javascript/dashboard/routes/dashboard/conversation/labels/LabelBox.vue
  app/javascript/shared/assets/stylesheets/colors.scss
  app/javascript/shared/components/ui/dropdown/AddLabel.vue
Labels: PR: reviewed-approved

#4893 fix: Display missing agent avatar in bulk actions and reports
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/AgentSelector.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue
Labels: bug, frontend, PR: unreviewed, PR: reviewed-approved

#4864 Feat: custom sort
  app/finders/conversation_finder.rb
  app/models/concerns/sort_handler.rb
  app/models/conversation.rb
  app/models/mention.rb
  spec/factories/mentions.rb
  spec/models/conversation_spec.rb
  spec/models/mention_spec.rb
Labels: PR: reviewed-approved

#4886 chore: Enhance contact merge action for identified users
  app/actions/contact_identify_action.rb
  app/controllers/api/v1/widget/base_controller.rb
  app/controllers/api/v1/widget/contacts_controller.rb
  app/controllers/api/v1/widget/conversations_controller.rb
  app/controllers/api/v1/widget/messages_controller.rb
  app/controllers/widgets_controller.rb
  app/helpers/widget_helper.rb
  app/javascript/sdk/IFrameHelper.js
  app/javascript/widget/App.vue
  app/javascript/widget/api/contacts.js
  app/javascript/widget/helpers/axios.js
  app/javascript/widget/helpers/utils.js
  app/javascript/widget/store/modules/contacts.js
  app/javascript/widget/store/modules/specs/contact/actions.spec.js
  app/views/api/v1/widget/contacts/set_user.json.jbuilder
  config/routes.rb
  spec/actions/contact_identify_action_spec.rb
  spec/controllers/api/v1/widget/contacts_controller_spec.rb
Labels: PR: reviewed-approved

#4913 feat: Add native support for CSML in agent_bot API
  app/controllers/api/v1/accounts/agent_bots_controller.rb
  app/javascript/widget/components/AgentMessage.vue
  app/javascript/widget/components/UserMessage.vue
  app/jobs/agent_bot_job.rb
  app/jobs/agent_bots/csml_job.rb
  app/jobs/agent_bots/webhook_job.rb
  app/listeners/agent_bot_listener.rb
  app/models/agent_bot.rb
  app/services/agent_bots/validate_bot_service.rb
  app/views/api/v1/models/_agent_bot.json.jbuilder
  config/installation_config.yml
  db/migrate/20220622090344_add_type_to_agent_bots.rb
  db/schema.rb
  lib/csml_engine.rb
  lib/integrations/bot_processor_service.rb
  lib/integrations/csml/processor_service.rb
  lib/integrations/dialogflow/processor_service.rb
  spec/factories/agent_bots.rb
  spec/jobs/agent_bots/csml_job_spec.rb
  spec/jobs/agent_bots/webhook_job_spec.rb
  spec/jobs/webhook_job_spec.rb
  spec/lib/csml_engine_spec.rb
  spec/lib/integrations/csml/processor_service_spec.rb
  spec/lib/integrations/dialogflow/processor_service_spec.rb
  spec/listeners/agent_bot_listener_spec.rb
  spec/services/agent_bots/validate_bot_service_spec.rb
Labels: PR: reviewed-approved

#4909 bug: Adds email validation in the email field of the new contact form
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactForm.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Email.vue
Labels: PR: unreviewed

#4919 chore: Revert the migration for inbox name changes
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/shared/helpers/Validators.js
  app/models/inbox.rb
  db/migrate/20220616154502_remove_special_characters_from_inbox_name.rb
Labels: PR: reviewed-approved

#4926 chore: Fix loader in inbox settings page
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/ImapSettings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/PreChatForm/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/SmtpSettings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Website.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/WeeklyAvailability.vue
  app/javascript/dashboard/store/modules/inboxes.js
  app/javascript/dashboard/store/modules/specs/inboxes/actions.spec.js
  app/javascript/dashboard/store/modules/specs/inboxes/getters.spec.js
  app/javascript/dashboard/store/utils/api.js
  app/javascript/dashboard/store/utils/specs/api.spec.js
Labels: PR: partially-approved

#4879 feat: Category API to handle linked categories and parent-sub categories
  app/controllers/api/v1/accounts/categories_controller.rb
  app/models/category.rb
  app/models/related_category.rb
  app/views/api/v1/accounts/categories/_associated_category.json.jbuilder
  app/views/api/v1/accounts/categories/_category.json.jbuilder
  app/views/api/v1/accounts/categories/show.json.jbuilder
  config/routes.rb
  db/migrate/20220623113405_add_parent_id_to_category.rb
  db/migrate/20220623113604_create_related_categories.rb
  db/migrate/20220627135753_add_linked_category_id_to_categories.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/categories_controller_spec.rb
  spec/factories/related_categories.rb
  spec/models/category_spec.rb
  spec/models/related_category_spec.rb
Labels: PR: partially-approved

#4944 chore: Display API key in the configuration for WhatsApp Channel
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/ConfigurationPage.vue
  app/javascript/survey/i18n/locale/ar.json
  app/views/api/v1/models/_inbox.json.jbuilder
Labels: PR: reviewed-approved

#4920 fix: Inbox name validation with regex format for special characters
  app/models/inbox.rb
  config/locales/en.yml
  spec/models/inbox_spec.rb
Labels: PR: reviewed-approved
