Repository chatwoot/chatwoot, pull requests merged in 2022-08, with the labels that each got.

#5039 feat: Improve email rendering, introduce a new layout for emails
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/components/widgets/conversation/EmptyState.vue
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Text.vue
  app/javascript/dashboard/constants.js
  app/javascript/dashboard/helper/URLHelper.js
  app/javascript/dashboard/helper/specs/URLHelper.spec.js
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
  app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
  app/javascript/dashboard/routes/dashboard/conversation/search/SwitchLayout.vue
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/javascript/shared/mixins/messageFormatterMixin.js
  app/javascript/shared/mixins/specs/messageFormatterMixin.spec.js
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#5160 chore: Round-robin should consider auto-offline false config
  lib/online_status_tracker.rb
  spec/lib/online_status_tracker_spec.rb
Labels: PR: unreviewed

#5114 fix: Trim search parameter value on contacts controller
  app/controllers/api/v1/accounts/contacts_controller.rb
Labels: PR: partially-approved

#5104 feat: Widget Builder
  app/javascript/dashboard/assets/images/bubble-logo.svg
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/modules/widget-preview/components/Widget.vue
  app/javascript/dashboard/modules/widget-preview/components/WidgetBody.vue
  app/javascript/dashboard/modules/widget-preview/components/WidgetFooter.vue
  app/javascript/dashboard/modules/widget-preview/components/WidgetHead.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/WidgetBuilder.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/InputRadioGroup.vue
  app/javascript/shared/assets/stylesheets/shadows.scss
Labels: PR: unreviewed

#5152 fix: search articles with status and author
  app/controllers/api/v1/accounts/articles_controller.rb
  app/models/article.rb
  app/views/api/v1/accounts/portals/_portal.json.jbuilder
  spec/models/article_spec.rb
Labels: PR: partially-approved

#5169 fix: Convert limits to Integer
  enterprise/app/models/enterprise/account.rb
Labels: PR: reviewed-approved

#5162 feat: Created a view for listing all the portals
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/AllPortals.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalPopover.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/SidebarHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/AllPortals.stories.js
Labels: PR: partially-approved

#5133 feat: Articles store integration
  app/controllers/api/v1/accounts/articles_controller.rb
  app/javascript/dashboard/api/helpCenter/portals.js
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleTable.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/mixins/portalMixin.js
  app/javascript/dashboard/routes/dashboard/helpcenter/mixins/specs/portalMixin.spec.js
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue
  app/javascript/dashboard/store/actions.js
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/helpCenterArticles/actions.js
  app/javascript/dashboard/store/modules/helpCenterArticles/getters.js
  app/javascript/dashboard/store/modules/helpCenterArticles/index.js
  app/javascript/dashboard/store/modules/helpCenterArticles/mutations.js
  app/javascript/dashboard/store/modules/helpCenterArticles/specs/action.spec.js
  app/javascript/dashboard/store/modules/helpCenterArticles/specs/fixtures.js
  app/javascript/dashboard/store/modules/helpCenterArticles/specs/getters.spec.js
  app/javascript/dashboard/store/modules/helpCenterArticles/specs/mutation.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/views/api/v1/accounts/articles/_article.json.jbuilder
  app/views/api/v1/accounts/articles/index.json.jbuilder
  spec/controllers/api/v1/accounts/articles_controller_spec.rb
Labels: PR: reviewed-approved

#5146 feat: Component for listing the portal
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItemTable.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalPopover.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/SidebarHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/PortalListItem.stories.js
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/ListAllPortals.vue
Labels: PR: partially-approved

#5177 chore: Add missing locale info in portal API
  app/views/api/v1/accounts/portals/_portal.json.jbuilder
  app/views/api/v1/models/_portal_config.json.jbuilder
  spec/controllers/api/v1/accounts/portals_controller_spec.rb
Labels: PR: reviewed-approved

#5174 chore: Allow super admin to suspend an account
  app/controllers/concerns/ensure_current_account_helper.rb
  app/controllers/concerns/website_token_helper.rb
  app/controllers/widgets_controller.rb
  app/dashboards/account_dashboard.rb
  app/javascript/dashboard/helper/routeHelpers.js
  app/javascript/dashboard/helper/specs/routeHelpers.spec.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/dashboard.routes.js
  app/javascript/dashboard/routes/dashboard/suspended/Index.vue
  app/javascript/dashboard/routes/index.js
  app/javascript/dashboard/routes/index.spec.js
  app/models/account.rb
  app/views/api/v1/models/_account.json.jbuilder
  app/views/api/v1/models/_user.json.jbuilder
  db/migrate/20220802133722_add_status_to_accounts.rb
  db/schema.rb
  spec/controllers/api/base_controller_spec.rb
  spec/controllers/api/v1/widget/configs_controller_spec.rb
  spec/controllers/widgets_controller_spec.rb
  spec/factories/accounts.rb
Labels: PR: unreviewed

#5184 fix: Avatar renders an incorrect symbol if it has emoji
  app/javascript/dashboard/components/widgets/Thumbnail.vue
  app/javascript/shared/helpers/emoji.js
  app/javascript/shared/helpers/specs/Emoji.spec.js
Labels: PR: partially-approved

#5183 fix: Broken styles in the editor
  app/javascript/dashboard/components/helpCenter/AddCategory.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyEmailHead.vue
  app/javascript/dashboard/components/widgets/forms/Input.vue
Labels: PR: unreviewed

#5140 Fix 5138: Replace some packages with native functions
  app/javascript/dashboard/components/Code.vue
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/helper/URLHelper.js
  app/javascript/dashboard/helper/flag.js
  app/javascript/dashboard/helper/specs/flag.spec.js
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfoRow.vue
  app/javascript/dashboard/routes/dashboard/conversation/customAttributes/CustomAttributes.vue
  app/javascript/shared/helpers/clipboard.js
  app/javascript/shared/mixins/filterMixin.js
  app/javascript/widget/helpers/utils.js
  app/javascript/widget/store/modules/conversation/getters.js
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#5180 Update .env.example
  .env.example
Labels: PR: unreviewed

#5127 feat: Add store to manage categories
  app/javascript/dashboard/api/helpCenter/categories.js
  app/javascript/dashboard/api/helpCenter/portals.js
  app/javascript/dashboard/api/specs/helpCenter/categories.spec.js
  app/javascript/dashboard/store/modules/helpCenterArticles/actions.js
  app/javascript/dashboard/store/modules/helpCenterCategories/actions.js
  app/javascript/dashboard/store/modules/helpCenterCategories/getters.js
  app/javascript/dashboard/store/modules/helpCenterCategories/index.js
  app/javascript/dashboard/store/modules/helpCenterCategories/mutations.js
  app/javascript/dashboard/store/modules/helpCenterCategories/specs/actions.spec.js
  app/javascript/dashboard/store/modules/helpCenterCategories/specs/fixtures.js
  app/javascript/dashboard/store/modules/helpCenterCategories/specs/getters.spec.js
  app/javascript/dashboard/store/modules/helpCenterCategories/specs/mutations.spec.js
  app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
  app/javascript/dashboard/store/mutation-types.js
Labels: PR: reviewed-approved

#5200 chore: Skip reprocessing invalid stripe events
  enterprise/app/services/enterprise/billing/handle_stripe_event_service.rb
Labels: PR: reviewed-approved

#5201 chore: Update styles in cc/bcc input
  app/javascript/dashboard/components/widgets/conversation/ReplyEmailHead.vue
Labels: PR: unreviewed

#5135 Fix: Sending Audio messages not working in Whatsapp Cloud
  app/services/whatsapp/providers/whatsapp_cloud_service.rb
Labels: PR: unreviewed

#5209 chore: Cleanup update banner with localstorage updates
  app/javascript/dashboard/components/app/UpdateBanner.vue
  app/javascript/dashboard/components/app/specs/versionCheckHelper.spec.js
  app/javascript/dashboard/components/app/versionCheckHelper.js
  app/javascript/dashboard/helper/localStorage.js
  app/javascript/dashboard/routes/dashboard/settings/inbox/WidgetBuilder.vue
Labels: PR: reviewed-approved

#5205 chore: Remove stale contact presence records
  lib/online_status_tracker.rb
  lib/redis/alfred.rb
  spec/lib/online_status_tracker_spec.rb
Labels: PR: reviewed-approved

#5214 chore(deps): Upgrade vuelidate to 0.7.7
  package.json
  yarn.lock
Labels: PR: unreviewed

#5185 feat: Portals store integration
  .codeclimate.yml
  app/javascript/dashboard/api/helpCenter/articles.js
  app/javascript/dashboard/api/helpCenter/portals.js
  app/javascript/dashboard/api/specs/article.spec.js
  app/javascript/dashboard/api/specs/portals.spec.js
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleTable.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItemTable.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalPopover.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSwitch.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/mixins/portalMixin.js
  app/javascript/dashboard/routes/dashboard/helpcenter/mixins/specs/portalMixin.spec.js
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/ListAllPortals.vue
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/helpCenterArticles/actions.js
  app/javascript/dashboard/store/modules/helpCenterCategories/index.js
  app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
  app/javascript/dashboard/store/modules/helpCenterPortals/getters.js
  app/javascript/dashboard/store/modules/helpCenterPortals/index.js
  app/javascript/dashboard/store/modules/helpCenterPortals/mutations.js
  app/javascript/dashboard/store/modules/helpCenterPortals/specs/actions.spec.js
  app/javascript/dashboard/store/modules/helpCenterPortals/specs/fixtures.js
  app/javascript/dashboard/store/modules/helpCenterPortals/specs/getters.spec.js
  app/javascript/dashboard/store/modules/helpCenterPortals/specs/mutations.spec.js
  app/javascript/shared/constants/locales.js
  app/views/api/v1/accounts/articles/_article.json.jbuilder
Labels: PR: reviewed-approved

#5215 chore: Remove bourbon dependancy
  app/javascript/dashboard/assets/scss/_animations.scss
  app/javascript/dashboard/assets/scss/_layout.scss
  app/javascript/dashboard/assets/scss/_woot.scss
  app/javascript/dashboard/assets/scss/plugins/_multiselect.scss
  app/javascript/dashboard/assets/scss/storybook.scss
  app/javascript/dashboard/assets/scss/views/settings/channel.scss
  app/javascript/dashboard/assets/scss/views/settings/inbox.scss
  app/javascript/dashboard/assets/scss/widgets/_conversation-card.scss
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/assets/scss/widgets/_forms.scss
  app/javascript/dashboard/assets/scss/widgets/_login.scss
  app/javascript/dashboard/assets/scss/widgets/_modal.scss
  app/javascript/dashboard/assets/scss/widgets/_reply-box.scss
  app/javascript/dashboard/assets/scss/widgets/_report.scss
  app/javascript/dashboard/assets/scss/widgets/_search-box.scss
  app/javascript/dashboard/assets/scss/widgets/_sidemenu.scss
  app/javascript/dashboard/assets/scss/widgets/_snackbar.scss
  app/javascript/dashboard/assets/scss/widgets/_status-bar.scss
  app/javascript/dashboard/assets/scss/widgets/_tabs.scss
  app/javascript/dashboard/assets/scss/widgets/_woot-tables.scss
  app/javascript/shared/assets/stylesheets/animations.scss
  app/javascript/widget/assets/scss/_mixins.scss
  app/javascript/widget/assets/scss/_variables.scss
  app/javascript/widget/assets/scss/woot.scss
  app/javascript/widget/components/UnreadMessageList.vue
  package.json
  yarn.lock
Labels: PR: unreviewed

#5222 chore: Lock closed threads automatically
  .github/workflows/lock.yml
Labels: PR: partially-approved

#5225 fix: assigned_conversation_new_message? NoMethod error
  app/builders/notification_builder.rb
  spec/builders/notification_builder_spec.rb
Labels: PR: reviewed-approved

#5227 chore: Add notification ID to tag to make it unique
  app/services/notification/push_notification_service.rb
Labels: PR: unreviewed

#5228 chore: Add support for conversation_id in SSO params
  app/javascript/dashboard/helper/URLHelper.js
  app/javascript/dashboard/helper/specs/URLHelper.spec.js
  app/javascript/dashboard/routes/login/Login.vue
  app/javascript/dashboard/routes/login/login.routes.js
  app/javascript/dashboard/store/modules/auth.js
Labels: PR: unreviewed

#5230 fix: Update styles to fix the status filter dropdown
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
Labels: PR: reviewed-approved

#5220 fix: Update only the relevant agent only
  app/javascript/dashboard/routes/dashboard/settings/reports/LiveReports.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/overview/AgentTable.vue
  app/javascript/dashboard/store/modules/agents.js
  app/javascript/dashboard/store/modules/auth.js
  app/javascript/dashboard/store/modules/reports.js
  app/javascript/dashboard/store/modules/specs/agents/actions.spec.js
  app/javascript/dashboard/store/modules/specs/agents/getters.spec.js
  app/javascript/dashboard/store/modules/specs/agents/mutations.spec.js
  app/javascript/dashboard/store/modules/specs/auth/actions.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/shared/helpers/vuex/mutationHelpers.js
Labels: PR: partially-approved

#5219 feat: Add the ability add new portal
  app/controllers/api/v1/accounts/portals_controller.rb
  app/javascript/dashboard/helper/commons.js
  app/javascript/dashboard/helper/specs/commons.spec.js
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/AddPortal.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/ListAllPortals.vue
  app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
  app/javascript/dashboard/store/modules/helpCenterPortals/specs/actions.spec.js
Labels: PR: partially-approved

#5218 feat: Category store integration
  app/javascript/dashboard/api/helpCenter/articles.js
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/components/widgets/forms/Input.vue
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/AddCategory.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/Sidebar.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/AddCategory.stories.js
  app/javascript/dashboard/routes/dashboard/helpcenter/helpcenter.routes.js
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue
  app/javascript/dashboard/store/modules/helpCenterArticles/actions.js
  app/javascript/dashboard/store/modules/helpCenterCategories/actions.js
  app/javascript/dashboard/store/modules/helpCenterCategories/specs/actions.spec.js
Labels: PR: partially-approved

#5197 feat: Created article settings side panel
  app/javascript/dashboard/components/helpCenter/EditArticle.vue
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/EditArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ArticleSettings.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue
Labels: PR: partially-approved

#5236 fix: Notification page breakages
  .rubocop.yml
  app/jobs/migration/remove_stale_notifications_job.rb
  app/models/account.rb
  app/models/account_user.rb
  app/models/agent_bot.rb
  app/models/article.rb
  app/models/campaign.rb
  app/models/category.rb
  app/models/contact_inbox.rb
  app/models/conversation.rb
  app/models/csat_survey_response.rb
  app/models/dashboard_app.rb
  app/models/data_import.rb
  app/models/macro.rb
  app/models/mention.rb
  app/models/message.rb
  app/models/note.rb
  app/models/team.rb
  app/models/team_member.rb
  db/migrate/20220809104508_revert_cascading_indexes.rb
  db/schema.rb
  spec/models/conversation_spec.rb
  spec/models/notification_spec.rb
Labels: PR: unreviewed

#5242 chore: Fix RemoveStaleNotificationJob query
  app/jobs/migration/remove_stale_notifications_job.rb
Labels: PR: unreviewed

#5250 fix: Auto populate team after assigned via API
  app/models/team.rb
  app/presenters/conversations/event_data_presenter.rb
  spec/models/conversation_spec.rb
  spec/presenters/conversations/event_data_presenter_spec.rb
Labels: PR: partially-approved

#5271 chore: Improve memory usage in RemoveStaleNotificationsJob
  app/jobs/migration/remove_stale_notifications_job.rb
Labels: PR: unreviewed

#5191 feat: add gh action for linux nightly installer
  .github/workflows/nightly_installer.yml
Labels: PR: unreviewed

#5221 Fix: Truncate overflowing dashboard apps text
  app/javascript/dashboard/routes/dashboard/settings/integrations/DashboardApps/DashboardAppsRow.vue
Labels: bug, frontend, PR: unreviewed, PR: partially-approved

#5164 feat: Enable Capacity Config UI
  app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/CollaboratorsPage.vue
  app/models/concerns/assignment_handler.rb
  app/models/concerns/auto_assignment_handler.rb
  app/models/conversation.rb
  app/models/inbox.rb
  app/models/inbox_member.rb
  app/services/auto_assignment/agent_assignment_service.rb
  app/services/auto_assignment/inbox_round_robin_service.rb
  app/services/round_robin/assignment_service.rb
  app/services/round_robin/manage_service.rb
  lib/online_status_tracker.rb
  spec/controllers/api/v1/accounts/conversations/assignments_controller_spec.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
  spec/factories/users.rb
  spec/models/concerns/assignment_handler_shared.rb
  spec/models/concerns/auto_assignment_handler_shared.rb
  spec/models/conversation_spec.rb
  spec/services/auto_assignment/agent_assignment_service_spec.rb
  spec/services/auto_assignment/inbox_round_robin_service_spec.rb
  spec/services/round_robin/manage_service_spec.rb
Labels: PR: unreviewed

#5232 feat: Adds the ability to edit article
  app/controllers/api/v1/accounts/articles_controller.rb
  app/javascript/dashboard/api/helpCenter/articles.js
  app/javascript/dashboard/api/specs/article.spec.js
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleEditor.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/ArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/EditArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/ArticleEditor.stories.js
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ArticleSettings.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue
  app/javascript/dashboard/store/modules/helpCenterArticles/actions.js
  app/javascript/dashboard/store/modules/helpCenterArticles/mutations.js
  app/javascript/dashboard/store/modules/helpCenterArticles/specs/action.spec.js
  app/javascript/dashboard/store/modules/helpCenterArticles/specs/mutation.spec.js
  app/views/api/v1/accounts/articles/_article.json.jbuilder
  package.json
  yarn.lock
Labels: PR: partially-approved

#5283 hotfix: linux installation failure due to empty database name
  .env.example
Labels: PR: unreviewed

#5293 chore: Handled help center sidebar in small screen
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/ArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/ListAllPortals.vue
Labels: PR: partially-approved

#5255 feat: Adds the ability to create a new article
  app/javascript/dashboard/api/helpCenter/articles.js
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue
  app/javascript/dashboard/store/modules/helpCenterArticles/actions.js
  app/javascript/dashboard/store/modules/helpCenterArticles/mutations.js
  app/javascript/dashboard/store/modules/helpCenterArticles/specs/action.spec.js
  app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
  app/javascript/dashboard/store/mutation-types.js
Labels: PR: unreviewed

#5279 fix: send confirmation email on re-adding agent
  app/controllers/api/v1/accounts/agents_controller.rb
  app/views/devise/mailer/confirmation_instructions.html.erb
  spec/mailers/confirmation_instructions_spec.rb
Labels: PR: reviewed-approved

#5292 feat: Adds the ability to create a portal using the wizard screen
  app/javascript/dashboard/api/helpCenter/portals.js
  app/javascript/dashboard/assets/scss/_utility-helpers.scss
  app/javascript/dashboard/assets/scss/views/settings/inbox.scss
  app/javascript/dashboard/components/ui/Wizard.vue
  app/javascript/dashboard/helper/labelColor.js
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalPopover.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/SidebarHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/NewPortal.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/PortalCustomization.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/PortalDetails.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/PortalSettingsFinish.vue
  app/javascript/dashboard/routes/dashboard/settings/labels/AddLabel.vue
  app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
  app/javascript/dashboard/store/modules/helpCenterPortals/mutations.js
  app/javascript/dashboard/store/modules/helpCenterPortals/specs/mutations.spec.js
Labels: PR: unreviewed

#5261 feat: Create portal UI improvements
  app/javascript/dashboard/api/helpCenter/portals.js
  app/javascript/dashboard/assets/scss/_utility-helpers.scss
  app/javascript/dashboard/assets/scss/views/settings/inbox.scss
  app/javascript/dashboard/components/ui/Wizard.vue
  app/javascript/dashboard/helper/labelColor.js
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalPopover.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/SidebarHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/helpcenter.routes.js
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/ListAllPortals.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/NewPortal.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/PortalCustomization.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/PortalDetails.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/PortalSettingsFinish.vue
  app/javascript/dashboard/routes/dashboard/settings/labels/AddLabel.vue
  app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
  app/javascript/dashboard/store/modules/helpCenterPortals/mutations.js
  app/javascript/dashboard/store/modules/helpCenterPortals/specs/mutations.spec.js
Labels: PR: partially-approved

#5313 feat: Allow Dashboard App Frames to query the information
  app/javascript/dashboard/components/widgets/DashboardApp/Frame.vue
Labels: PR: unreviewed

#5302 fix: Automation case insensitive filter
  app/services/automation_rules/conditions_filter_service.rb
  app/services/filter_service.rb
  lib/filters/filter_keys.json
  spec/listeners/automation_rule_listener_spec.rb
Labels: PR: reviewed-approved

#5317 Fix: Instagram webhook test event
  app/jobs/webhooks/instagram_events_job.rb
  app/services/instagram/message_text.rb
  spec/factories/instagram/instagram_message_create_event.rb
  spec/jobs/webhooks/instagram_events_job_spec.rb
Labels: PR: reviewed-approved

#5294 chore: Removed unsupported file type from Twilio WhatsApp Channel and added file limit for Twilio SMS Channel
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/shared/constants/messages.js
Labels: PR: unreviewed

#5329 feat: abort cwctl upgrade if custom code changes detected
  VERSION_CW
  deployment/setup_20.04.sh
Labels: PR: unreviewed

#5179 chore: Add index on conversations.uuid
  app/models/conversation.rb
  db/migrate/20220802193353_add_conversation_uuid_unique_index.rb
  db/schema.rb
Labels: PR: unreviewed

#5346 chore: Displayed WhatsApp API provider name in inbox settings
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/ConfigurationPage.vue
  app/javascript/shared/mixins/inboxMixin.js
  app/javascript/shared/mixins/specs/inboxMixin.spec.js
Labels: PR: partially-approved

#5338 fix: heorku deploy failure
  app.json
  db/schema.rb
Labels: PR: reviewed-approved

#5355 feat: Article settings sidebar in new article page
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/EditArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ArticleSettings.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue
Labels: PR: partially-approved

#5359 chore: Moves portal slug as ID to query resources in vue store
  app/javascript/dashboard/routes/dashboard/helpcenter/components/AddCategory.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalPopover.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/PortalCustomization.vue
  app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
  app/javascript/dashboard/store/modules/helpCenterPortals/getters.js
  app/javascript/dashboard/store/modules/helpCenterPortals/index.js
  app/javascript/dashboard/store/modules/helpCenterPortals/mutations.js
  app/javascript/dashboard/store/modules/helpCenterPortals/specs/actions.spec.js
  app/javascript/dashboard/store/modules/helpCenterPortals/specs/fixtures.js
  app/javascript/dashboard/store/modules/helpCenterPortals/specs/getters.spec.js
  app/javascript/dashboard/store/modules/helpCenterPortals/specs/mutations.spec.js
Labels: PR: partially-approved

#5352 feat: Ability to seed Demo Accounts
  .rubocop.yml
  Gemfile
  app/controllers/super_admin/accounts_controller.rb
  app/fields/avatar_field.rb
  app/views/super_admin/accounts/_seed_data.html.erb
  app/views/super_admin/accounts/show.html.erb
  config/routes.rb
  db/seeds.rb
  lib/seeders/account_seeder.rb
  lib/seeders/inbox_seeder.rb
  lib/seeders/seed_data.yml
  public/assets/administrate/bot/avatar.png
  public/assets/administrate/user/avatar.png
Labels: PR: unreviewed
