Repository chatwoot/chatwoot, pull requests merged in 2022-03, with the labels that each got.

#3991 feat: Toggle automation status
  app/controllers/api/v1/accounts/automation_rules_controller.rb
  app/javascript/dashboard/components/index.js
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/components/widgets/modal/ConfirmationModal.vue
  app/javascript/dashboard/i18n/locale/en/automation.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue
  app/listeners/automation_rule_listener.rb
Labels: PR: unreviewed

#4086 chore: Add Github in contact social profiles
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactForm.vue
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: PR: unreviewed

#4102 fix: Show new message screen instead of input field
  app/javascript/widget/components/ChatFooter.vue
  app/javascript/widget/components/PreChat/Form.vue
  app/javascript/widget/mixins/routerMixin.js
  app/javascript/widget/views/Home.vue
  app/javascript/widget/views/PreChatForm.vue
Labels: PR: partially-approved, in-QA

#4104 chore: remove unnecessary dependent destroy
  app/javascript/sdk/IFrameHelper.js
  app/models/agent_bot.rb
Labels: PR: unreviewed

#4103 chore: Pass sso_account_id to select the account during SSO Login
  app/javascript/dashboard/api/auth.js
  app/javascript/dashboard/helper/URLHelper.js
  app/javascript/dashboard/helper/specs/URLHelper.spec.js
  app/javascript/dashboard/routes/index.js
  app/javascript/dashboard/routes/login/Login.vue
  app/javascript/dashboard/routes/login/login.routes.js
  app/javascript/dashboard/store/modules/auth.js
  app/javascript/dashboard/store/utils/api.js
Labels: PR: reviewed-approved

#4106 feat: Add agents filter in CSAT reports
  app/controllers/api/v1/accounts/csat_survey_responses_controller.rb
  app/javascript/dashboard/api/csatReports.js
  app/javascript/dashboard/i18n/locale/en/report.json
  app/javascript/dashboard/routes/dashboard/settings/reports/CsatResponses.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/FilterSelector.vue
  app/javascript/dashboard/store/modules/csat.js
  app/models/csat_survey_response.rb
  spec/controllers/api/v1/accounts/csat_survey_responses_controller_spec.rb
Labels: PR: partially-approved

#4064 feat: Ability to send voice message to channel
  app/javascript/dashboard/components/widgets/AttachmentsPreview.vue
  app/javascript/dashboard/components/widgets/WootWriter/AudioRecorder.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/javascript/shared/helpers/FileHelper.js
  package.json
Labels: PR: unreviewed

#4123 fix: Update brand name in mailers
  app/views/devise/mailer/confirmation_instructions.html.erb
  yarn.lock
Labels: PR: unreviewed

#4143 chore: Upgrade rails to 6.1.4.7 to fix CVE-2022-21831
  Gemfile.lock
Labels: PR: unreviewed

#4142 fix: Contact search is skipping the '+' sign for email.
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
Labels: PR: unreviewed

#4100 Fix: Attach instagram images with file type share
  app/builders/messages/messenger/message_builder.rb
  app/helpers/file_type_helper.rb
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
  app/javascript/dashboard/i18n/locale/en/chatlist.json
  app/models/attachment.rb
  app/models/message.rb
  config/locales/en.yml
  spec/factories/instagram/instagram_message_create_event.rb
  spec/jobs/webhooks/instagram_events_job_spec.rb
Labels: PR: partially-approved

#4116 fix: Fixes audio notifications not working on widget
  app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue
  app/javascript/sdk/IFrameHelper.js
  app/javascript/shared/helpers/AudioNotificationHelper.js
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/test.rb
Labels: PR: unreviewed

#4152 fixes: Showing vue warning in the console
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: partially-approved

#4155 feat: Adds ability to delete contact without having to type name
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
Labels: PR: unreviewed

#4135 feat: Custom fields in pre-chat form
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/controllers/api/v1/widget/base_controller.rb
  app/controllers/api/v1/widget/conversations_controller.rb
  app/javascript/dashboard/components/buttons/ToggleButton.vue
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/PreChatForm/Settings.vue
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/javascript/widget/api/endPoints.js
  app/javascript/widget/components/PreChat/Form.vue
  app/javascript/widget/i18n/locale/en.json
  app/javascript/widget/mixins/configMixin.js
  app/javascript/widget/views/PreChatForm.vue
  app/models/channel/web_widget.rb
  db/migrate/20220309103742_add_custom_fields_to_pre_chat_form.rb
  db/schema.rb
Labels: PR: partially-approved

#4110 fix: Handle unsanitized markup in DOM
  app/javascript/shared/helpers/MessageFormatter.js
  app/javascript/shared/helpers/specs/MessageFormatter.spec.js
Labels: PR: partially-approved

#4144 feat: Display trends in report metrics
  app/controllers/api/v2/accounts/reports_controller.rb
  app/javascript/dashboard/assets/scss/widgets/_report.scss
  app/javascript/dashboard/components/widgets/ReportStatsCard.vue
  app/javascript/dashboard/mixins/reportMixin.js
  app/javascript/dashboard/mixins/specs/reportMixin.spec.js
  app/javascript/dashboard/mixins/specs/reportMixinFixtures.js
  app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/WootReports.vue
  app/javascript/dashboard/store/modules/reports.js
  swagger/definitions/resource/report.yml
  swagger/swagger.json
Labels: PR: partially-approved

#4031 Feat - New filters for contacts and conversations
  app/javascript/dashboard/components/widgets/FilterInput/FilterOperatorTypes.js
  app/javascript/dashboard/components/widgets/FilterInput/FilterOperatorTypes.spec.js
  app/javascript/dashboard/components/widgets/FilterInput/Index.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationAdvancedFilter.vue
  app/javascript/dashboard/components/widgets/conversation/advancedFilterItems/advancedFilterItems.spec.js
  app/javascript/dashboard/components/widgets/conversation/advancedFilterItems/index.js
  app/javascript/dashboard/i18n/locale/en/advancedFilters.json
  app/javascript/dashboard/i18n/locale/en/contactFilters.json
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsAdvancedFilters.vue
  app/javascript/dashboard/routes/dashboard/contacts/contactFilterItems/index.js
Labels: PR: partially-approved

#4172 fix: NoMethodError: undefined method `id' for nil:NilClass
  app/channels/room_channel.rb
Labels: PR: unreviewed

#4182 revert: Custom fields in pre-chat form #4135
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/controllers/api/v1/widget/base_controller.rb
  app/controllers/api/v1/widget/conversations_controller.rb
  app/javascript/dashboard/components/buttons/ToggleButton.vue
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/PreChatForm/Settings.vue
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/javascript/widget/api/endPoints.js
  app/javascript/widget/components/PreChat/Form.vue
  app/javascript/widget/i18n/locale/en.json
  app/javascript/widget/mixins/configMixin.js
  app/javascript/widget/views/PreChatForm.vue
  app/models/channel/web_widget.rb
  db/migrate/20220309103742_add_custom_fields_to_pre_chat_form.rb
  db/schema.rb
Labels: PR: partially-approved

#4173 fix: error receiving documents and files in WhatsApp via 360Dialog
  app/services/whatsapp/incoming_message_service.rb
Labels: PR: unreviewed

#4184 fix: Delete content_attributes in message destroy API
  app/controllers/api/v1/accounts/conversations/messages_controller.rb
  spec/controllers/api/v1/accounts/conversations/messages_controller_spec.rb
Labels: PR: reviewed-approved

#3660 feat: End conversation from widget
  app/controllers/api/v1/widget/base_controller.rb
  app/controllers/api/v1/widget/conversations_controller.rb
  app/javascript/shared/components/FluentIcon/icons.json
  app/javascript/widget/api/conversation.js
  app/javascript/widget/components/HeaderActions.vue
  app/javascript/widget/components/dropdown/DropdownMenu.vue
  app/javascript/widget/components/dropdown/DropdownMenuItem.vue
  app/javascript/widget/helpers/actionCable.js
  app/javascript/widget/i18n/locale/en.json
  app/javascript/widget/store/modules/campaign.js
  app/javascript/widget/store/modules/conversation/actions.js
  app/javascript/widget/store/modules/specs/campaign/actions.spec.js
  app/javascript/widget/store/modules/specs/campaign/mutations.spec.js
  app/listeners/action_cable_listener.rb
  app/models/concerns/activity_message_handler.rb
  config/locales/en.yml
  config/routes.rb
  lib/current.rb
  spec/controllers/api/v1/widget/conversations_controller_spec.rb
Labels: PR: unreviewed

#4160 Feat: authenticate direct upload
  app/controllers/api/v1/accounts/base_controller.rb
  app/controllers/api/v1/accounts/conversations/base_controller.rb
  app/controllers/api/v1/accounts/conversations/direct_uploads_controller.rb
  app/controllers/api/v1/widget/base_controller.rb
  app/controllers/api/v1/widget/direct_uploads_controller.rb
  app/controllers/concerns/ensure_current_account_helper.rb
  app/controllers/concerns/website_token_helper.rb
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/widget/components/ChatAttachment.vue
  config/routes.rb
  spec/controllers/api/v1/accounts/conversations/direct_uploads_controller_spec.rb
  spec/controllers/api/v1/widget/direct_uploads_controller_spec.rb
Labels: PR: unreviewed, post-planning

#4185 fix: Reduce the height of the unread container while campaign is active
  app/javascript/sdk/sdk.js
Labels: PR: partially-approved

#4202 chore: Improve n+1 queries in agents endpoint
  app/controllers/api/v1/accounts/agents_controller.rb
  app/models/user.rb
  app/views/api/v1/models/_agent.json.jbuilder
Labels: PR: partially-approved

#4154 feat: Notification action cable event
  .rubocop.yml
  app/listeners/action_cable_listener.rb
  app/listeners/base_listener.rb
  app/models/notification.rb
  lib/events/types.rb
Labels: PR: unreviewed

#4208 New Crowdin updates
  app/javascript/dashboard/i18n/locale/hi/agentMgmt.json
  app/javascript/dashboard/i18n/locale/pt/contact.json
  app/javascript/dashboard/i18n/locale/pt/settings.json
  config/locales/el.yml
Labels: PR: unreviewed

#4195 fix: Add missing contact information to fix invalid activity messages
  app/controllers/api/v1/widget/conversations_controller.rb
  app/controllers/concerns/website_token_helper.rb
  spec/controllers/api/v1/widget/conversations_controller_spec.rb
Labels: PR: reviewed-approved

#4206 chore: filter .xml files for Bandwidth MMS
  app/services/sms/incoming_message_service.rb
Labels: PR: unreviewed

#4222 System default monospace fonts for code elem
  app/javascript/dashboard/assets/scss/_foundation-custom.scss
Labels: PR: partially-approved

#4207 fix: Update survey locale based on the account
  .codeclimate.yml
  .eslintrc.js
  app/javascript/packs/survey.js
  app/javascript/shared/components/Branding.vue
  app/javascript/survey/i18n/index.js
  app/javascript/survey/store/index.js
  app/javascript/survey/views/Response.vue
  app/views/public/api/v1/models/_csat_survey.json.jbuilder
Labels: PR: unreviewed

#4078 fix: Contact conversations are showing in the chat list.
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
  app/javascript/dashboard/store/modules/contactConversations.js
  app/javascript/dashboard/store/modules/specs/contactConversations/actions.spec.js
Labels: PR: unreviewed

#4217 New Crowdin updates
  app/javascript/dashboard/i18n/locale/ar/advancedFilters.json
  app/javascript/dashboard/i18n/locale/ar/contactFilters.json
  app/javascript/dashboard/i18n/locale/ar/generalSettings.json
  app/javascript/dashboard/i18n/locale/it/contact.json
  app/javascript/dashboard/i18n/locale/it/generalSettings.json
  app/javascript/dashboard/i18n/locale/it/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/pt/advancedFilters.json
  app/javascript/dashboard/i18n/locale/pt/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/pt/automation.json
  app/javascript/dashboard/i18n/locale/pt/campaign.json
  app/javascript/dashboard/i18n/locale/pt/contactFilters.json
  app/javascript/dashboard/i18n/locale/pt/conversation.json
  app/javascript/dashboard/i18n/locale/pt/generalSettings.json
  app/javascript/dashboard/i18n/locale/pt/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/pt/integrationApps.json
  app/javascript/dashboard/i18n/locale/pt/report.json
  app/javascript/dashboard/i18n/locale/pt/settings.json
  app/javascript/widget/i18n/locale/ar.json
  app/javascript/widget/i18n/locale/pt.json
  config/locales/ar.yml
  config/locales/pt.yml
Labels: PR: reviewed-approved

#4120 feat: enhancement to un-send instagram message
  app/services/instagram/message_text.rb
  spec/factories/instagram/instagram_message_create_event.rb
  spec/jobs/webhooks/instagram_events_job_spec.rb
Labels: PR: reviewed-approved

#4234 fix: Disable pre-chat for identified users
  app/javascript/widget/views/Home.vue
Labels: PR: reviewed-approved

#4176 chore: Disable fetching new emails after mailbox error
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/jobs/inboxes/fetch_imap_emails_job.rb
  app/mailboxes/mailbox_helper.rb
  app/mailers/administrator_notifications/channel_notifications_mailer.rb
  app/models/channel/email.rb
  app/models/concerns/reauthorizable.rb
  app/views/mailers/administrator_notifications/channel_notifications_mailer/email_disconnect.liquid
  app/views/mailers/administrator_notifications/channel_notifications_mailer/facebook_disconnect.liquid
Labels: PR: reviewed-approved

#4231 New Crowdin updates
  app/javascript/dashboard/i18n/locale/it/automation.json
Labels: PR: unreviewed

#4251 fix: Update scroll event name to fix auto-scroll
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js
Labels: PR: unreviewed

#4253 chore: Disable invalid contact resolved activity messages
  app/models/concerns/activity_message_handler.rb
  spec/controllers/api/v1/widget/messages_controller_spec.rb
Labels: PR: reviewed-approved

#4248 chore: Use bang version of "find_or_create_by!" in Plaform UsersController
  app/controllers/platform/api/v1/users_controller.rb
Labels: PR: unreviewed

#4066 fix: Add multiple file paste support and fix for bugs
  app/javascript/dashboard/components/widgets/AttachmentsPreview.vue
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: partially-approved

#4257 Don't override "action_mailer.delivery_method" in the test env
  config/initializers/mailer.rb
Labels: PR: unreviewed

#4250 feat: support audio player on widget
  app/javascript/widget/assets/scss/views/_conversation.scss
  app/javascript/widget/components/AgentMessage.vue
Labels: PR: reviewed-approved

#4259 Use "destroy!" instead of "destroy" when not checking the return value
  app/controllers/api/v1/accounts/agent_bots_controller.rb
  app/controllers/api/v1/accounts/agents_controller.rb
  app/controllers/api/v1/accounts/campaigns_controller.rb
  app/controllers/api/v1/accounts/canned_responses_controller.rb
  app/controllers/api/v1/accounts/contacts/notes_controller.rb
  app/controllers/api/v1/accounts/custom_attribute_definitions_controller.rb
  app/controllers/api/v1/accounts/custom_filters_controller.rb
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/controllers/api/v1/accounts/integrations/hooks_controller.rb
  app/controllers/api/v1/accounts/integrations/slack_controller.rb
  app/controllers/api/v1/accounts/kbase/categories_controller.rb
  app/controllers/api/v1/accounts/kbase/portals_controller.rb
  app/controllers/api/v1/accounts/labels_controller.rb
  app/controllers/api/v1/accounts/teams_controller.rb
  app/controllers/api/v1/accounts/webhooks_controller.rb
  app/controllers/api/v1/notification_subscriptions_controller.rb
  app/controllers/platform/api/v1/account_users_controller.rb
  app/models/team.rb
  spec/controllers/api/v1/widget/messages_controller_spec.rb
  spec/models/conversation_spec.rb
Labels: PR: unreviewed

#4258 Eliminate deprecation warning in "app_config_controller_spec.rb"
  spec/controllers/super_admin/app_config_controller_spec.rb
Labels: PR: unreviewed

#4256 fix: drop conv and campaign seq on account delete
  app/models/account.rb
  spec/models/account_spec.rb
Labels: PR: unreviewed

#4243 Use "contain_exactly" in some tests
  spec/controllers/api/v1/accounts/bulk_actions_controller_spec.rb
  spec/listeners/automation_rule_listener_spec.rb
Labels: PR: unreviewed

#4260 Fix: added validation for custom and additional attribute
  app/models/conversation.rb
  app/models/jsonb_attributes_length_validator.rb
  spec/models/conversation_spec.rb
Labels: PR: reviewed-approved

#4272 Don't send confirmation email when creating User via platform api
  app/controllers/platform/api/v1/users_controller.rb
  spec/controllers/platform/api/v1/users_controller_spec.rb
Labels: PR: unreviewed

#4194 feat: Add support for rich editor and allow CCs in email for a new conversation.
  app/javascript/dashboard/components/widgets/conversation/ReplyEmailHead.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
Labels: PR: partially-approved

#4246 Timezone fixes for ReportBuilder and for ReportController spec
  app/builders/v2/report_builder.rb
  spec/controllers/api/v2/accounts/report_controller_spec.rb
Labels: PR: unreviewed

#4162 Fix: SMTP IMAP configuration from email
  app/mailers/conversation_reply_mailer_helper.rb
Labels: PR: unreviewed

#4270 chore: Support Email should give priority to environment variable
  app/models/account.rb
Labels: PR: unreviewed

#4238 fix: Avatars get cropped on the widget
  app/javascript/widget/components/GroupedAvatars.vue
  app/javascript/widget/components/TeamAvailability.vue
Labels: PR: unreviewed

#4288 fix: Remove unnecessary dispatchWindowEvent
  app/javascript/sdk/IFrameHelper.js
Labels: PR: partially-approved

#4295 chore: Add swagger docs for Canned Responses
  config/routes.rb
  swagger/definitions/index.yml
  swagger/definitions/request/canned_response/create_update_payload.yml
  swagger/definitions/resource/canned_response.yml
  swagger/index.yml
  swagger/paths/application/canned_responses/create.yml
  swagger/paths/application/canned_responses/delete.yml
  swagger/paths/application/canned_responses/index.yml
  swagger/paths/application/canned_responses/update.yml
  swagger/paths/index.yml
  swagger/swagger.json
Labels: PR: unreviewed

#4304 fix: Report controller specs
  spec/controllers/api/v2/accounts/report_controller_spec.rb
Labels: PR: partially-approved

#4273 feat: Display how many conversations are considered for the metric calculation
  app/builders/v2/report_builder.rb
  app/javascript/dashboard/assets/scss/widgets/_report.scss
  app/javascript/dashboard/components/widgets/ReportStatsCard.vue
  app/javascript/dashboard/components/widgets/chart/BarChart.js
  app/javascript/dashboard/i18n/locale/en/report.json
  app/javascript/dashboard/mixins/reportMixin.js
  app/javascript/dashboard/mixins/specs/reportMixin.spec.js
  app/javascript/dashboard/mixins/specs/reportMixinFixtures.js
  app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/WootReports.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/constants.js
Labels: PR: partially-approved

#4294 feat: Add a confirmation note before deleting a note about a contact
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/modules/notes/components/ContactNote.vue
Labels: PR: reviewed-approved

#4237 chore: Use Round Robin service for team assignment
  .circleci/config.yml
  app/models/concerns/assignment_handler.rb
  app/services/round_robin/assignment_service.rb
  app/services/round_robin/manage_service.rb
  spec/controllers/api/v1/accounts/conversations/assignments_controller_spec.rb
  spec/services/round_robin/manage_service_spec.rb
Labels: PR: reviewed-approved

#4314 feat: fix logging levels
  app/builders/contact_builder.rb
  app/builders/messages/facebook/message_builder.rb
  app/controllers/api/v1/accounts/callbacks_controller.rb
  app/controllers/twitter/callbacks_controller.rb
  app/controllers/webhooks/instagram_controller.rb
  app/jobs/contact_avatar_job.rb
  app/jobs/contact_ip_lookup_job.rb
  app/mailers/application_mailer.rb
  app/models/channel/facebook_page.rb
  app/models/channel/twitter_profile.rb
  app/models/channel/web_widget.rb
  app/services/instagram/send_on_instagram_service.rb
  app/services/notification/push_notification_service.rb
  app/services/twilio/webhook_setup_service.rb
  app/services/twitter/send_on_twitter_service.rb
  config/initializers/rack_attack.rb
  lib/chatwoot_hub.rb
  lib/integrations/slack/send_on_slack_service.rb
  spec/cypress/app_commands/log_fail.rb
Labels: PR: partially-approved

#4310 chore: Upgrade to next gen docker convenience image
  .circleci/config.yml
Labels: PR: unreviewed

#4297 feat: Add live agent load report api
  app/builders/v2/report_builder.rb
  app/controllers/api/v2/accounts/reports_controller.rb
  app/helpers/report_helper.rb
  config/routes.rb
  spec/controllers/api/v2/accounts/report_controller_spec.rb
  swagger/definitions/index.yml
  swagger/definitions/resource/reports/conversation/agent.yml
  swagger/definitions/resource/reports/summary.yml
  swagger/paths/application/reports/conversation/account.yml
  swagger/paths/application/reports/conversation/agent.yml
  swagger/paths/application/reports/index.yml
  swagger/paths/application/reports/summary.yml
  swagger/paths/index.yml
  swagger/swagger.json
Labels: PR: unreviewed

#4322 Add active_storage_purge queue to Sidekiq
  config/sidekiq.yml
Labels: PR: reviewed-approved

#4033 feat: New automation actions
  app/controllers/api/v1/accounts/automation_rules_controller.rb
  app/javascript/dashboard/components/widgets/AutomationActionInput.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/AddAutomationRule.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/EditAutomationRule.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
  app/models/concerns/activity_message_handler.rb
  app/services/automation_rules/action_service.rb
  app/services/filter_service.rb
  spec/listeners/automation_rule_listener_spec.rb
Labels: PR: partially-approved, on-hold

#4230 Feat: automation rule based on contact conditions
  app/controllers/api/v1/accounts/automation_rules_controller.rb
  app/services/automation_rules/conditions_filter_service.rb
  app/services/contacts/filter_service.rb
  app/services/conversations/filter_service.rb
  app/services/filter_service.rb
  lib/filters/filter_keys.json
  spec/listeners/automation_rule_listener_spec.rb
Labels: PR: partially-approved

#4319 fix: Fetch conversationAttributes after contact reset
  app/javascript/widget/store/modules/contacts.js
  app/javascript/widget/store/modules/specs/contact/actions.spec.js
  app/views/widget_tests/index.html.erb
Labels: PR: reviewed-approved

#4266 Feat: attachments automation
  app/controllers/api/v1/accounts/automation_rules_controller.rb
  app/models/automation_rule.rb
  app/services/automation_rules/action_service.rb
  spec/controllers/api/v1/accounts/automation_rules_controller_spec.rb
  spec/listeners/automation_rule_listener_spec.rb
Labels: PR: unreviewed

#4317 chore: Webhook event data improvements
  app/listeners/base_listener.rb
  app/listeners/webhook_listener.rb
  app/models/conversation.rb
  spec/listeners/webhook_listener_spec.rb
  spec/models/conversation_spec.rb
Labels: PR: unreviewed

#4309 fix: Referer URL validation
  .rubocop.yml
  app/models/campaign.rb
  app/models/conversation.rb
  lib/url_helper.rb
  spec/helpers/url_helper_spec.rb
  spec/models/conversation_spec.rb
Labels: PR: partially-approved

#4011 Fix: html mail fix with html_body content
  app/presenters/mail_presenter.rb
  spec/fixtures/files/html_and_attachments.eml
  spec/fixtures/files/only_attachments.eml
  spec/fixtures/files/only_html.eml
  spec/fixtures/files/only_text.eml
  spec/fixtures/files/support_1.eml
  spec/mailboxes/support_mailbox_spec.rb
Labels: PR: reviewed-approved

#4324 fix: Disable showing read messages in unread view
  app/javascript/widget/App.vue
  app/javascript/widget/store/modules/conversation/actions.js
  app/javascript/widget/store/modules/specs/conversation/actions.spec.js
  app/views/api/v1/widget/messages/index.json.jbuilder
  spec/controllers/api/v1/widget/messages_controller_spec.rb
Labels: PR: unreviewed

#4326 fixes: Agent name in Twitter channel private note acts as a link
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/shared/helpers/MessageFormatter.js
  app/javascript/shared/helpers/specs/MessageFormatter.spec.js
  app/javascript/shared/mixins/messageFormatterMixin.js
Labels: PR: partially-approved

#4279 fix: Captcha gets invalidated
  app/javascript/dashboard/components/widgets/conversation/AvailabilityStatusBadge.vue
  app/javascript/dashboard/i18n/locale/en/setNewPassword.json
  app/javascript/dashboard/routes/auth/Signup.vue
Labels: PR: partially-approved

#4354 fix: Update the URL for POST inbox_members
  swagger/paths/index.yml
  swagger/swagger.json
Labels: PR: unreviewed

#4355 feat: make linux installation non-interactive
  deployment/setup_20.04.sh
Labels: PR: reviewed-approved
