Repository chatwoot/chatwoot, pull requests merged in 2022-10, with the labels that each got.

#5144 Fix 5143: Improve Nginx settings for speed and security
  deployment/nginx_chatwoot.conf
Labels: PR: reviewed-approved, self-hosted

#4401 feat: Adds the ability to send messages by clicking `Cmd+Enter` key
  app/javascript/dashboard/components/ui/PreviewCard.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/mixins/specs/uiSettings.spec.js
  app/javascript/dashboard/mixins/uiSettings.js
  app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/profile/MessageSignature.vue
  app/javascript/dashboard/routes/dashboard/settings/profile/NotificationSettings.vue
  app/javascript/shared/helpers/KeyboardHelpers.js
  app/javascript/shared/helpers/specs/KeyboardHelpers.spec.js
  public/assets/images/dashboard/editor/cmd-editor.png
  public/assets/images/dashboard/editor/enter-editor.png
Labels: PR: partially-approved

#4440 feat: Adds draft support for reply box in conversations
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/store/modules/auth.js
  app/javascript/dashboard/store/utils/api.js
Labels: PR: partially-approved

#5545 Enable Docker Buildx multi-arch builds
  .github/workflows/publish_foss_docker.yml
Labels: PR: reviewed-approved

#5562 fix: Flakiness in CI pipeline
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  spec/factories/articles.rb
Labels: PR: unreviewed

#5551 feat: Update the design of mentions with thumbnail
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/components/widgets/conversation/TagAgents.vue
  app/javascript/dashboard/components/widgets/mentions/MentionBox.vue
  app/javascript/dashboard/components/widgets/mentions/mentionSelectionKeyboardMixin.js
  app/javascript/dashboard/components/widgets/mentions/specs/mentionSelectionKeyboardMixin.spec.js
Labels: PR: partially-approved

#5393 chore: Ability to change default account
  app/controllers/api/v1/profiles_controller.rb
  app/javascript/dashboard/App.vue
  app/javascript/dashboard/api/auth.js
  app/javascript/dashboard/api/endPoints.js
  app/javascript/dashboard/components/layout/sidebarComponents/AccountSelector.vue
  app/javascript/dashboard/helper/URLHelper.js
  app/javascript/dashboard/store/modules/auth.js
  app/javascript/dashboard/store/modules/specs/auth/actions.spec.js
  config/routes.rb
  spec/controllers/api/v1/profiles_controller_spec.rb
Labels: PR: unreviewed

#5563 feat: Quickly create canned responses
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/modules/conversations/components/MessageContextMenu.vue
  app/javascript/dashboard/routes/dashboard/settings/canned/AddCanned.vue
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: PR: partially-approved

#5206 Fix: "presence" checks in Channel::TwilioSms
  app/models/channel/twilio_sms.rb
Labels: PR: reviewed-approved

#5588 chore: Add missing indexes for attachments table
  app/models/attachment.rb
  app/models/conversation.rb
  db/migrate/20221010212946_add_index_to_message_attachments.rb
  db/schema.rb
Labels: PR: unreviewed

#5578 New Crowdin updates
  app/javascript/dashboard/i18n/locale/ar/conversation.json
  app/javascript/dashboard/i18n/locale/ar/helpCenter.json
  app/javascript/dashboard/i18n/locale/ar/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/ar/settings.json
Labels: PR: unreviewed

#5596 fix: Password reset page format updated
  app/controllers/devise_overrides/passwords_controller.rb
Labels: PR: partially-approved

#4244 add nice scrollbars to emoji picker
  app/javascript/shared/components/emoji/EmojiInput.vue
  app/javascript/widget/components/ChatInputWrap.vue
Labels: PR: unreviewed

#5585 fix: Added "None" option in bulk actions assignment menu
  app/javascript/dashboard/components/widgets/conversation/contextMenu/Index.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/AgentSelector.vue
  app/javascript/dashboard/i18n/locale/en/bulkActions.json
  app/jobs/bulk_actions_job.rb
  spec/controllers/api/v1/accounts/bulk_actions_controller_spec.rb
Labels: PR: unreviewed

#5599 chore: Add AgentBot API module
  app/javascript/dashboard/api/agentBots.js
  app/javascript/dashboard/api/specs/agentBots.spec.js
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/agentBots.js
  app/javascript/dashboard/store/modules/specs/agentBots/actions.spec.js
  app/javascript/dashboard/store/modules/specs/agentBots/fixtures.js
  app/javascript/dashboard/store/modules/specs/agentBots/getters.spec.js
  app/javascript/dashboard/store/modules/specs/agentBots/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
Labels: PR: unreviewed

#5593 chore: Generate webhook-verify-token automatically
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/CloudWhatsapp.vue
  app/models/channel/whatsapp.rb
  lib/regex_helper.rb
  spec/factories/channel/channel_whatsapp.rb
  spec/models/channel/whatsapp_spec.rb
  spec/models/contact_inbox_spec.rb
Labels: PR: unreviewed

#5600 chore: Add router views for agent_bots
  app/javascript/dashboard/components/layout/config/sidebarItems/settings.js
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/i18n/locale/en/agentBots.json
  app/javascript/dashboard/i18n/locale/en/index.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/agentBots/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/agentBots/agentBot.routes.js
  app/javascript/dashboard/routes/dashboard/settings/agentBots/csml/Edit.vue
  app/javascript/dashboard/routes/dashboard/settings/agentBots/csml/New.vue
  app/javascript/dashboard/routes/dashboard/settings/settings.routes.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  config/features.yml
Labels: PR: unreviewed

#5603 feat: Add API module and Vuex store for Macros
  app/javascript/dashboard/api/macros.js
  app/javascript/dashboard/api/specs/macros.spec.js
  app/javascript/dashboard/store/modules/macros.js
  app/javascript/dashboard/store/modules/specs/macros/actions.spec.js
  app/javascript/dashboard/store/modules/specs/macros/fixtures.js
  app/javascript/dashboard/store/modules/specs/macros/getters.spec.js
  app/javascript/dashboard/store/modules/specs/macros/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
Labels: PR: unreviewed

#5604 feat: Macros routes and parent views
  app/javascript/dashboard/components/layout/config/sidebarItems/settings.js
  app/javascript/dashboard/i18n/locale/en/index.js
  app/javascript/dashboard/i18n/locale/en/macros.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/macros/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroEditor.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/macros.routes.js
  app/javascript/dashboard/routes/dashboard/settings/settings.routes.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  config/features.yml
Labels: PR: unreviewed

#5211 Find by downcased email in SupportMailbox
  app/mailboxes/support_mailbox.rb
  spec/fixtures/files/support_uppercase.eml
  spec/mailboxes/support_mailbox_spec.rb
  spec/support/negated_matchers.rb
Labels: PR: unreviewed

#5607 chore: `Vscode` extension recommendations
  .gitignore
  .vscode/extensions.json
Labels: PR: partially-approved

#5612 fix: Fix .editorconfig syntax
  .editorconfig
Labels: PR: unreviewed

#5605 Chore: Time zone fix for business hours
  app/models/working_hour.rb
  spec/models/working_hour_spec.rb
  spec/services/contacts/filter_service_spec.rb
  spec/services/conversations/filter_service_spec.rb
Labels: PR: unreviewed

#5614 chore: Improve widget SDK
  app/javascript/packs/sdk.js
  app/javascript/sdk/DOMHelpers.js
  app/javascript/sdk/IFrameHelper.js
  app/javascript/sdk/bubbleHelpers.js
Labels: frontend, hacktoberfest

#5611 chore: Replace deprecated functions
  app/javascript/dashboard/components/widgets/Avatar.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/WidgetBuilder.vue
  app/javascript/shared/mixins/campaignMixin.js
  app/javascript/survey/views/Response.vue
  app/models/working_hour.rb
Labels: PR: reviewed-approved

#5616 feat: Show last active portal page when sidebar portal icon is clicked
  app/javascript/dashboard/components/layout/config/sidebarItems/primaryMenu.js
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/helpcenter.routes.js
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/DefaultPortalArticles.vue
Labels: PR: partially-approved

#5618 fix: Show webhook url only on WhatsApp inbox
  app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue
Labels: PR: unreviewed

#5619 chore: revert arm64 docker build in gh action
  .github/workflows/publish_foss_docker.yml
Labels: PR: unreviewed

#5541 fix: Stop raising errors for unsupported Whatsapp messages
  app/services/whatsapp/incoming_message_base_service.rb
  spec/jobs/webhooks/whatsapp_events_job_spec.rb
Labels: PR: unreviewed

#5625 enhancement: Updates design for dropdown buttons
  app/javascript/dashboard/assets/scss/widgets/_buttons.scss
  app/javascript/dashboard/assets/scss/widgets/_modal.scss
  app/javascript/dashboard/components/Modal.vue
  app/javascript/shared/components/ui/MultiselectDropdown.vue
  app/javascript/shared/components/ui/MultiselectDropdownItems.vue
  app/javascript/shared/components/ui/dropdown/DropdownItem.vue
Labels: PR: unreviewed

#5617 chore: Refactor Contact Inbox Builders
  .rubocop.yml
  app/builders/contact_inbox_builder.rb
  app/builders/contact_inbox_with_contact_builder.rb
  app/builders/messages/facebook/message_builder.rb
  app/controllers/api/v1/accounts/contacts/contact_inboxes_controller.rb
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/controllers/concerns/request_exception_handler.rb
  app/controllers/public/api/v1/inboxes/contacts_controller.rb
  app/mailboxes/mailbox_helper.rb
  app/models/channel/facebook_page.rb
  app/models/channel/twitter_profile.rb
  app/models/channel/web_widget.rb
  app/services/line/incoming_message_service.rb
  app/services/sms/incoming_message_service.rb
  app/services/telegram/incoming_message_service.rb
  app/services/twilio/incoming_message_service.rb
  app/services/whatsapp/incoming_message_base_service.rb
  db/seeds.rb
  spec/builders/contact_inbox_builder_spec.rb
  spec/builders/contact_inbox_with_contact_builder_spec.rb
Labels: PR: unreviewed

#5621 chore: Refactor widget
  app/javascript/widget/api/agent.js
  app/javascript/widget/api/campaign.js
  app/javascript/widget/api/conversation.js
  app/javascript/widget/assets/scss/woot.scss
  app/javascript/widget/components/AgentMessage.vue
  app/javascript/widget/components/ChatAttachment.vue
  app/javascript/widget/components/ChatHeaderExpanded.vue
  app/javascript/widget/components/ChatInputWrap.vue
  app/javascript/widget/components/FileBubble.vue
  app/javascript/widget/components/PreChat/Form.vue
  app/javascript/widget/components/TeamAvailability.vue
  app/javascript/widget/components/UnreadMessageList.vue
  app/javascript/widget/helpers/IframeEventHelper.js
  app/javascript/widget/helpers/utils.js
  app/javascript/widget/store/modules/conversation/getters.js
  app/javascript/widget/store/modules/conversation/helpers.js
  app/javascript/widget/store/modules/conversation/mutations.js
  app/javascript/widget/store/modules/conversationLabels.js
Labels: PR: unreviewed

#5636 New Crowdin updates
  app/javascript/dashboard/i18n/locale/lv/agentMgmt.json
  app/javascript/dashboard/i18n/locale/lv/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/lv/automation.json
  app/javascript/dashboard/i18n/locale/lv/contact.json
  app/javascript/dashboard/i18n/locale/lv/contactFilters.json
  app/javascript/dashboard/i18n/locale/lv/conversation.json
  app/javascript/dashboard/i18n/locale/lv/generalSettings.json
  app/javascript/dashboard/i18n/locale/lv/helpCenter.json
  app/javascript/dashboard/i18n/locale/lv/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/lv/integrations.json
  app/javascript/dashboard/i18n/locale/lv/labelsMgmt.json
  app/javascript/dashboard/i18n/locale/lv/settings.json
  app/javascript/dashboard/i18n/locale/lv/teamsSettings.json
  app/javascript/dashboard/i18n/locale/pt_BR/bulkActions.json
Labels: PR: unreviewed

#5633 fix: Avoid email icon getting distorted
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfoRow.vue
Labels: PR: unreviewed

#5638 chore: Add woot button to message context menu
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/modules/conversations/components/MessageContextMenu.vue
  app/javascript/shared/components/ui/dropdown/DropdownItem.vue
Labels: PR: reviewed-approved

#5644 New Crowdin updates
  app/javascript/dashboard/i18n/locale/el/agentBots.json
  app/javascript/dashboard/i18n/locale/el/bulkActions.json
  app/javascript/dashboard/i18n/locale/el/contact.json
  app/javascript/dashboard/i18n/locale/el/contactFilters.json
  app/javascript/dashboard/i18n/locale/el/conversation.json
  app/javascript/dashboard/i18n/locale/el/helpCenter.json
  app/javascript/dashboard/i18n/locale/el/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/el/integrations.json
  app/javascript/dashboard/i18n/locale/el/macros.json
  app/javascript/dashboard/i18n/locale/el/settings.json
  app/javascript/dashboard/i18n/locale/he/chatlist.json
  app/javascript/dashboard/i18n/locale/he/contact.json
  app/javascript/dashboard/i18n/locale/he/conversation.json
  app/javascript/dashboard/i18n/locale/he/generalSettings.json
  app/javascript/dashboard/i18n/locale/he/inboxMgmt.json
  app/javascript/dashboard/i18n/locale/he/settings.json
  config/locales/el.yml
Labels: PR: unreviewed

#5656 chore: Syncs colors from dashboard colors file to tailwind config file
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/Index.vue
  app/javascript/dashboard/modules/widget-preview/components/Widget.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalPopover.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/CategoryListItem.vue
  app/javascript/shared/assets/stylesheets/colors.scss
  tailwind.config.js
Labels: PR: partially-approved

#5657 chore: Add feature flags to the settings console
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/config/sidebarItems/settings.js
  app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/featureFlags.js
  app/javascript/dashboard/routes/dashboard/commands/goToCommandHotKeys.js
  app/javascript/dashboard/routes/dashboard/settings/account/account.routes.js
  app/javascript/dashboard/routes/dashboard/settings/settings.routes.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/views/fields/account_features_field/_form.html.erb
  config/features.yml
  db/migrate/20221017201914_add_features_to_accounts.rb
  db/schema.rb
Labels: PR: reviewed-approved

#5648 fix: Added validation for checkbox
  app/javascript/widget/components/PreChat/Form.vue
Labels: PR: partially-approved

#5658 Fix: Fixes overflow issue for category name in article list
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleItem.vue
Labels: PR: unreviewed

#5659 chore: Add attachments key to `message_created` webhook payload
  app/listeners/webhook_listener.rb
  app/models/message.rb
  app/models/webhook.rb
  spec/models/message_spec.rb
Labels: PR: unreviewed

#5660 chore: Add editor toggle for API inbox
  app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/store/modules/inboxes.js
Labels: PR: reviewed-approved

#5661 fix: Fix typo in help center
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
Labels: PR: reviewed-approved

#5595 chore: ability to delete user in super admin console
  app/models/user.rb
  config/routes.rb
Labels: PR: unreviewed

#5664 fix: Discard invalid contact attributes in widget conversation end point
  app/controllers/api/v1/widget/conversations_controller.rb
  spec/controllers/api/v1/widget/conversations_controller_spec.rb
Labels: PR: unreviewed

#5113 Fix: Overflowing submenus in conversation context menus
  app/javascript/dashboard/components/widgets/conversation/contextMenu/Index.vue
  app/javascript/dashboard/components/widgets/conversation/contextMenu/menuItem.vue
  app/javascript/dashboard/components/widgets/conversation/contextMenu/menuItemWithSubmenu.vue
Labels: enhancement, frontend, PR: unreviewed

#5538 chore: Add test case for `AddReminder` component
  app/javascript/dashboard/routes/dashboard/contacts/components/specs/AddReminder.spec.js
  jest.config.js
Labels: PR: partially-approved

#5667 fix: ensure contact_inbox if contact was already present
  Gemfile.lock
  app/jobs/webhooks/instagram_events_job.rb
  app/services/instagram/message_text.rb
Labels: PR: unreviewed

#5681 feat: Make links more accesible on helpcenter public views
  app/views/public/api/v1/portals/_category-block.html.erb
Labels: enhancement, frontend, PR: unreviewed

#5639 chore: Refactor `urlParamsHelper.js`
  app/javascript/widget/helpers/specs/urlParamsHelper.spec.js
  app/javascript/widget/helpers/urlParamsHelper.js
Labels: PR: partially-approved

#5650 Fix: Handled IG unsupported file type
  app/builders/messages/instagram/message_builder.rb
  app/builders/messages/messenger/message_builder.rb
  spec/builders/messages/instagram/message_builder_spec.rb
Labels: PR: unreviewed

#5556 chore: improve pr and bug report templates legibility
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: unreviewed

#5683 feat: Adds search functionality for public portal
  app/controllers/public/api/v1/portals/articles_controller.rb
  app/javascript/packs/portal.js
  app/javascript/portal/api/article.js
  app/javascript/portal/components/PublicArticleSearch.vue
  app/javascript/portal/components/PublicSearchInput.vue
  app/javascript/portal/components/SearchSuggestions.vue
  app/javascript/portal/portalHelpers.js
  app/javascript/shared/components/FluentIcon/icons.json
  app/views/layouts/portal.html.erb
  app/views/public/api/v1/models/_article.json.jbuilder
  app/views/public/api/v1/portals/_footer.html.erb
  app/views/public/api/v1/portals/_header.html.erb
  app/views/public/api/v1/portals/_hero.html.erb
  app/views/public/api/v1/portals/articles/index.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: PR: unreviewed

#5606 feat: Macros listing and Editor
  .codeclimate.yml
  app/javascript/dashboard/components/widgets/AutomationActionInput.vue
  app/javascript/dashboard/helper/specs/macrosFixtures.js
  app/javascript/dashboard/helper/specs/macrosHelper.spec.js
  app/javascript/dashboard/i18n/locale/en/macros.json
  app/javascript/dashboard/mixins/macrosMixin.js
  app/javascript/dashboard/mixins/specs/macros.spec.js
  app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/ActionButton.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroEditor.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroForm.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroNode.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroNodes.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroProperties.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacrosTableRow.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/Pill.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/constants.js
  app/javascript/dashboard/routes/dashboard/settings/macros/macroHelper.js
  app/javascript/dashboard/routes/dashboard/settings/macros/macros.routes.js
  app/javascript/dashboard/store/index.js
  app/javascript/shared/assets/stylesheets/border-radius.scss
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: PR: unreviewed

#4550 chore: Ability to Remove password info from sentinel config
  .env.example
  lib/redis/config.rb
  spec/lib/redis/config_spec.rb
Labels: PR: unreviewed

#5542 Update conversation attributes to frontend when they changed
  app/javascript/dashboard/helper/actionCable.js
  app/listeners/action_cable_listener.rb
  spec/listeners/action_cable_listener_spec.rb
Labels: PR: unreviewed

#5589 chore: feature flags and agents limit parameters in account creation through platform API
  app/controllers/platform/api/v1/accounts_controller.rb
  app/views/platform/api/v1/accounts/create.json.jbuilder
  app/views/platform/api/v1/accounts/show.json.jbuilder
  app/views/platform/api/v1/accounts/update.json.jbuilder
  app/views/platform/api/v1/models/_account.json.jbuilder
  spec/controllers/platform/api/v1/accounts_controller_spec.rb
Labels: PR: unreviewed

#5686 fix: Add portal pack to tailwind config
  tailwind.config.js
Labels: PR: unreviewed

#5641 Avoid crashing when `AudioContext` is not available.
  app/javascript/shared/helpers/AudioNotificationHelper.js
Labels: PR: partially-approved

#5609 Macros enhancement
  app/controllers/api/v1/accounts/macros_controller.rb
  app/models/macro.rb
  app/policies/macro_policy.rb
  app/services/action_service.rb
  app/services/automation_rules/action_service.rb
  app/services/macros/execution_service.rb
  app/views/api/v1/models/_macro.json.jbuilder
  config/routes.rb
  spec/controllers/api/v1/accounts/macros_controller_spec.rb
Labels: PR: unreviewed

#5693 fix: Update pagination logic in the help center
  app/javascript/dashboard/components/widgets/TableFooter.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleTable.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue
  app/javascript/shared/helpers/AudioNotificationHelper.js
  app/views/api/v1/accounts/articles/index.json.jbuilder
  app/views/api/v1/accounts/portals/_portal.json.jbuilder
  spec/controllers/api/v1/accounts/articles_controller_spec.rb
Labels: PR: reviewed-approved

#5647 Help center count fix
  app/controllers/api/v1/accounts/articles_controller.rb
  app/controllers/api/v1/accounts/categories_controller.rb
  app/controllers/api/v1/accounts/portals_controller.rb
  app/javascript/dashboard/api/helpCenter/categories.js
  app/javascript/dashboard/api/helpCenter/portals.js
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSwitch.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue
  app/javascript/dashboard/store/modules/helpCenterCategories/actions.js
  app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
  app/javascript/dashboard/store/modules/helpCenterPortals/getters.js
  app/javascript/dashboard/store/modules/helpCenterPortals/index.js
  app/javascript/dashboard/store/modules/helpCenterPortals/mutations.js
  app/javascript/dashboard/store/modules/helpCenterPortals/specs/actions.spec.js
  app/javascript/dashboard/store/modules/helpCenterPortals/specs/mutations.spec.js
  app/models/article.rb
  app/views/api/v1/accounts/articles/_article.json.jbuilder
  app/views/api/v1/accounts/articles/_associated_article.json.jbuilder
  app/views/api/v1/accounts/articles/index.json.jbuilder
  app/views/api/v1/accounts/categories/_category.json.jbuilder
  app/views/api/v1/accounts/portals/_portal.json.jbuilder
  app/views/api/v1/accounts/portals/add_members.json.jbuilder
  app/views/api/v1/accounts/portals/create.json.jbuilder
  app/views/api/v1/accounts/portals/index.json.jbuilder
  app/views/api/v1/accounts/portals/show.json.jbuilder
  app/views/api/v1/accounts/portals/update.json.jbuilder
  spec/controllers/api/v1/accounts/articles_controller_spec.rb
  spec/controllers/api/v1/accounts/portals_controller_spec.rb
  spec/models/article_spec.rb
Labels: PR: unreviewed

#5694 fix: Add an action cable events for label updates
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/models/conversation.rb
  app/presenters/conversations/event_data_presenter.rb
  spec/listeners/action_cable_listener_spec.rb
  spec/models/conversation_spec.rb
  spec/presenters/conversations/event_data_presenter_spec.rb
Labels: PR: unreviewed

#5695 chore: Refactors sidebar components used in help center
  app/controllers/api/v1/accounts/articles_controller.rb
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryChildNavItem.vue
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/Sidebar.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/SidebarHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/DefaultPortalArticles.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/PortalDetails.vue
  app/javascript/dashboard/store/modules/helpCenterPortals/mutations.js
Labels: PR: unreviewed

#5712 fix: Show account switch modal from portal dashboard
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
Labels: PR: reviewed-approved

#5713 fix: Update public partials to fix help center search
  app/views/public/api/v1/models/_article.json.jbuilder
  app/views/public/api/v1/models/hc/_associated_article.json.jbuilder
  app/views/public/api/v1/models/hc/_author.json.jbuilder
  app/views/public/api/v1/models/hc/_portal.json.jbuilder
Labels: PR: unreviewed

#5378 fix: check the content type for the file when uploading from cloud storage
  app/builders/messages/message_builder.rb
  app/helpers/file_type_helper.rb
  spec/builders/messages/message_builder_spec.rb
  spec/rails_helper.rb
  spec/support/file_upload_helpers.rb
Labels: PR: unreviewed

#5711 chore: Stop duplicate socket updates for conversation update
  app/models/conversation.rb
Labels: PR: unreviewed

#5727 bug: Fixes width overflow issue with emoji selector in widget
  app/javascript/widget/components/ChatInputWrap.vue
Labels: PR: reviewed-approved

#5698 feat: Macros execution
  app/javascript/dashboard/components/index.js
  app/javascript/dashboard/components/widgets/FeatureToggle.vue
  app/javascript/dashboard/helper/specs/macrosHelper.spec.js
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/i18n/locale/en/macros.json
  app/javascript/dashboard/mixins/specs/uiSettings.spec.js
  app/javascript/dashboard/mixins/uiSettings.js
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/Macros/List.vue
  app/javascript/dashboard/routes/dashboard/conversation/Macros/MacroItem.vue
  app/javascript/dashboard/routes/dashboard/conversation/Macros/MacroPreview.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/macroHelper.js
  app/javascript/shared/assets/stylesheets/spacing.scss
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: frontend, feature, PR: unreviewed, PR: partially-approved

#5700 chore: Improve macros stability
  app/javascript/dashboard/components/widgets/AutomationActionInput.vue
  app/javascript/dashboard/components/widgets/AutomationFileInput.vue
  app/javascript/dashboard/mixins/specs/uiSettings.spec.js
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroEditor.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroForm.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroNodes.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroProperties.vue
  app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
Labels: PR: partially-approved

#5627 feat: Add ability to paste file/image from clipboard
  app/javascript/shared/helpers/FileHelper.js
  app/javascript/shared/helpers/specs/FileHelper.spec.js
  app/javascript/widget/components/ChatAttachment.vue
Labels: PR: unreviewed, PR: reviewed-changes-requested

#5726 fix: Add preference to choose browser lang for widget settings page
  app/javascript/packs/sdk.js
  app/javascript/widget/App.vue
  app/views/widget_tests/index.html.erb
Labels: PR: unreviewed

#5749 Use @page-change instead of on-page-change
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
  app/javascript/dashboard/routes/dashboard/notifications/components/NotificationsView.vue
Labels: PR: reviewed-approved

#5740 fix: Wrong colour for the action button in the card message
  app/javascript/shared/components/CardButton.vue
Labels: PR: partially-approved

#5762 chore: Disable email processing for suspended accounts
  app/mailboxes/support_mailbox.rb
  spec/mailboxes/support_mailbox_spec.rb
Labels: PR: unreviewed

#5682 chore: Refactor thumbnail
  app/javascript/dashboard/components/widgets/Avatar.vue
  app/javascript/dashboard/components/widgets/Thumbnail.vue
Labels: PR: reviewed-approved

#5640 fix: Fix timestamp auto-update
  app/javascript/dashboard/components/ui/TimeAgo.vue
Labels: PR: unreviewed

#5772 chore: Fix import paths in storybook
  app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/AddCategory.stories.js
  app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/ArticleEditor.stories.js
Labels: PR: reviewed-approved

#5761 feat: Adds URL validation for domain and home page links
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSettingsBasicForm.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSettingsCustomizationForm.vue
Labels: PR: unreviewed

#5776 chore: Fix `Thumbnail` component specs
  app/javascript/dashboard/components/widgets/Thumbnail.spec.js
Labels: PR: partially-approved

#5769 fix: Set message sender to macros excution
  app/services/macros/execution_service.rb
  spec/controllers/api/v1/accounts/macros_controller_spec.rb
Labels: PR: partially-approved

#5777 fix: Conversation read update
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/helper/actionCable.js
  app/javascript/dashboard/mixins/specs/conversaton.spec.js
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/getters.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/getters.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
Labels: PR: partially-approved
