Repository chatwoot/chatwoot, pull requests merged in 2022-07, with the labels that each got.

#4952 fix: Fetch email address to create contact
  app/presenters/mail_presenter.rb
  spec/fixtures/files/support_in_reply_to.eml
  spec/mailboxes/support_mailbox_spec.rb
Labels: PR: partially-approved

#4968 fix: Update gems to fix the security vulnerability
  Gemfile.lock
Labels: PR: partially-approved

#4946 feat: Portal and Category public APIs
  app/controllers/api/v1/accounts/articles_controller.rb
  app/controllers/api/v1/accounts/portals_controller.rb
  app/controllers/public/api/v1/portals/categories_controller.rb
  app/controllers/public/api/v1/portals_controller.rb
  app/models/article.rb
  app/models/portal.rb
  app/views/public/api/v1/kbase/portal/show.json.jbuilder
  app/views/public/api/v1/models/_associated_category.json.jbuilder
  app/views/public/api/v1/models/_category.json.jbuilder
  app/views/public/api/v1/models/_portal.json.jbuilder
  app/views/public/api/v1/portals/categories/index.json.jbuilder
  app/views/public/api/v1/portals/categories/show.json.jbuilder
  app/views/public/api/v1/portals/index.json.jbuilder
  app/views/public/api/v1/portals/show.json.jbuilder
  config/routes.rb
  spec/controllers/api/v1/accounts/articles_controller_spec.rb
  spec/controllers/public/api/v1/portals/categories_controller_spec.rb
  spec/controllers/public/api/v1/portals_controller_spec.rb
Labels: PR: partially-approved

#4966 Remove no-op condition in Api::V1::InboxesHelper
  app/helpers/api/v1/inboxes_helper.rb
Labels: PR: reviewed-approved

#4906 chore: Append incoming SMS to last conversation
  app/services/sms/incoming_message_service.rb
  spec/services/sms/incoming_message_service_spec.rb
  spec/services/whatsapp/incoming_message_service_spec.rb
Labels: PR: unreviewed

#4972 fix: last incoming message sort
  app/models/concerns/sort_handler.rb
  app/models/conversation.rb
  app/models/mention.rb
  spec/models/conversation_spec.rb
  spec/models/mention_spec.rb
Labels: PR: partially-approved

#4976 chore: Remove confirm password in the account signup step
  app/javascript/dashboard/routes/auth/Signup.vue
Labels: PR: partially-approved

#4979 fix: Fixing message create issue for deleted instagram story
  app/builders/messages/messenger/message_builder.rb
Labels: PR: partially-approved

#4938 feat: Support for Whatsapp Cloud API
  app/controllers/concerns/meta_token_verify_concern.rb
  app/controllers/webhooks/instagram_controller.rb
  app/controllers/webhooks/whatsapp_controller.rb
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/CloudWhatsapp.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Whatsapp.vue
  app/jobs/webhooks/whatsapp_events_job.rb
  app/models/channel/whatsapp.rb
  app/models/inbox.rb
  app/services/whatsapp/incoming_message_base_service.rb
  app/services/whatsapp/incoming_message_service.rb
  app/services/whatsapp/incoming_message_whatsapp_cloud_service.rb
  app/services/whatsapp/providers/base_service.rb
  app/services/whatsapp/providers/whatsapp_360_dialog_service.rb
  app/services/whatsapp/providers/whatsapp_cloud_service.rb
  app/services/whatsapp/send_on_whatsapp_service.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  config/routes.rb
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
  spec/controllers/webhooks/instagram_controller_spec.rb
  spec/controllers/webhooks/whatsapp_controller_spec.rb
  spec/factories/channel/channel_whatsapp.rb
  spec/jobs/webhooks/whatsapp_events_job_spec.rb
  spec/models/channel/whatsapp_spec.rb
  spec/services/whatsapp/providers/whatsapp_360_dialog_service_spec.rb
  spec/services/whatsapp/providers/whatsapp_cloud_service_spec.rb
Labels: PR: unreviewed

#4868 chore: Copy change for inbox management page
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
Labels: PR: unreviewed

#4807 feat: show HMAC and enforcement for identity validation for API inbox
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/ConfigurationPage.vue
  app/models/channel/api.rb
  app/views/api/v1/models/_inbox.json.jbuilder
Labels: PR: unreviewed

#4984 fix: Handling facebook client error for deleted story
  app/builders/messages/messenger/message_builder.rb
  config/locales/en.yml
  spec/builders/messages/instagram/message_builder_spec.rb
  spec/factories/instagram/instagram_message_create_event.rb
  spec/jobs/webhooks/instagram_events_job_spec.rb
Labels: PR: reviewed-approved

#4997 feat: Add responsive tab styles
  app/javascript/dashboard/assets/scss/_variables.scss
  app/javascript/dashboard/assets/scss/widgets/_tabs.scss
  app/javascript/dashboard/components/ui/Tabs/Tabs.js
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: PR: partially-approved

#4994 chore: Fix contact model silently discarding invalid attributes
  app/actions/contact_identify_action.rb
  app/controllers/api/v1/widget/contacts_controller.rb
  app/models/contact.rb
  spec/actions/contact_identify_action_spec.rb
  spec/controllers/api/v1/widget/contacts_controller_spec.rb
  spec/models/contact_spec.rb
Labels: PR: unreviewed

#4924 feat: Add the ability to create dashboard apps from the UI
  app/javascript/dashboard/components/layout/config/sidebarItems/settings.js
  app/javascript/dashboard/i18n/locale/en/integrations.json
  app/javascript/dashboard/routes/dashboard/settings/integrations/DashboardApps/DashboardAppModal.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/DashboardApps/DashboardAppsRow.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/DashboardApps/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/integrations.routes.js
  app/javascript/dashboard/store/modules/dashboardApps.js
  app/javascript/dashboard/store/modules/specs/dashboardApps/actions.spec.js
  app/javascript/dashboard/store/modules/specs/dashboardApps/fixtures.js
  app/javascript/dashboard/store/modules/specs/dashboardApps/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  public/dashboard/images/integrations/cable.svg
  public/dashboard/images/integrations/dashboard-apps.svg
Labels: PR: partially-approved

#4940 chore: Fix sentry issues
  app/jobs/inboxes/fetch_imap_emails_job.rb
  app/mailboxes/mailbox_helper.rb
Labels: PR: unreviewed

#4901 chore: Email improvements.
  app/jobs/inboxes/fetch_imap_emails_job.rb
  config/schedule.yml
  spec/jobs/inboxes/fetch_imap_emails_job_spec.rb
Labels: PR: partially-approved

#4955 Feat: Article public apis
  app/controllers/api/v1/accounts/articles_controller.rb
  app/controllers/api/v1/accounts/categories_controller.rb
  app/controllers/public/api/v1/portals/articles_controller.rb
  app/models/article.rb
  app/models/category.rb
  app/views/api/v1/accounts/categories/_category.json.jbuilder
  app/views/public/api/v1/models/_article.json.jbuilder
  app/views/public/api/v1/models/_associated_article.json.jbuilder
  app/views/public/api/v1/models/_category.json.jbuilder
  app/views/public/api/v1/portals/articles/index.json.jbuilder
  app/views/public/api/v1/portals/articles/show.json.jbuilder
  config/routes.rb
  db/migrate/20220706085458_rename_linked_category_column_name.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/articles_controller_spec.rb
  spec/controllers/api/v1/accounts/categories_controller_spec.rb
  spec/controllers/public/api/v1/portals/articles_controller_spec.rb
  spec/models/article_spec.rb
  spec/models/category_spec.rb
Labels: PR: unreviewed

#5006 fix: non-zero exit on --logs and handle no opts
  VERSION_CWCTL
  deployment/setup_20.04.sh
Labels: PR: unreviewed

#4987 feat: Header for help-center pages
  .eslintrc.js
  .storybook/preview.js
  app/javascript/dashboard/components/helpCenter/Header/ArticleHeader.stories.js
  app/javascript/dashboard/components/helpCenter/Header/ArticleHeader.vue
  app/javascript/dashboard/components/helpCenter/Header/EditArticleHeader.stories.js
  app/javascript/dashboard/components/helpCenter/Header/EditArticleHeader.vue
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/i18n/locale/en/index.js
  app/javascript/shared/components/CustomerSatisfaction.stories.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/javascript/shared/components/ui/label/LabelDropdownItem.stories.js
  package.json
Labels: PR: partially-approved

#5003 feat: Support square variants of thumbnail and avatar components
  app/javascript/dashboard/components/widgets/Avatar.vue
  app/javascript/dashboard/components/widgets/Thumbnail.stories.js
  app/javascript/dashboard/components/widgets/Thumbnail.vue
Labels: PR: partially-approved

#4996 feat: Added portal logo and the updated the JSON
  app/controllers/api/v1/accounts/portals_controller.rb
  app/models/category.rb
  app/models/portal.rb
  app/views/api/v1/accounts/portals/_portal.json.jbuilder
  spec/controllers/api/v1/accounts/categories_controller_spec.rb
  spec/controllers/api/v1/accounts/portals_controller_spec.rb
  spec/controllers/public/api/v1/portals/articles_controller_spec.rb
  spec/models/article_spec.rb
  spec/models/category_spec.rb
  spec/models/portal_spec.rb
Labels: PR: unreviewed

#5007 feat: Article item component
  app/javascript/dashboard/components/helpCenter/ArticleItem.stories.js
  app/javascript/dashboard/components/helpCenter/ArticleItem.vue
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
Labels: PR: partially-approved

#5016 chore: fix schema error from PR merge
  app/models/agent_bot.rb
  app/models/channel/twilio_sms.rb
  db/schema.rb
Labels: PR: unreviewed

#5019 fix: Update yarn.lock file to fix deployment issue
  yarn.lock
Labels: PR: unreviewed

#5021 Fix: Add missing referrer-link key for i18n
  app/javascript/dashboard/i18n/locale/en/contactFilters.json
Labels: PR: partially-approved

#4719 feat: Update API for contact avatar
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/javascript/dashboard/api/contacts.js
  app/javascript/dashboard/api/specs/contacts.spec.js
  app/javascript/dashboard/components/ui/WootButton.vue
  app/javascript/dashboard/components/widgets/forms/AvatarUploader.vue
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactForm.vue
  app/javascript/dashboard/store/modules/contacts/actions.js
  app/javascript/dashboard/store/modules/specs/contacts/actions.spec.js
  app/jobs/contact_avatar_job.rb
  app/policies/contact_policy.rb
  app/views/api/v1/accounts/contacts/avatar.json.jbuilder
  config/routes.rb
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
  spec/factories/contacts.rb
  swagger/definitions/request/contact/create.yml
  swagger/definitions/request/contact/update.yml
  swagger/swagger.json
Labels: PR: unreviewed

#5023 chore: Fix puma configuration
  config/puma.rb
Labels: PR: unreviewed

#5024 fix: Conversation filter on dates
  app/services/filter_service.rb
  spec/services/conversations/filter_service_spec.rb
Labels: PR: reviewed-approved

#5034 feat: Init HelpCenter Routes
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/routes/dashboard/dashboard.routes.js
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/helpcenter.routes.js
  app/javascript/dashboard/routes/dashboard/helpcenter/helpers/routeHelper.js
  app/javascript/dashboard/routes/dashboard/helpcenter/helpers/specs/routeHelper.spec.js
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListArchivedArticles.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListCategoryArticles.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListDraftArticles.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListMyArticles.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/EditCategory.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/ListAllCategories.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/NewCategory.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/ShowCategory.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/EditPortal.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/ListAllPortals.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/NewPortal.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/ShowPortal.vue
Labels: PR: partially-approved

#5037 chore: improve output of cwctl -w option
  VERSION_CWCTL
  deployment/setup_20.04.sh
Labels: PR: unreviewed

#5040 fix: Twilio channel selection when MessagingServiceSid is empty
  .circleci/config.yml
  app/services/twilio/incoming_message_service.rb
  spec/services/twilio/incoming_message_service_spec.rb
Labels: PR: reviewed-approved

#5035 fix: Fixes text overflow issue with notification content
  app/javascript/dashboard/routes/dashboard/notifications/components/NotificationTable.vue
Labels: PR: partially-approved

#5045 feat: add -I option to cwctl and modify -i option
  VERSION_CWCTL
  deployment/setup_20.04.sh
Labels: PR: unreviewed

#5018 feat: Article table component
  app/javascript/dashboard/components/helpCenter/ArticleItem.vue
  app/javascript/dashboard/components/helpCenter/ArticleTable.stories.js
  app/javascript/dashboard/components/helpCenter/ArticleTable.vue
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
Labels: PR: unreviewed

#5017 feat: New sidebar component for help-center
  app/javascript/dashboard/components/helpCenter/Sidebar/Sidebar.stories.js
  app/javascript/dashboard/components/helpCenter/Sidebar/Sidebar.vue
  app/javascript/dashboard/components/helpCenter/Sidebar/SidebarHeader.vue
  app/javascript/dashboard/components/helpCenter/Sidebar/SidebarSearch.vue
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryChildNavItem.vue
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: PR: partially-approved

#5054 feat: add file size to response
  app/models/attachment.rb
Labels: PR: unreviewed

#5055 fix: Twilio validation over blank messaging_service_sid
  app/controllers/api/v1/accounts/channels/twilio_channels_controller.rb
  app/models/channel/twilio_sms.rb
  spec/controllers/api/v1/accounts/channels/twilio_channels_controller_spec.rb
  spec/models/channel/twilio_sms_spec.rb
Labels: PR: reviewed-approved

#5058 chore: Add ee helper, custom_attributes to account
  .env.example
  Gemfile
  Gemfile.lock
  app/javascript/dashboard/api/ApiClient.js
  app/javascript/dashboard/store/modules/inboxes.js
  app/javascript/dashboard/store/utils/api.js
  app/javascript/dashboard/store/utils/specs/api.spec.js
  app/models/account.rb
  app/views/api/v1/accounts/show.json.jbuilder
  app/views/api/v1/accounts/update.json.jbuilder
  app/views/api/v1/models/_account.json.jbuilder
  config/initializers/stripe.rb
  db/migrate/20220718123938_add_custom_attributes_to_account.rb
  db/schema.rb
Labels: PR: unreviewed

#5051 chore: Catch audio context errors
  app/javascript/shared/helpers/AudioNotificationHelper.js
Labels: PR: reviewed-approved

#5032 feat: Component for editing an article
  app/javascript/dashboard/components/helpCenter/EditArticle.stories.js
  app/javascript/dashboard/components/helpCenter/EditArticle.vue
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
Labels: PR: partially-approved

#5047 feat: Macros CRUD api
  app/controllers/api/v1/accounts/articles_controller.rb
  app/controllers/api/v1/accounts/macros_controller.rb
  app/models/account.rb
  app/models/macro.rb
  app/models/user.rb
  app/policies/macro_policy.rb
  app/views/api/v1/accounts/macros/create.json.jbuilder
  app/views/api/v1/accounts/macros/index.json.jbuilder
  app/views/api/v1/accounts/macros/show.json.jbuilder
  app/views/api/v1/accounts/macros/update.json.jbuilder
  app/views/api/v1/models/_macro.json.jbuilder
  config/routes.rb
  db/migrate/20220711090528_create_macros.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/macros_controller_spec.rb
  spec/factories/macros.rb
  spec/models/macro_spec.rb
Labels: PR: reviewed-approved

#5068 fix: Do not enqueue job if it is already enqueued
  enterprise/app/controllers/enterprise/api/v1/accounts_controller.rb
  spec/enterprise/controllers/enterprise/api/v1/accounts_controller_spec.rb
Labels: PR: partially-approved

#5027 chore: Ability to Disable Gravatars
  app/actions/contact_identify_action.rb
  app/builders/contact_builder.rb
  app/builders/messages/facebook/message_builder.rb
  app/controllers/api/v1/accounts/callbacks_controller.rb
  app/controllers/api/v1/accounts/contacts_controller.rb
  app/jobs/avatar/avatar_from_gravatar_job.rb
  app/jobs/avatar/avatar_from_url_job.rb
  app/jobs/contact_avatar_job.rb
  app/models/concerns/avatarable.rb
  app/services/instagram/webhooks_base_service.rb
  app/services/telegram/incoming_message_service.rb
  app/services/twitter/webhooks_base_service.rb
  db/migrate/20220712145440_sync_gravatar_for_existing_avatarables.rb
  spec/actions/contact_identify_action_spec.rb
  spec/builders/v2/report_builder_spec.rb
  spec/controllers/api/v1/accounts/bulk_actions_controller_spec.rb
  spec/controllers/api/v1/accounts/contacts_controller_spec.rb
  spec/factories/inbox_members.rb
  spec/jobs/avatar/avatar_from_gravatar_job_spec.rb
  spec/jobs/avatar/avatar_from_url_job_spec.rb
  spec/models/agent_bot_spec.rb
  spec/models/concerns/avatarable_shared.rb
  spec/models/contact_spec.rb
  spec/models/inbox_spec.rb
  spec/models/user_spec.rb
Labels: PR: unreviewed

#5090 fix: Update browser_language logic to include all languages
  app/controllers/api/v1/widget/base_controller.rb
  app/javascript/dashboard/components/widgets/conversation/advancedFilterItems/languages.js
  app/javascript/dashboard/components/widgets/conversation/advancedFilterItems/specs/advancedFilterItems.spec.js
  app/javascript/dashboard/components/widgets/conversation/advancedFilterItems/specs/languages.spec.js
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/conversation/ConversationInfo.vue
Labels: PR: unreviewed

#5075 fix: help center clearing minor bugs
  app/models/article.rb
  app/views/api/v1/accounts/categories/_category.json.jbuilder
  app/views/public/api/v1/models/_category.json.jbuilder
  db/migrate/20220720080126_add_meta_column_to_article.rb
  db/schema.rb
Labels: PR: unreviewed

#5004 chore: Support for Elastic APM
  .env.example
  Gemfile
  Gemfile.lock
  config/elastic_apm.yml
Labels: PR: unreviewed

#5087 chore: Add specs for stripe Webhooks endpoint
  config/routes.rb
  enterprise/app/controllers/enterprise/webhooks/stripe_controller.rb
  spec/enterprise/controllers/enterprise/webooks/stripe_controller_spec.rb
  spec/enterprise/services/enterprise/billing/handle_stripe_event_service_spec.rb
Labels: PR: unreviewed

#5091 fix: mention notification mail for empty contact name
  app/drops/conversation_drop.rb
  spec/mailers/agent_notifications/conversation_notifications_mailer_spec.rb
Labels: PR: unreviewed

#5108 fix: Do not reset the scroll if there is no new message
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
Labels: PR: partially-approved

#4923 feat: Conversation context menu
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/buttons/ResolveAction.vue
  app/javascript/dashboard/components/index.js
  app/javascript/dashboard/components/ui/ContextMenu.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/components/widgets/conversation/contextMenu/Index.vue
  app/javascript/dashboard/components/widgets/conversation/contextMenu/agentLoadingPlaceholder.vue
  app/javascript/dashboard/components/widgets/conversation/contextMenu/menuItem.vue
  app/javascript/dashboard/components/widgets/conversation/contextMenu/menuItemWithSubmenu.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/mixins/conversation/snoozeTimesMixin.js
  app/javascript/shared/assets/stylesheets/shadows.scss
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: frontend, feature, PR: unreviewed, PR: reviewed-changes-requested

#5061 feat: Creates view for edit/new article page
  app/javascript/dashboard/components/helpCenter/EditArticle.vue
  app/javascript/dashboard/components/helpCenter/Header/ArticleHeader.vue
  app/javascript/dashboard/components/helpCenter/Header/EditArticleHeader.vue
  app/javascript/dashboard/components/helpCenter/Sidebar/SidebarHeader.vue
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/ListAllPortals.vue
Labels: PR: unreviewed

#5103 feat: Create category component
  app/javascript/dashboard/components/helpCenter/AddCategory.stories.js
  app/javascript/dashboard/components/helpCenter/AddCategory.vue
  app/javascript/dashboard/components/widgets/forms/Input.vue
  app/javascript/dashboard/helper/commons.js
  app/javascript/dashboard/helper/specs/commons.spec.js
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/settings/attributes/AddAttribute.vue
Labels: PR: partially-approved

#5066 feat: Execute macro actions, for the conversation
  app/controllers/api/v1/accounts/macros_controller.rb
  app/jobs/macros_execution_job.rb
  app/models/automation_rule.rb
  app/models/macro.rb
  app/policies/macro_policy.rb
  app/services/action_service.rb
  app/services/automation_rules/action_service.rb
  app/services/macros/execution_service.rb
  config/routes.rb
  db/migrate/20220711090528_create_macros.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/automation_rules_controller_spec.rb
  spec/controllers/api/v1/accounts/macros_controller_spec.rb
  spec/factories/automation_rules.rb
  spec/listeners/automation_rule_listener_spec.rb
  spec/models/automation_rule_spec.rb
  spec/models/macro_spec.rb
Labels: PR: unreviewed

#5117 fix: Console warnings from help-center routes
  app/javascript/dashboard/routes/dashboard/helpcenter/helpcenter.routes.js
Labels: PR: partially-approved

#5086 fix: Set account default language in account API
  app/builders/account_builder.rb
  app/controllers/api/v1/accounts_controller.rb
  app/controllers/platform/api/v1/accounts_controller.rb
  app/views/api/v1/accounts/create.json.jbuilder
  db/migrate/20220720123615_set_default_locale_at_accounts.rb
  db/schema.rb
  spec/controllers/api/v1/accounts_controller_spec.rb
  spec/controllers/platform/api/v1/accounts_controller_spec.rb
  spec/models/account_spec.rb
Labels: PR: unreviewed

#5119 Chore: Add link to product docs on sidebar
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/sidebarComponents/Primary.vue
  app/javascript/dashboard/components/layout/sidebarComponents/PrimaryNavItem.vue
  app/javascript/dashboard/constants.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/javascript/shared/store/globalConfig.js
Labels: PR: unreviewed

#5020 feat: Creates store to manage Portals API and data
  app/javascript/dashboard/api/helpCenter/portals.js
  app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
  app/javascript/dashboard/store/modules/helpCenterPortals/getters.js
  app/javascript/dashboard/store/modules/helpCenterPortals/index.js
  app/javascript/dashboard/store/modules/helpCenterPortals/mutations.js
  app/javascript/dashboard/store/modules/helpCenterPortals/specs/actions.spec.js
  app/javascript/dashboard/store/modules/helpCenterPortals/specs/fixtures.js
  app/javascript/dashboard/store/modules/helpCenterPortals/specs/getters.spec.js
  app/javascript/dashboard/store/modules/helpCenterPortals/specs/mutations.spec.js
Labels: PR: unreviewed

#5048 feat: Add store to manage Articles
  app/javascript/dashboard/api/helpCenter/articles.js
  app/javascript/dashboard/store/modules/helpCenterArticles/actions.js
  app/javascript/dashboard/store/modules/helpCenterArticles/getters.js
  app/javascript/dashboard/store/modules/helpCenterArticles/index.js
  app/javascript/dashboard/store/modules/helpCenterArticles/mutations.js
  app/javascript/dashboard/store/modules/helpCenterArticles/specs/action.spec.js
  app/javascript/dashboard/store/modules/helpCenterArticles/specs/fixtures.js
  app/javascript/dashboard/store/modules/helpCenterArticles/specs/getters.spec.js
  app/javascript/dashboard/store/modules/helpCenterArticles/specs/mutation.spec.js
  app/javascript/dashboard/store/mutation-types.js
Labels: PR: unreviewed

#5122 feat: Article list view page
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleTable.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/ArticleItem.stories.js
  app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/ArticleTable.stories.js
  app/javascript/dashboard/routes/dashboard/helpcenter/helpcenter.routes.js
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListArchivedArticles.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListDraftArticles.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListMyArticles.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/ListAllPortals.vue
Labels: PR: partially-approved

#5008 Feat: Portal Switch component
  app/javascript/dashboard/components/helpCenter/Portal/Switch/Index.vue
  app/javascript/dashboard/components/helpCenter/Portal/Switch/Switch.stories.js
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
Labels: enhancement, frontend, PR: unreviewed, PR: reviewed-approved, PR: reviewed-changes-requested, PR: partially-approved

#5052 Portals Popover component
  app/javascript/dashboard/components/helpCenter/Portal/Switch/Switch.stories.js
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalPopover.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSwitch.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/PortalPopover.stories.js
  app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/PortalSwitch.stories.js
Labels: PR: partially-approved

#5130 chore: adding env example for direct_upload
  .env.example
Labels: PR: reviewed-approved

#5123 Add 'Note:' and 'Private:' to slack note prefix
  lib/integrations/slack/incoming_message_builder.rb
  spec/lib/integrations/slack/incoming_message_builder_spec.rb
Labels: PR: reviewed-approved

#5125 Fix: add articles metadata
  app/controllers/api/v1/accounts/articles_controller.rb
  app/controllers/api/v1/accounts/categories_controller.rb
  app/controllers/api/v1/accounts/portals_controller.rb
  app/controllers/public/api/v1/portals/articles_controller.rb
  app/models/portal.rb
  app/views/api/v1/accounts/articles/index.json.jbuilder
  app/views/api/v1/accounts/categories/_category.json.jbuilder
  app/views/api/v1/accounts/categories/index.json.jbuilder
  app/views/api/v1/accounts/portals/_portal.json.jbuilder
  app/views/api/v1/accounts/portals/index.json.jbuilder
  app/views/public/api/v1/models/_category.json.jbuilder
  app/views/public/api/v1/models/_portal.json.jbuilder
  app/views/public/api/v1/portals/articles/index.json.jbuilder
  spec/controllers/api/v1/accounts/articles_controller_spec.rb
  spec/controllers/api/v1/accounts/portals_controller_spec.rb
  spec/controllers/public/api/v1/portals/articles_controller_spec.rb
  spec/controllers/public/api/v1/portals/categories_controller_spec.rb
  spec/controllers/public/api/v1/portals_controller_spec.rb
  spec/models/portal_spec.rb
Labels: PR: reviewed-approved

#5126 feat: Opening and closing portal switch
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/ArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/EditArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalPopover.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/Sidebar.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/SidebarHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/SidebarSearch.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/ArticleHeader.stories.js
  app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/EditArticleHeader.stories.js
  app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/PortalPopover.stories.js
  app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/Sidebar.stories.js
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue
Labels: PR: partially-approved
