Repository chatwoot/chatwoot, pull requests merged in 2023-06, with the labels that each got.

#7200 chore: Show chatwoot_edition in Instance details
  app/controllers/super_admin/instance_statuses_controller.rb
Labels: community

#6886 feat: added input_select type message support for whatsapp
  app/services/whatsapp/providers/base_service.rb
  app/services/whatsapp/providers/whatsapp_360_dialog_service.rb
  app/services/whatsapp/providers/whatsapp_cloud_service.rb
  spec/services/whatsapp/providers/whatsapp360_dialog_service_spec.rb
  spec/services/whatsapp/providers/whatsapp_cloud_service_spec.rb
Labels: PR: unreviewed, on-hold

#7421 feat: Adds Plus Jakarta Font to dashboard
  app/assets/javascripts/dashboardChart.js
  app/assets/stylesheets/administrate/library/_variables.scss
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/assets/scss/_typography.scss
  app/javascript/dashboard/assets/scss/_woot.scss
  app/javascript/dashboard/assets/scss/storybook.scss
  app/javascript/dashboard/assets/scss/super_admin/pages.scss
  app/javascript/dashboard/routes/dashboard/commands/commandbar.vue
  app/javascript/portal/application.scss
  app/javascript/shared/assets/fonts/PlusJakartaSans/PlusJakartaSans-Bold.woff2
  app/javascript/shared/assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraBold.woff2
  app/javascript/shared/assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraLight.woff2
  app/javascript/shared/assets/fonts/PlusJakartaSans/PlusJakartaSans-Italic.woff2
  app/javascript/shared/assets/fonts/PlusJakartaSans/PlusJakartaSans-Light.woff2
  app/javascript/shared/assets/fonts/PlusJakartaSans/PlusJakartaSans-Medium.woff2
  app/javascript/shared/assets/fonts/PlusJakartaSans/PlusJakartaSans-Regular.woff2
  app/javascript/shared/assets/fonts/PlusJakartaSans/PlusJakartaSans-SemiBold.woff2
  app/javascript/shared/assets/fonts/plus-jakarta.scss
Labels: frontend

#6878 feat: Support Azure single-tenant application using the Graph API (#6728)
  .env.example
  app/controllers/api/v1/accounts/microsoft/authorizations_controller.rb
  app/controllers/concerns/microsoft_concern.rb
  app/jobs/inboxes/fetch_imap_email_inboxes_job.rb
  app/jobs/inboxes/fetch_ms_graph_email_for_tenant_job.rb
  app/mailers/conversation_reply_mailer_helper.rb
  config/initializers/delivery_methods.rb
  lib/microsoft_graph_api.rb
  lib/microsoft_graph_auth.rb
  lib/microsoft_graph_delivery_method.rb
  spec/controllers/api/v1/accounts/microsoft/authorization_controller_spec.rb
  spec/jobs/inboxes/fetch_imap_email_inboxes_job_spec.rb
  spec/jobs/inboxes/fetch_ms_graph_email_for_tenant_job_spec.rb
  spec/lib/microsoft_graph_api_spec.rb
Labels: PR: unreviewed, PR: reviewed-changes-requested, PR: draft, on-hold

#7010 fix: CC conditions when the last email is from someone else
  app/builders/messages/message_builder.rb
  app/javascript/dashboard/api/inbox/message.js
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyEmailHead.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/mailers/conversation_reply_mailer.rb
  app/mailers/conversation_reply_mailer_helper.rb
Labels: PR: unreviewed
