Repository chatwoot/chatwoot, pull requests merged in 2023-05, with the labels that each got.

#6912 feat: Add support to uncategorized articles
  app/controllers/public/api/v1/portals/articles_controller.rb
  app/controllers/public/api/v1/portals/base_controller.rb
  app/javascript/dashboard/helper/portalHelper.js
  app/javascript/dashboard/helper/specs/portalHelper.spec.js
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
  app/javascript/portal/components/SearchSuggestions.vue
  app/models/article.rb
  app/views/api/v1/accounts/articles/_article.json.jbuilder
  app/views/public/api/v1/portals/_category-block.html.erb
  app/views/public/api/v1/portals/_uncategorized-block.html.erb
  app/views/public/api/v1/portals/articles/show.html.erb
  app/views/public/api/v1/portals/categories/_category-block.html.erb
  app/views/public/api/v1/portals/categories/show.html.erb
  app/views/public/api/v1/portals/show.html.erb
  config/routes.rb
  spec/controllers/public/api/v1/portals/articles_controller_spec.rb
  spec/controllers/public/api/v1/portals/categories_controller_spec.rb
  spec/models/article_spec.rb
Labels: PR: partially-approved

#7022 chore: Bump utils from `0.0.15` to `0.0.16`
  app/javascript/dashboard/helper/messageHelper.js
  app/javascript/dashboard/helper/specs/messageHelper.spec.js
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#7004 feat: whatsapp duplicate message
  app/services/whatsapp/incoming_message_base_service.rb
  app/services/whatsapp/incoming_message_service_helpers.rb
  lib/redis/redis_keys.rb
  spec/services/whatsapp/incoming_message_service_spec.rb
Labels: PR: partially-approved

#6976 chore: Reorganize Sidekiq Queues
  app/jobs/action_cable_broadcast_job.rb
  app/jobs/agent_bots/csml_job.rb
  app/jobs/agent_bots/webhook_job.rb
  app/jobs/agents/destroy_job.rb
  app/jobs/avatar/avatar_from_url_job.rb
  app/jobs/conversations/activity_message_job.rb
  app/jobs/delete_object_job.rb
  app/jobs/event_dispatcher_job.rb
  app/jobs/hook_job.rb
  app/jobs/inboxes/fetch_imap_email_inboxes_job.rb
  app/jobs/inboxes/fetch_imap_emails_job.rb
  app/jobs/webhook_job.rb
  app/models/custom_attribute_definition.rb
  config/sidekiq.yml
  spec/jobs/agent_bots/webhook_job_spec.rb
  spec/jobs/agents/destroy_job_spec.rb
  spec/jobs/avatar/avatar_from_url_job_spec.rb
  spec/jobs/delete_object_job_spec.rb
  spec/jobs/event_dispatcher_job_spec.rb
  spec/jobs/hook_job_spec.rb
  spec/jobs/inboxes/fetch_imap_email_inboxes_job_spec.rb
  spec/jobs/inboxes/fetch_imap_emails_job_spec.rb
  spec/jobs/webhook_job_spec.rb
Labels: PR: unreviewed

#6853 feat: Adds the ability to sort conversations
  app/javascript/dashboard/api/inbox/conversation.js
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/widgets/conversation/ChatFilter.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationBasicFilter.vue
  app/javascript/dashboard/components/widgets/conversation/FilterItem.vue
  app/javascript/dashboard/constants/globals.js
  app/javascript/dashboard/helper/actionCable.js
  app/javascript/dashboard/i18n/locale/en/chatlist.json
  app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/getters.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/shared/assets/stylesheets/colors.scss
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/javascript/shared/components/ui/dropdown/DropdownSubMenu.vue
  app/models/message.rb
  app/views/api/v1/conversations/partials/_conversation.json.jbuilder
Labels: PR: unreviewed

#6719 chore: Upgrade to Rails 7
  .circleci/config.yml
  .devcontainer/Dockerfile.base
  .gitignore
  .rubocop.yml
  .ruby-version
  .slugignore
  Gemfile
  Gemfile.lock
  app/controllers/api_controller.rb
  app/controllers/widgets_controller.rb
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/AgentSelector.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/Index.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/LabelActions.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/TeamActions.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/UpdateActions.vue
  app/mailboxes/application_mailbox.rb
  app/models/attachment.rb
  app/models/concerns/avatarable.rb
  app/models/concerns/pubsubable.rb
  app/views/public/api/v1/inboxes/show.json.jbuilder
  app/views/public/api/v1/models/_category.json.jbuilder
  app/views/public/api/v1/portals/articles/index.json.jbuilder
  app/views/public/api/v1/portals/categories/index.json.jbuilder
  app/views/public/api/v1/portals/index.json.jbuilder
  bin/validate_push
  config/application.rb
  config/database.yml
  config/initializers/01_redis.rb
  config/initializers/new_framework_defaults_6_0.rb
  config/initializers/permissions_policy.rb
  config/sidekiq.yml
  db/migrate/20230321073727_remove_not_null_on_active_storage_blobs_checksum.active_storage.rb
  db/schema.rb
  deployment/chatwoot-web.1.service
  deployment/chatwoot-worker.1.service
  deployment/setup_20.04.sh
  docker/Dockerfile
  lib/config_loader.rb
  lib/integrations/dialogflow/processor_service.rb
  lib/integrations/google_translate/detect_language_service.rb
  lib/integrations/google_translate/processor_service.rb
  lib/redis/config.rb
  lib/tasks/db_enhancements.rake
  lib/tasks/yarn.rake
  package.json
  spec/controllers/api/v1/accounts/articles_controller_spec.rb
  spec/lib/integrations/dialogflow/processor_service_spec.rb
  spec/lib/integrations/google_translate/detect_language_service_spec.rb
  spec/lib/redis/config_spec.rb
  spec/listeners/action_cable_listener_spec.rb
  spec/mailboxes/support_mailbox_spec.rb
  spec/rails_helper.rb
  yarn.lock
Labels: PR: unreviewed

#7026 fix: enabling lograge in superadmin path
  Gemfile.lock
  config/initializers/lograge.rb
  spec/controllers/super_admin/devise/sessions_controller_spec.rb
Labels: PR: unreviewed

#7042 fix: Fix rendering issues in Help Center
  Gemfile.lock
  app/views/public/api/v1/portals/_header.html.erb
  app/views/public/api/v1/portals/show.html.erb
Labels: PR: unreviewed

#7035 feat: add feature flag for Audit Log UI
  app/javascript/dashboard/components/layout/config/sidebarItems/settings.js
  app/javascript/dashboard/featureFlags.js
  config/features.yml
  enterprise/app/controllers/api/v1/accounts/audit_logs_controller.rb
  spec/enterprise/controllers/api/v1/accounts/audit_logs_controller_spec.rb
Labels: PR: unreviewed

#6775 chore: Update the design of the help center portal
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/accounts/portals_controller.rb
  app/javascript/portal/application.scss
  app/javascript/portal/components/PublicArticleSearch.vue
  app/javascript/portal/components/PublicSearchInput.vue
  app/javascript/shared/assets/stylesheets/shadows.scss
  app/views/public/api/v1/models/_article.json.jbuilder
  app/views/public/api/v1/portals/_category-block.html.erb
  app/views/public/api/v1/portals/_header.html.erb
  app/views/public/api/v1/portals/_hero.html.erb
  app/views/public/api/v1/portals/_uncategorized-block.html.erb
  app/views/public/api/v1/portals/articles/index.html.erb
  app/views/public/api/v1/portals/articles/show.html.erb
  app/views/public/api/v1/portals/categories/_category-block.html.erb
  app/views/public/api/v1/portals/categories/_hero.html.erb
  app/views/public/api/v1/portals/categories/index.html.erb
  app/views/public/api/v1/portals/categories/show.html.erb
  app/views/public/api/v1/portals/show.html.erb
  public/assets/images/hc/grid.svg
Labels: PR: unreviewed

#7043 fix: Re-order gem list to fix rubocop errors
  Gemfile
Labels: PR: unreviewed

#7024 Rate conversation mailer
  app/models/conversation.rb
  app/views/mailers/conversation_reply_mailer/reply_with_summary.html.erb
Labels: PR: unreviewed

#7044 feat(perf): add index to messages created at
  app/models/message.rb
  db/migrate/20230509101256_add_index_to_messages_created_at.rb
  db/schema.rb
Labels: PR: reviewed-approved

#7046 fix: Record audio in wav format for web/facebook
  app/javascript/dashboard/components/widgets/WootWriter/AudioRecorder.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/shared/constants/messages.js
Labels: PR: unreviewed

#6905 fix: Welcome email copy changes and canned response API error handling [cw-1290]
  app/javascript/dashboard/i18n/locale/en/cannedMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/canned/AddCanned.vue
  app/javascript/dashboard/routes/dashboard/settings/canned/EditCanned.vue
  app/javascript/dashboard/routes/dashboard/settings/canned/Index.vue
  app/javascript/dashboard/store/modules/cannedResponse.js
  app/views/devise/mailer/confirmation_instructions.html.erb
  spec/mailers/confirmation_instructions_spec.rb
Labels: PR: partially-approved

#7047 chore: Add the specs for sort conversation
  app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/getters.spec.js
  app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js
Labels: PR: unreviewed

#7029 feat: Reply suggestion and summary generation using OpenAI
  app/javascript/dashboard/api/integrations/openapi.js
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/components/ui/WootButton.vue
  app/javascript/dashboard/components/widgets/AIAssistanceButton.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/i18n/locale/en/integrations.json
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/javascript/shared/components/Spinner.vue
  app/javascript/shared/components/specs/__snapshots__/Spinner.spec.js.snap
  lib/integrations/openai/processor_service.rb
Labels: PR: unreviewed

#6979 feat: Add ability to filter Conversations by underlying `source_id`
  app/finders/conversation_finder.rb
  spec/finders/conversation_finder_spec.rb
Labels: PR: unreviewed, community

#6902 feat: Show next available day/hour and minutes on widget
  app/javascript/shared/helpers/DateHelper.js
  app/javascript/shared/helpers/specs/DateHelper.spec.js
  app/javascript/widget/components/ChatHeader.vue
  app/javascript/widget/components/TeamAvailability.vue
  app/javascript/widget/i18n/locale/en.json
  app/javascript/widget/mixins/availability.js
  app/javascript/widget/mixins/nextAvailabilityTime.js
  app/javascript/widget/mixins/specs/nextAvailabilityTime.spec.js
  app/views/widgets/show.html.erb
Labels: PR: unreviewed

#7030 chore: fetch mails with multiple attachments
  app/jobs/inboxes/fetch_imap_emails_job.rb
  app/mailboxes/mailbox_helper.rb
  spec/fixtures/files/multiple_attachments.eml
  spec/jobs/inboxes/fetch_imap_emails_job_spec.rb
Labels: PR: reviewed-approved

#7092 fix: Open AI Integration should respond in conversation language
  lib/integrations/openai/processor_service.rb
  spec/lib/integrations/openai/processor_service_spec.rb
Labels: community

#7038 feat: more CSAT filters
  Gemfile.lock
  app/controllers/api/v1/accounts/csat_survey_responses_controller.rb
  app/javascript/dashboard/api/csatReports.js
  app/javascript/dashboard/assets/scss/_date-picker.scss
  app/javascript/dashboard/assets/scss/plugins/_multiselect.scss
  app/javascript/dashboard/i18n/locale/en/csatMgmt.json
  app/javascript/dashboard/i18n/locale/en/report.json
  app/javascript/dashboard/routes/dashboard/settings/reports/CsatResponses.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/FilterSelector.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/Filters/Agents.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/Filters/DateGroupBy.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/Filters/DateRange.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/Filters/Inboxes.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/Filters/Labels.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/Filters/Ratings.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/Filters/Teams.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/specs/Filters/FiltersAgents.spec.js
  app/javascript/dashboard/routes/dashboard/settings/reports/components/specs/Filters/FiltersDateGroupBy.spec.js
  app/javascript/dashboard/routes/dashboard/settings/reports/components/specs/Filters/FiltersDateRange.spec.js
  app/javascript/dashboard/routes/dashboard/settings/reports/components/specs/Filters/FiltersInboxes.spec.js
  app/javascript/dashboard/routes/dashboard/settings/reports/components/specs/Filters/FiltersLabels.spec.js
  app/javascript/dashboard/routes/dashboard/settings/reports/components/specs/Filters/FiltersRatings.spec.js
  app/javascript/dashboard/routes/dashboard/settings/reports/components/specs/Filters/FiltersTeams.spec.js
  app/javascript/dashboard/routes/dashboard/settings/reports/constants.js
  app/javascript/dashboard/store/modules/csat.js
  app/javascript/shared/constants/messages.js
  app/javascript/shared/helpers/DateHelper.js
  app/models/csat_survey_response.rb
Labels: PR: unreviewed

#7203 fix: profile picture distortion (#7202)
  app/views/public/api/v1/portals/articles/show.html.erb
Labels: community
