Repository chatwoot/chatwoot, pull requests merged in 2023-04, with the labels that each got.

#6783 feat: Phone number based automation conditions
  app/javascript/dashboard/i18n/locale/en/advancedFilters.json
  app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
  app/javascript/dashboard/routes/dashboard/settings/automation/operators.js
  app/models/automation_rule.rb
  app/services/automation_rules/conditions_filter_service.rb
  app/services/filter_service.rb
  lib/automation_rules/conditions.json
  lib/filters/filter_keys.json
  spec/services/automation_rules/conditions_filter_service_spec.rb
Labels: PR: partially-approved

#6802 feat(perf): update contacts filter query
  app/controllers/api/v1/accounts/contacts_controller.rb
Labels: PR: reviewed-approved

#6812 chore: Update conversation thread rendering in Slack
  lib/integrations/slack/send_on_slack_service.rb
  spec/lib/integrations/slack/send_on_slack_service_spec.rb
Labels: PR: unreviewed

#6811 slack with template message link
  lib/integrations/slack/send_on_slack_service.rb
Labels: PR: reviewed-approved

#6813 fix: Disable the pre-chat form in new conversation if pre-chat is disabled
  app/javascript/widget/components/PreChat/Form.vue
Labels: PR: partially-approved

#6815 CW-1399 Phone number import
  app/jobs/data_import_job.rb
  spec/assets/contacts.csv
  spec/jobs/data_import_job_spec.rb
Labels: PR: unreviewed

#6792 feat: Adds an option to edit City/Country
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactForm.vue
Labels: PR: partially-approved

#6660 Feat: detect language of the message content
  app/javascript/dashboard/helper/automationHelper.js
  app/javascript/dashboard/mixins/automations/methodsMixin.js
  app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
  app/jobs/hook_job.rb
  app/models/automation_rule.rb
  app/models/conversation.rb
  lib/automation_rules/conditions.json
  lib/filters/filter_keys.json
  lib/integrations/google_translate/detect_language_service.rb
  spec/factories/integrations/hooks.rb
  spec/jobs/hook_job_spec.rb
  spec/lib/integrations/google_translate/detect_language_service_spec.rb
  spec/listeners/automation_rule_listener_spec.rb
  spec/models/conversation_spec.rb
Labels: PR: partially-approved

#6782 feat: allow adding custom attributes to conversations from the SDK
  app/controllers/api/v1/widget/conversations_controller.rb
  app/javascript/packs/sdk.js
  app/javascript/widget/App.vue
  app/javascript/widget/api/conversation.js
  app/javascript/widget/store/modules/conversation/actions.js
  config/routes.rb
  spec/controllers/api/v1/widget/conversations_controller_spec.rb
Labels: PR: partially-approved

#6822 fix: Disable import option in agent account
  app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue
Labels: PR: partially-approved

#6824 fix: inconsistent usage of snake_case and camelCase
  app/javascript/dashboard/api/reports.js
  app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/WootReports.vue
  app/javascript/dashboard/store/modules/reports.js
Labels: PR: partially-approved

#6820 chore: Use feature_flags attribute instead of settings_flags
  app/javascript/dashboard/routes/dashboard/settings/account/Index.vue
  app/models/account.rb
  app/views/api/v1/models/_account.json.jbuilder
  config/features.yml
  db/migrate/20230404030719_remove_settings_flags_from_account.rb
  db/schema.rb
  spec/factories/accounts.rb
Labels: PR: reviewed-approved

#6825 feat: allow agents to merge contacts
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
Labels: PR: unreviewed

#6816 feature: Extend the message limit for the Facebook Channels
  app/javascript/shared/helpers/MessageTypeHelper.js
Labels: PR: unreviewed

#6829 fix: Canned Responses are not sent in the new message editor
  app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
Labels: PR: partially-approved

#6830 feat: Show year in message timestamp if the message is not from the current year
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
  app/javascript/dashboard/mixins/specs/time.spec.js
  app/javascript/dashboard/mixins/time.js
Labels: PR: partially-approved

#6841 fix: Time specs
  app/javascript/dashboard/mixins/specs/time.spec.js
Labels: PR: partially-approved

#6827 Search bar improvements
  app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
Labels: PR: reviewed-approved

#6845 fix: specs failing for teams/actions.js
  app/javascript/dashboard/store/modules/reports.js
  app/javascript/dashboard/store/modules/specs/inboxes/actions.spec.js
  app/javascript/dashboard/store/modules/specs/labels/actions.spec.js
  app/javascript/dashboard/store/modules/specs/teams/actions.spec.js
Labels: PR: reviewed-approved

#6848 feat: Support `after` param in messages end point
  app/finders/message_finder.rb
  spec/finders/message_finder_spec.rb
Labels: PR: unreviewed

#5423 feat: add lograge to improve logging
  .env.example
  Gemfile
  Gemfile.lock
  config/environments/development.rb
  config/initializers/lograge.rb
  config/initializers/sidekiq.rb
Labels: PR: unreviewed

#6849 fix: Disable processing events if account is suspended
  app/jobs/webhooks/whatsapp_events_job.rb
  spec/jobs/webhooks/whatsapp_events_job_spec.rb
Labels: PR: unreviewed

#6859 feat: Use inbox image as avatar for the bot
  .env.example
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/widget/components/AgentMessage.vue
  app/javascript/widget/components/UnreadMessage.vue
  app/javascript/widget/mixins/configMixin.js
  app/javascript/widget/mixins/specs/configMixin.spec.js
  app/models/channel/web_widget.rb
  app/views/api/v1/widget/configs/create.json.jbuilder
  app/views/widgets/show.html.erb
  db/migrate/20230407191457_migrate_env_var_to_channel_feature.rb
  db/schema.rb
Labels: PR: unreviewed

#6855 feat: Add the ability to change the agent availability status
  app/javascript/dashboard/components/layout/AvailabilityStatus.vue
  app/javascript/dashboard/constants.js
  app/javascript/dashboard/i18n/locale/en/agentMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/agents/EditAgent.vue
  app/javascript/dashboard/routes/dashboard/settings/agents/Index.vue
Labels: PR: partially-approved

#6835 Feat: Fetch whatsapp templates till next cursor
  app/services/whatsapp/providers/whatsapp_cloud_service.rb
Labels: PR: partially-approved

#6865 feat: one-click codepen for widget configuration
  app/javascript/dashboard/components/Code.vue
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/ConfigurationPage.vue
Labels: PR: partially-approved

#6860 fix: Invalidate cache if any of the related objects change
  app/models/concerns/account_cache_revalidator.rb
  app/models/concerns/channelable.rb
  spec/models/inbox_spec.rb
Labels: PR: reviewed-approved

#6839 Add status reopen activity message for api channel
  app/models/concerns/activity_message_handler.rb
  app/models/message.rb
  config/locales/en.yml
  spec/controllers/api/v1/accounts/conversations/messages_controller_spec.rb
Labels: PR: unreviewed

#6870 chore: Specs for Whatsapp template pagination
  spec/services/whatsapp/providers/whatsapp_cloud_service_spec.rb
Labels: PR: unreviewed

#6843 feat: add pagination support for auditlogs api
  .gitignore
  enterprise/app/controllers/api/v1/accounts/audit_logs_controller.rb
  spec/enterprise/controllers/api/v1/accounts/audit_logs_controller_spec.rb
Labels: PR: unreviewed

#6875 fix: Update the profile API URL in the documentation
  swagger/paths/index.yml
  swagger/swagger.json
Labels: PR: unreviewed

#6755 feat: better download for conversation traffic heatmap
  app/controllers/api/v2/accounts/reports_controller.rb
  app/helpers/api/v2/accounts/heatmap_helper.rb
  app/helpers/api/v2/accounts/reports_helper.rb
  app/javascript/dashboard/api/reports.js
  app/javascript/dashboard/routes/dashboard/settings/reports/LiveReports.vue
  app/javascript/dashboard/store/modules/reports.js
  app/views/api/v2/accounts/reports/conversation_traffic.erb
  config/locales/en.yml
Labels: PR: reviewed-approved

#6728 Azure single-tenant application support, using the Graph API
  .env.example
  app/controllers/api/v1/accounts/microsoft/authorizations_controller.rb
  app/controllers/concerns/microsoft_concern.rb
  app/jobs/inboxes/fetch_imap_email_inboxes_job.rb
  app/jobs/inboxes/fetch_ms_graph_emails_job.rb
  app/mailers/conversation_reply_mailer_helper.rb
  config/initializers/delivery_methods.rb
  lib/delivery_methods/microsoft_graph.rb
  lib/microsoft_graph_api.rb
  lib/microsoft_graph_auth.rb
Labels: PR: reviewed-changes-requested, community

#6880 fix: flatten template array for whatsapp templates
  app/services/whatsapp/providers/whatsapp_cloud_service.rb
  spec/services/whatsapp/providers/whatsapp_cloud_service_spec.rb
Labels: PR: unreviewed

#6885 feat: Account deletion with deleteObjectJob
  app/controllers/super_admin/accounts_controller.rb
  config/routes.rb
  spec/controllers/super_admin/accounts_controller_spec.rb
Labels: PR: partially-approved

#6667 fix: save twitter profile for inbox
  Gemfile
  Gemfile.lock
  app/controllers/twitter/callbacks_controller.rb
  spec/controllers/twitter/callbacks_controller_spec.rb
Labels: PR: reviewed-approved

#6901 fix: Find email channel with bcc and x-original-to
  app/finders/email_channel_finder.rb
  spec/finders/email_channel_finder_spec.rb
Labels: PR: reviewed-approved

#6900 Add email address in from header of email
  app/mailers/conversation_reply_mailer.rb
  config/locales/en.yml
  spec/mailers/conversation_reply_mailer_spec.rb
Labels: PR: partially-approved

#6906 fix: use response.status instead of success
  app/controllers/twitter/callbacks_controller.rb
Labels: PR: unreviewed

#6907 fix: response body in twitter callback
  app/controllers/twitter/callbacks_controller.rb
  spec/controllers/twitter/callbacks_controller_spec.rb
Labels: PR: reviewed-approved

#6833 feat: allow sorting of articles
  app/controllers/api/v1/accounts/articles_controller.rb
  app/javascript/dashboard/api/helpCenter/articles.js
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleTable.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ListAllArticles.vue
  app/javascript/dashboard/store/modules/helpCenterArticles/actions.js
  app/javascript/shared/assets/stylesheets/spacing.scss
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/models/article.rb
  app/policies/article_policy.rb
  config/routes.rb
  db/migrate/20230405104405_update_position_for_articles.rb
  db/schema.rb
Labels: PR: reviewed-approved

#6916 feat: show webhook verify token for WhatsApp
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/ConfigurationPage.vue
Labels: PR: partially-approved

#6915 fix: Border color for CSAT component in widget
  app/javascript/shared/components/CustomerSatisfaction.vue
  app/javascript/widget/components/template/EmailInput.vue
Labels: PR: partially-approved

#6803 feat: audit logs UI
  .gitignore
  app/javascript/dashboard/api/auditLogs.js
  app/javascript/dashboard/components/layout/config/sidebarItems/settings.js
  app/javascript/dashboard/i18n/locale/en/auditLogs.json
  app/javascript/dashboard/i18n/locale/en/index.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/settings/auditlogs/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/auditlogs/audit.routes.js
  app/javascript/dashboard/routes/dashboard/settings/settings.routes.js
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/auditlogs.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  enterprise/app/controllers/api/v1/accounts/audit_logs_controller.rb
  enterprise/app/views/api/v1/accounts/audit_logs/show.json.jbuilder
Labels: PR: partially-approved

#6801 feat: Improved country code in contact form view.
  app/javascript/dashboard/components/index.js
  app/javascript/dashboard/components/widgets/forms/PhoneInput.vue
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactForm.vue
  app/javascript/shared/constants/countries.js
  app/javascript/shared/helpers/Validators.js
  package.json
  yarn.lock
Labels: PR: partially-approved

#6873 chore: add build id to settings page
  .dockerignore
  .gitignore
  Procfile
  app/controllers/dashboard_controller.rb
  app/javascript/dashboard/routes/dashboard/settings/account/Index.vue
  app/javascript/shared/store/globalConfig.js
  config/initializers/git_sha.rb
  docker/Dockerfile
Labels: PR: unreviewed

#6921 feat: add priority field to conversation
  app/models/conversation.rb
  db/migrate/20230418100944_add_priority_to_conversation.rb
  db/schema.rb
Labels: PR: partially-approved

#6788 fix: Handle spaces in CC/BCC email lists
  app/builders/messages/message_builder.rb
  app/javascript/dashboard/components/widgets/conversation/helpers/emailHeadHelper.js
  app/javascript/dashboard/components/widgets/conversation/helpers/specs/emailHeadHelper.spec.js
  spec/builders/messages/message_builder_spec.rb
Labels: PR: unreviewed, community

#6904 fix: Remove fallback phone_number search in WhatsApp event processing
  app/jobs/webhooks/whatsapp_events_job.rb
  spec/factories/channel/channel_whatsapp.rb
  spec/jobs/webhooks/whatsapp_events_job_spec.rb
Labels: PR: unreviewed

#6774 chore: Cache the dashboard app on the first load
  app/javascript/dashboard/components/widgets/DashboardApp/Frame.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
Labels: PR: unreviewed

#6923 fix: Fixes flaky reporting_event_listener spec
  spec/listeners/reporting_event_listener_spec.rb
Labels: PR: reviewed-approved

#6926 chore: Cloud account management updates
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/helper/scriptHelpers.js
Labels: PR: unreviewed

#6927 feat: add priority field to conversation (#6921)
  app/models/conversation.rb
  db/migrate/20230418100944_add_priority_to_conversation.rb
  db/schema.rb
Labels: PR: reviewed-approved

#6930 Delete inbox api doc update
  swagger/paths/index.yml
  swagger/swagger.json
Labels: PR: partially-approved

#6924 feat: Support multiple emails in email transcript automation
  app/services/action_service.rb
  spec/listeners/automation_rule_listener_old_spec.rb
  spec/services/automation_rules/action_service_spec.rb
Labels: PR: partially-approved

#6823 feat: Adds new inbox selector with more info for new message modal [cw-1358]
  app/javascript/dashboard/assets/scss/plugins/_multiselect.scss
  app/javascript/dashboard/components/widgets/InboxDropdownItem.stories.js
  app/javascript/dashboard/components/widgets/InboxDropdownItem.vue
  app/javascript/dashboard/helper/inbox.js
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
Labels: PR: partially-approved

#6934 fix: Code fix from PR #6823
  app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
Labels: PR: reviewed-approved

#6925 feat: Add an action on automation to change the priority
  app/javascript/dashboard/helper/automationHelper.js
  app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
  app/models/automation_rule.rb
  app/services/action_service.rb
  spec/services/action_service_spec.rb
Labels: PR: partially-approved

#6939 feat: Add a condition for filters based on the priority of automation
  app/javascript/dashboard/helper/automationHelper.js
  app/javascript/dashboard/i18n/locale/en/advancedFilters.json
  app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
  app/models/automation_rule.rb
Labels: PR: reviewed-approved

#6964 feat: Save in_reply_to from WhatsApp messages
  app/models/message.rb
  app/services/whatsapp/incoming_message_base_service.rb
  app/services/whatsapp/incoming_message_service_helpers.rb
Labels: PR: unreviewed

#6790 feat: Refetch the active conversation messages on action cable reconnect
  app/javascript/dashboard/helper/actionCable.js
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/modules/specs/conversations/actions.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/shared/constants/busEvents.js
  app/javascript/shared/helpers/BaseActionCableConnector.js
Labels: PR: partially-approved

#6948 feat: add Makefile
  Makefile
Labels: PR: unreviewed

#6903 feat: Link help center portal to an Inbox
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/models/inbox.rb
  app/models/portal.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  db/migrate/20230413085302_add_portal_id_to_inbox.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
  spec/models/inbox_spec.rb
  spec/models/portal_spec.rb
Labels: PR: partially-approved

#6940 feat: Add an action in Macro to change the priority
  app/javascript/dashboard/helper/specs/macrosHelper.spec.js
  app/javascript/dashboard/mixins/macrosMixin.js
  app/javascript/dashboard/mixins/specs/macros.spec.js
  app/javascript/dashboard/routes/dashboard/settings/macros/constants.js
  app/models/macro.rb
Labels: PR: partially-approved

#6966 feat: priority UI
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/components/widgets/conversation/PriorityMark.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/routes/dashboard/conversation/ConversationAction.vue
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/mutation-types.js
  app/views/api/v1/conversations/partials/_conversation.json.jbuilder
  public/assets/images/dashboard/priority/high.svg
  public/assets/images/dashboard/priority/low.svg
  public/assets/images/dashboard/priority/medium.svg
  public/assets/images/dashboard/priority/none.svg
  public/assets/images/dashboard/priority/urgent.svg
Labels: PR: reviewed-approved

#6947 feat: Right click context menu action to change the priority
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/components/widgets/conversation/contextMenu/Index.vue
Labels: PR: reviewed-approved

#6968 feat: track conversation priority events
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/helper/AnalyticsHelper/events.js
  app/javascript/dashboard/routes/dashboard/conversation/ConversationAction.vue
Labels: PR: unreviewed

#6914 fix vertical overflow scroll on `BackButton`
  app/javascript/dashboard/assets/scss/_rtl.scss
  app/javascript/dashboard/components/widgets/BackButton.vue
Labels: PR: reviewed-approved

#6978 fix: Update the icon for low priority
  app/javascript/dashboard/components/widgets/conversation/PriorityMark.vue
  app/javascript/shared/components/FluentIcon/DashboardIcon.vue
  app/javascript/shared/components/FluentIcon/Icon.vue
  app/javascript/shared/components/FluentIcon/Index.vue
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: PR: unreviewed

#6899 fix: Pagination bug in chat list
  app/javascript/dashboard/components/ChatList.vue
Labels: PR: partially-approved

#6975 chore: Use find_each instead of .all.each
  .rubocop.yml
  app/jobs/account/conversations_resolution_scheduler_job.rb
  app/jobs/conversations/reopen_snoozed_conversations_job.rb
  app/jobs/inboxes/fetch_imap_email_inboxes_job.rb
  app/jobs/migration/update_first_response_time_in_reporting_events_job.rb
  app/jobs/trigger_scheduled_items_job.rb
  spec/controllers/api/v1/accounts/bulk_actions_controller_spec.rb
  spec/jobs/bulk_actions_job_spec.rb
  spec/jobs/inboxes/fetch_imap_email_inboxes_job_spec.rb
Labels: PR: unreviewed

#6943 feat: sort conversation on priority
  app/models/concerns/sort_handler.rb
  lib/seeders/account_seeder.rb
  lib/seeders/seed_data.yml
  spec/models/conversation_spec.rb
Labels: PR: partially-approved

#6881 fix: validate `template_params` for WhatsApp
  app/models/concerns/json_schema_validator.rb
  app/models/message.rb
  app/services/whatsapp/send_on_whatsapp_service.rb
  spec/models/concerns/json_schema_validator_spec.rb
  spec/services/whatsapp/send_on_whatsapp_service_spec.rb
Labels: PR: reviewed-approved

#6942 feat: Splits search api by resources to improve query time [cw-47]
  app/javascript/dashboard/api/search.js
  app/javascript/dashboard/modules/search/components/SearchHeader.vue
  app/javascript/dashboard/modules/search/components/SearchResultContactsList.vue
  app/javascript/dashboard/modules/search/components/SearchResultConversationsList.vue
  app/javascript/dashboard/modules/search/components/SearchResultMessagesList.vue
  app/javascript/dashboard/modules/search/components/SearchResultSection.vue
  app/javascript/dashboard/modules/search/components/SearchView.vue
  app/javascript/dashboard/store/modules/conversationSearch.js
  app/javascript/dashboard/store/mutation-types.js
Labels: PR: partially-approved

#6981 feat: improvements to priority
  app/javascript/dashboard/components/widgets/conversation/PriorityMark.vue
  app/models/conversation.rb
  app/presenters/conversations/event_data_presenter.rb
  spec/models/conversation_spec.rb
  spec/presenters/conversations/event_data_presenter_spec.rb
Labels: PR: reviewed-approved

#6842 feat: Hides dismissed campaigns while browsing [cw-33]
  app/javascript/sdk/IFrameHelper.js
  app/javascript/widget/App.vue
  app/javascript/widget/components/UnreadMessageList.vue
  app/javascript/widget/views/Campaigns.vue
  app/javascript/widget/views/UnreadMessages.vue
Labels: PR: reviewed-changes-requested

#6986 fix: whatsapp template params validation
  app/models/message.rb
Labels: PR: partially-approved

#6987 fix: Add `/api/v1` to the team_members API documentation
  swagger/paths/index.yml
  swagger/swagger.json
Labels: PR: unreviewed

#6372 feat: update product copy [CWM-45]
  app/javascript/dashboard/i18n/locale/en/login.json
  app/javascript/dashboard/i18n/locale/en/resetPassword.json
  app/javascript/dashboard/i18n/locale/en/setNewPassword.json
  app/javascript/dashboard/i18n/locale/en/signup.json
Labels: PR: unreviewed

#6989 feat: Command bar action for priority
  app/javascript/dashboard/i18n/locale/en/generalSettings.json
  app/javascript/dashboard/routes/dashboard/commands/CommandBarIcons.js
  app/javascript/dashboard/routes/dashboard/commands/conversationHotKeys.js
Labels: PR: partially-approved

#6990 feat: Enable rich editor support for unavailable message
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/WeeklyAvailability.vue
Labels: PR: partially-approved

#6897 Fixed installation of gem bundles (lograge, rack-mini-profiler, stack…
  docker/Dockerfile
Labels: PR: reviewed-approved, community

#6998 chore: Add Index for widget contact lookup
  app/models/contact.rb
  db/migrate/20230426130150_add_index_for_widget_contact_look_up.rb
  db/schema.rb
Labels: PR: unreviewed

#6971 feat: Enable template variables in channel greeting messages
  app/drops/account_drop.rb
  app/helpers/email_helper.rb
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/WeeklyAvailability.vue
  app/javascript/shared/components/GreetingsEditor.vue
  app/models/concerns/liquidable.rb
  app/services/action_service.rb
  spec/services/automation_rules/action_service_spec.rb
  spec/services/message_templates/template/greeting_spec.rb
  spec/services/message_templates/template/out_of_office_spec.rb
Labels: PR: partially-approved

#6995 feat: update demo data to include better messages
  lib/seeders/seed_data.yml
Labels: PR: reviewed-approved

#6993 fix: spacing for priority mark in inbox page
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
Labels: PR: reviewed-approved

#6982 chore: add issue forms for GitHub
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: PR: reviewed-approved

#7003 fix: Remove duplicates message in WhatsApp Channel
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/mixins/conversations.js
  app/javascript/dashboard/mixins/specs/conversation.spec.js
Labels: PR: unreviewed

#6985 fix: Search improvements and bug fixes [CW-1604]
  app/javascript/dashboard/i18n/locale/en/search.json
  app/javascript/dashboard/modules/search/components/SearchTabs.vue
  app/javascript/dashboard/modules/search/components/SearchView.vue
  app/javascript/dashboard/store/modules/conversationSearch.js
Labels: PR: partially-approved

#7007 chore: Use canned response variable helpers from `utils`
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/helper/messageHelper.js
  app/javascript/dashboard/helper/specs/messageHelper.spec.js
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#6994 feat: update identity validation docs link
  app/javascript/dashboard/components/SettingsSection.vue
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/ConfigurationPage.vue
Labels: PR: partially-approved

#6992 chore: Move the reconnect logic from the update presence
  app/javascript/shared/helpers/BaseActionCableConnector.js
Labels: PR: partially-approved

#7011 chore: GPT Reply suggestion & summarize endpoints
  lib/integrations/openai/processor_service.rb
  spec/lib/integrations/openai/processor_service_spec.rb
Labels: PR: unreviewed
