Repository chatwoot/chatwoot, pull requests merged in 2023-12, with the labels that each got.

#8435 chore: Change primary actor to `Conversation` for all the notification types.
  app/builders/notification_builder.rb
  app/jobs/migration/remove_message_notifications.rb
  app/models/notification.rb
  app/services/messages/mention_service.rb
  app/services/messages/new_message_notification_service.rb
  app/views/api/v1/accounts/notifications/index.json.jbuilder
  db/migrate/20231201014644_remove_notifications_with_message_primary_actor.rb
  db/schema.rb
  spec/jobs/migration/remove_message_notifications_spec.rb
  spec/models/notification_spec.rb
  spec/services/messages/mention_service_spec.rb
  spec/services/messages/new_message_notification_service_spec.rb
Labels: Do not merge

#8337 fix: switch to nodejs ppa for linux installations
  VERSION_CW
  VERSION_CWCTL
  deployment/setup_20.04.sh
Labels: stale

#8520 feat: Enable custom attributes in the suggestion for variables.
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/conversation/VariableList.vue
  app/javascript/dashboard/components/widgets/mentions/MentionBox.vue
  package.json
  yarn.lock
Labels: PR: reviewed-changes-requested
