Repository chatwoot/chatwoot, pull requests merged in 2023-01, with the labels that each got.

#6132 Buttons must have discernible text
  app/javascript/sdk/bubbleHelpers.js
Labels: PR: reviewed-approved

#6158 Feat/telegram incoming location message
  app/services/telegram/incoming_message_service.rb
  spec/services/telegram/incoming_message_service_spec.rb
Labels: PR: unreviewed

#6160 New Crowdin updates
  app/javascript/dashboard/i18n/locale/de/agentBots.json
  app/javascript/dashboard/i18n/locale/de/generalSettings.json
  app/javascript/dashboard/i18n/locale/de/inboxMgmt.json
Labels: PR: reviewed-approved

#6177 fix: Update the page size to 15, change default sort to last_activity
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
Labels: PR: unreviewed

#6182 Fix: Errors in Heroku deployments
  config/initializers/01_redis.rb
Labels: PR: unreviewed

#6180 fix: incorrect label for team members
  app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue
Labels: PR: partially-approved

#6187 Update error message in Custom Attributes
  app/javascript/dashboard/i18n/locale/en/attributesMgmt.json
Labels: PR: partially-approved

#6170 chore: Christmas Promo
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/sidebarComponents/GiftIcon.vue
  app/javascript/dashboard/components/layout/sidebarComponents/Primary.vue
  app/javascript/dashboard/featureFlags.js
  app/javascript/dashboard/routes/dashboard/ChristmasPromoPopup.vue
  app/javascript/dashboard/routes/dashboard/Dashboard.vue
  public/dashboard/images/christmas-promo.webp
Labels: PR: unreviewed

#6171 fix: Fixes broken style in automation page
  app/javascript/dashboard/assets/scss/_foundation-settings.scss
  app/javascript/dashboard/assets/scss/widgets/_modal.scss
  app/javascript/dashboard/components/ModalHeader.vue
  app/javascript/dashboard/components/widgets/modal/ConfirmationModal.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacroNode.vue
Labels: PR: partially-approved

#6189 chore: Fix sentry errors for Instagram channel
  app/services/instagram/message_text.rb
Labels: PR: unreviewed

#6190 fix: padding for empty state
  app/views/public/api/v1/portals/categories/show.html.erb
Labels: PR: partially-approved

#6197 feat: Add backend APIs for Dyte integration
  app/controllers/api/v1/accounts/integrations/dyte_controller.rb
  app/models/message.rb
  config/integration/apps.yml
  config/locales/en.yml
  config/routes.rb
  lib/dyte.rb
  lib/integrations/dyte/processor_service.rb
  public/dashboard/images/integrations/dyte.png
  spec/controllers/api/v1/accounts/integrations/dyte_controller_spec.rb
  spec/factories/integrations/hooks.rb
  spec/lib/dyte_spec.rb
  spec/lib/integrations/dyte/processor_service_spec.rb
Labels: PR: reviewed-approved

#6134 feat: Uses expanded layout as default if the breakpoint is less than or equal to 992px
  app/javascript/dashboard/assets/scss/widgets/_conv-header.scss
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
  app/javascript/dashboard/constants.js
  app/javascript/dashboard/routes/dashboard/Dashboard.vue
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/Sidebar.vue
  app/javascript/dashboard/routes/dashboard/settings/profile/profile.routes.js
  app/javascript/shared/components/ui/MultiselectDropdown.vue
  app/views/layouts/vueapp.html.erb
Labels: PR: partially-approved

#6166 fix: Invalid portal domain validation
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSettingsBasicForm.vue
  app/javascript/shared/helpers/Validators.js
  app/javascript/shared/helpers/specs/ValidatorsHelper.spec.js
Labels: PR: unreviewed

#6207 feat: Add video call option in the dashboard
  app/javascript/dashboard/api/integrations/dyte.js
  app/javascript/dashboard/api/specs/integrations/dyte.spec.js
  app/javascript/dashboard/components/widgets/VideoCallButton.vue
  app/javascript/dashboard/components/widgets/WootWriter/ReplyBottomPanel.vue
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Integration.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/integrations/Dyte.vue
  app/javascript/dashboard/i18n/locale/en/integrations.json
  app/javascript/dashboard/store/modules/integrations.js
  app/javascript/dashboard/store/modules/specs/integrations/getters.spec.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: PR: unreviewed

#6208 feat: Add video call support in live-chat widget
  app/controllers/api/v1/widget/integrations/dyte_controller.rb
  app/javascript/dashboard/components/widgets/conversation/bubble/Integration.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/integrations/Dyte.vue
  app/javascript/sdk/IFrameHelper.js
  app/javascript/shared/components/FluentIcon/icons.json
  app/javascript/shared/helpers/IntegrationHelper.js
  app/javascript/widget/api/integration.js
  app/javascript/widget/components/AgentMessageBubble.vue
  app/javascript/widget/components/template/IntegrationCard.vue
  app/javascript/widget/i18n/locale/en.json
  config/routes.rb
  spec/controllers/api/v1/widget/integrations/dyte_controller_spec.rb
Labels: PR: unreviewed

#6191 fix: default article sidebar state
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/EditArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue
Labels: frontend, PR: unreviewed, PR: partially-approved

#6214 fix: If desktop view is false then the view not getting updated
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/constants.js
  app/javascript/dashboard/routes/dashboard/Dashboard.vue
Labels: PR: partially-approved

#6216 feat: Use rich text editor for automation and macros message action
  app/javascript/dashboard/components/widgets/AutomationActionInput.vue
Labels: frontend, PR: unreviewed, PR: partially-approved, ready-for-pickup

#6224 fix: Not able to create a portal if the custom domain is empty
  app/javascript/shared/helpers/Validators.js
Labels: PR: partially-approved

#6219 fix: Fixes inconsistent spacing in message bubble
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
Labels: PR: reviewed-approved

#6232 fix: Handle overflowing content in custom attrs table
  app/javascript/dashboard/routes/dashboard/settings/attributes/CustomAttribute.vue
Labels: PR: partially-approved

#6236 fix: Stop processing broken liquid tags
  app/models/concerns/liquidable.rb
  spec/models/concerns/liquidable_shared.rb
Labels: PR: reviewed-approved

#6241 chore: Create a resuable component for selecting a channel
  app/javascript/dashboard/assets/images/channels/facebook.png
  app/javascript/dashboard/assets/scss/_woot.scss
  app/javascript/dashboard/assets/scss/views/settings/channel.scss
  app/javascript/dashboard/components/ChannelSelector.vue
  app/javascript/dashboard/components/widgets/ChannelItem.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/ChannelList.vue
  public/assets/images/dashboard/channels/api.png
  public/assets/images/dashboard/channels/email.png
  public/assets/images/dashboard/channels/facebook.png
  public/assets/images/dashboard/channels/line.png
  public/assets/images/dashboard/channels/microsoft.png
  public/assets/images/dashboard/channels/sms.png
  public/assets/images/dashboard/channels/telegram.png
  public/assets/images/dashboard/channels/twilio.png
  public/assets/images/dashboard/channels/twitter.png
  public/assets/images/dashboard/channels/website.png
  public/assets/images/dashboard/channels/whatsapp.png
Labels: PR: unreviewed

#6205 fix: Path traversal at SwaggerController
  app/controllers/swagger_controller.rb
Labels: PR: unreviewed

#6245 feat: Allow disconnecting agent bots
  app/javascript/dashboard/i18n/locale/en/agentBots.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/components/BotConfiguration.vue
  app/javascript/dashboard/store/modules/agentBots.js
  app/javascript/dashboard/store/modules/specs/agentBots/agentBots.spec.js
Labels: frontend, chore, PR: unreviewed, PR: reviewed-approved

#6248 fix: Use account locale as the default locale on widget
  app/javascript/packs/sdk.js
  app/javascript/widget/App.vue
Labels: PR: partially-approved

#6005 chore: Fix connection pool
  .env.example
  Procfile.dev
  Procfile.test
  config/database.yml
  config/sidekiq.yml
  db/migrate/20200417093432_remove_name_from_channels.rb
  db/migrate/20200418124534_add_sender_to_messages.rb
  db/migrate/20200605130625_agent_away_message_to_auto_reply.rb
  deployment/chatwoot-worker.1.service
Labels: PR: unreviewed

#6252 fix: Adds animation to live chat trigger button
  app/javascript/sdk/sdk.js
Labels: PR: partially-approved

#6145 feat: Revamps editor for message and article
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/components/widgets/WootWriter/FullEditor.vue
  app/javascript/dashboard/components/widgets/mentions/MentionBox.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleEditor.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/ArticleEditor.stories.js
  package.json
  yarn.lock
Labels: PR: unreviewed

#6262 chore: Update styles for canned response
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/components/widgets/conversation/TagAgents.vue
  app/javascript/dashboard/components/widgets/mentions/MentionBox.vue
Labels: PR: unreviewed

#6227 Feat: Support for Microsoft Oauth in Email Channel
  .env.example
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/accounts/microsoft/authorizations_controller.rb
  app/controllers/concerns/microsoft_concern.rb
  app/controllers/microsoft/callbacks_controller.rb
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/jobs/inboxes/fetch_imap_emails_job.rb
  app/mailers/conversation_reply_mailer_helper.rb
  app/models/channel/email.rb
  app/services/microsoft/refresh_oauth_token_service.rb
  app/views/api/v1/models/_inbox.json.jbuilder
  config/routes.rb
  db/migrate/20221230113108_add_ms_oauth_token_to_channel.rb
  db/schema.rb
  lib/microsoft_graph_auth.rb
  spec/controllers/api/v1/accounts/microsoft/authorization_controller_spec.rb
  spec/controllers/microsoft/callbacks_controller_spec.rb
  spec/jobs/inboxes/fetch_imap_emails_job_spec.rb
  spec/mailers/conversation_reply_mailer_spec.rb
  spec/models/channel/email_spec.rb
  spec/services/microsoft/refresh_oauth_token_service_spec.rb
Labels: PR: unreviewed

#6263 fix: Add missing translations
  app/javascript/widget/i18n/locale/en.json
Labels: PR: unreviewed

#6024 Fix performance of report builder spec
  Gemfile
  Gemfile.lock
  spec/builders/v2/report_builder_spec.rb
  spec/rails_helper.rb
Labels: PR: partially-approved

#6265 Fixes #3670
  app/javascript/dashboard/i18n/locale/en/settings.json
Labels: PR: reviewed-approved

#5857 chore: Refactor code in ApplicationMailbox
  app/mailboxes/application_mailbox.rb
Labels: PR: partially-approved

#6243 feat: Add the UI flow for Microsoft Oauth
  app/controllers/dashboard_controller.rb
  app/javascript/dashboard/api/channel/microsoftClient.js
  app/javascript/dashboard/components/ChannelSelector.vue
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/FinishSetup.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Email.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/emailChannels/ForwardToOption.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/emailChannels/Microsoft.vue
  app/javascript/shared/store/globalConfig.js
  app/views/api/v1/models/_inbox.json.jbuilder
Labels: PR: reviewed-approved

#6272 fix: Update the inbox id if changed
  app/javascript/dashboard/routes/dashboard/settings/campaigns/EditCampaign.vue
Labels: PR: reviewed-approved

#6234 feat: more events tracking for SaaS
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/helper/AnalyticsHelper/events.js
  app/javascript/dashboard/helper/AnalyticsHelper/index.js
  app/javascript/dashboard/helper/AnalyticsHelper/plugin.js
  app/javascript/dashboard/helper/AnalyticsHelper/specs/events.spec.js
  app/javascript/dashboard/helper/AnalyticsHelper/specs/helper.spec.js
  app/javascript/dashboard/helper/AnalyticsHelper/specs/plugin.spec.js
  app/javascript/dashboard/modules/contact/ContactMergeModal.vue
  app/javascript/dashboard/modules/conversations/components/MessageContextMenu.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsAdvancedFilters.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ImportContacts.vue
  app/javascript/dashboard/routes/dashboard/conversation/Macros/MacroItem.vue
  app/javascript/dashboard/routes/dashboard/customviews/AddCustomViews.vue
  app/javascript/dashboard/routes/dashboard/customviews/DeleteCustomViews.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/AddLocale.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/EditArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/EditArticle.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/NewArticle.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/AddCategory.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/CategoryListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/EditCategory.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/categories/ListAllCategories.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/EditPortalLocales.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/PortalCustomization.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/PortalDetails.vue
  app/javascript/dashboard/routes/dashboard/settings/campaigns/AddCampaign.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/CsatResponses.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/WootReports.vue
  app/javascript/dashboard/store/modules/campaigns.js
  app/javascript/dashboard/store/modules/contacts/actions.js
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/csat.js
  app/javascript/dashboard/store/modules/inboxes.js
  app/javascript/dashboard/store/modules/labels.js
  app/javascript/dashboard/store/modules/reports.js
  app/javascript/packs/application.js
Labels: frontend, PR: unreviewed, PR: reviewed-approved, PR: partially-approved, product

#6264 chore: Update Inconsistent lang
  app/javascript/dashboard/i18n/locale/en/signup.json
Labels: PR: reviewed-approved

#6268 Microsoft Re-authorization flow
  app/controllers/microsoft_controller.rb
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/microsoft/Reauthorize.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/ConfigurationPage.vue
  app/views/microsoft/identity_association.json.erb
  config/routes.rb
  spec/controllers/microsoft_controller_spec.rb
Labels: PR: partially-approved

#6288 fix: Show only approved whatsapp templates
  app/javascript/dashboard/components/widgets/conversation/WhatsappTemplates/TemplatesPicker.vue
Labels: frontend, PR: unreviewed, PR: partially-approved

#6293 fix: Whatsapp template picker bug
  app/javascript/dashboard/components/widgets/conversation/WhatsappTemplates/TemplatesPicker.vue
Labels: PR: partially-approved

#6298 Fix: more events tracking for SaaS (#6234)
  app/javascript/dashboard/store/modules/conversations/actions.js
Labels: PR: reviewed-approved

#6297 feat: ignore errors from extensions
  app/javascript/packs/application.js
Labels: PR: partially-approved

#6295 fix: Error when unsupported Whatsapp message status
  app/services/whatsapp/incoming_message_base_service.rb
  app/services/whatsapp/incoming_message_service_helpers.rb
  spec/services/whatsapp/incoming_message_service_spec.rb
Labels: PR: unreviewed

#6289 chore: add stale PR bot
  .github/workflows/stale.yml
Labels: PR: unreviewed

#6306 chore: Add an event for conversation filter
  app/javascript/dashboard/components/widgets/conversation/ConversationAdvancedFilter.vue
  app/javascript/dashboard/helper/AnalyticsHelper/events.js
Labels: PR: unreviewed

#6287 fix: Prevent overflowing content in articles in phones
  app/views/public/api/v1/portals/articles/show.html.erb
Labels: PR: partially-approved

#5986 Update setup_20.04.sh
  deployment/setup_20.04.sh
Labels: PR: reviewed-approved, need-testing, community

#6267 feat: Shows the last activity, created at timestamp in the same row
  app/javascript/dashboard/assets/scss/_foundation-custom.scss
  app/javascript/dashboard/components/ui/TimeAgo.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/mixins/specs/time.spec.js
  app/javascript/dashboard/mixins/time.js
  app/javascript/shared/assets/stylesheets/colors.scss
  app/views/api/v1/conversations/partials/_conversation.json.jbuilder
Labels: PR: partially-approved

#6310 chore: Adds the ability to see the existing filter when we apply a new filter
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/widgets/conversation/ChatFilter.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationAdvancedFilter.vue
  app/javascript/dashboard/i18n/locale/en/chatlist.json
  app/javascript/shared/mixins/filterMixin.js
  app/javascript/shared/mixins/specs/filterMixin.spec.js
Labels: PR: unreviewed

#6308 chore: Fixes grammatical errors with content on inbox page
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
Labels: PR: unreviewed

#6077 feat: Support variables in canned response
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/conversation/VariableList.vue
  app/javascript/dashboard/helper/AnalyticsHelper/events.js
  app/javascript/dashboard/helper/messageHelper.js
  app/javascript/dashboard/helper/specs/messageHelper.spec.js
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
  app/javascript/dashboard/routes/dashboard/settings/canned/AddCanned.vue
  app/javascript/dashboard/routes/dashboard/settings/canned/EditCanned.vue
  app/javascript/shared/constants/messages.js
  package.json
  yarn.lock
Labels: PR: partially-approved

#6331 fix: Remove whatsapp formats which are currently not supported
  app/javascript/dashboard/components/widgets/conversation/WhatsappTemplates/TemplatesPicker.vue
Labels: PR: reviewed-approved

#5555 chore: upgrade ruby to 3.1.3
  .circleci/config.yml
  .github/workflows/run_foss_spec.yml
  .rubocop.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  app/controllers/concerns/switch_locale.rb
  app/mailers/application_mailer.rb
  app/models/dashboard_app.rb
  app/services/whatsapp/providers/whatsapp_cloud_service.rb
  deployment/chatwoot-web.1.service
  deployment/chatwoot-worker.1.service
  deployment/setup_20.04.sh
  docker/Dockerfile
  spec/controllers/api/v1/accounts/macros_controller_spec.rb
  spec/factories/twitter/twitter_message_create_event.rb
  spec/jobs/webhooks/line_events_job_spec.rb
  spec/jobs/webhooks/telegram_events_job_spec.rb
  spec/services/whatsapp/incoming_message_service_spec.rb
  spec/spec_helper.rb
Labels: PR: reviewed-approved, ready-for-pickup

#6349 fix: Add missing timestamp in the real-time event
  app/presenters/conversations/event_data_presenter.rb
  spec/models/conversation_spec.rb
  spec/presenters/conversations/event_data_presenter_spec.rb
Labels: PR: unreviewed

#6350 fix: Update styles for canned responses modal
  app/javascript/dashboard/components/widgets/conversation/CannedResponse.vue
  app/javascript/dashboard/components/widgets/conversation/VariableList.vue
  app/javascript/dashboard/components/widgets/mentions/MentionBox.vue
  app/javascript/dashboard/routes/dashboard/settings/canned/AddCanned.vue
  app/javascript/dashboard/routes/dashboard/settings/canned/EditCanned.vue
Labels: PR: unreviewed

#6340 fix: validate instagram story only while saving the message
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/instagramImageErrorPlaceholder.vue
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/models/message.rb
  spec/models/attachment_spec.rb
  spec/models/channel/facebook_page_spec.rb
  spec/models/message_spec.rb
Labels: PR: unreviewed

#6358 feat: Add support for variables in macros and automation
  app/javascript/dashboard/components/widgets/AutomationActionInput.vue
Labels: PR: reviewed-approved

#6359 fix: Fixes enter key sending text while mentions menu is active
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: reviewed-approved

#6045 feat: add chatwoot instance status in superadmin
  app/controllers/api_controller.rb
  app/controllers/super_admin/instance_statuses_controller.rb
  app/views/super_admin/application/_navigation.html.erb
  app/views/super_admin/instance_statuses/show.html.erb
  config/routes.rb
  spec/controllers/api_controller_spec.rb
  spec/controllers/super_admin/instance_statuses_controller_spec.rb
Labels: PR: unreviewed

#6317 fix: Uses woot-button in mention box
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/conversation/TagAgents.vue
  app/javascript/dashboard/components/widgets/mentions/MentionBox.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
Labels: PR: unreviewed

#6324 feat: Order articles by updated_at
  app/controllers/api/v1/accounts/articles_controller.rb
  app/models/article.rb
Labels: PR: unreviewed

#6347 chore: run linting on staged files only
  .husky/pre-commit
  package.json
Labels: PR: unreviewed

#6363 fix: redis health status in superadmin panel
  app/controllers/super_admin/instance_statuses_controller.rb
Labels: PR: unreviewed, ready-for-pickup
