Repository chatwoot/chatwoot, pull requests merged in 2023-02, with the labels that each got.

#6373 chore: Enable language Icelandic(is)
  config/initializers/languages.rb
Labels: PR: unreviewed

#6326 fix: Identity JSON response header
  app/controllers/microsoft_controller.rb
  app/views/microsoft/identity_association.json.erb
  app/views/microsoft/identity_association.json.jbuilder
  spec/controllers/microsoft_controller_spec.rb
Labels: PR: reviewed-approved

#6379 Chore: specs for process_emails in message builder
  spec/builders/messages/message_builder_spec.rb
Labels: PR: reviewed-approved

#6380 fix: Increases font size for canned response list item
  app/javascript/dashboard/components/widgets/mentions/MentionBox.vue
Labels: bug, PR: unreviewed, PR: partially-approved

#6378 fix: Cannot delete message with attachments without content
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/modules/conversations/components/MessageContextMenu.vue
Labels: PR: partially-approved

#6381 feat: Don't run lock action on forks
  .github/workflows/lock.yml
Labels: PR: reviewed-approved

#6388 chore: Update New relic agent
  Gemfile.lock
Labels: PR: unreviewed

#6390 chore: Switch to web-push gem
  Gemfile
  Gemfile.lock
  app/services/notification/push_notification_service.rb
  lib/vapid_service.rb
  spec/services/notification/push_notification_service_spec.rb
Labels: PR: unreviewed

#6364 feat: Show contact created date in contact panel
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
  app/views/api/v1/models/_contact.json.jbuilder
Labels: PR: unreviewed

#6384 Translation Fix
  app/javascript/dashboard/i18n/locale/pt_BR/conversation.json
Labels: PR: reviewed-approved

#6382 feat: Ability for super admin to impersonate a user
  app/controllers/platform/api/v1/users_controller.rb
  app/models/concerns/sso_authenticatable.rb
  app/views/super_admin/users/_impersonate.erb
  app/views/super_admin/users/show.html.erb
  lib/seeders/account_seeder.rb
  lib/seeders/seed_data.yml
Labels: PR: unreviewed

#6375 fix: Update user availability status in real-time when change from the mobile app
  app/javascript/dashboard/store/modules/auth.js
  app/javascript/dashboard/store/modules/specs/auth/mutations.spec.js
Labels: PR: partially-approved

#6403 fix: data.attachments is undefined for emails without body
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: unreviewed

#6404 chore: Add subject line to the slack message summary
  lib/integrations/slack/send_on_slack_service.rb
  spec/lib/integrations/slack/send_on_slack_service_spec.rb
Labels: PR: unreviewed

#6400 fix: order for canned response
  app/controllers/api/v1/accounts/canned_responses_controller.rb
  app/models/canned_response.rb
  spec/controllers/api/v1/accounts/canned_responses_controller_spec.rb
Labels: PR: partially-approved

#6405 fix: Add defaults for the cc, bcc emails
  app/builders/messages/message_builder.rb
Labels: PR: unreviewed

#6330 feat: Ability to receive contact on whatsapp inbox
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Contact.vue
  app/javascript/dashboard/components/widgets/conversation/stories/ContactBubble.stories.js
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/store/modules/contacts/actions.js
  app/models/attachment.rb
  app/services/whatsapp/incoming_message_base_service.rb
  app/services/whatsapp/incoming_message_service_helpers.rb
  spec/jobs/webhooks/whatsapp_events_job_spec.rb
  spec/services/whatsapp/incoming_message_service_spec.rb
Labels: PR: reviewed-approved

#6412 Added event for conversation opened
  app/javascript/dashboard/helper/automationHelper.js
  app/javascript/dashboard/mixins/automations/methodsMixin.js
  app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
  app/listeners/automation_rule_listener.rb
  spec/listeners/automation_rule_listener_spec.rb
Labels: PR: reviewed-approved

#6408 fixBug: email notification error, Attachment Message without content
  app/helpers/message_format_helper.rb
Labels: PR: reviewed-approved

#6304 [Snyk] Fix for 9 vulnerabilities
  Gemfile
  Gemfile.lock
Labels: PR: reviewed-approved

#6348 feat: Adds the ability to change WhatsApp API key
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/settingsPage/ConfigurationPage.vue
Labels: PR: unreviewed

#6407 Added one more endpoint to attach tempfile and get logo
  app/controllers/api/v1/accounts/articles_controller.rb
  app/controllers/api/v1/accounts/portals_controller.rb
  app/policies/article_policy.rb
  app/policies/portal_policy.rb
  app/views/public/api/v1/models/hc/_portal.json.jbuilder
  config/routes.rb
  spec/controllers/api/v1/accounts/articles_controller_spec.rb
  spec/controllers/api/v1/accounts/portals_controller_spec.rb
Labels: PR: reviewed-approved

#6399 fix: Text color bug on attachment bubble
  app/javascript/widget/components/AgentMessage.vue
  app/javascript/widget/components/FileBubble.vue
  app/javascript/widget/components/UserMessage.vue
Labels: PR: partially-approved

#6419 chore: Remove pagination from macros listing api
  app/models/macro.rb
Labels: PR: partially-approved

#6425 chore: Add chatwoot:on-message event
  app/javascript/sdk/IFrameHelper.js
  app/javascript/widget/constants/sdkEvents.js
  app/javascript/widget/helpers/actionCable.js
  app/views/widget_tests/index.html.erb
Labels: PR: unreviewed

#6433 chore: Limit conversation resolution Job
  app/jobs/conversations/resolution_job.rb
  app/models/conversation.rb
  lib/limits.rb
  spec/jobs/conversations/resolution_job_spec.rb
Labels: PR: reviewed-approved

#6443 test: fix test breaking circle CI
  app/javascript/dashboard/mixins/specs/time.spec.js
Labels: PR: partially-approved

#6415 feat: Add contacts webhooks
  .rubocop.yml
  app/javascript/dashboard/i18n/locale/en/integrations.json
  app/javascript/dashboard/routes/dashboard/settings/integrations/Webhooks/WebhookForm.vue
  app/listeners/webhook_listener.rb
  app/models/contact.rb
  app/models/webhook.rb
  db/migrate/20230209033203_update_default_on_subscriptions_webhooks.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/webhook_controller_spec.rb
  spec/factories/webhooks.rb
  spec/listeners/webhook_listener_spec.rb
  swagger/definitions/resource/webhook.yml
  swagger/swagger.json
Labels: PR: unreviewed

#6444 chore: Switch to csv-safe gem to avoid csv injection
  Gemfile
  Gemfile.lock
  app/views/api/v2/accounts/reports/agents.csv.erb
  app/views/api/v2/accounts/reports/inboxes.csv.erb
  app/views/api/v2/accounts/reports/labels.csv.erb
  app/views/api/v2/accounts/reports/teams.csv.erb
Labels: PR: reviewed-approved

#6429 fix : Help Center article view count
  app/controllers/api/v1/accounts/articles_controller.rb
  app/controllers/public/api/v1/portals/articles_controller.rb
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleTable.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/ArticleItem.stories.js
Labels: PR: unreviewed

#6447 chore: Add formatting for the view count
  app/controllers/public/api/v1/portals/articles_controller.rb
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleItem.vue
  app/models/article.rb
  spec/controllers/public/api/v1/portals/articles_controller_spec.rb
  spec/factories/articles.rb
Labels: PR: unreviewed

#6448 fix: interactive messages - button should not respond to double click
  app/javascript/widget/store/modules/message.js
  app/javascript/widget/store/modules/specs/message/actions.spec.js
Labels: PR: reviewed-approved

#6430 feat: Adds support on direction RTL in UI (2)
  app/javascript/dashboard/assets/scss/_layout.scss
  app/javascript/dashboard/assets/scss/_rtl.scss
  app/javascript/dashboard/assets/scss/_woot.scss
  app/javascript/dashboard/assets/scss/plugins/_multiselect.scss
  app/javascript/dashboard/assets/scss/widgets/_buttons.scss
  app/javascript/dashboard/assets/scss/widgets/_conv-header.scss
  app/javascript/dashboard/assets/scss/widgets/_conversation-card.scss
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/assets/scss/widgets/_report.scss
  app/javascript/dashboard/assets/scss/widgets/_reports.scss
  app/javascript/dashboard/assets/scss/widgets/_sidemenu.scss
  app/javascript/dashboard/assets/scss/widgets/_tabs.scss
  app/javascript/dashboard/assets/scss/widgets/_woot-tables.scss
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/CustomAttribute.vue
  app/javascript/dashboard/components/SidemenuIcon.vue
  app/javascript/dashboard/components/buttons/ResolveAction.vue
  app/javascript/dashboard/components/layout/Sidebar.vue
  app/javascript/dashboard/components/layout/sidebarComponents/AccountContext.vue
  app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue
  app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/components/widgets/BackButton.vue
  app/javascript/dashboard/components/widgets/TableFooter.vue
  app/javascript/dashboard/components/widgets/UserAvatarWithName.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/contextMenu/menuItem.vue
  app/javascript/dashboard/components/widgets/conversation/contextMenu/menuItemWithSubmenu.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/AgentSelector.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/Index.vue
  app/javascript/dashboard/components/widgets/conversation/conversationCardComponents/CardLabels.vue
  app/javascript/dashboard/modules/notes/components/ContactNote.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
  app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/ArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/EditArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSwitch.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Sidebar/Sidebar.vue
  app/javascript/dashboard/routes/dashboard/notifications/components/NotificationPanel.vue
  app/javascript/dashboard/routes/dashboard/notifications/components/NotificationPanelList.vue
  app/javascript/dashboard/routes/dashboard/settings/SettingsHeader.vue
  app/javascript/dashboard/routes/dashboard/settings/campaigns/CampaignsTable.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatTable.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/FilterSelector.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/overview/AgentTable.vue
Labels: PR: unreviewed

#6428 fix: Send attachments as multiple messages for whatsapp channel
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: unreviewed

#6461 chore: Refactor the notification service for participants
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/listeners/notification_listener.rb
  app/models/concerns/message_filter_helpers.rb
  app/models/inbox.rb
  app/services/messages/mention_service.rb
  app/services/messages/new_message_notification_service.rb
  spec/services/messages/mention_service_spec.rb
  spec/services/messages/new_message_notification_service_spec.rb
Labels: PR: unreviewed

#6462 chore: Add controllers for conversation participants
  .rubocop.yml
  app/controllers/api/v1/accounts/conversations/participants_controller.rb
  app/finders/conversation_finder.rb
  app/mailers/agent_notifications/conversation_notifications_mailer.rb
  app/models/concerns/assignment_handler.rb
  app/models/concerns/user_attribute_helpers.rb
  app/models/conversation.rb
  app/models/conversation_participant.rb
  app/models/notification.rb
  app/models/user.rb
  app/services/messages/mention_service.rb
  app/services/messages/new_message_notification_service.rb
  app/views/api/v1/accounts/conversations/participants/create.json.jbuilder
  app/views/api/v1/accounts/conversations/participants/show.json.jbuilder
  app/views/api/v1/accounts/notifications/index.json.jbuilder
  app/views/mailers/agent_notifications/conversation_notifications_mailer/participating_conversation_new_message.liquid
  config/routes.rb
  db/migrate/20220808193420_add_conversation_participants.rb
  db/migrate/20230118155353_add_unique_index_to_conversation_participants.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/bulk_actions_controller_spec.rb
  spec/controllers/api/v1/accounts/conversations/assignments_controller_spec.rb
  spec/controllers/api/v1/accounts/conversations/participants_controller_spec.rb
  spec/controllers/api/v2/accounts/report_controller_spec.rb
  spec/factories/conversation_participants.rb
  spec/jobs/bulk_actions_job_spec.rb
  spec/mailers/agent_notifications/conversation_notifications_mailer_spec.rb
  spec/models/concerns/assignment_handler_shared.rb
  spec/models/conversation_participants_spec.rb
  spec/models/conversation_spec.rb
  spec/models/notification_spec.rb
  spec/services/auto_assignment/agent_assignment_service_spec.rb
  spec/services/messages/mention_service_spec.rb
  spec/services/messages/new_message_notification_service_spec.rb
Labels: PR: unreviewed

#6465 chore: Limit widget endpoint with rack attack
  config/initializers/rack_attack.rb
Labels: PR: reviewed-approved

#6454 feat: Add Google Translate API Integration
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/accounts/conversations/messages_controller.rb
  app/javascript/dashboard/api/inbox/message.js
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/modules/conversations/components/MessageContextMenu.vue
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/dashboard/store/modules/conversations/actions/messageTranslateActions.js
  app/javascript/dashboard/store/modules/integrations.js
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/models/message.rb
  config/integration/apps.yml
  config/locales/en.yml
  config/routes.rb
  lib/integrations/google_translate/processor_service.rb
  public/dashboard/images/integrations/googletranslate.png
Labels: PR: unreviewed

#6426 feat: Adds image attachment for help center articles
  app/javascript/dashboard/api/helpCenter/articles.js
  app/javascript/dashboard/components/widgets/WootWriter/FullEditor.vue
  app/javascript/dashboard/i18n/locale/en/helpCenter.json
  app/javascript/dashboard/store/modules/helpCenterArticles/actions.js
  package.json
  yarn.lock
Labels: PR: partially-approved

#6346 feat: Google OAuth for login & signup
  .env.example
  .gitignore
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  app/controllers/devise_overrides/omniauth_callbacks_controller.rb
  app/helpers/email_helper.rb
  app/javascript/dashboard/components/ui/Auth/GoogleOAuthButton.spec.js
  app/javascript/dashboard/components/ui/Auth/GoogleOAuthButton.vue
  app/javascript/dashboard/i18n/locale/en/login.json
  app/javascript/dashboard/i18n/locale/en/signup.json
  app/javascript/dashboard/routes/auth/Signup.vue
  app/javascript/dashboard/routes/auth/components/Signup/Form.vue
  app/javascript/dashboard/routes/auth/components/Testimonials/Index.vue
  app/javascript/dashboard/routes/index.js
  app/javascript/dashboard/routes/login/Login.vue
  app/javascript/dashboard/routes/login/login.routes.js
  app/models/user.rb
  app/views/layouts/vueapp.html.erb
  config/initializers/omniauth.rb
  config/routes.rb
  config/webpack/resolve.js
  package.json
  public/assets/images/auth/google.svg
  spec/controllers/devise/omniauth_callbacks_controller_spec.rb
  yarn.lock
Labels: PR: unreviewed

#4145 feat: conversation participants
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/layout/config/sidebarItems/conversations.js
  app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue
  app/javascript/dashboard/helper/URLHelper.js
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/i18n/locale/en/generalSettings.json
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/mixins/specs/uiSettings.spec.js
  app/javascript/dashboard/mixins/uiSettings.js
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/ConversationParticipant.vue
  app/javascript/dashboard/routes/dashboard/conversation/conversation.routes.js
  app/javascript/dashboard/routes/dashboard/settings/profile/NotificationSettings.vue
  app/javascript/dashboard/store/modules/conversationWatchers.js
  app/javascript/dashboard/store/modules/conversations/getters.js
  app/javascript/dashboard/store/modules/conversations/index.js
  app/javascript/dashboard/store/modules/specs/conversationWatchers/actions.spec.js
  app/javascript/dashboard/store/modules/specs/conversationWatchers/mutations.spec.js
  app/javascript/dashboard/store/mutation-types.js
  app/javascript/shared/components/ChatForm.vue
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
  app/javascript/shared/components/ui/MultiselectDropdown.vue
  app/javascript/shared/components/ui/MultiselectDropdownItems.stories.js
  app/javascript/shared/components/ui/MultiselectDropdownItems.vue
  spec/listeners/notification_listener_spec.rb
Labels: PR: unreviewed

#5485 swagger: fixed invalid specification
  .circleci/config.yml
  swagger/definitions/index.yml
  swagger/definitions/request/contact/create.yml
  swagger/definitions/request/contact/update.yml
  swagger/definitions/resource/extension/conversation/show.yml
  swagger/definitions/resource/extension/message/with_source_sender.yml
  swagger/swagger.json
Labels: PR: unreviewed, community

#6472 fix: Add scoped CSS for participants
  app/javascript/dashboard/routes/dashboard/conversation/ConversationParticipant.vue
Labels: PR: reviewed-approved

#6475 fix: Add a settings link for portals in sidebar
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
Labels: PR: partially-approved

#6474 chore: Enable push permissions if available
  app/javascript/dashboard/routes/dashboard/settings/profile/NotificationSettings.vue
  app/views/layouts/vueapp.html.erb
Labels: PR: unreviewed

#6479 fix: Warning in conversations page from participants
  app/javascript/dashboard/routes/dashboard/conversation/ConversationParticipant.vue
Labels: PR: unreviewed

#6458 feat: Adds rtl related scss to a single file
  app/javascript/dashboard/assets/scss/_rtl.scss
  app/javascript/dashboard/components/layout/AvailabilityStatus.vue
  app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/ListAllPortals.vue
Labels: PR: partially-approved

#6495 fix: foss_spec github action
  .github/workflows/run_foss_spec.yml
Labels: PR: unreviewed

#6494 feat: Integrate LogRocket
  .env.example
  app/javascript/dashboard/helper/scriptHelpers.js
  app/javascript/dashboard/store/index.js
  app/views/layouts/vueapp.html.erb
  package.json
  yarn.lock
Labels: PR: unreviewed

#6496 fix: sentry CHATWOOT-37A ActiveRecord::RecordNotUnique
  app/controllers/api/v1/accounts/conversations_controller.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
Labels: PR: unreviewed

#6490 Bumped Ruby version on codespace image to 3.1.3
  .devcontainer/Dockerfile.base
Labels: PR: reviewed-approved

#6492 fix: Access token should be hidden/masked by default in Agent Dashboard
  app/javascript/dashboard/components/MaskedText.vue
  app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue
  app/javascript/shared/components/FluentIcon/dashboard-icons.json
Labels: PR: reviewed-approved

#6505 fix: Icelandic locale shows only english
  app/javascript/dashboard/i18n/index.js
  app/javascript/dashboard/i18n/locale/is/index.js
Labels: PR: unreviewed

#6520 chore: Refactors chatlist header css to work with RTL
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/components/SidemenuIcon.vue
  app/javascript/dashboard/components/layout/AvailabilityStatus.vue
  app/javascript/dashboard/components/widgets/conversation/ChatFilter.vue
  app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
  app/javascript/dashboard/routes/dashboard/conversation/search/SwitchLayout.vue
Labels: PR: reviewed-approved

#6516 chore: Refactor integrations pages for RTL
  app/javascript/dashboard/assets/scss/views/settings/integrations.scss
  app/javascript/dashboard/routes/dashboard/settings/integrationapps/IntegrationItem.vue
  app/javascript/dashboard/routes/dashboard/settings/integrationapps/SingleIntegrationHooks.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/Integration.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/IntegrationHelpText.vue
Labels: PR: reviewed-approved

#6521 chore: RTL configuration
  app/javascript/dashboard/App.vue
  app/javascript/dashboard/assets/scss/_rtl.scss
  app/javascript/dashboard/assets/scss/_woot.scss
  app/javascript/dashboard/components/widgets/conversation/advancedFilterItems/languages.js
  app/javascript/dashboard/components/widgets/conversation/advancedFilterItems/specs/languages.spec.js
  app/javascript/dashboard/routes/dashboard/settings/account/Index.vue
  app/javascript/shared/mixins/rtlMixin.js
  app/javascript/shared/mixins/specs/rtlMixin.spec.js
Labels: PR: reviewed-approved

#6523 fix: ActiveRecord::RecordNotFound Couldn't find Channel::WebWidget
  app/controllers/widgets_controller.rb
  spec/controllers/widgets_controller_spec.rb
Labels: PR: partially-approved

#6517 chore: Refactor reports for RTL
  app/javascript/dashboard/assets/scss/_date-picker.scss
  app/javascript/dashboard/assets/scss/_foundation-custom.scss
  app/javascript/dashboard/assets/scss/_utility-helpers.scss
  app/javascript/dashboard/assets/scss/plugins/_multiselect.scss
  app/javascript/dashboard/assets/scss/widgets/_reports.scss
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/AgentSelector.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue
  app/javascript/dashboard/routes/dashboard/contacts/pages/ContactManageView.vue
  app/javascript/dashboard/routes/dashboard/settings/campaigns/AddCampaign.vue
  app/javascript/dashboard/routes/dashboard/settings/integrations/Webhooks/WebhookForm.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/FilterSelector.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/ReportFilters.vue
Labels: PR: unreviewed

#6529 chore: Display CSAT responses in the message itself
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: unreviewed

#6524 chore: Refactor chat list for RTL
  app/javascript/dashboard/assets/scss/_rtl.scss
  app/javascript/dashboard/assets/scss/widgets/_conversation-card.scss
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/components/widgets/InboxName.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/components/widgets/conversation/conversationCardComponents/CardLabels.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
Labels: PR: reviewed-approved

#6519 chore: Refactor sidebar related changes for RTL
  app/javascript/dashboard/assets/scss/_rtl.scss
  app/javascript/dashboard/assets/scss/widgets/_conv-header.scss
  app/javascript/dashboard/assets/scss/widgets/_sidemenu.scss
  app/javascript/dashboard/assets/scss/widgets/_tabs.scss
  app/javascript/dashboard/components/layout/sidebarComponents/AccountContext.vue
  app/javascript/dashboard/components/layout/sidebarComponents/OptionsMenu.vue
  app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
  app/javascript/dashboard/components/widgets/BackButton.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationBox.vue
  app/javascript/dashboard/components/widgets/conversation/contextMenu/menuItem.vue
  app/javascript/dashboard/components/widgets/conversation/contextMenu/menuItemWithSubmenu.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/ArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/EditArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/HelpCenterLayout.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalSwitch.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/ListAllPortals.vue
  app/javascript/dashboard/routes/dashboard/notifications/components/NotificationPanelList.vue
  app/javascript/dashboard/routes/dashboard/settings/inbox/WidgetBuilder.vue
  app/javascript/shared/components/ui/MultiselectDropdown.vue
  app/javascript/shared/components/ui/dropdown/DropdownHeader.vue
Labels: PR: reviewed-approved

#6528 Add sender_name in the SMTP reply mails
  app/mailers/conversation_reply_mailer.rb
  app/mailers/conversation_reply_mailer_helper.rb
  config/locales/en.yml
  spec/mailers/conversation_reply_mailer_spec.rb
Labels: PR: partially-approved

#6530 fix: Name missing when email is collected via email hook
  app/controllers/api/v1/widget/messages_controller.rb
  spec/controllers/api/v1/widget/messages_controller_spec.rb
Labels: PR: unreviewed

#6535 chore: add `--force-exclusion` option to rubocop pre-commit hook
  .husky/pre-commit
Labels: PR: reviewed-approved

#6526 chore: Refactor conversation info panel for RTL
  app/javascript/dashboard/assets/scss/_rtl.scss
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/assets/scss/widgets/_sidemenu.scss
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/Index.vue
  app/javascript/dashboard/modules/contact/components/ContactDropdownItem.vue
  app/javascript/dashboard/modules/notes/components/ContactNote.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactInfoPanel.vue
  app/javascript/dashboard/routes/dashboard/contacts/pages/ContactManageView.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactConversations.vue
  app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
  app/javascript/dashboard/routes/dashboard/conversation/contact/SocialIcons.vue
Labels: PR: reviewed-approved

#6409 fix: bots included in time to response metrics
  app/helpers/reporting_event_helper.rb
  app/jobs/migration/update_first_response_time_in_reporting_events_job.rb
  app/listeners/reporting_event_listener.rb
  app/models/concerns/conversation_mute_helpers.rb
  app/models/conversation.rb
  app/models/message.rb
  db/migrate/20230214025901_update_reporting_events_with_incorrect_first_responses.rb
  db/schema.rb
  lib/events/types.rb
  lib/integrations/bot_processor_service.rb
  spec/listeners/reporting_event_listener_spec.rb
Labels: PR: partially-approved

#6525 chore: Refactor tables in all screen for RTL
  app/javascript/dashboard/assets/scss/_rtl.scss
  app/javascript/dashboard/assets/scss/plugins/_multiselect.scss
  app/javascript/dashboard/assets/scss/widgets/_woot-tables.scss
  app/javascript/dashboard/components/widgets/TableFooter.vue
  app/javascript/dashboard/components/widgets/UserAvatarWithName.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
  app/javascript/dashboard/routes/dashboard/notifications/components/NotificationPanel.vue
  app/javascript/dashboard/routes/dashboard/settings/campaigns/CampaignsTable.vue
  app/javascript/dashboard/routes/dashboard/settings/macros/MacrosTableRow.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatTable.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/overview/AgentTable.vue
Labels: PR: reviewed-approved

#6537 chore: Refactor reports css for RTL
  app/javascript/dashboard/assets/scss/widgets/_report.scss
  app/javascript/dashboard/assets/scss/widgets/_reports.scss
  app/javascript/dashboard/components/widgets/UserAvatarWithName.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatMetricCard.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/CsatMetrics.vue
Labels: PR: unreviewed

#6531 chore: Adds the ability to automatically initialize the RTL direction
  app/javascript/dashboard/App.vue
  app/javascript/shared/mixins/rtlMixin.js
Labels: PR: unreviewed

#6533 fix: Email subject automation issue
  lib/filters/filter_keys.json
  spec/listeners/automation_rule_listener_spec.rb
Labels: PR: partially-approved

#6554 fix: Condition based backend validation
  app/models/automation_rule.rb
  spec/models/automation_rule_spec.rb
Labels: PR: reviewed-approved

#6557 fix: Fetch categories by locale
  app/controllers/public/api/v1/portals/articles_controller.rb
  spec/controllers/public/api/v1/portals/articles_controller_spec.rb
Labels: PR: unreviewed

#6559 fix: Fix i18n issues with help center
  app/controllers/public/api/v1/portals/articles_controller.rb
  app/controllers/public/api/v1/portals/base_controller.rb
  app/controllers/public/api/v1/portals/categories_controller.rb
  app/controllers/public/api/v1/portals_controller.rb
  app/views/public/api/v1/portals/_article_count.html.erb
  app/views/public/api/v1/portals/_category-block.html.erb
  app/views/public/api/v1/portals/_footer.html.erb
  app/views/public/api/v1/portals/_header.html.erb
  app/views/public/api/v1/portals/articles/index.html.erb
  app/views/public/api/v1/portals/articles/show.html.erb
  app/views/public/api/v1/portals/categories/_category-block.html.erb
  app/views/public/api/v1/portals/categories/_hero.html.erb
  app/views/public/api/v1/portals/categories/show.html.erb
  config/locales/en.yml
  config/locales/fr.yml
Labels: PR: unreviewed

#6513 chore: upload log artifact in nightly gh action
  .github/workflows/nightly_installer.yml
Labels: PR: unreviewed

#6511 feat: Add the option for data protection consent form in pre-chat form
  .vscode/settings.json
  app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
  app/javascript/dashboard/routes/dashboard/settings/inbox/PreChatForm/Settings.vue
  app/javascript/widget/components/PreChat/Form.vue
  app/javascript/widget/i18n/locale/en.json
Labels: PR: unreviewed

#6562 bug: Fixes i18n is not working on the help center dashboard
  app/javascript/dashboard/i18n/locale/ar/index.js
  app/javascript/dashboard/i18n/locale/bg/index.js
  app/javascript/dashboard/i18n/locale/ca/index.js
  app/javascript/dashboard/i18n/locale/cs/index.js
  app/javascript/dashboard/i18n/locale/da/index.js
  app/javascript/dashboard/i18n/locale/de/index.js
  app/javascript/dashboard/i18n/locale/el/index.js
  app/javascript/dashboard/i18n/locale/es/index.js
  app/javascript/dashboard/i18n/locale/fa/index.js
  app/javascript/dashboard/i18n/locale/fi/index.js
  app/javascript/dashboard/i18n/locale/fr/index.js
  app/javascript/dashboard/i18n/locale/he/index.js
  app/javascript/dashboard/i18n/locale/hi/index.js
  app/javascript/dashboard/i18n/locale/hu/index.js
  app/javascript/dashboard/i18n/locale/id/index.js
  app/javascript/dashboard/i18n/locale/it/index.js
  app/javascript/dashboard/i18n/locale/ja/index.js
  app/javascript/dashboard/i18n/locale/ko/index.js
  app/javascript/dashboard/i18n/locale/lv/index.js
  app/javascript/dashboard/i18n/locale/ml/index.js
  app/javascript/dashboard/i18n/locale/ne/index.js
  app/javascript/dashboard/i18n/locale/nl/index.js
  app/javascript/dashboard/i18n/locale/no/index.js
  app/javascript/dashboard/i18n/locale/pl/index.js
  app/javascript/dashboard/i18n/locale/pt/index.js
  app/javascript/dashboard/i18n/locale/pt_BR/index.js
  app/javascript/dashboard/i18n/locale/ro/index.js
  app/javascript/dashboard/i18n/locale/ru/index.js
  app/javascript/dashboard/i18n/locale/sk/index.js
  app/javascript/dashboard/i18n/locale/sr/index.js
  app/javascript/dashboard/i18n/locale/sv/index.js
  app/javascript/dashboard/i18n/locale/ta/index.js
  app/javascript/dashboard/i18n/locale/th/index.js
  app/javascript/dashboard/i18n/locale/tr/index.js
  app/javascript/dashboard/i18n/locale/uk/index.js
  app/javascript/dashboard/i18n/locale/ur/index.js
  app/javascript/dashboard/i18n/locale/ur_IN/index.js
  app/javascript/dashboard/i18n/locale/vi/index.js
  app/javascript/dashboard/i18n/locale/zh/index.js
  app/javascript/dashboard/i18n/locale/zh_CN/index.js
  app/javascript/dashboard/i18n/locale/zh_TW/index.js
  app/javascript/dashboard/routes/dashboard/helpcenter/components/Header/ArticleHeader.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/PortalListItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/portals/ListAllPortals.vue
Labels: PR: partially-approved

#6564 feat: New APIs for search
  app/controllers/api/v1/accounts/search_controller.rb
  app/jobs/migration/add_search_indexes_job.rb
  app/models/contact.rb
  app/models/message.rb
  app/services/search_service.rb
  app/views/api/v1/accounts/search/_agent.json.jbuilder
  app/views/api/v1/accounts/search/_contact.json.jbuilder
  app/views/api/v1/accounts/search/_inbox.json.jbuilder
  app/views/api/v1/accounts/search/_message.json.jbuilder
  app/views/api/v1/accounts/search/contacts.json.jbuilder
  app/views/api/v1/accounts/search/conversations.json.jbuilder
  app/views/api/v1/accounts/search/index.json.jbuilder
  app/views/api/v1/accounts/search/messages.json.jbuilder
  config/routes.rb
  db/migrate/20230224124632_add_index_for_search_operations.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/search_controller_spec.rb
  spec/services/search_service_spec.rb
Labels: PR: unreviewed
