Repository chatwoot/chatwoot, pull requests merged in 2023-10, with the labels that each got.

#8011 chore: Refactor Response Bot Data Schema
  app/views/api/v1/models/_response_source.json.jbuilder
  config/initializers/monkey_patches/schema_dumper.rb
  enterprise/app/controllers/api/v1/accounts/response_sources_controller.rb
  enterprise/app/dashboards/response_dashboard.rb
  enterprise/app/dashboards/response_document_dashboard.rb
  enterprise/app/dashboards/response_source_dashboard.rb
  enterprise/app/jobs/response_builder_job.rb
  enterprise/app/models/enterprise/audit_log.rb
  enterprise/app/models/enterprise/concerns/inbox.rb
  enterprise/app/models/enterprise/inbox.rb
  enterprise/app/models/inbox_response_source.rb
  enterprise/app/models/response.rb
  enterprise/app/models/response_document.rb
  enterprise/app/models/response_source.rb
  enterprise/app/services/features/response_bot_service.rb
  lib/tasks/auto_annotate_models.rake
  spec/enterprise/controllers/api/v1/accounts/response_sources_controller_spec.rb
  spec/enterprise/controllers/enterprise/api/v1/accounts/inboxes_controller_spec.rb
Labels: Enterprise

#7949 fix: Issue on the status filter field
  app/javascript/dashboard/assets/scss/plugins/_multiselect.scss
Labels: community

#7979 feat: Adds dark theme support for public portal [CW-2525]
  app/controllers/public/api/v1/portals/base_controller.rb
  app/helpers/portal_helper.rb
  app/javascript/portal/components/PublicSearchInput.vue
  app/javascript/portal/components/SearchSuggestions.vue
  app/javascript/portal/components/TableOfContents.vue
  app/views/layouts/portal.html.erb
  app/views/public/api/v1/portals/_category-block.html.erb
  app/views/public/api/v1/portals/_footer.html.erb
  app/views/public/api/v1/portals/_header.html.erb
  app/views/public/api/v1/portals/_hero.html.erb
  app/views/public/api/v1/portals/_uncategorized-block.html.erb
  app/views/public/api/v1/portals/articles/_article_header.html.erb
  app/views/public/api/v1/portals/articles/index.html.erb
  app/views/public/api/v1/portals/articles/show.html.erb
  app/views/public/api/v1/portals/categories/_category-block.html.erb
  app/views/public/api/v1/portals/categories/_category-hero.html.erb
  app/views/public/api/v1/portals/categories/_hero.html.erb
  app/views/public/api/v1/portals/categories/show.html.erb
  public/assets/images/hc/grid_dark.svg
  spec/helpers/portal_helper_spec.rb
Labels: PR: reviewed-changes-requested

#7950 chore: added fix for mouseup event in modal
  app/javascript/dashboard/components/Modal.vue
Labels: community

#7968 chore: Adds a bus event to insert text at cursor in editor
  app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
  app/javascript/dashboard/helper/editorHelper.js
  app/javascript/dashboard/helper/specs/editorHelper.spec.js
Labels: PR: reviewed-changes-requested

#7957 feat: Creates components for Article Search in Reply [CW-2285]
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleSearch/ArticleSearchResultItem.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleSearch/ArticleView.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleSearch/Header.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/ArticleSearch/SearchResults.vue
  app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/ArticleSearchArticleView.stories.js
  app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/ArticleSearchHeader.stories.js
  app/javascript/dashboard/routes/dashboard/helpcenter/components/stories/ArticleSearchResultItem.stories.js
  app/javascript/shared/components/ArticleSkeletonLoader.vue
  tailwind.config.js
Labels: PR: reviewed-changes-requested
