Repository chatwoot/chatwoot, pull requests merged in 2023-03, with the labels that each got.

#6568 bug: Bulk actions Assign agent is not working
  app/javascript/dashboard/components/widgets/conversation/conversationBulkActions/AgentSelector.vue
Labels: PR: partially-approved

#6567 fix: Show only categories where published articles count > 0
  app/views/public/api/v1/portals/show.html.erb
Labels: PR: partially-approved

#6569 chore: Fix flaky test in search service spec
  spec/services/search_service_spec.rb
Labels: PR: reviewed-approved

#6497 chore: Load only required APMs
  Gemfile
  Gemfile.lock
  config/application.rb
  config/scout_apm.yml
  spec/lib/chatwoot_exception_tracker_spec.rb
Labels: PR: unreviewed

#6482 chore: Support plus forwarding in email channel
  app/finders/email_channel_finder.rb
  app/helpers/email_helper.rb
  spec/finders/email_channel_finder_spec.rb
  spec/helpers/email_helper_spec.rb
Labels: PR: unreviewed

#6575 feat: Creates component to display conversation search results
  app/javascript/dashboard/modules/search/components/SearchResultConversationItem.vue
  app/javascript/dashboard/modules/search/stories/SearchResultConversationItem.stories.js
Labels: PR: unreviewed

#6434 feat: Audit log APIs
  Gemfile
  Gemfile.lock
  app/models/account.rb
  app/models/automation_rule.rb
  app/models/inbox.rb
  app/models/webhook.rb
  config/initializers/audited.rb
  config/routes.rb
  db/migrate/20230202132107_install_audited.rb
  db/schema.rb
  enterprise/app/controllers/api/v1/accounts/audit_logs_controller.rb
  enterprise/app/models/enterprise/audit/account.rb
  enterprise/app/models/enterprise/audit/automation_rule.rb
  enterprise/app/models/enterprise/audit/inbox.rb
  enterprise/app/models/enterprise/audit/webhook.rb
  enterprise/app/models/enterprise/audit_log.rb
  spec/enterprise/controllers/api/v1/accounts/audit_logs_controller_spec.rb
  spec/enterprise/models/account_spec.rb
  spec/enterprise/models/automation_rule_spec.rb
  spec/enterprise/models/inbox_spec.rb
  spec/enterprise/models/webhook_spec.rb
Labels: PR: partially-approved, Enterprise, ready-for-pickup

#6576 Update: contact create swagger JSON
  swagger/definitions/resource/contact.yml
  swagger/swagger.json
Labels: PR: partially-approved

#6579 Fix: product#804: email sender improvement
  app/mailers/conversation_reply_mailer.rb
  config/locales/en.yml
  spec/mailers/conversation_reply_mailer_spec.rb
Labels: PR: reviewed-approved

#6587 fix: Allow integration apps to be listed by an agent
  app/controllers/api/v1/accounts/integrations/apps_controller.rb
  app/views/api/v1/models/_app.json.jbuilder
  app/views/api/v1/models/_hook.json.jbuilder
  spec/controllers/api/v1/accounts/integrations/apps_controller_spec.rb
Labels: PR: partially-approved

#6580 fix: Clicking contact name in conversation should open contact details panel
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
Labels: PR: reviewed-approved

#6594 chore: Handle APM variables being empty
  config/initializers/datadog.rb
  config/initializers/sentry.rb
Labels: PR: reviewed-approved

#6590 fix: migration script to run on all reporting events
  app/jobs/migration/update_first_response_time_in_reporting_events_job.rb
  config/sidekiq.yml
  db/migrate/20230214025901_update_reporting_events_with_incorrect_first_responses.rb
  db/migrate/20230302054408_update_reporting_events_first_response_time.rb
  db/schema.rb
Labels: PR: partially-approved

#6593 Chore: bot exception tracking
  lib/integrations/bot_processor_service.rb
  spec/lib/integrations/dialogflow/processor_service_spec.rb
Labels: PR: reviewed-approved

#6589 fix: Fixes assignee and inbox name spacing issues
  app/javascript/dashboard/assets/scss/_rtl.scss
  app/javascript/dashboard/assets/scss/widgets/_conversation-card.scss
  app/javascript/dashboard/components/ui/Label.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue
  app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
  app/javascript/dashboard/components/widgets/conversation/conversationCardComponents/CardLabels.vue
Labels: PR: partially-approved

#6603 Exception tracker with account for AgentBot
  app/services/agent_bots/validate_bot_service.rb
  lib/integrations/bot_processor_service.rb
Labels: PR: reviewed-approved

#6591 Fallback name branch
  app/controllers/microsoft/callbacks_controller.rb
  spec/controllers/microsoft/callbacks_controller_spec.rb
Labels: PR: unreviewed

#6123 chore: Use markdown-it instead of marked
  app/javascript/dashboard/assets/scss/widgets/_conversation-view.scss
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Text.vue
  app/javascript/shared/helpers/MessageFormatter.js
  app/javascript/shared/helpers/markdownIt/link.js
  app/javascript/shared/helpers/specs/MessageFormatter.spec.js
  app/javascript/widget/assets/scss/_variables.scss
  app/javascript/widget/assets/scss/views/_conversation.scss
  app/javascript/widget/components/AgentMessageBubble.vue
  app/javascript/widget/components/ChatMessage.vue
  app/javascript/widget/components/UserMessageBubble.vue
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#6582 feat: Revamps search to use new search API's
  app/javascript/dashboard/api/search.js
  app/javascript/dashboard/components/widgets/InboxName.vue
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
  app/javascript/dashboard/helper/AnalyticsHelper/events.js
  app/javascript/dashboard/i18n/locale/en/index.js
  app/javascript/dashboard/i18n/locale/en/search.json
  app/javascript/dashboard/modules/search/components/MessageContent.vue
  app/javascript/dashboard/modules/search/components/ReadMore.vue
  app/javascript/dashboard/modules/search/components/SearchHeader.vue
  app/javascript/dashboard/modules/search/components/SearchResultContactItem.vue
  app/javascript/dashboard/modules/search/components/SearchResultContactsList.vue
  app/javascript/dashboard/modules/search/components/SearchResultConversationItem.vue
  app/javascript/dashboard/modules/search/components/SearchResultConversationsList.vue
  app/javascript/dashboard/modules/search/components/SearchResultMessagesList.vue
  app/javascript/dashboard/modules/search/components/SearchResultSection.vue
  app/javascript/dashboard/modules/search/components/SearchTabs.vue
  app/javascript/dashboard/modules/search/components/SearchView.vue
  app/javascript/dashboard/modules/search/search.routes.js
  app/javascript/dashboard/modules/search/stories/MessageContent.stories.js
  app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
  app/javascript/dashboard/routes/dashboard/dashboard.routes.js
  app/javascript/dashboard/store/modules/conversationSearch.js
  app/javascript/dashboard/store/mutation-types.js
  app/views/api/v1/accounts/search/_message.json.jbuilder
Labels: PR: unreviewed

#6606 Fix comment in schedule.yml
  config/schedule.yml
Labels: PR: reviewed-approved

#6618 fix: Add a check for automation_created message in FIRST_REPLY_CREATED
  app/models/message.rb
Labels: PR: partially-approved

#6552 fix : Meta tags input in help center clears the input value after clicking outside
  app/javascript/dashboard/routes/dashboard/helpcenter/pages/articles/ArticleSettings.vue
Labels: PR: reviewed-approved, community

#6628 chore: Update gems
  Gemfile.lock
Labels: PR: unreviewed

#6455 chore: Ensure Template messages work even when bot is connected
  app/services/message_templates/hook_execution_service.rb
Labels: PR: reviewed-approved

#6615 feat: add trigram index to tags
  db/migrate/20230306100327_add_trgm_index_to_tag_name.rb
  db/schema.rb
Labels: PR: unreviewed

#6622 feat: add env WHATSAPP_CLOUD_BASE_URL
  app/services/whatsapp/providers/whatsapp_cloud_service.rb
Labels: PR: unreviewed

#6630 feat: Add specs for `WHATSAPP_CLOUD_BASE_URL` env variable
  spec/services/whatsapp/providers/whatsapp_cloud_service_spec.rb
Labels: PR: unreviewed

#6470 feat: Ability to update CSAT over Message API for Inbox with channel type API
  app/controllers/public/api/v1/inboxes/messages_controller.rb
  spec/controllers/public/api/v1/inbox/messages_controller_spec.rb
Labels: PR: unreviewed, community

#6627 chore: Disable error tracking for Whatsapp error webhooks
  app/services/whatsapp/incoming_message_base_service.rb
  app/services/whatsapp/incoming_message_service_helpers.rb
  spec/services/whatsapp/incoming_message_whatsapp_cloud_service_spec.rb
Labels: PR: unreviewed

#6633 fix: timing in the API
  app/javascript/dashboard/api/reports.js
  app/javascript/dashboard/api/specs/reports.spec.js
Labels: PR: reviewed-approved

#6635 fix: String interpolation
  config/locales/en.yml
Labels: PR: reviewed-approved

#6632 fix: Warn Facebook error code 100-2018218
  app/builders/messages/facebook/message_builder.rb
  spec/builders/messages/facebook/message_builder_spec.rb
Labels: PR: unreviewed

#6646 fix: hook exception for empty hook
  lib/integrations/bot_processor_service.rb
Labels: PR: partially-approved

#6222 fix: Duplicate conversations and contacts WA and Brazil numbers
  app/services/whatsapp/incoming_message_base_service.rb
  app/services/whatsapp/incoming_message_service_helpers.rb
  spec/services/whatsapp/incoming_message_service_spec.rb
Labels: PR: unreviewed, community

#6655 feat: Backend changes for article and categories ordering
  app/controllers/api/v1/accounts/articles_controller.rb
  app/controllers/public/api/v1/portals/articles_controller.rb
  app/controllers/public/api/v1/portals/categories_controller.rb
  app/models/article.rb
  app/views/api/v1/accounts/articles/_article.json.jbuilder
  app/views/public/api/v1/models/_article.json.jbuilder
  app/views/public/api/v1/portals/_category-block.html.erb
  app/views/public/api/v1/portals/categories/_category-block.html.erb
  app/views/public/api/v1/portals/show.html.erb
  db/migrate/20230313113920_add_position_to_articles.rb
  db/schema.rb
  spec/controllers/api/v1/accounts/articles_controller_spec.rb
  spec/controllers/api/v1/accounts/categories_controller_spec.rb
Labels: PR: reviewed-approved

#6644 chore: Search optimisations
  app/models/contact.rb
  app/models/installation_config.rb
  app/models/message.rb
  app/models/notification.rb
  app/services/search_service.rb
  spec/controllers/api/v1/accounts/search_controller_spec.rb
  spec/services/search_service_spec.rb
Labels: PR: unreviewed

#6645 feat: Search improvements for conversations
  app/javascript/dashboard/i18n/locale/en/search.json
  app/javascript/dashboard/modules/search/components/SearchHeader.vue
  app/javascript/dashboard/modules/search/components/SearchInput.vue
  app/javascript/dashboard/modules/search/components/SearchResultContactItem.vue
  app/javascript/dashboard/modules/search/components/SearchResultConversationItem.vue
  app/javascript/dashboard/modules/search/components/SearchResultSection.vue
  app/javascript/dashboard/modules/search/components/SearchTabs.vue
  app/javascript/dashboard/modules/search/components/SearchView.vue
  app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
  app/javascript/dashboard/store/modules/conversationSearch.js
Labels: PR: partially-approved

#6663 chore: Disable throwing Webhook exceptions to Sentry
  lib/webhooks/trigger.rb
Labels: PR: unreviewed

#6662 Fix: Add articles order in category show page
  app/views/public/api/v1/portals/categories/show.html.erb
Labels: PR: reviewed-approved

#6659 chore: Add sidekiq metrics to newrelic
  Gemfile
  Gemfile.lock
  config/application.rb
Labels: PR: unreviewed

#6658 feat(poc): Disable widget based on country
  .env.example
  Procfile
  app/controllers/widgets_controller.rb
  app/jobs/contact_ip_lookup_job.rb
  app/services/ip_lookup_service.rb
  config/initializers/geocoder.rb
  enterprise/app/controllers/enterprise/widgets_controller.rb
  lib/tasks/ip_lookup.rake
Labels: PR: reviewed-approved

#6671 chore: Resolve bundle Audit
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/administrate/application.scss
  spec/presenters/mail_presenter_spec.rb
Labels: PR: unreviewed

#6664 fix: delete user record if belongs to no account
  app/controllers/api/v1/accounts/agents_controller.rb
  spec/controllers/api/v1/accounts/agents_controller_spec.rb
Labels: PR: unreviewed

#6682 chore: Enable Icelandic language
  app/javascript/survey/i18n/index.js
  app/javascript/widget/i18n/index.js
Labels: PR: unreviewed

#6685 chore: Upgrade prosemirror package to fix link rendering issue
  yarn.lock
Labels: PR: reviewed-approved

#6688 fix: Reverts popover styling for search page
  app/javascript/dashboard/modules/search/components/SearchHeader.vue
  app/javascript/dashboard/modules/search/components/SearchTabs.vue
  app/javascript/dashboard/modules/search/components/SearchView.vue
Labels: frontend, PR: unreviewed, PR: reviewed-approved

#6702 Fix issues with Microsoft Provider
  app/controllers/api/v1/accounts/microsoft/authorizations_controller.rb
  app/controllers/microsoft/callbacks_controller.rb
  spec/controllers/api/v1/accounts/microsoft/authorization_controller_spec.rb
Labels: PR: reviewed-approved

#6708 [CW-1342]: Inbox deletion in background job
  app/controllers/api/v1/accounts/inboxes_controller.rb
  config/locales/en.yml
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
Labels: PR: reviewed-approved

#6683 [CW-53] feat: allow downloading heatmap report
  app/controllers/api/v2/accounts/reports_controller.rb
  app/helpers/api/v2/accounts/reports_helper.rb
  app/javascript/dashboard/api/reports.js
  app/javascript/dashboard/routes/dashboard/settings/reports/LiveReports.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/overview/MetricCard.vue
  app/javascript/dashboard/store/modules/reports.js
  app/views/api/v2/accounts/reports/conversation_traffic.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/api/v2/accounts/report_controller_spec.rb
Labels: PR: unreviewed

#6705 [CW-1348] fix: Update email regex validation for contact_inbox
  app/models/contact_inbox.rb
  spec/controllers/api/v1/accounts/contacts/contact_inboxes_controller_spec.rb
Labels: PR: partially-approved

#6717 fix: Fixes scroll behaviour for search page
  app/javascript/dashboard/modules/search/components/SearchView.vue
Labels: PR: reviewed-approved

#6718 fix: Design issues after RTL changes [CW-1314]
  app/javascript/dashboard/components/ChatList.vue
  app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue
Labels: PR: unreviewed

#6715 fix: Super admin redirect issue [CW-1370]
  app/controllers/super_admin/users_controller.rb
  spec/controllers/super_admin/users_controller_spec.rb
Labels: PR: partially-approved

#6735 feat: Show custom attributes in pre-chat form on new conversation
  app/javascript/widget/components/ChatFooter.vue
  app/javascript/widget/components/PreChat/Form.vue
  app/javascript/widget/views/PreChatForm.vue
Labels: PR: unreviewed

#6748 chore: Refactor messages to support right click context menu
  app/finders/message_finder.rb
  app/javascript/dashboard/api/inbox/message.js
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/TranslateModal.vue
  app/javascript/dashboard/components/widgets/conversation/contextMenu/menuItem.vue
  app/javascript/dashboard/components/widgets/conversation/contextMenu/menuItemWithSubmenu.vue
  app/javascript/dashboard/store/modules/conversations/actions.js
Labels: PR: unreviewed

#6750 feat: Setup context menu for message
  app/javascript/dashboard/assets/scss/widgets/_modal.scss
  app/javascript/dashboard/components/ui/ContextMenu.vue
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/helper/AnalyticsHelper/events.js
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/modules/conversations/components/MessageContextMenu.vue
  app/javascript/shared/constants/busEvents.js
Labels: PR: unreviewed

#6752 fix: Move subscription calls to after initialize
  app/javascript/dashboard/App.vue
Labels: PR: partially-approved

#6756 fix: Display native context menu on image, video preview modals
  app/javascript/dashboard/components/Modal.vue
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Image.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Video.vue
  app/javascript/dashboard/modules/conversations/components/MessageContextMenu.vue
Labels: PR: unreviewed

#5912 feat: Copy Link to a message
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/components/widgets/conversation/contextMenu/menuItemWithSubmenu.vue
  app/javascript/dashboard/i18n/locale/en/conversation.json
  app/javascript/dashboard/modules/conversations/components/MessageContextMenu.vue
  app/javascript/dashboard/modules/search/components/SearchResultConversationItem.vue
  app/javascript/dashboard/modules/search/components/SearchResultMessagesList.vue
  app/javascript/dashboard/routes/dashboard/conversation/ConversationView.vue
  app/javascript/dashboard/store/modules/conversations/actions.js
Labels: PR: unreviewed, linear

#6710 feat: IndexedDB based caching for labels, inboxes and teams [CW-50]
  app/controllers/api/v1/accounts_controller.rb
  app/helpers/cache_keys_helper.rb
  app/javascript/dashboard/api/ApiClient.js
  app/javascript/dashboard/api/CacheEnabledApiClient.js
  app/javascript/dashboard/api/auth.js
  app/javascript/dashboard/api/inboxes.js
  app/javascript/dashboard/api/labels.js
  app/javascript/dashboard/api/teams.js
  app/javascript/dashboard/helper/CacheHelper/DataManager.js
  app/javascript/dashboard/helper/CacheHelper/version.js
  app/javascript/dashboard/helper/actionCable.js
  app/javascript/dashboard/helper/specs/CacheHelper/DataManger.spec.js
  app/javascript/dashboard/store/modules/inboxes.js
  app/javascript/dashboard/store/modules/labels.js
  app/javascript/dashboard/store/modules/teams/actions.js
  app/javascript/dashboard/store/utils/api.js
  app/listeners/action_cable_listener.rb
  app/models/account.rb
  app/models/concerns/account_cache_revalidator.rb
  app/models/concerns/cache_keys.rb
  app/models/inbox.rb
  app/models/label.rb
  app/models/team.rb
  app/policies/account_policy.rb
  app/views/api/v1/models/_account.json.jbuilder
  config/routes.rb
  config/webpack/environment.js
  jest.config.js
  lib/events/types.rb
  package.json
  spec/controllers/api/v1/accounts_controller_spec.rb
  spec/helpers/cache_keys_helper_spec.rb
  yarn.lock
Labels: PR: unreviewed

#6711 fix: Show meaning full error message while creating and email inbox [CW-1312]
  app/javascript/dashboard/routes/dashboard/settings/inbox/channels/emailChannels/ForwardToOption.vue
  app/javascript/dashboard/store/modules/inboxes.js
Labels: PR: unreviewed

#6758 chore: Auto capitalize the name field while sending the canned response/variables
  app/drops/contact_drop.rb
  app/drops/user_drop.rb
  app/javascript/dashboard/helper/messageHelper.js
  app/javascript/dashboard/helper/specs/messageHelper.spec.js
  spec/drops/contact_drop_spec.rb
  spec/drops/user_drop_spec.rb
  spec/models/concerns/liquidable_shared.rb
Labels: PR: unreviewed

#6707 fix: [CW-44] don't count private message as first reply
  app/models/message.rb
  spec/models/message_spec.rb
Labels: PR: unreviewed

#6767 chore: Auto capitalize the last name field while sending the canned response/variables
  app/drops/contact_drop.rb
  app/drops/user_drop.rb
  app/javascript/dashboard/helper/messageHelper.js
  app/javascript/dashboard/helper/specs/messageHelper.spec.js
  spec/drops/contact_drop_spec.rb
  spec/drops/user_drop_spec.rb
Labels: PR: partially-approved

#6762 fix: mentions are not rendered properly in slack
  lib/integrations/slack/send_on_slack_service.rb
  spec/lib/integrations/slack/send_on_slack_service_spec.rb
Labels: PR: unreviewed

#6757 feat: add index to conversation `id` and `account_id`
  Gemfile
  Gemfile.lock
  app/models/conversation.rb
  config/initializers/rack_profiler.rb
  db/migrate/20230327081350_add_index_to_conversations_account_id_and_id.rb
  db/schema.rb
Labels: PR: reviewed-approved

#5887 feat: Support input_select messages on telegram
  app/models/channel/telegram.rb
  app/services/telegram/incoming_message_service.rb
  app/services/telegram/param_helpers.rb
  spec/models/channel/telegram_spec.rb
  spec/services/telegram/incoming_message_service_spec.rb
Labels: PR: unreviewed, community

#6772 fix memory leek
  app/javascript/dashboard/components/CustomAttribute.vue
Labels: PR: unreviewed, community

#6769 chore: Remove extra audit column
  db/migrate/20230202132107_install_audited.rb
  db/migrate/20230328131926_drop_extra_audit_integer_column.rb
  db/schema.rb
Labels: PR: unreviewed

#6770 chore: Re-add "public" prefix to "public.gen_random_uuid()" in schema.rb
  db/schema.rb
Labels: PR: unreviewed

#6701 feat: show external error in message
  app/javascript/dashboard/components/widgets/conversation/Message.vue
  app/javascript/dashboard/components/widgets/conversation/bubble/Actions.vue
Labels: PR: reviewed-approved, community

#6784 chore: Fixes avatar position on failed messages
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: PR: reviewed-approved

#6785 chore: Support telegram `edited_message` events
  app/jobs/webhooks/telegram_events_job.rb
  app/services/telegram/update_message_service.rb
  spec/jobs/webhooks/telegram_events_job_spec.rb
  spec/services/telegram/incoming_message_service_spec.rb
  spec/services/telegram/update_message_service_spec.rb
Labels: PR: unreviewed

#6789 fix: Adds assignee as a participant during auto-assign
  app/models/concerns/auto_assignment_handler.rb
  app/services/messages/mention_service.rb
  spec/models/concerns/auto_assignment_handler_shared.rb
Labels: PR: reviewed-approved

#6780 fix: Check valid params are exist in `WhatsAapp` payload
  app/services/whatsapp/incoming_message_base_service.rb
  app/services/whatsapp/incoming_message_whatsapp_cloud_service.rb
  spec/services/whatsapp/incoming_message_whatsapp_cloud_service_spec.rb
Labels: PR: unreviewed

#6768 fix: Add link to conversation in slack message
  lib/integrations/slack/send_on_slack_service.rb
  spec/lib/integrations/slack/send_on_slack_service_spec.rb
Labels: PR: reviewed-approved

#6796 chore: Refactor Automation Specs [CW-1447]
  app/listeners/automation_rule_listener.rb
  app/services/automation_rules/action_service.rb
  spec/factories/automation_rules.rb
  spec/listeners/automation_rule_listener_old_spec.rb
  spec/listeners/automation_rule_listener_spec.rb
  spec/services/action_service_spec.rb
  spec/services/automation_rules/action_service_spec.rb
  spec/services/automation_rules/conditions_filter_service_spec.rb
Labels: PR: reviewed-approved

#6786 fix: Email based automation conditions filter
  app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
  lib/automation_rules/conditions.json
Labels: PR: partially-approved

#6791 chore: Adds the ability to copy phone number from user details
  app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
Labels: PR: partially-approved

#6777 fix: Agent avatar instead of bot avatar in pending message
  app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
Labels: PR: unreviewed
