Repository chatwoot/chatwoot, pull requests merged in 2024-06, with the labels that each got.

#9592 feat: Make context meny visible only on hover
  app/javascript/dashboard/components/widgets/conversation/Message.vue
Labels: frontend

#9596 fix: Missing mitt.js in vue 3 instance of app
  app/javascript/packs/v3app.js
Labels: frontend, Bug

#9668 feat: Add the ability to un-assign teams using automation
  app/javascript/dashboard/helper/automationHelper.js
  app/models/concerns/json_schema_validator.rb
  app/services/action_service.rb
  spec/factories/conversations.rb
  spec/services/action_service_spec.rb
Labels: PR: reviewed-approved
