Repository chatwoot/chatwoot, pull requests merged in 2024-02, with the labels that each got.

#7636 fix: Send push notification on `bot_handoff`
  app/listeners/notification_listener.rb
  spec/listeners/notification_listener_spec.rb
Labels: community

#8015 feat: Agent bot cant assign conversations to teams
  app/controllers/concerns/access_token_auth_helper.rb
  app/controllers/concerns/ensure_current_account_helper.rb
  spec/controllers/api/v1/accounts/conversations/assignments_controller_spec.rb
  spec/controllers/api/v1/accounts/conversations_controller_spec.rb
  swagger/paths/application/conversation/assignments.yml
  swagger/swagger.json
Labels: community

#8947 chore: Support for updated_within in ConverationFinder
  app/finders/conversation_finder.rb
  spec/finders/conversation_finder_spec.rb
Labels: PR: reviewed-changes-requested

#8932 feat: Adds textarea component to use in forms
  app/javascript/v3/components/Form/Textarea.vue
Labels: PR: reviewed-changes-requested

#8907 fix: Inbox view Read/Snoozed display filters
  app/controllers/api/v1/accounts/notifications_controller.rb
  app/finders/notification_finder.rb
  app/javascript/dashboard/api/notifications.js
  app/javascript/dashboard/api/specs/notifications.spec.js
  app/javascript/dashboard/store/modules/notifications/getters.js
  app/javascript/dashboard/store/modules/notifications/helpers.js
  app/javascript/dashboard/store/modules/specs/notifications/getters.spec.js
  app/javascript/dashboard/store/modules/specs/notifications/helpers.spec.js
  spec/factories/notifications.rb
  spec/finders/notification_finder_spec.rb
Labels: PR: reviewed-changes-requested

#8934 chore: Hide banners on onboarding view
  app/javascript/dashboard/App.vue
  app/javascript/v3/helpers/RouteHelper.js
  app/javascript/v3/helpers/specs/RouteHelper.spec.js
Labels: PR: reviewed-changes-requested

#8777 feat: sla-3 UI for SLA
  app/javascript/dashboard/api/sla.js
  app/javascript/dashboard/components/layout/config/sidebarItems/settings.js
  app/javascript/dashboard/featureFlags.js
  app/javascript/dashboard/helper/AnalyticsHelper/events.js
  app/javascript/dashboard/i18n/locale/en/index.js
  app/javascript/dashboard/i18n/locale/en/settings.json
  app/javascript/dashboard/i18n/locale/en/sla.json
  app/javascript/dashboard/routes/dashboard/settings/settings.routes.js
  app/javascript/dashboard/routes/dashboard/settings/sla/AddSLA.vue
  app/javascript/dashboard/routes/dashboard/settings/sla/EditSLA.vue
  app/javascript/dashboard/routes/dashboard/settings/sla/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/sla/SlaForm.vue
  app/javascript/dashboard/routes/dashboard/settings/sla/sla.routes.js
  app/javascript/dashboard/routes/dashboard/settings/sla/specs/validationMixin.spec.js
  app/javascript/dashboard/routes/dashboard/settings/sla/validationMixin.js
  app/javascript/dashboard/routes/dashboard/settings/sla/validations.js
  app/javascript/dashboard/store/index.js
  app/javascript/dashboard/store/modules/sla.js
  app/javascript/dashboard/store/mutation-types.js
  config/features.yml
  enterprise/config/premium_features.yml
Labels: PR: reviewed-changes-requested

#8910 feat: sla-5 add_sla support in automation UI
  app/javascript/dashboard/helper/automationHelper.js
  app/javascript/dashboard/mixins/automations/methodsMixin.js
  app/javascript/dashboard/routes/dashboard/settings/automation/AddAutomationRule.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/EditAutomationRule.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/Index.vue
  app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
  app/javascript/dashboard/routes/dashboard/settings/sla/Index.vue
  app/javascript/shared/mixins/specs/automationFixtures.js
  app/javascript/shared/mixins/specs/automationMixin.spec.js
Labels: PR: reviewed-changes-requested

#8994 docs: Add filter status=all to conversation list and meta
  swagger/paths/application/conversation/index.yml
  swagger/paths/application/conversation/meta.yml
  swagger/swagger.json
Labels: PR: reviewed-changes-requested, community
