Repository chatwoot/chatwoot, pull requests merged in 2024-01, with the labels that each got.

#8264 chore: Fix codespaces
  .devcontainer/Dockerfile
  .devcontainer/Dockerfile.base
  .devcontainer/docker-compose.yml
  .github/workflows/publish_codespace_image.yml
Labels: stale

#8613 fix: change teamid
  app/javascript/dashboard/components/ChatList.vue
Labels: on-hold

#7856 feat: Adds regex to custom attribute definitions
  app/controllers/api/v1/accounts/custom_attribute_definitions_controller.rb
  app/javascript/dashboard/components/CustomAttribute.vue
  app/javascript/dashboard/helper/preChat.js
  app/javascript/dashboard/helper/specs/inboxFixture.js
  app/javascript/dashboard/helper/specs/preChat.spec.js
  app/javascript/dashboard/i18n/locale/en/attributesMgmt.json
  app/javascript/dashboard/i18n/locale/en/contact.json
  app/javascript/dashboard/mixins/customAttributeMixin.js
  app/javascript/dashboard/routes/dashboard/conversation/customAttributes/CustomAttributes.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/AddAttribute.vue
  app/javascript/dashboard/routes/dashboard/settings/attributes/EditAttribute.vue
  app/javascript/widget/components/PreChat/Form.vue
  app/javascript/widget/i18n/locale/en.json
  app/jobs/inboxes/update_widget_pre_chat_custom_fields_job.rb
  app/models/channel/web_widget.rb
  app/models/custom_attribute_definition.rb
  app/views/api/v1/models/_custom_attribute_definition.json.jbuilder
  db/migrate/20230905060223_add_regex_to_custom_attribute_definition.rb
  db/schema.rb
  spec/jobs/inboxes/update_widget_pre_chat_custom_fields_job_spec.rb
Labels: community, stale
